// Generated by CIRCT firtool-1.135.0
module Arbiter4_StoreStageIO(
  input          io_in_0_valid,
  input  [2:0]   io_in_0_bits_accessType_instrType,
  input          io_in_0_bits_accessType_isCbo,
  input          io_in_0_bits_accessType_isCboNoZero,
  input  [31:0]  io_in_0_bits_uop_instr,
  input  [49:0]  io_in_0_bits_uop_pc,
  input  [9:0]   io_in_0_bits_uop_foldpc,
  input          io_in_0_bits_uop_exceptionVec_23,
  input          io_in_0_bits_uop_exceptionVec_22,
  input          io_in_0_bits_uop_exceptionVec_21,
  input          io_in_0_bits_uop_exceptionVec_20,
  input          io_in_0_bits_uop_exceptionVec_19,
  input          io_in_0_bits_uop_exceptionVec_18,
  input          io_in_0_bits_uop_exceptionVec_16,
  input          io_in_0_bits_uop_exceptionVec_15,
  input          io_in_0_bits_uop_exceptionVec_13,
  input          io_in_0_bits_uop_exceptionVec_12,
  input          io_in_0_bits_uop_exceptionVec_11,
  input          io_in_0_bits_uop_exceptionVec_10,
  input          io_in_0_bits_uop_exceptionVec_9,
  input          io_in_0_bits_uop_exceptionVec_8,
  input          io_in_0_bits_uop_exceptionVec_7,
  input          io_in_0_bits_uop_exceptionVec_6,
  input          io_in_0_bits_uop_exceptionVec_5,
  input          io_in_0_bits_uop_exceptionVec_4,
  input          io_in_0_bits_uop_exceptionVec_3,
  input          io_in_0_bits_uop_exceptionVec_2,
  input          io_in_0_bits_uop_exceptionVec_1,
  input          io_in_0_bits_uop_exceptionVec_0,
  input          io_in_0_bits_uop_isFetchMalAddr,
  input          io_in_0_bits_uop_hasException,
  input  [3:0]   io_in_0_bits_uop_trigger,
  input          io_in_0_bits_uop_isRVC,
  input          io_in_0_bits_uop_fixedTaken,
  input          io_in_0_bits_uop_predTaken,
  input          io_in_0_bits_uop_crossPageIPFFix,
  input          io_in_0_bits_uop_ftqPtr_flag,
  input  [2:0]   io_in_0_bits_uop_ftqPtr_value,
  input  [3:0]   io_in_0_bits_uop_ftqOffset,
  input  [3:0]   io_in_0_bits_uop_ftqLastOffset,
  input          io_in_0_bits_uop_stdwriteNeed,
  input  [3:0]   io_in_0_bits_uop_srcType_0,
  input  [3:0]   io_in_0_bits_uop_srcType_1,
  input  [3:0]   io_in_0_bits_uop_srcType_2,
  input  [3:0]   io_in_0_bits_uop_srcType_3,
  input  [5:0]   io_in_0_bits_uop_ldest,
  input  [35:0]  io_in_0_bits_uop_fuType,
  input  [8:0]   io_in_0_bits_uop_fuOpType,
  input          io_in_0_bits_uop_rfWen,
  input          io_in_0_bits_uop_fpWen,
  input          io_in_0_bits_uop_vecWen,
  input          io_in_0_bits_uop_v0Wen,
  input          io_in_0_bits_uop_vlWen,
  input          io_in_0_bits_uop_isXSTrap,
  input          io_in_0_bits_uop_waitForward,
  input          io_in_0_bits_uop_blockBackward,
  input          io_in_0_bits_uop_flushPipe,
  input          io_in_0_bits_uop_canRobCompress,
  input  [1:0]   io_in_0_bits_uop_fusionNum,
  input  [3:0]   io_in_0_bits_uop_selImm,
  input  [31:0]  io_in_0_bits_uop_imm,
  input          io_in_0_bits_uop_fpu_wflags,
  input  [1:0]   io_in_0_bits_uop_fpu_fmt,
  input  [2:0]   io_in_0_bits_uop_fpu_rm,
  input          io_in_0_bits_uop_vpu_vill,
  input          io_in_0_bits_uop_vpu_vma,
  input          io_in_0_bits_uop_vpu_vta,
  input  [1:0]   io_in_0_bits_uop_vpu_vsew,
  input  [2:0]   io_in_0_bits_uop_vpu_vlmul,
  input          io_in_0_bits_uop_vpu_specVill,
  input          io_in_0_bits_uop_vpu_specVma,
  input          io_in_0_bits_uop_vpu_specVta,
  input  [1:0]   io_in_0_bits_uop_vpu_specVsew,
  input  [2:0]   io_in_0_bits_uop_vpu_specVlmul,
  input          io_in_0_bits_uop_vpu_vm,
  input  [7:0]   io_in_0_bits_uop_vpu_vstart,
  input  [2:0]   io_in_0_bits_uop_vpu_frm,
  input          io_in_0_bits_uop_vpu_fpu_isFpToVecInst,
  input          io_in_0_bits_uop_vpu_fpu_isFP32Instr,
  input          io_in_0_bits_uop_vpu_fpu_isFP64Instr,
  input          io_in_0_bits_uop_vpu_fpu_isReduction,
  input          io_in_0_bits_uop_vpu_fpu_isFoldTo1_2,
  input          io_in_0_bits_uop_vpu_fpu_isFoldTo1_4,
  input          io_in_0_bits_uop_vpu_fpu_isFoldTo1_8,
  input  [1:0]   io_in_0_bits_uop_vpu_vxrm,
  input  [6:0]   io_in_0_bits_uop_vpu_vuopIdx,
  input          io_in_0_bits_uop_vpu_lastUop,
  input  [127:0] io_in_0_bits_uop_vpu_vmask,
  input  [7:0]   io_in_0_bits_uop_vpu_vl,
  input  [2:0]   io_in_0_bits_uop_vpu_nf,
  input  [1:0]   io_in_0_bits_uop_vpu_veew,
  input          io_in_0_bits_uop_vpu_isReverse,
  input          io_in_0_bits_uop_vpu_isExt,
  input          io_in_0_bits_uop_vpu_isNarrow,
  input          io_in_0_bits_uop_vpu_isDstMask,
  input          io_in_0_bits_uop_vpu_isOpMask,
  input          io_in_0_bits_uop_vpu_isMove,
  input          io_in_0_bits_uop_vpu_isDependOldVd,
  input          io_in_0_bits_uop_vpu_isWritePartVd,
  input          io_in_0_bits_uop_vpu_isVleff,
  input  [15:0]  io_in_0_bits_uop_vpu_maskVecGen,
  input          io_in_0_bits_uop_vpu_sew8,
  input          io_in_0_bits_uop_vpu_sew16,
  input          io_in_0_bits_uop_vpu_sew32,
  input          io_in_0_bits_uop_vpu_sew64,
  input          io_in_0_bits_uop_vlsInstr,
  input          io_in_0_bits_uop_wfflags,
  input          io_in_0_bits_uop_isMove,
  input          io_in_0_bits_uop_isDropAmocasSta,
  input  [6:0]   io_in_0_bits_uop_uopIdx,
  input          io_in_0_bits_uop_isVset,
  input          io_in_0_bits_uop_firstUop,
  input          io_in_0_bits_uop_lastUop,
  input  [6:0]   io_in_0_bits_uop_numUops,
  input  [6:0]   io_in_0_bits_uop_numWB,
  input  [1:0]   io_in_0_bits_uop_commitType,
  input          io_in_0_bits_uop_srcState_0,
  input          io_in_0_bits_uop_srcState_1,
  input          io_in_0_bits_uop_srcState_2,
  input          io_in_0_bits_uop_srcState_3,
  input  [1:0]   io_in_0_bits_uop_srcLoadDependency_0_0,
  input  [1:0]   io_in_0_bits_uop_srcLoadDependency_0_1,
  input  [1:0]   io_in_0_bits_uop_srcLoadDependency_0_2,
  input  [1:0]   io_in_0_bits_uop_srcLoadDependency_1_0,
  input  [1:0]   io_in_0_bits_uop_srcLoadDependency_1_1,
  input  [1:0]   io_in_0_bits_uop_srcLoadDependency_1_2,
  input  [1:0]   io_in_0_bits_uop_srcLoadDependency_2_0,
  input  [1:0]   io_in_0_bits_uop_srcLoadDependency_2_1,
  input  [1:0]   io_in_0_bits_uop_srcLoadDependency_2_2,
  input  [1:0]   io_in_0_bits_uop_srcLoadDependency_3_0,
  input  [1:0]   io_in_0_bits_uop_srcLoadDependency_3_1,
  input  [1:0]   io_in_0_bits_uop_srcLoadDependency_3_2,
  input  [7:0]   io_in_0_bits_uop_psrc_0,
  input  [7:0]   io_in_0_bits_uop_psrc_1,
  input  [7:0]   io_in_0_bits_uop_psrc_2,
  input  [7:0]   io_in_0_bits_uop_psrc_3,
  input  [7:0]   io_in_0_bits_uop_pdest,
  input  [4:0]   io_in_0_bits_uop_pdestVl,
  input  [1:0]   io_in_0_bits_uop_rasAction,
  input          io_in_0_bits_uop_useRegCache_0,
  input          io_in_0_bits_uop_useRegCache_1,
  input  [5:0]   io_in_0_bits_uop_regCacheIdx_0,
  input  [5:0]   io_in_0_bits_uop_regCacheIdx_1,
  input          io_in_0_bits_uop_robIdx_flag,
  input  [5:0]   io_in_0_bits_uop_robIdx_value,
  input          io_in_0_bits_uop_dirtyFs,
  input          io_in_0_bits_uop_dirtyVs,
  input  [3:0]   io_in_0_bits_uop_traceBlockInPipe_itype,
  input  [5:0]   io_in_0_bits_uop_traceBlockInPipe_iretire,
  input          io_in_0_bits_uop_traceBlockInPipe_ilastsize,
  input          io_in_0_bits_uop_snapshot,
  input          io_in_0_bits_uop_perfDebugInfo_eliminatedMove,
  input  [63:0]  io_in_0_bits_uop_perfDebugInfo_renameTime,
  input  [63:0]  io_in_0_bits_uop_perfDebugInfo_dispatchTime,
  input  [63:0]  io_in_0_bits_uop_perfDebugInfo_enqRsTime,
  input  [63:0]  io_in_0_bits_uop_perfDebugInfo_selectTime,
  input  [63:0]  io_in_0_bits_uop_perfDebugInfo_issueTime,
  input  [63:0]  io_in_0_bits_uop_perfDebugInfo_writebackTime,
  input  [63:0]  io_in_0_bits_uop_perfDebugInfo_runahead_checkpoint_id,
  input  [63:0]  io_in_0_bits_uop_perfDebugInfo_tlbFirstReqTime,
  input  [63:0]  io_in_0_bits_uop_perfDebugInfo_tlbRespTime,
  input  [55:0]  io_in_0_bits_uop_debug_seqNum_seqNum,
  input  [7:0]   io_in_0_bits_uop_debug_seqNum_uopIdx,
  input          io_in_0_bits_uop_storeSetHit,
  input          io_in_0_bits_uop_waitForRobIdx_flag,
  input  [5:0]   io_in_0_bits_uop_waitForRobIdx_value,
  input          io_in_0_bits_uop_loadWaitBit,
  input          io_in_0_bits_uop_loadWaitStrict,
  input  [5:0]   io_in_0_bits_uop_ssid,
  input          io_in_0_bits_uop_nc,
  input          io_in_0_bits_uop_mmio,
  input          io_in_0_bits_uop_lqIdx_flag,
  input  [4:0]   io_in_0_bits_uop_lqIdx_value,
  input          io_in_0_bits_uop_sqIdx_first_flag,
  input          io_in_0_bits_uop_sqIdx_second_flag,
  input  [3:0]   io_in_0_bits_uop_sqIdx_value,
  input          io_in_0_bits_uop_singleStep,
  input          io_in_0_bits_uop_replayInst,
  input  [35:0]  io_in_0_bits_uop_debug_fuType,
  input          io_in_0_bits_uop_debug_sim_trig,
  input  [4:0]   io_in_0_bits_uop_numLsElem,
  input  [49:0]  io_in_0_bits_vaddr,
  input  [63:0]  io_in_0_bits_fullva,
  input  [2:0]   io_in_0_bits_size,
  input  [15:0]  io_in_0_bits_mask,
  input          io_in_0_bits_isFirstIssue,
  input  [7:0]   io_in_0_bits_elemIdx,
  input  [3:0]   io_in_0_bits_mbIndex,
  output         io_in_1_ready,
  input          io_in_1_valid,
  input  [31:0]  io_in_1_bits_uop_instr,
  input  [49:0]  io_in_1_bits_uop_pc,
  input  [9:0]   io_in_1_bits_uop_foldpc,
  input          io_in_1_bits_uop_exceptionVec_23,
  input          io_in_1_bits_uop_exceptionVec_19,
  input          io_in_1_bits_uop_exceptionVec_15,
  input          io_in_1_bits_uop_exceptionVec_7,
  input          io_in_1_bits_uop_exceptionVec_6,
  input          io_in_1_bits_uop_exceptionVec_3,
  input          io_in_1_bits_uop_isFetchMalAddr,
  input          io_in_1_bits_uop_hasException,
  input  [3:0]   io_in_1_bits_uop_trigger,
  input          io_in_1_bits_uop_isRVC,
  input          io_in_1_bits_uop_fixedTaken,
  input          io_in_1_bits_uop_predTaken,
  input          io_in_1_bits_uop_crossPageIPFFix,
  input          io_in_1_bits_uop_ftqPtr_flag,
  input  [2:0]   io_in_1_bits_uop_ftqPtr_value,
  input  [3:0]   io_in_1_bits_uop_ftqOffset,
  input  [3:0]   io_in_1_bits_uop_ftqLastOffset,
  input          io_in_1_bits_uop_stdwriteNeed,
  input  [3:0]   io_in_1_bits_uop_srcType_0,
  input  [3:0]   io_in_1_bits_uop_srcType_1,
  input  [3:0]   io_in_1_bits_uop_srcType_2,
  input  [3:0]   io_in_1_bits_uop_srcType_3,
  input  [5:0]   io_in_1_bits_uop_ldest,
  input  [35:0]  io_in_1_bits_uop_fuType,
  input  [8:0]   io_in_1_bits_uop_fuOpType,
  input          io_in_1_bits_uop_rfWen,
  input          io_in_1_bits_uop_fpWen,
  input          io_in_1_bits_uop_vecWen,
  input          io_in_1_bits_uop_v0Wen,
  input          io_in_1_bits_uop_vlWen,
  input          io_in_1_bits_uop_isXSTrap,
  input          io_in_1_bits_uop_waitForward,
  input          io_in_1_bits_uop_blockBackward,
  input          io_in_1_bits_uop_flushPipe,
  input          io_in_1_bits_uop_canRobCompress,
  input  [1:0]   io_in_1_bits_uop_fusionNum,
  input  [3:0]   io_in_1_bits_uop_selImm,
  input          io_in_1_bits_uop_fpu_wflags,
  input  [1:0]   io_in_1_bits_uop_fpu_fmt,
  input  [2:0]   io_in_1_bits_uop_fpu_rm,
  input          io_in_1_bits_uop_vpu_vill,
  input          io_in_1_bits_uop_vpu_vma,
  input          io_in_1_bits_uop_vpu_vta,
  input  [1:0]   io_in_1_bits_uop_vpu_vsew,
  input  [2:0]   io_in_1_bits_uop_vpu_vlmul,
  input          io_in_1_bits_uop_vpu_specVill,
  input          io_in_1_bits_uop_vpu_specVma,
  input          io_in_1_bits_uop_vpu_specVta,
  input  [1:0]   io_in_1_bits_uop_vpu_specVsew,
  input  [2:0]   io_in_1_bits_uop_vpu_specVlmul,
  input          io_in_1_bits_uop_vpu_vm,
  input  [7:0]   io_in_1_bits_uop_vpu_vstart,
  input  [2:0]   io_in_1_bits_uop_vpu_frm,
  input          io_in_1_bits_uop_vpu_fpu_isFpToVecInst,
  input          io_in_1_bits_uop_vpu_fpu_isFP32Instr,
  input          io_in_1_bits_uop_vpu_fpu_isFP64Instr,
  input          io_in_1_bits_uop_vpu_fpu_isReduction,
  input          io_in_1_bits_uop_vpu_fpu_isFoldTo1_2,
  input          io_in_1_bits_uop_vpu_fpu_isFoldTo1_4,
  input          io_in_1_bits_uop_vpu_fpu_isFoldTo1_8,
  input  [1:0]   io_in_1_bits_uop_vpu_vxrm,
  input  [6:0]   io_in_1_bits_uop_vpu_vuopIdx,
  input          io_in_1_bits_uop_vpu_lastUop,
  input  [127:0] io_in_1_bits_uop_vpu_vmask,
  input  [7:0]   io_in_1_bits_uop_vpu_vl,
  input  [2:0]   io_in_1_bits_uop_vpu_nf,
  input  [1:0]   io_in_1_bits_uop_vpu_veew,
  input          io_in_1_bits_uop_vpu_isReverse,
  input          io_in_1_bits_uop_vpu_isExt,
  input          io_in_1_bits_uop_vpu_isNarrow,
  input          io_in_1_bits_uop_vpu_isDstMask,
  input          io_in_1_bits_uop_vpu_isOpMask,
  input          io_in_1_bits_uop_vpu_isMove,
  input          io_in_1_bits_uop_vpu_isDependOldVd,
  input          io_in_1_bits_uop_vpu_isWritePartVd,
  input          io_in_1_bits_uop_vpu_isVleff,
  input  [15:0]  io_in_1_bits_uop_vpu_maskVecGen,
  input          io_in_1_bits_uop_vpu_sew8,
  input          io_in_1_bits_uop_vpu_sew16,
  input          io_in_1_bits_uop_vpu_sew32,
  input          io_in_1_bits_uop_vpu_sew64,
  input          io_in_1_bits_uop_vlsInstr,
  input          io_in_1_bits_uop_wfflags,
  input          io_in_1_bits_uop_isMove,
  input          io_in_1_bits_uop_isDropAmocasSta,
  input  [6:0]   io_in_1_bits_uop_uopIdx,
  input          io_in_1_bits_uop_isVset,
  input          io_in_1_bits_uop_firstUop,
  input          io_in_1_bits_uop_lastUop,
  input  [6:0]   io_in_1_bits_uop_numUops,
  input  [6:0]   io_in_1_bits_uop_numWB,
  input  [1:0]   io_in_1_bits_uop_commitType,
  input          io_in_1_bits_uop_srcState_0,
  input          io_in_1_bits_uop_srcState_1,
  input          io_in_1_bits_uop_srcState_2,
  input          io_in_1_bits_uop_srcState_3,
  input  [1:0]   io_in_1_bits_uop_srcLoadDependency_0_0,
  input  [1:0]   io_in_1_bits_uop_srcLoadDependency_0_1,
  input  [1:0]   io_in_1_bits_uop_srcLoadDependency_0_2,
  input  [1:0]   io_in_1_bits_uop_srcLoadDependency_1_0,
  input  [1:0]   io_in_1_bits_uop_srcLoadDependency_1_1,
  input  [1:0]   io_in_1_bits_uop_srcLoadDependency_1_2,
  input  [1:0]   io_in_1_bits_uop_srcLoadDependency_2_0,
  input  [1:0]   io_in_1_bits_uop_srcLoadDependency_2_1,
  input  [1:0]   io_in_1_bits_uop_srcLoadDependency_2_2,
  input  [1:0]   io_in_1_bits_uop_srcLoadDependency_3_0,
  input  [1:0]   io_in_1_bits_uop_srcLoadDependency_3_1,
  input  [1:0]   io_in_1_bits_uop_srcLoadDependency_3_2,
  input  [7:0]   io_in_1_bits_uop_psrc_0,
  input  [7:0]   io_in_1_bits_uop_psrc_1,
  input  [7:0]   io_in_1_bits_uop_psrc_2,
  input  [7:0]   io_in_1_bits_uop_psrc_3,
  input  [7:0]   io_in_1_bits_uop_pdest,
  input  [4:0]   io_in_1_bits_uop_pdestVl,
  input  [1:0]   io_in_1_bits_uop_rasAction,
  input          io_in_1_bits_uop_useRegCache_0,
  input          io_in_1_bits_uop_useRegCache_1,
  input  [5:0]   io_in_1_bits_uop_regCacheIdx_0,
  input  [5:0]   io_in_1_bits_uop_regCacheIdx_1,
  input          io_in_1_bits_uop_robIdx_flag,
  input  [5:0]   io_in_1_bits_uop_robIdx_value,
  input          io_in_1_bits_uop_dirtyFs,
  input          io_in_1_bits_uop_dirtyVs,
  input  [3:0]   io_in_1_bits_uop_traceBlockInPipe_itype,
  input  [5:0]   io_in_1_bits_uop_traceBlockInPipe_iretire,
  input          io_in_1_bits_uop_traceBlockInPipe_ilastsize,
  input          io_in_1_bits_uop_snapshot,
  input          io_in_1_bits_uop_perfDebugInfo_eliminatedMove,
  input  [63:0]  io_in_1_bits_uop_perfDebugInfo_renameTime,
  input  [63:0]  io_in_1_bits_uop_perfDebugInfo_dispatchTime,
  input  [63:0]  io_in_1_bits_uop_perfDebugInfo_enqRsTime,
  input  [63:0]  io_in_1_bits_uop_perfDebugInfo_selectTime,
  input  [63:0]  io_in_1_bits_uop_perfDebugInfo_issueTime,
  input  [63:0]  io_in_1_bits_uop_perfDebugInfo_writebackTime,
  input  [63:0]  io_in_1_bits_uop_perfDebugInfo_runahead_checkpoint_id,
  input  [63:0]  io_in_1_bits_uop_perfDebugInfo_tlbFirstReqTime,
  input  [63:0]  io_in_1_bits_uop_perfDebugInfo_tlbRespTime,
  input  [55:0]  io_in_1_bits_uop_debug_seqNum_seqNum,
  input  [7:0]   io_in_1_bits_uop_debug_seqNum_uopIdx,
  input          io_in_1_bits_uop_storeSetHit,
  input          io_in_1_bits_uop_waitForRobIdx_flag,
  input  [5:0]   io_in_1_bits_uop_waitForRobIdx_value,
  input          io_in_1_bits_uop_loadWaitBit,
  input          io_in_1_bits_uop_loadWaitStrict,
  input  [5:0]   io_in_1_bits_uop_ssid,
  input          io_in_1_bits_uop_nc,
  input          io_in_1_bits_uop_mmio,
  input          io_in_1_bits_uop_lqIdx_flag,
  input  [4:0]   io_in_1_bits_uop_lqIdx_value,
  input          io_in_1_bits_uop_sqIdx_first_flag,
  input          io_in_1_bits_uop_sqIdx_second_flag,
  input  [3:0]   io_in_1_bits_uop_sqIdx_value,
  input          io_in_1_bits_uop_singleStep,
  input          io_in_1_bits_uop_replayInst,
  input  [35:0]  io_in_1_bits_uop_debug_fuType,
  input          io_in_1_bits_uop_debug_sim_trig,
  input  [4:0]   io_in_1_bits_uop_numLsElem,
  input  [49:0]  io_in_1_bits_vaddr,
  input  [63:0]  io_in_1_bits_fullva,
  input  [2:0]   io_in_1_bits_size,
  input  [15:0]  io_in_1_bits_mask,
  input  [7:0]   io_in_1_bits_elemIdx,
  input  [3:0]   io_in_1_bits_mbIndex,
  output         io_in_2_ready,
  input          io_in_2_valid,
  input          io_in_2_bits_accessType_isCbo,
  input          io_in_2_bits_accessType_isCboNoZero,
  input  [49:0]  io_in_2_bits_uop_pc,
  input          io_in_2_bits_uop_isRVC,
  input          io_in_2_bits_uop_ftqPtr_flag,
  input  [2:0]   io_in_2_bits_uop_ftqPtr_value,
  input  [3:0]   io_in_2_bits_uop_ftqOffset,
  input  [35:0]  io_in_2_bits_uop_fuType,
  input  [8:0]   io_in_2_bits_uop_fuOpType,
  input          io_in_2_bits_uop_rfWen,
  input  [31:0]  io_in_2_bits_uop_imm,
  input  [7:0]   io_in_2_bits_uop_pdest,
  input          io_in_2_bits_uop_robIdx_flag,
  input  [5:0]   io_in_2_bits_uop_robIdx_value,
  input          io_in_2_bits_uop_perfDebugInfo_eliminatedMove,
  input  [63:0]  io_in_2_bits_uop_perfDebugInfo_renameTime,
  input  [63:0]  io_in_2_bits_uop_perfDebugInfo_dispatchTime,
  input  [63:0]  io_in_2_bits_uop_perfDebugInfo_enqRsTime,
  input  [63:0]  io_in_2_bits_uop_perfDebugInfo_selectTime,
  input  [63:0]  io_in_2_bits_uop_perfDebugInfo_issueTime,
  input  [63:0]  io_in_2_bits_uop_perfDebugInfo_writebackTime,
  input  [63:0]  io_in_2_bits_uop_perfDebugInfo_runahead_checkpoint_id,
  input  [63:0]  io_in_2_bits_uop_perfDebugInfo_tlbFirstReqTime,
  input  [63:0]  io_in_2_bits_uop_perfDebugInfo_tlbRespTime,
  input  [55:0]  io_in_2_bits_uop_debug_seqNum_seqNum,
  input  [7:0]   io_in_2_bits_uop_debug_seqNum_uopIdx,
  input          io_in_2_bits_uop_storeSetHit,
  input  [5:0]   io_in_2_bits_uop_ssid,
  input          io_in_2_bits_uop_sqIdx_first_flag,
  input          io_in_2_bits_uop_sqIdx_second_flag,
  input  [3:0]   io_in_2_bits_uop_sqIdx_value,
  input  [49:0]  io_in_2_bits_vaddr,
  input  [63:0]  io_in_2_bits_fullva,
  input  [2:0]   io_in_2_bits_size,
  input  [15:0]  io_in_2_bits_mask,
  input          io_in_2_bits_isFirstIssue,
  input  [5:0]   io_in_2_bits_ssid,
  input          io_in_2_bits_storeSetHit,
  output         io_out_valid,
  output [3:0]   io_out_bits_entrance,
  output [2:0]   io_out_bits_accessType_instrType,
  output         io_out_bits_accessType_isCbo,
  output         io_out_bits_accessType_isCboNoZero,
  output [31:0]  io_out_bits_uop_instr,
  output [49:0]  io_out_bits_uop_pc,
  output [9:0]   io_out_bits_uop_foldpc,
  output         io_out_bits_uop_exceptionVec_23,
  output         io_out_bits_uop_exceptionVec_22,
  output         io_out_bits_uop_exceptionVec_21,
  output         io_out_bits_uop_exceptionVec_20,
  output         io_out_bits_uop_exceptionVec_19,
  output         io_out_bits_uop_exceptionVec_18,
  output         io_out_bits_uop_exceptionVec_16,
  output         io_out_bits_uop_exceptionVec_15,
  output         io_out_bits_uop_exceptionVec_13,
  output         io_out_bits_uop_exceptionVec_12,
  output         io_out_bits_uop_exceptionVec_11,
  output         io_out_bits_uop_exceptionVec_10,
  output         io_out_bits_uop_exceptionVec_9,
  output         io_out_bits_uop_exceptionVec_8,
  output         io_out_bits_uop_exceptionVec_7,
  output         io_out_bits_uop_exceptionVec_6,
  output         io_out_bits_uop_exceptionVec_5,
  output         io_out_bits_uop_exceptionVec_4,
  output         io_out_bits_uop_exceptionVec_3,
  output         io_out_bits_uop_exceptionVec_2,
  output         io_out_bits_uop_exceptionVec_1,
  output         io_out_bits_uop_exceptionVec_0,
  output         io_out_bits_uop_isFetchMalAddr,
  output         io_out_bits_uop_hasException,
  output [3:0]   io_out_bits_uop_trigger,
  output         io_out_bits_uop_isRVC,
  output         io_out_bits_uop_fixedTaken,
  output         io_out_bits_uop_predTaken,
  output         io_out_bits_uop_crossPageIPFFix,
  output         io_out_bits_uop_ftqPtr_flag,
  output [2:0]   io_out_bits_uop_ftqPtr_value,
  output [3:0]   io_out_bits_uop_ftqOffset,
  output [3:0]   io_out_bits_uop_ftqLastOffset,
  output         io_out_bits_uop_stdwriteNeed,
  output [3:0]   io_out_bits_uop_srcType_0,
  output [3:0]   io_out_bits_uop_srcType_1,
  output [3:0]   io_out_bits_uop_srcType_2,
  output [3:0]   io_out_bits_uop_srcType_3,
  output [5:0]   io_out_bits_uop_ldest,
  output [35:0]  io_out_bits_uop_fuType,
  output [8:0]   io_out_bits_uop_fuOpType,
  output         io_out_bits_uop_rfWen,
  output         io_out_bits_uop_fpWen,
  output         io_out_bits_uop_vecWen,
  output         io_out_bits_uop_v0Wen,
  output         io_out_bits_uop_vlWen,
  output         io_out_bits_uop_isXSTrap,
  output         io_out_bits_uop_waitForward,
  output         io_out_bits_uop_blockBackward,
  output         io_out_bits_uop_flushPipe,
  output         io_out_bits_uop_canRobCompress,
  output [1:0]   io_out_bits_uop_fusionNum,
  output [3:0]   io_out_bits_uop_selImm,
  output [31:0]  io_out_bits_uop_imm,
  output         io_out_bits_uop_fpu_wflags,
  output [1:0]   io_out_bits_uop_fpu_fmt,
  output [2:0]   io_out_bits_uop_fpu_rm,
  output         io_out_bits_uop_vpu_vill,
  output         io_out_bits_uop_vpu_vma,
  output         io_out_bits_uop_vpu_vta,
  output [1:0]   io_out_bits_uop_vpu_vsew,
  output [2:0]   io_out_bits_uop_vpu_vlmul,
  output         io_out_bits_uop_vpu_specVill,
  output         io_out_bits_uop_vpu_specVma,
  output         io_out_bits_uop_vpu_specVta,
  output [1:0]   io_out_bits_uop_vpu_specVsew,
  output [2:0]   io_out_bits_uop_vpu_specVlmul,
  output         io_out_bits_uop_vpu_vm,
  output [7:0]   io_out_bits_uop_vpu_vstart,
  output [2:0]   io_out_bits_uop_vpu_frm,
  output         io_out_bits_uop_vpu_fpu_isFpToVecInst,
  output         io_out_bits_uop_vpu_fpu_isFP32Instr,
  output         io_out_bits_uop_vpu_fpu_isFP64Instr,
  output         io_out_bits_uop_vpu_fpu_isReduction,
  output         io_out_bits_uop_vpu_fpu_isFoldTo1_2,
  output         io_out_bits_uop_vpu_fpu_isFoldTo1_4,
  output         io_out_bits_uop_vpu_fpu_isFoldTo1_8,
  output [1:0]   io_out_bits_uop_vpu_vxrm,
  output [6:0]   io_out_bits_uop_vpu_vuopIdx,
  output         io_out_bits_uop_vpu_lastUop,
  output [127:0] io_out_bits_uop_vpu_vmask,
  output [7:0]   io_out_bits_uop_vpu_vl,
  output [2:0]   io_out_bits_uop_vpu_nf,
  output [1:0]   io_out_bits_uop_vpu_veew,
  output         io_out_bits_uop_vpu_isReverse,
  output         io_out_bits_uop_vpu_isExt,
  output         io_out_bits_uop_vpu_isNarrow,
  output         io_out_bits_uop_vpu_isDstMask,
  output         io_out_bits_uop_vpu_isOpMask,
  output         io_out_bits_uop_vpu_isMove,
  output         io_out_bits_uop_vpu_isDependOldVd,
  output         io_out_bits_uop_vpu_isWritePartVd,
  output         io_out_bits_uop_vpu_isVleff,
  output [15:0]  io_out_bits_uop_vpu_maskVecGen,
  output         io_out_bits_uop_vpu_sew8,
  output         io_out_bits_uop_vpu_sew16,
  output         io_out_bits_uop_vpu_sew32,
  output         io_out_bits_uop_vpu_sew64,
  output         io_out_bits_uop_vlsInstr,
  output         io_out_bits_uop_wfflags,
  output         io_out_bits_uop_isMove,
  output         io_out_bits_uop_isDropAmocasSta,
  output [6:0]   io_out_bits_uop_uopIdx,
  output         io_out_bits_uop_isVset,
  output         io_out_bits_uop_firstUop,
  output         io_out_bits_uop_lastUop,
  output [6:0]   io_out_bits_uop_numUops,
  output [6:0]   io_out_bits_uop_numWB,
  output [1:0]   io_out_bits_uop_commitType,
  output         io_out_bits_uop_srcState_0,
  output         io_out_bits_uop_srcState_1,
  output         io_out_bits_uop_srcState_2,
  output         io_out_bits_uop_srcState_3,
  output [1:0]   io_out_bits_uop_srcLoadDependency_0_0,
  output [1:0]   io_out_bits_uop_srcLoadDependency_0_1,
  output [1:0]   io_out_bits_uop_srcLoadDependency_0_2,
  output [1:0]   io_out_bits_uop_srcLoadDependency_1_0,
  output [1:0]   io_out_bits_uop_srcLoadDependency_1_1,
  output [1:0]   io_out_bits_uop_srcLoadDependency_1_2,
  output [1:0]   io_out_bits_uop_srcLoadDependency_2_0,
  output [1:0]   io_out_bits_uop_srcLoadDependency_2_1,
  output [1:0]   io_out_bits_uop_srcLoadDependency_2_2,
  output [1:0]   io_out_bits_uop_srcLoadDependency_3_0,
  output [1:0]   io_out_bits_uop_srcLoadDependency_3_1,
  output [1:0]   io_out_bits_uop_srcLoadDependency_3_2,
  output [7:0]   io_out_bits_uop_psrc_0,
  output [7:0]   io_out_bits_uop_psrc_1,
  output [7:0]   io_out_bits_uop_psrc_2,
  output [7:0]   io_out_bits_uop_psrc_3,
  output [7:0]   io_out_bits_uop_pdest,
  output [4:0]   io_out_bits_uop_pdestVl,
  output [1:0]   io_out_bits_uop_rasAction,
  output         io_out_bits_uop_useRegCache_0,
  output         io_out_bits_uop_useRegCache_1,
  output [5:0]   io_out_bits_uop_regCacheIdx_0,
  output [5:0]   io_out_bits_uop_regCacheIdx_1,
  output         io_out_bits_uop_robIdx_flag,
  output [5:0]   io_out_bits_uop_robIdx_value,
  output         io_out_bits_uop_dirtyFs,
  output         io_out_bits_uop_dirtyVs,
  output [3:0]   io_out_bits_uop_traceBlockInPipe_itype,
  output [5:0]   io_out_bits_uop_traceBlockInPipe_iretire,
  output         io_out_bits_uop_traceBlockInPipe_ilastsize,
  output         io_out_bits_uop_snapshot,
  output         io_out_bits_uop_perfDebugInfo_eliminatedMove,
  output [63:0]  io_out_bits_uop_perfDebugInfo_renameTime,
  output [63:0]  io_out_bits_uop_perfDebugInfo_dispatchTime,
  output [63:0]  io_out_bits_uop_perfDebugInfo_enqRsTime,
  output [63:0]  io_out_bits_uop_perfDebugInfo_selectTime,
  output [63:0]  io_out_bits_uop_perfDebugInfo_issueTime,
  output [63:0]  io_out_bits_uop_perfDebugInfo_writebackTime,
  output [63:0]  io_out_bits_uop_perfDebugInfo_runahead_checkpoint_id,
  output [63:0]  io_out_bits_uop_perfDebugInfo_tlbFirstReqTime,
  output [63:0]  io_out_bits_uop_perfDebugInfo_tlbRespTime,
  output [55:0]  io_out_bits_uop_debug_seqNum_seqNum,
  output [7:0]   io_out_bits_uop_debug_seqNum_uopIdx,
  output         io_out_bits_uop_storeSetHit,
  output         io_out_bits_uop_waitForRobIdx_flag,
  output [5:0]   io_out_bits_uop_waitForRobIdx_value,
  output         io_out_bits_uop_loadWaitBit,
  output         io_out_bits_uop_loadWaitStrict,
  output [5:0]   io_out_bits_uop_ssid,
  output         io_out_bits_uop_nc,
  output         io_out_bits_uop_mmio,
  output         io_out_bits_uop_lqIdx_flag,
  output [4:0]   io_out_bits_uop_lqIdx_value,
  output         io_out_bits_uop_sqIdx_first_flag,
  output         io_out_bits_uop_sqIdx_second_flag,
  output [3:0]   io_out_bits_uop_sqIdx_value,
  output         io_out_bits_uop_singleStep,
  output         io_out_bits_uop_replayInst,
  output [35:0]  io_out_bits_uop_debug_fuType,
  output         io_out_bits_uop_debug_sim_trig,
  output [4:0]   io_out_bits_uop_numLsElem,
  output [49:0]  io_out_bits_vaddr,
  output [63:0]  io_out_bits_fullva,
  output [2:0]   io_out_bits_size,
  output [15:0]  io_out_bits_mask,
  output         io_out_bits_isFirstIssue,
  output [5:0]   io_out_bits_ssid,
  output         io_out_bits_storeSetHit,
  output [7:0]   io_out_bits_elemIdx,
  output [3:0]   io_out_bits_mbIndex
);

  wire _GEN = io_in_0_valid | io_in_1_valid;
  wire _grant_T = io_in_0_valid | io_in_1_valid;
  assign io_in_1_ready = ~io_in_0_valid;
  assign io_in_2_ready = ~_grant_T;
  assign io_out_valid = _grant_T | io_in_2_valid;
  assign io_out_bits_entrance =
    io_in_0_valid ? 4'h1 : io_in_1_valid ? 4'h4 : io_in_2_valid ? 4'h8 : 4'h2;
  assign io_out_bits_accessType_instrType =
    io_in_0_valid
      ? io_in_0_bits_accessType_instrType
      : io_in_1_valid ? 3'h2 : io_in_2_valid ? 3'h1 : 3'h4;
  assign io_out_bits_accessType_isCbo =
    io_in_0_valid
      ? io_in_0_bits_accessType_isCbo
      : ~io_in_1_valid & io_in_2_valid & io_in_2_bits_accessType_isCbo;
  assign io_out_bits_accessType_isCboNoZero =
    io_in_0_valid
      ? io_in_0_bits_accessType_isCboNoZero
      : ~io_in_1_valid & io_in_2_valid & io_in_2_bits_accessType_isCboNoZero;
  assign io_out_bits_uop_instr =
    io_in_0_valid
      ? io_in_0_bits_uop_instr
      : io_in_1_valid ? io_in_1_bits_uop_instr : 32'h0;
  assign io_out_bits_uop_pc =
    io_in_0_valid
      ? io_in_0_bits_uop_pc
      : io_in_1_valid ? io_in_1_bits_uop_pc : io_in_2_valid ? io_in_2_bits_uop_pc : 50'h0;
  assign io_out_bits_uop_foldpc =
    io_in_0_valid
      ? io_in_0_bits_uop_foldpc
      : io_in_1_valid ? io_in_1_bits_uop_foldpc : 10'h0;
  assign io_out_bits_uop_exceptionVec_23 =
    io_in_0_valid
      ? io_in_0_bits_uop_exceptionVec_23
      : io_in_1_valid & io_in_1_bits_uop_exceptionVec_23;
  assign io_out_bits_uop_exceptionVec_22 =
    io_in_0_valid & io_in_0_bits_uop_exceptionVec_22;
  assign io_out_bits_uop_exceptionVec_21 =
    io_in_0_valid & io_in_0_bits_uop_exceptionVec_21;
  assign io_out_bits_uop_exceptionVec_20 =
    io_in_0_valid & io_in_0_bits_uop_exceptionVec_20;
  assign io_out_bits_uop_exceptionVec_19 =
    io_in_0_valid
      ? io_in_0_bits_uop_exceptionVec_19
      : io_in_1_valid & io_in_1_bits_uop_exceptionVec_19;
  assign io_out_bits_uop_exceptionVec_18 =
    io_in_0_valid & io_in_0_bits_uop_exceptionVec_18;
  assign io_out_bits_uop_exceptionVec_16 =
    io_in_0_valid & io_in_0_bits_uop_exceptionVec_16;
  assign io_out_bits_uop_exceptionVec_15 =
    io_in_0_valid
      ? io_in_0_bits_uop_exceptionVec_15
      : io_in_1_valid & io_in_1_bits_uop_exceptionVec_15;
  assign io_out_bits_uop_exceptionVec_13 =
    io_in_0_valid & io_in_0_bits_uop_exceptionVec_13;
  assign io_out_bits_uop_exceptionVec_12 =
    io_in_0_valid & io_in_0_bits_uop_exceptionVec_12;
  assign io_out_bits_uop_exceptionVec_11 =
    io_in_0_valid & io_in_0_bits_uop_exceptionVec_11;
  assign io_out_bits_uop_exceptionVec_10 =
    io_in_0_valid & io_in_0_bits_uop_exceptionVec_10;
  assign io_out_bits_uop_exceptionVec_9 = io_in_0_valid & io_in_0_bits_uop_exceptionVec_9;
  assign io_out_bits_uop_exceptionVec_8 = io_in_0_valid & io_in_0_bits_uop_exceptionVec_8;
  assign io_out_bits_uop_exceptionVec_7 =
    io_in_0_valid
      ? io_in_0_bits_uop_exceptionVec_7
      : io_in_1_valid & io_in_1_bits_uop_exceptionVec_7;
  assign io_out_bits_uop_exceptionVec_6 =
    io_in_0_valid
      ? io_in_0_bits_uop_exceptionVec_6
      : io_in_1_valid & io_in_1_bits_uop_exceptionVec_6;
  assign io_out_bits_uop_exceptionVec_5 = io_in_0_valid & io_in_0_bits_uop_exceptionVec_5;
  assign io_out_bits_uop_exceptionVec_4 = io_in_0_valid & io_in_0_bits_uop_exceptionVec_4;
  assign io_out_bits_uop_exceptionVec_3 =
    io_in_0_valid
      ? io_in_0_bits_uop_exceptionVec_3
      : io_in_1_valid & io_in_1_bits_uop_exceptionVec_3;
  assign io_out_bits_uop_exceptionVec_2 = io_in_0_valid & io_in_0_bits_uop_exceptionVec_2;
  assign io_out_bits_uop_exceptionVec_1 = io_in_0_valid & io_in_0_bits_uop_exceptionVec_1;
  assign io_out_bits_uop_exceptionVec_0 = io_in_0_valid & io_in_0_bits_uop_exceptionVec_0;
  assign io_out_bits_uop_isFetchMalAddr =
    io_in_0_valid
      ? io_in_0_bits_uop_isFetchMalAddr
      : io_in_1_valid & io_in_1_bits_uop_isFetchMalAddr;
  assign io_out_bits_uop_hasException =
    io_in_0_valid
      ? io_in_0_bits_uop_hasException
      : io_in_1_valid & io_in_1_bits_uop_hasException;
  assign io_out_bits_uop_trigger =
    io_in_0_valid
      ? io_in_0_bits_uop_trigger
      : io_in_1_valid ? io_in_1_bits_uop_trigger : 4'h0;
  assign io_out_bits_uop_isRVC =
    io_in_0_valid
      ? io_in_0_bits_uop_isRVC
      : io_in_1_valid ? io_in_1_bits_uop_isRVC : io_in_2_valid & io_in_2_bits_uop_isRVC;
  assign io_out_bits_uop_fixedTaken =
    io_in_0_valid
      ? io_in_0_bits_uop_fixedTaken
      : io_in_1_valid & io_in_1_bits_uop_fixedTaken;
  assign io_out_bits_uop_predTaken =
    io_in_0_valid
      ? io_in_0_bits_uop_predTaken
      : io_in_1_valid & io_in_1_bits_uop_predTaken;
  assign io_out_bits_uop_crossPageIPFFix =
    io_in_0_valid
      ? io_in_0_bits_uop_crossPageIPFFix
      : io_in_1_valid & io_in_1_bits_uop_crossPageIPFFix;
  assign io_out_bits_uop_ftqPtr_flag =
    io_in_0_valid
      ? io_in_0_bits_uop_ftqPtr_flag
      : io_in_1_valid
          ? io_in_1_bits_uop_ftqPtr_flag
          : io_in_2_valid & io_in_2_bits_uop_ftqPtr_flag;
  assign io_out_bits_uop_ftqPtr_value =
    io_in_0_valid
      ? io_in_0_bits_uop_ftqPtr_value
      : io_in_1_valid
          ? io_in_1_bits_uop_ftqPtr_value
          : io_in_2_valid ? io_in_2_bits_uop_ftqPtr_value : 3'h0;
  assign io_out_bits_uop_ftqOffset =
    io_in_0_valid
      ? io_in_0_bits_uop_ftqOffset
      : io_in_1_valid
          ? io_in_1_bits_uop_ftqOffset
          : io_in_2_valid ? io_in_2_bits_uop_ftqOffset : 4'h0;
  assign io_out_bits_uop_ftqLastOffset =
    io_in_0_valid
      ? io_in_0_bits_uop_ftqLastOffset
      : io_in_1_valid ? io_in_1_bits_uop_ftqLastOffset : 4'h0;
  assign io_out_bits_uop_stdwriteNeed =
    io_in_0_valid
      ? io_in_0_bits_uop_stdwriteNeed
      : io_in_1_valid & io_in_1_bits_uop_stdwriteNeed;
  assign io_out_bits_uop_srcType_0 =
    io_in_0_valid
      ? io_in_0_bits_uop_srcType_0
      : io_in_1_valid ? io_in_1_bits_uop_srcType_0 : 4'h0;
  assign io_out_bits_uop_srcType_1 =
    io_in_0_valid
      ? io_in_0_bits_uop_srcType_1
      : io_in_1_valid ? io_in_1_bits_uop_srcType_1 : 4'h0;
  assign io_out_bits_uop_srcType_2 =
    io_in_0_valid
      ? io_in_0_bits_uop_srcType_2
      : io_in_1_valid ? io_in_1_bits_uop_srcType_2 : 4'h0;
  assign io_out_bits_uop_srcType_3 =
    io_in_0_valid
      ? io_in_0_bits_uop_srcType_3
      : io_in_1_valid ? io_in_1_bits_uop_srcType_3 : 4'h0;
  assign io_out_bits_uop_ldest =
    io_in_0_valid
      ? io_in_0_bits_uop_ldest
      : io_in_1_valid ? io_in_1_bits_uop_ldest : 6'h0;
  assign io_out_bits_uop_fuType =
    io_in_0_valid
      ? io_in_0_bits_uop_fuType
      : io_in_1_valid
          ? io_in_1_bits_uop_fuType
          : io_in_2_valid ? io_in_2_bits_uop_fuType : 36'h0;
  assign io_out_bits_uop_fuOpType =
    io_in_0_valid
      ? io_in_0_bits_uop_fuOpType
      : io_in_1_valid
          ? io_in_1_bits_uop_fuOpType
          : io_in_2_valid ? io_in_2_bits_uop_fuOpType : 9'h0;
  assign io_out_bits_uop_rfWen =
    io_in_0_valid
      ? io_in_0_bits_uop_rfWen
      : io_in_1_valid ? io_in_1_bits_uop_rfWen : io_in_2_valid & io_in_2_bits_uop_rfWen;
  assign io_out_bits_uop_fpWen =
    io_in_0_valid ? io_in_0_bits_uop_fpWen : io_in_1_valid & io_in_1_bits_uop_fpWen;
  assign io_out_bits_uop_vecWen =
    io_in_0_valid ? io_in_0_bits_uop_vecWen : io_in_1_valid & io_in_1_bits_uop_vecWen;
  assign io_out_bits_uop_v0Wen =
    io_in_0_valid ? io_in_0_bits_uop_v0Wen : io_in_1_valid & io_in_1_bits_uop_v0Wen;
  assign io_out_bits_uop_vlWen =
    io_in_0_valid ? io_in_0_bits_uop_vlWen : io_in_1_valid & io_in_1_bits_uop_vlWen;
  assign io_out_bits_uop_isXSTrap =
    io_in_0_valid ? io_in_0_bits_uop_isXSTrap : io_in_1_valid & io_in_1_bits_uop_isXSTrap;
  assign io_out_bits_uop_waitForward =
    io_in_0_valid
      ? io_in_0_bits_uop_waitForward
      : io_in_1_valid & io_in_1_bits_uop_waitForward;
  assign io_out_bits_uop_blockBackward =
    io_in_0_valid
      ? io_in_0_bits_uop_blockBackward
      : io_in_1_valid & io_in_1_bits_uop_blockBackward;
  assign io_out_bits_uop_flushPipe =
    io_in_0_valid
      ? io_in_0_bits_uop_flushPipe
      : io_in_1_valid & io_in_1_bits_uop_flushPipe;
  assign io_out_bits_uop_canRobCompress =
    io_in_0_valid
      ? io_in_0_bits_uop_canRobCompress
      : io_in_1_valid & io_in_1_bits_uop_canRobCompress;
  assign io_out_bits_uop_fusionNum =
    io_in_0_valid
      ? io_in_0_bits_uop_fusionNum
      : io_in_1_valid ? io_in_1_bits_uop_fusionNum : 2'h0;
  assign io_out_bits_uop_selImm =
    io_in_0_valid
      ? io_in_0_bits_uop_selImm
      : io_in_1_valid ? io_in_1_bits_uop_selImm : 4'h0;
  assign io_out_bits_uop_imm =
    io_in_0_valid
      ? io_in_0_bits_uop_imm
      : io_in_1_valid | ~io_in_2_valid ? 32'h0 : io_in_2_bits_uop_imm;
  assign io_out_bits_uop_fpu_wflags =
    io_in_0_valid
      ? io_in_0_bits_uop_fpu_wflags
      : io_in_1_valid & io_in_1_bits_uop_fpu_wflags;
  assign io_out_bits_uop_fpu_fmt =
    io_in_0_valid
      ? io_in_0_bits_uop_fpu_fmt
      : io_in_1_valid ? io_in_1_bits_uop_fpu_fmt : 2'h0;
  assign io_out_bits_uop_fpu_rm =
    io_in_0_valid
      ? io_in_0_bits_uop_fpu_rm
      : io_in_1_valid ? io_in_1_bits_uop_fpu_rm : 3'h0;
  assign io_out_bits_uop_vpu_vill =
    io_in_0_valid ? io_in_0_bits_uop_vpu_vill : io_in_1_valid & io_in_1_bits_uop_vpu_vill;
  assign io_out_bits_uop_vpu_vma =
    io_in_0_valid ? io_in_0_bits_uop_vpu_vma : io_in_1_valid & io_in_1_bits_uop_vpu_vma;
  assign io_out_bits_uop_vpu_vta =
    io_in_0_valid ? io_in_0_bits_uop_vpu_vta : io_in_1_valid & io_in_1_bits_uop_vpu_vta;
  assign io_out_bits_uop_vpu_vsew =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_vsew
      : io_in_1_valid ? io_in_1_bits_uop_vpu_vsew : 2'h0;
  assign io_out_bits_uop_vpu_vlmul =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_vlmul
      : io_in_1_valid ? io_in_1_bits_uop_vpu_vlmul : 3'h0;
  assign io_out_bits_uop_vpu_specVill =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_specVill
      : io_in_1_valid & io_in_1_bits_uop_vpu_specVill;
  assign io_out_bits_uop_vpu_specVma =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_specVma
      : io_in_1_valid & io_in_1_bits_uop_vpu_specVma;
  assign io_out_bits_uop_vpu_specVta =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_specVta
      : io_in_1_valid & io_in_1_bits_uop_vpu_specVta;
  assign io_out_bits_uop_vpu_specVsew =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_specVsew
      : io_in_1_valid ? io_in_1_bits_uop_vpu_specVsew : 2'h0;
  assign io_out_bits_uop_vpu_specVlmul =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_specVlmul
      : io_in_1_valid ? io_in_1_bits_uop_vpu_specVlmul : 3'h0;
  assign io_out_bits_uop_vpu_vm =
    io_in_0_valid ? io_in_0_bits_uop_vpu_vm : io_in_1_valid & io_in_1_bits_uop_vpu_vm;
  assign io_out_bits_uop_vpu_vstart =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_vstart
      : io_in_1_valid ? io_in_1_bits_uop_vpu_vstart : 8'h0;
  assign io_out_bits_uop_vpu_frm =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_frm
      : io_in_1_valid ? io_in_1_bits_uop_vpu_frm : 3'h0;
  assign io_out_bits_uop_vpu_fpu_isFpToVecInst =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_fpu_isFpToVecInst
      : io_in_1_valid & io_in_1_bits_uop_vpu_fpu_isFpToVecInst;
  assign io_out_bits_uop_vpu_fpu_isFP32Instr =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_fpu_isFP32Instr
      : io_in_1_valid & io_in_1_bits_uop_vpu_fpu_isFP32Instr;
  assign io_out_bits_uop_vpu_fpu_isFP64Instr =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_fpu_isFP64Instr
      : io_in_1_valid & io_in_1_bits_uop_vpu_fpu_isFP64Instr;
  assign io_out_bits_uop_vpu_fpu_isReduction =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_fpu_isReduction
      : io_in_1_valid & io_in_1_bits_uop_vpu_fpu_isReduction;
  assign io_out_bits_uop_vpu_fpu_isFoldTo1_2 =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_fpu_isFoldTo1_2
      : io_in_1_valid & io_in_1_bits_uop_vpu_fpu_isFoldTo1_2;
  assign io_out_bits_uop_vpu_fpu_isFoldTo1_4 =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_fpu_isFoldTo1_4
      : io_in_1_valid & io_in_1_bits_uop_vpu_fpu_isFoldTo1_4;
  assign io_out_bits_uop_vpu_fpu_isFoldTo1_8 =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_fpu_isFoldTo1_8
      : io_in_1_valid & io_in_1_bits_uop_vpu_fpu_isFoldTo1_8;
  assign io_out_bits_uop_vpu_vxrm =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_vxrm
      : io_in_1_valid ? io_in_1_bits_uop_vpu_vxrm : 2'h0;
  assign io_out_bits_uop_vpu_vuopIdx =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_vuopIdx
      : io_in_1_valid ? io_in_1_bits_uop_vpu_vuopIdx : 7'h0;
  assign io_out_bits_uop_vpu_lastUop =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_lastUop
      : io_in_1_valid & io_in_1_bits_uop_vpu_lastUop;
  assign io_out_bits_uop_vpu_vmask =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_vmask
      : io_in_1_valid ? io_in_1_bits_uop_vpu_vmask : 128'h0;
  assign io_out_bits_uop_vpu_vl =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_vl
      : io_in_1_valid ? io_in_1_bits_uop_vpu_vl : 8'h0;
  assign io_out_bits_uop_vpu_nf =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_nf
      : io_in_1_valid ? io_in_1_bits_uop_vpu_nf : 3'h0;
  assign io_out_bits_uop_vpu_veew =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_veew
      : io_in_1_valid ? io_in_1_bits_uop_vpu_veew : 2'h0;
  assign io_out_bits_uop_vpu_isReverse =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_isReverse
      : io_in_1_valid & io_in_1_bits_uop_vpu_isReverse;
  assign io_out_bits_uop_vpu_isExt =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_isExt
      : io_in_1_valid & io_in_1_bits_uop_vpu_isExt;
  assign io_out_bits_uop_vpu_isNarrow =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_isNarrow
      : io_in_1_valid & io_in_1_bits_uop_vpu_isNarrow;
  assign io_out_bits_uop_vpu_isDstMask =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_isDstMask
      : io_in_1_valid & io_in_1_bits_uop_vpu_isDstMask;
  assign io_out_bits_uop_vpu_isOpMask =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_isOpMask
      : io_in_1_valid & io_in_1_bits_uop_vpu_isOpMask;
  assign io_out_bits_uop_vpu_isMove =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_isMove
      : io_in_1_valid & io_in_1_bits_uop_vpu_isMove;
  assign io_out_bits_uop_vpu_isDependOldVd =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_isDependOldVd
      : io_in_1_valid & io_in_1_bits_uop_vpu_isDependOldVd;
  assign io_out_bits_uop_vpu_isWritePartVd =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_isWritePartVd
      : io_in_1_valid & io_in_1_bits_uop_vpu_isWritePartVd;
  assign io_out_bits_uop_vpu_isVleff =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_isVleff
      : io_in_1_valid & io_in_1_bits_uop_vpu_isVleff;
  assign io_out_bits_uop_vpu_maskVecGen =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_maskVecGen
      : io_in_1_valid ? io_in_1_bits_uop_vpu_maskVecGen : 16'h0;
  assign io_out_bits_uop_vpu_sew8 =
    io_in_0_valid ? io_in_0_bits_uop_vpu_sew8 : io_in_1_valid & io_in_1_bits_uop_vpu_sew8;
  assign io_out_bits_uop_vpu_sew16 =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_sew16
      : io_in_1_valid & io_in_1_bits_uop_vpu_sew16;
  assign io_out_bits_uop_vpu_sew32 =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_sew32
      : io_in_1_valid & io_in_1_bits_uop_vpu_sew32;
  assign io_out_bits_uop_vpu_sew64 =
    io_in_0_valid
      ? io_in_0_bits_uop_vpu_sew64
      : io_in_1_valid & io_in_1_bits_uop_vpu_sew64;
  assign io_out_bits_uop_vlsInstr =
    io_in_0_valid ? io_in_0_bits_uop_vlsInstr : io_in_1_valid & io_in_1_bits_uop_vlsInstr;
  assign io_out_bits_uop_wfflags =
    io_in_0_valid ? io_in_0_bits_uop_wfflags : io_in_1_valid & io_in_1_bits_uop_wfflags;
  assign io_out_bits_uop_isMove =
    io_in_0_valid ? io_in_0_bits_uop_isMove : io_in_1_valid & io_in_1_bits_uop_isMove;
  assign io_out_bits_uop_isDropAmocasSta =
    io_in_0_valid
      ? io_in_0_bits_uop_isDropAmocasSta
      : io_in_1_valid & io_in_1_bits_uop_isDropAmocasSta;
  assign io_out_bits_uop_uopIdx =
    io_in_0_valid
      ? io_in_0_bits_uop_uopIdx
      : io_in_1_valid ? io_in_1_bits_uop_uopIdx : 7'h0;
  assign io_out_bits_uop_isVset =
    io_in_0_valid ? io_in_0_bits_uop_isVset : io_in_1_valid & io_in_1_bits_uop_isVset;
  assign io_out_bits_uop_firstUop =
    io_in_0_valid ? io_in_0_bits_uop_firstUop : io_in_1_valid & io_in_1_bits_uop_firstUop;
  assign io_out_bits_uop_lastUop =
    io_in_0_valid ? io_in_0_bits_uop_lastUop : io_in_1_valid & io_in_1_bits_uop_lastUop;
  assign io_out_bits_uop_numUops =
    io_in_0_valid
      ? io_in_0_bits_uop_numUops
      : io_in_1_valid ? io_in_1_bits_uop_numUops : 7'h0;
  assign io_out_bits_uop_numWB =
    io_in_0_valid
      ? io_in_0_bits_uop_numWB
      : io_in_1_valid ? io_in_1_bits_uop_numWB : 7'h0;
  assign io_out_bits_uop_commitType =
    io_in_0_valid
      ? io_in_0_bits_uop_commitType
      : io_in_1_valid ? io_in_1_bits_uop_commitType : 2'h0;
  assign io_out_bits_uop_srcState_0 =
    io_in_0_valid
      ? io_in_0_bits_uop_srcState_0
      : io_in_1_valid & io_in_1_bits_uop_srcState_0;
  assign io_out_bits_uop_srcState_1 =
    io_in_0_valid
      ? io_in_0_bits_uop_srcState_1
      : io_in_1_valid & io_in_1_bits_uop_srcState_1;
  assign io_out_bits_uop_srcState_2 =
    io_in_0_valid
      ? io_in_0_bits_uop_srcState_2
      : io_in_1_valid & io_in_1_bits_uop_srcState_2;
  assign io_out_bits_uop_srcState_3 =
    io_in_0_valid
      ? io_in_0_bits_uop_srcState_3
      : io_in_1_valid & io_in_1_bits_uop_srcState_3;
  assign io_out_bits_uop_srcLoadDependency_0_0 =
    io_in_0_valid
      ? io_in_0_bits_uop_srcLoadDependency_0_0
      : io_in_1_valid ? io_in_1_bits_uop_srcLoadDependency_0_0 : 2'h0;
  assign io_out_bits_uop_srcLoadDependency_0_1 =
    io_in_0_valid
      ? io_in_0_bits_uop_srcLoadDependency_0_1
      : io_in_1_valid ? io_in_1_bits_uop_srcLoadDependency_0_1 : 2'h0;
  assign io_out_bits_uop_srcLoadDependency_0_2 =
    io_in_0_valid
      ? io_in_0_bits_uop_srcLoadDependency_0_2
      : io_in_1_valid ? io_in_1_bits_uop_srcLoadDependency_0_2 : 2'h0;
  assign io_out_bits_uop_srcLoadDependency_1_0 =
    io_in_0_valid
      ? io_in_0_bits_uop_srcLoadDependency_1_0
      : io_in_1_valid ? io_in_1_bits_uop_srcLoadDependency_1_0 : 2'h0;
  assign io_out_bits_uop_srcLoadDependency_1_1 =
    io_in_0_valid
      ? io_in_0_bits_uop_srcLoadDependency_1_1
      : io_in_1_valid ? io_in_1_bits_uop_srcLoadDependency_1_1 : 2'h0;
  assign io_out_bits_uop_srcLoadDependency_1_2 =
    io_in_0_valid
      ? io_in_0_bits_uop_srcLoadDependency_1_2
      : io_in_1_valid ? io_in_1_bits_uop_srcLoadDependency_1_2 : 2'h0;
  assign io_out_bits_uop_srcLoadDependency_2_0 =
    io_in_0_valid
      ? io_in_0_bits_uop_srcLoadDependency_2_0
      : io_in_1_valid ? io_in_1_bits_uop_srcLoadDependency_2_0 : 2'h0;
  assign io_out_bits_uop_srcLoadDependency_2_1 =
    io_in_0_valid
      ? io_in_0_bits_uop_srcLoadDependency_2_1
      : io_in_1_valid ? io_in_1_bits_uop_srcLoadDependency_2_1 : 2'h0;
  assign io_out_bits_uop_srcLoadDependency_2_2 =
    io_in_0_valid
      ? io_in_0_bits_uop_srcLoadDependency_2_2
      : io_in_1_valid ? io_in_1_bits_uop_srcLoadDependency_2_2 : 2'h0;
  assign io_out_bits_uop_srcLoadDependency_3_0 =
    io_in_0_valid
      ? io_in_0_bits_uop_srcLoadDependency_3_0
      : io_in_1_valid ? io_in_1_bits_uop_srcLoadDependency_3_0 : 2'h0;
  assign io_out_bits_uop_srcLoadDependency_3_1 =
    io_in_0_valid
      ? io_in_0_bits_uop_srcLoadDependency_3_1
      : io_in_1_valid ? io_in_1_bits_uop_srcLoadDependency_3_1 : 2'h0;
  assign io_out_bits_uop_srcLoadDependency_3_2 =
    io_in_0_valid
      ? io_in_0_bits_uop_srcLoadDependency_3_2
      : io_in_1_valid ? io_in_1_bits_uop_srcLoadDependency_3_2 : 2'h0;
  assign io_out_bits_uop_psrc_0 =
    io_in_0_valid
      ? io_in_0_bits_uop_psrc_0
      : io_in_1_valid ? io_in_1_bits_uop_psrc_0 : 8'h0;
  assign io_out_bits_uop_psrc_1 =
    io_in_0_valid
      ? io_in_0_bits_uop_psrc_1
      : io_in_1_valid ? io_in_1_bits_uop_psrc_1 : 8'h0;
  assign io_out_bits_uop_psrc_2 =
    io_in_0_valid
      ? io_in_0_bits_uop_psrc_2
      : io_in_1_valid ? io_in_1_bits_uop_psrc_2 : 8'h0;
  assign io_out_bits_uop_psrc_3 =
    io_in_0_valid
      ? io_in_0_bits_uop_psrc_3
      : io_in_1_valid ? io_in_1_bits_uop_psrc_3 : 8'h0;
  assign io_out_bits_uop_pdest =
    io_in_0_valid
      ? io_in_0_bits_uop_pdest
      : io_in_1_valid
          ? io_in_1_bits_uop_pdest
          : io_in_2_valid ? io_in_2_bits_uop_pdest : 8'h0;
  assign io_out_bits_uop_pdestVl =
    io_in_0_valid
      ? io_in_0_bits_uop_pdestVl
      : io_in_1_valid ? io_in_1_bits_uop_pdestVl : 5'h0;
  assign io_out_bits_uop_rasAction =
    io_in_0_valid
      ? io_in_0_bits_uop_rasAction
      : io_in_1_valid ? io_in_1_bits_uop_rasAction : 2'h0;
  assign io_out_bits_uop_useRegCache_0 =
    io_in_0_valid
      ? io_in_0_bits_uop_useRegCache_0
      : io_in_1_valid & io_in_1_bits_uop_useRegCache_0;
  assign io_out_bits_uop_useRegCache_1 =
    io_in_0_valid
      ? io_in_0_bits_uop_useRegCache_1
      : io_in_1_valid & io_in_1_bits_uop_useRegCache_1;
  assign io_out_bits_uop_regCacheIdx_0 =
    io_in_0_valid
      ? io_in_0_bits_uop_regCacheIdx_0
      : io_in_1_valid ? io_in_1_bits_uop_regCacheIdx_0 : 6'h0;
  assign io_out_bits_uop_regCacheIdx_1 =
    io_in_0_valid
      ? io_in_0_bits_uop_regCacheIdx_1
      : io_in_1_valid ? io_in_1_bits_uop_regCacheIdx_1 : 6'h0;
  assign io_out_bits_uop_robIdx_flag =
    io_in_0_valid
      ? io_in_0_bits_uop_robIdx_flag
      : io_in_1_valid
          ? io_in_1_bits_uop_robIdx_flag
          : io_in_2_valid & io_in_2_bits_uop_robIdx_flag;
  assign io_out_bits_uop_robIdx_value =
    io_in_0_valid
      ? io_in_0_bits_uop_robIdx_value
      : io_in_1_valid
          ? io_in_1_bits_uop_robIdx_value
          : io_in_2_valid ? io_in_2_bits_uop_robIdx_value : 6'h0;
  assign io_out_bits_uop_dirtyFs =
    io_in_0_valid ? io_in_0_bits_uop_dirtyFs : io_in_1_valid & io_in_1_bits_uop_dirtyFs;
  assign io_out_bits_uop_dirtyVs =
    io_in_0_valid ? io_in_0_bits_uop_dirtyVs : io_in_1_valid & io_in_1_bits_uop_dirtyVs;
  assign io_out_bits_uop_traceBlockInPipe_itype =
    io_in_0_valid
      ? io_in_0_bits_uop_traceBlockInPipe_itype
      : io_in_1_valid ? io_in_1_bits_uop_traceBlockInPipe_itype : 4'h0;
  assign io_out_bits_uop_traceBlockInPipe_iretire =
    io_in_0_valid
      ? io_in_0_bits_uop_traceBlockInPipe_iretire
      : io_in_1_valid ? io_in_1_bits_uop_traceBlockInPipe_iretire : 6'h0;
  assign io_out_bits_uop_traceBlockInPipe_ilastsize =
    io_in_0_valid
      ? io_in_0_bits_uop_traceBlockInPipe_ilastsize
      : io_in_1_valid & io_in_1_bits_uop_traceBlockInPipe_ilastsize;
  assign io_out_bits_uop_snapshot =
    io_in_0_valid ? io_in_0_bits_uop_snapshot : io_in_1_valid & io_in_1_bits_uop_snapshot;
  assign io_out_bits_uop_perfDebugInfo_eliminatedMove =
    io_in_0_valid
      ? io_in_0_bits_uop_perfDebugInfo_eliminatedMove
      : io_in_1_valid
          ? io_in_1_bits_uop_perfDebugInfo_eliminatedMove
          : io_in_2_valid & io_in_2_bits_uop_perfDebugInfo_eliminatedMove;
  assign io_out_bits_uop_perfDebugInfo_renameTime =
    io_in_0_valid
      ? io_in_0_bits_uop_perfDebugInfo_renameTime
      : io_in_1_valid
          ? io_in_1_bits_uop_perfDebugInfo_renameTime
          : io_in_2_valid ? io_in_2_bits_uop_perfDebugInfo_renameTime : 64'h0;
  assign io_out_bits_uop_perfDebugInfo_dispatchTime =
    io_in_0_valid
      ? io_in_0_bits_uop_perfDebugInfo_dispatchTime
      : io_in_1_valid
          ? io_in_1_bits_uop_perfDebugInfo_dispatchTime
          : io_in_2_valid ? io_in_2_bits_uop_perfDebugInfo_dispatchTime : 64'h0;
  assign io_out_bits_uop_perfDebugInfo_enqRsTime =
    io_in_0_valid
      ? io_in_0_bits_uop_perfDebugInfo_enqRsTime
      : io_in_1_valid
          ? io_in_1_bits_uop_perfDebugInfo_enqRsTime
          : io_in_2_valid ? io_in_2_bits_uop_perfDebugInfo_enqRsTime : 64'h0;
  assign io_out_bits_uop_perfDebugInfo_selectTime =
    io_in_0_valid
      ? io_in_0_bits_uop_perfDebugInfo_selectTime
      : io_in_1_valid
          ? io_in_1_bits_uop_perfDebugInfo_selectTime
          : io_in_2_valid ? io_in_2_bits_uop_perfDebugInfo_selectTime : 64'h0;
  assign io_out_bits_uop_perfDebugInfo_issueTime =
    io_in_0_valid
      ? io_in_0_bits_uop_perfDebugInfo_issueTime
      : io_in_1_valid
          ? io_in_1_bits_uop_perfDebugInfo_issueTime
          : io_in_2_valid ? io_in_2_bits_uop_perfDebugInfo_issueTime : 64'h0;
  assign io_out_bits_uop_perfDebugInfo_writebackTime =
    io_in_0_valid
      ? io_in_0_bits_uop_perfDebugInfo_writebackTime
      : io_in_1_valid
          ? io_in_1_bits_uop_perfDebugInfo_writebackTime
          : io_in_2_valid ? io_in_2_bits_uop_perfDebugInfo_writebackTime : 64'h0;
  assign io_out_bits_uop_perfDebugInfo_runahead_checkpoint_id =
    io_in_0_valid
      ? io_in_0_bits_uop_perfDebugInfo_runahead_checkpoint_id
      : io_in_1_valid
          ? io_in_1_bits_uop_perfDebugInfo_runahead_checkpoint_id
          : io_in_2_valid ? io_in_2_bits_uop_perfDebugInfo_runahead_checkpoint_id : 64'h0;
  assign io_out_bits_uop_perfDebugInfo_tlbFirstReqTime =
    io_in_0_valid
      ? io_in_0_bits_uop_perfDebugInfo_tlbFirstReqTime
      : io_in_1_valid
          ? io_in_1_bits_uop_perfDebugInfo_tlbFirstReqTime
          : io_in_2_valid ? io_in_2_bits_uop_perfDebugInfo_tlbFirstReqTime : 64'h0;
  assign io_out_bits_uop_perfDebugInfo_tlbRespTime =
    io_in_0_valid
      ? io_in_0_bits_uop_perfDebugInfo_tlbRespTime
      : io_in_1_valid
          ? io_in_1_bits_uop_perfDebugInfo_tlbRespTime
          : io_in_2_valid ? io_in_2_bits_uop_perfDebugInfo_tlbRespTime : 64'h0;
  assign io_out_bits_uop_debug_seqNum_seqNum =
    io_in_0_valid
      ? io_in_0_bits_uop_debug_seqNum_seqNum
      : io_in_1_valid
          ? io_in_1_bits_uop_debug_seqNum_seqNum
          : io_in_2_valid ? io_in_2_bits_uop_debug_seqNum_seqNum : 56'h0;
  assign io_out_bits_uop_debug_seqNum_uopIdx =
    io_in_0_valid
      ? io_in_0_bits_uop_debug_seqNum_uopIdx
      : io_in_1_valid
          ? io_in_1_bits_uop_debug_seqNum_uopIdx
          : io_in_2_valid ? io_in_2_bits_uop_debug_seqNum_uopIdx : 8'h0;
  assign io_out_bits_uop_storeSetHit =
    io_in_0_valid
      ? io_in_0_bits_uop_storeSetHit
      : io_in_1_valid
          ? io_in_1_bits_uop_storeSetHit
          : io_in_2_valid & io_in_2_bits_uop_storeSetHit;
  assign io_out_bits_uop_waitForRobIdx_flag =
    io_in_0_valid
      ? io_in_0_bits_uop_waitForRobIdx_flag
      : io_in_1_valid & io_in_1_bits_uop_waitForRobIdx_flag;
  assign io_out_bits_uop_waitForRobIdx_value =
    io_in_0_valid
      ? io_in_0_bits_uop_waitForRobIdx_value
      : io_in_1_valid ? io_in_1_bits_uop_waitForRobIdx_value : 6'h0;
  assign io_out_bits_uop_loadWaitBit =
    io_in_0_valid
      ? io_in_0_bits_uop_loadWaitBit
      : io_in_1_valid & io_in_1_bits_uop_loadWaitBit;
  assign io_out_bits_uop_loadWaitStrict =
    io_in_0_valid
      ? io_in_0_bits_uop_loadWaitStrict
      : io_in_1_valid & io_in_1_bits_uop_loadWaitStrict;
  assign io_out_bits_uop_ssid =
    io_in_0_valid
      ? io_in_0_bits_uop_ssid
      : io_in_1_valid
          ? io_in_1_bits_uop_ssid
          : io_in_2_valid ? io_in_2_bits_uop_ssid : 6'h0;
  assign io_out_bits_uop_nc =
    io_in_0_valid ? io_in_0_bits_uop_nc : io_in_1_valid & io_in_1_bits_uop_nc;
  assign io_out_bits_uop_mmio =
    io_in_0_valid ? io_in_0_bits_uop_mmio : io_in_1_valid & io_in_1_bits_uop_mmio;
  assign io_out_bits_uop_lqIdx_flag =
    io_in_0_valid
      ? io_in_0_bits_uop_lqIdx_flag
      : io_in_1_valid & io_in_1_bits_uop_lqIdx_flag;
  assign io_out_bits_uop_lqIdx_value =
    io_in_0_valid
      ? io_in_0_bits_uop_lqIdx_value
      : io_in_1_valid ? io_in_1_bits_uop_lqIdx_value : 5'h0;
  assign io_out_bits_uop_sqIdx_first_flag =
    io_in_0_valid
      ? io_in_0_bits_uop_sqIdx_first_flag
      : io_in_1_valid
          ? io_in_1_bits_uop_sqIdx_first_flag
          : io_in_2_valid & io_in_2_bits_uop_sqIdx_first_flag;
  assign io_out_bits_uop_sqIdx_second_flag =
    io_in_0_valid
      ? io_in_0_bits_uop_sqIdx_second_flag
      : io_in_1_valid
          ? io_in_1_bits_uop_sqIdx_second_flag
          : io_in_2_valid & io_in_2_bits_uop_sqIdx_second_flag;
  assign io_out_bits_uop_sqIdx_value =
    io_in_0_valid
      ? io_in_0_bits_uop_sqIdx_value
      : io_in_1_valid
          ? io_in_1_bits_uop_sqIdx_value
          : io_in_2_valid ? io_in_2_bits_uop_sqIdx_value : 4'h0;
  assign io_out_bits_uop_singleStep =
    io_in_0_valid
      ? io_in_0_bits_uop_singleStep
      : io_in_1_valid & io_in_1_bits_uop_singleStep;
  assign io_out_bits_uop_replayInst =
    io_in_0_valid
      ? io_in_0_bits_uop_replayInst
      : io_in_1_valid & io_in_1_bits_uop_replayInst;
  assign io_out_bits_uop_debug_fuType =
    io_in_0_valid
      ? io_in_0_bits_uop_debug_fuType
      : io_in_1_valid ? io_in_1_bits_uop_debug_fuType : 36'h0;
  assign io_out_bits_uop_debug_sim_trig =
    io_in_0_valid
      ? io_in_0_bits_uop_debug_sim_trig
      : io_in_1_valid & io_in_1_bits_uop_debug_sim_trig;
  assign io_out_bits_uop_numLsElem =
    io_in_0_valid
      ? io_in_0_bits_uop_numLsElem
      : io_in_1_valid ? io_in_1_bits_uop_numLsElem : 5'h0;
  assign io_out_bits_vaddr =
    io_in_0_valid
      ? io_in_0_bits_vaddr
      : io_in_1_valid ? io_in_1_bits_vaddr : io_in_2_valid ? io_in_2_bits_vaddr : 50'h0;
  assign io_out_bits_fullva =
    io_in_0_valid
      ? io_in_0_bits_fullva
      : io_in_1_valid ? io_in_1_bits_fullva : io_in_2_valid ? io_in_2_bits_fullva : 64'h0;
  assign io_out_bits_size =
    io_in_0_valid
      ? io_in_0_bits_size
      : io_in_1_valid ? io_in_1_bits_size : io_in_2_valid ? io_in_2_bits_size : 3'h4;
  assign io_out_bits_mask =
    io_in_0_valid
      ? io_in_0_bits_mask
      : io_in_1_valid ? io_in_1_bits_mask : io_in_2_valid ? io_in_2_bits_mask : 16'hFFFF;
  assign io_out_bits_isFirstIssue =
    io_in_0_valid
      ? io_in_0_bits_isFirstIssue
      : io_in_1_valid | ~io_in_2_valid | io_in_2_bits_isFirstIssue;
  assign io_out_bits_ssid = _GEN | ~io_in_2_valid ? 6'h0 : io_in_2_bits_ssid;
  assign io_out_bits_storeSetHit = ~_GEN & io_in_2_valid & io_in_2_bits_storeSetHit;
  assign io_out_bits_elemIdx =
    io_in_0_valid ? io_in_0_bits_elemIdx : io_in_1_valid ? io_in_1_bits_elemIdx : 8'h0;
  assign io_out_bits_mbIndex =
    io_in_0_valid ? io_in_0_bits_mbIndex : io_in_1_valid ? io_in_1_bits_mbIndex : 4'h0;
endmodule

