// Generated by CIRCT firtool-1.135.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module AXI4UserYanker_4(
  input         clock,
  input         reset,
  output        auto_in_aw_ready,
  input         auto_in_aw_valid,
  input         auto_in_aw_bits_id,
  input  [48:0] auto_in_aw_bits_addr,
  input  [7:0]  auto_in_aw_bits_len,
  input  [2:0]  auto_in_aw_bits_size,
  input  [3:0]  auto_in_aw_bits_cache,
  input  [2:0]  auto_in_aw_bits_prot,
  input         auto_in_aw_bits_echo_extra_id,
  output        auto_in_w_ready,
  input         auto_in_w_valid,
  input  [63:0] auto_in_w_bits_data,
  input  [7:0]  auto_in_w_bits_strb,
  input         auto_in_w_bits_last,
  input         auto_in_b_ready,
  output        auto_in_b_valid,
  output        auto_in_b_bits_id,
  output [1:0]  auto_in_b_bits_resp,
  output        auto_in_b_bits_echo_extra_id,
  output        auto_in_ar_ready,
  input         auto_in_ar_valid,
  input         auto_in_ar_bits_id,
  input  [48:0] auto_in_ar_bits_addr,
  input  [7:0]  auto_in_ar_bits_len,
  input  [2:0]  auto_in_ar_bits_size,
  input  [3:0]  auto_in_ar_bits_cache,
  input  [2:0]  auto_in_ar_bits_prot,
  input         auto_in_ar_bits_echo_extra_id,
  input         auto_in_r_ready,
  output        auto_in_r_valid,
  output        auto_in_r_bits_id,
  output [63:0] auto_in_r_bits_data,
  output [1:0]  auto_in_r_bits_resp,
  output        auto_in_r_bits_echo_extra_id,
  output        auto_in_r_bits_last,
  input         auto_out_aw_ready,
  output        auto_out_aw_valid,
  output        auto_out_aw_bits_id,
  output [48:0] auto_out_aw_bits_addr,
  output [7:0]  auto_out_aw_bits_len,
  output [2:0]  auto_out_aw_bits_size,
  output [3:0]  auto_out_aw_bits_cache,
  output [2:0]  auto_out_aw_bits_prot,
  input         auto_out_w_ready,
  output        auto_out_w_valid,
  output [63:0] auto_out_w_bits_data,
  output [7:0]  auto_out_w_bits_strb,
  output        auto_out_w_bits_last,
  output        auto_out_b_ready,
  input         auto_out_b_valid,
  input         auto_out_b_bits_id,
  input  [1:0]  auto_out_b_bits_resp,
  input         auto_out_ar_ready,
  output        auto_out_ar_valid,
  output        auto_out_ar_bits_id,
  output [48:0] auto_out_ar_bits_addr,
  output [7:0]  auto_out_ar_bits_len,
  output [2:0]  auto_out_ar_bits_size,
  output [3:0]  auto_out_ar_bits_cache,
  output [2:0]  auto_out_ar_bits_prot,
  output        auto_out_r_ready,
  input         auto_out_r_valid,
  input         auto_out_r_bits_id,
  input  [63:0] auto_out_r_bits_data,
  input  [1:0]  auto_out_r_bits_resp,
  input         auto_out_r_bits_last
);

  wire       _Queue6144_BundleMap_1_io_enq_ready;
  wire       _Queue6144_BundleMap_1_io_deq_valid;
  wire       _Queue6144_BundleMap_1_io_deq_bits_extra_id;
  wire       _Queue6145_BundleMap_1_io_enq_ready;
  wire       _Queue6145_BundleMap_1_io_deq_valid;
  wire       _Queue6145_BundleMap_1_io_deq_bits_extra_id;
  wire       _Queue6144_BundleMap_io_enq_ready;
  wire       _Queue6144_BundleMap_io_deq_valid;
  wire       _Queue6144_BundleMap_io_deq_bits_extra_id;
  wire       _Queue6145_BundleMap_io_enq_ready;
  wire       _Queue6145_BundleMap_io_deq_valid;
  wire       _Queue6145_BundleMap_io_deq_bits_extra_id;
  wire       _GEN =
    auto_in_ar_bits_id
      ? _Queue6144_BundleMap_io_enq_ready
      : _Queue6145_BundleMap_io_enq_ready;
  wire [1:0] _arsel_T_1 = 2'h1 << auto_in_ar_bits_id;
  wire [1:0] _rsel_T_1 = 2'h1 << auto_out_r_bits_id;
  wire       _GEN_0 = auto_out_r_valid & auto_in_r_ready;
  wire       _GEN_1 = auto_in_ar_valid & auto_out_ar_ready;
  wire       _GEN_2 =
    auto_in_aw_bits_id
      ? _Queue6144_BundleMap_1_io_enq_ready
      : _Queue6145_BundleMap_1_io_enq_ready;
  `ifndef SYNTHESIS
    always @(posedge clock) begin
      if (~reset
          & ~(~auto_out_r_valid
              | (auto_out_r_bits_id
                   ? _Queue6144_BundleMap_io_deq_valid
                   : _Queue6145_BundleMap_io_deq_valid))) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed at UserYanker.scala:66\n");
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
      if (~reset
          & ~(~auto_out_b_valid
              | (auto_out_b_bits_id
                   ? _Queue6144_BundleMap_1_io_deq_valid
                   : _Queue6145_BundleMap_1_io_deq_valid))) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed at UserYanker.scala:95\n");
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire [1:0] _awsel_T_1 = 2'h1 << auto_in_aw_bits_id;
  wire [1:0] _bsel_T_1 = 2'h1 << auto_out_b_bits_id;
  wire       _GEN_3 = auto_out_b_valid & auto_in_b_ready;
  wire       _GEN_4 = auto_in_aw_valid & auto_out_aw_ready;
  Queue6145_BundleMap Queue6145_BundleMap (
    .clock                (clock),
    .reset                (reset),
    .io_enq_ready         (_Queue6145_BundleMap_io_enq_ready),
    .io_enq_valid         (_GEN_1 & _arsel_T_1[0]),
    .io_enq_bits_extra_id (auto_in_ar_bits_echo_extra_id),
    .io_deq_ready         (_GEN_0 & _rsel_T_1[0] & auto_out_r_bits_last),
    .io_deq_valid         (_Queue6145_BundleMap_io_deq_valid),
    .io_deq_bits_extra_id (_Queue6145_BundleMap_io_deq_bits_extra_id)
  );
  Queue6144_BundleMap Queue6144_BundleMap (
    .clock                (clock),
    .reset                (reset),
    .io_enq_ready         (_Queue6144_BundleMap_io_enq_ready),
    .io_enq_valid         (_GEN_1 & _arsel_T_1[1]),
    .io_enq_bits_extra_id (auto_in_ar_bits_echo_extra_id),
    .io_deq_ready         (_GEN_0 & _rsel_T_1[1] & auto_out_r_bits_last),
    .io_deq_valid         (_Queue6144_BundleMap_io_deq_valid),
    .io_deq_bits_extra_id (_Queue6144_BundleMap_io_deq_bits_extra_id)
  );
  Queue6145_BundleMap Queue6145_BundleMap_1 (
    .clock                (clock),
    .reset                (reset),
    .io_enq_ready         (_Queue6145_BundleMap_1_io_enq_ready),
    .io_enq_valid         (_GEN_4 & _awsel_T_1[0]),
    .io_enq_bits_extra_id (auto_in_aw_bits_echo_extra_id),
    .io_deq_ready         (_GEN_3 & _bsel_T_1[0]),
    .io_deq_valid         (_Queue6145_BundleMap_1_io_deq_valid),
    .io_deq_bits_extra_id (_Queue6145_BundleMap_1_io_deq_bits_extra_id)
  );
  Queue6144_BundleMap Queue6144_BundleMap_1 (
    .clock                (clock),
    .reset                (reset),
    .io_enq_ready         (_Queue6144_BundleMap_1_io_enq_ready),
    .io_enq_valid         (_GEN_4 & _awsel_T_1[1]),
    .io_enq_bits_extra_id (auto_in_aw_bits_echo_extra_id),
    .io_deq_ready         (_GEN_3 & _bsel_T_1[1]),
    .io_deq_valid         (_Queue6144_BundleMap_1_io_deq_valid),
    .io_deq_bits_extra_id (_Queue6144_BundleMap_1_io_deq_bits_extra_id)
  );
  assign auto_in_aw_ready = auto_out_aw_ready & _GEN_2;
  assign auto_in_w_ready = auto_out_w_ready;
  assign auto_in_b_valid = auto_out_b_valid;
  assign auto_in_b_bits_id = auto_out_b_bits_id;
  assign auto_in_b_bits_resp = auto_out_b_bits_resp;
  assign auto_in_b_bits_echo_extra_id =
    auto_out_b_bits_id
      ? _Queue6144_BundleMap_1_io_deq_bits_extra_id
      : _Queue6145_BundleMap_1_io_deq_bits_extra_id;
  assign auto_in_ar_ready = auto_out_ar_ready & _GEN;
  assign auto_in_r_valid = auto_out_r_valid;
  assign auto_in_r_bits_id = auto_out_r_bits_id;
  assign auto_in_r_bits_data = auto_out_r_bits_data;
  assign auto_in_r_bits_resp = auto_out_r_bits_resp;
  assign auto_in_r_bits_echo_extra_id =
    auto_out_r_bits_id
      ? _Queue6144_BundleMap_io_deq_bits_extra_id
      : _Queue6145_BundleMap_io_deq_bits_extra_id;
  assign auto_in_r_bits_last = auto_out_r_bits_last;
  assign auto_out_aw_valid = auto_in_aw_valid & _GEN_2;
  assign auto_out_aw_bits_id = auto_in_aw_bits_id;
  assign auto_out_aw_bits_addr = auto_in_aw_bits_addr;
  assign auto_out_aw_bits_len = auto_in_aw_bits_len;
  assign auto_out_aw_bits_size = auto_in_aw_bits_size;
  assign auto_out_aw_bits_cache = auto_in_aw_bits_cache;
  assign auto_out_aw_bits_prot = auto_in_aw_bits_prot;
  assign auto_out_w_valid = auto_in_w_valid;
  assign auto_out_w_bits_data = auto_in_w_bits_data;
  assign auto_out_w_bits_strb = auto_in_w_bits_strb;
  assign auto_out_w_bits_last = auto_in_w_bits_last;
  assign auto_out_b_ready = auto_in_b_ready;
  assign auto_out_ar_valid = auto_in_ar_valid & _GEN;
  assign auto_out_ar_bits_id = auto_in_ar_bits_id;
  assign auto_out_ar_bits_addr = auto_in_ar_bits_addr;
  assign auto_out_ar_bits_len = auto_in_ar_bits_len;
  assign auto_out_ar_bits_size = auto_in_ar_bits_size;
  assign auto_out_ar_bits_cache = auto_in_ar_bits_cache;
  assign auto_out_ar_bits_prot = auto_in_ar_bits_prot;
  assign auto_out_r_ready = auto_in_r_ready;
endmodule

