// Generated by CIRCT firtool-1.135.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module CHILinkCreditManagerTX(
  input  clock,
  input  reset,
  input  io_linkState_stop,
  input  io_linkState_activate,
  input  io_linkState_run,
  input  io_linkState_deactivate,
  output io_linkCreditAvailable,
  input  io_linkCreditConsume,
  input  io_linkCreditReturn,
  input  io_lcrdv,
  output debug_LinkActiveStateNotOneHot,
  output debug_LinkCreditConsumeOutOfRun,
  output debug_LinkCreditReturnOutOfDeactivate,
  output debug_LinkCreditValidWhenLinkStop,
  output debug_LinkCreditOverflow,
  output debug_LinkCreditUnderflow
);

  reg        regLcrdv;
  reg  [3:0] regLinkCreditCounter;
  wire       _debug_LinkActiveStateNotOneHot_output =
    3'({1'h0, 2'({1'h0, io_linkState_stop} + {1'h0, io_linkState_activate})}
       + {1'h0, 2'({1'h0, io_linkState_run} + {1'h0, io_linkState_deactivate})}) != 3'h1;
  wire       _debug_LinkCreditConsumeOutOfRun_output =
    ~io_linkState_run & io_linkCreditConsume;
  wire       _debug_LinkCreditReturnOutOfDeactivate_output =
    ~io_linkState_deactivate & io_linkCreditReturn;
  wire       _debug_LinkCreditValidWhenLinkStop_output = io_linkState_stop & io_lcrdv;
  wire       _debug_LinkCreditOverflow_output = (&regLinkCreditCounter) & regLcrdv;
  wire       _debug_LinkCreditUnderflow_output =
    regLinkCreditCounter == 4'h0 & io_linkCreditConsume;
  `ifndef SYNTHESIS
    always @(posedge clock) begin
      if (~reset & _debug_LinkActiveStateNotOneHot_output) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed: linkactive state must be one-hot\n");
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
      if (~reset & _debug_LinkCreditConsumeOutOfRun_output) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed: link credit consume out of RUN state\n");
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
      if (~reset & _debug_LinkCreditReturnOutOfDeactivate_output) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed: link credit return out of DEACTIVATE state\n");
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
      if (~reset & _debug_LinkCreditValidWhenLinkStop_output) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed: unexpected 'lcrdv' during link STOP\n");
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
      if (~reset & _debug_LinkCreditOverflow_output) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed: link credit overflow (with maximum 15)\n");
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
      if (~reset & _debug_LinkCreditUnderflow_output) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed: link credit underflow\n");
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      regLcrdv <= 1'h0;
      regLinkCreditCounter <= 4'h0;
    end
    else begin
      regLcrdv <= io_lcrdv;
      if (regLcrdv & ~io_linkCreditConsume & ~io_linkCreditReturn)
        regLinkCreditCounter <= 4'(regLinkCreditCounter + 4'h1);
      else if (~regLcrdv & (io_linkCreditConsume | io_linkCreditReturn))
        regLinkCreditCounter <= 4'(regLinkCreditCounter - 4'h1);
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;
        regLcrdv = _RANDOM[/*Zero width*/ 1'b0][0];
        regLinkCreditCounter = _RANDOM[/*Zero width*/ 1'b0][4:1];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        regLcrdv = 1'h0;
        regLinkCreditCounter = 4'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_linkCreditAvailable = |regLinkCreditCounter;
  assign debug_LinkActiveStateNotOneHot = _debug_LinkActiveStateNotOneHot_output;
  assign debug_LinkCreditConsumeOutOfRun = _debug_LinkCreditConsumeOutOfRun_output;
  assign debug_LinkCreditReturnOutOfDeactivate =
    _debug_LinkCreditReturnOutOfDeactivate_output;
  assign debug_LinkCreditValidWhenLinkStop = _debug_LinkCreditValidWhenLinkStop_output;
  assign debug_LinkCreditOverflow = _debug_LinkCreditOverflow_output;
  assign debug_LinkCreditUnderflow = _debug_LinkCreditUnderflow_output;
endmodule

