// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module DelayReg_25(
  input         clock,
  input         reset,
  input         i_valid,
  input  [63:0] i_addr,
  input  [7:0]  i_data_0,
  input  [7:0]  i_data_1,
  input  [7:0]  i_data_2,
  input  [7:0]  i_data_3,
  input  [7:0]  i_data_4,
  input  [7:0]  i_data_5,
  input  [7:0]  i_data_6,
  input  [7:0]  i_data_7,
  input  [7:0]  i_mask,
  input  [7:0]  i_coreid,
  input  [7:0]  i_index,
  output        o_valid,
  output [63:0] o_addr,
  output [7:0]  o_data_0,
  output [7:0]  o_data_1,
  output [7:0]  o_data_2,
  output [7:0]  o_data_3,
  output [7:0]  o_data_4,
  output [7:0]  o_data_5,
  output [7:0]  o_data_6,
  output [7:0]  o_data_7,
  output [7:0]  o_mask,
  output [7:0]  o_coreid,
  output [7:0]  o_index,
  input         enable
);

  reg        r_1_valid;
  reg [63:0] r_1_addr;
  reg [7:0]  r_1_data_0;
  reg [7:0]  r_1_data_1;
  reg [7:0]  r_1_data_2;
  reg [7:0]  r_1_data_3;
  reg [7:0]  r_1_data_4;
  reg [7:0]  r_1_data_5;
  reg [7:0]  r_1_data_6;
  reg [7:0]  r_1_data_7;
  reg [7:0]  r_1_mask;
  reg [7:0]  r_1_coreid;
  reg [7:0]  r_1_index;
  always @(posedge clock) begin
    if (reset) begin
      r_1_valid <= 1'h0;
      r_1_addr <= 64'h0;
      r_1_data_0 <= 8'h0;
      r_1_data_1 <= 8'h0;
      r_1_data_2 <= 8'h0;
      r_1_data_3 <= 8'h0;
      r_1_data_4 <= 8'h0;
      r_1_data_5 <= 8'h0;
      r_1_data_6 <= 8'h0;
      r_1_data_7 <= 8'h0;
      r_1_mask <= 8'h0;
      r_1_coreid <= 8'h0;
      r_1_index <= 8'h0;
    end
    else if (enable) begin
      r_1_valid <= i_valid;
      r_1_addr <= i_addr;
      r_1_data_0 <= i_data_0;
      r_1_data_1 <= i_data_1;
      r_1_data_2 <= i_data_2;
      r_1_data_3 <= i_data_3;
      r_1_data_4 <= i_data_4;
      r_1_data_5 <= i_data_5;
      r_1_data_6 <= i_data_6;
      r_1_data_7 <= i_data_7;
      r_1_mask <= i_mask;
      r_1_coreid <= i_coreid;
      r_1_index <= i_index;
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:4];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [2:0] i = 3'h0; i < 3'h5; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        r_1_valid = _RANDOM[3'h0][0];
        r_1_addr = {_RANDOM[3'h0][31:1], _RANDOM[3'h1], _RANDOM[3'h2][0]};
        r_1_data_0 = _RANDOM[3'h2][8:1];
        r_1_data_1 = _RANDOM[3'h2][16:9];
        r_1_data_2 = _RANDOM[3'h2][24:17];
        r_1_data_3 = {_RANDOM[3'h2][31:25], _RANDOM[3'h3][0]};
        r_1_data_4 = _RANDOM[3'h3][8:1];
        r_1_data_5 = _RANDOM[3'h3][16:9];
        r_1_data_6 = _RANDOM[3'h3][24:17];
        r_1_data_7 = {_RANDOM[3'h3][31:25], _RANDOM[3'h4][0]};
        r_1_mask = _RANDOM[3'h4][8:1];
        r_1_coreid = _RANDOM[3'h4][16:9];
        r_1_index = _RANDOM[3'h4][24:17];
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign o_valid = r_1_valid;
  assign o_addr = r_1_addr;
  assign o_data_0 = r_1_data_0;
  assign o_data_1 = r_1_data_1;
  assign o_data_2 = r_1_data_2;
  assign o_data_3 = r_1_data_3;
  assign o_data_4 = r_1_data_4;
  assign o_data_5 = r_1_data_5;
  assign o_data_6 = r_1_data_6;
  assign o_data_7 = r_1_data_7;
  assign o_mask = r_1_mask;
  assign o_coreid = r_1_coreid;
  assign o_index = r_1_index;
endmodule

