// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module DelayNWithValid_14(
  input         clock,
  input         reset,
  input  [55:0] io_in_bits_seqNum,
  input  [7:0]  io_in_bits_uopIdx,
  input         io_in_valid,
  output [55:0] io_out_bits_seqNum,
  output [7:0]  io_out_bits_uopIdx
);

  reg        valid_REG;
  reg [55:0] data_seqNum;
  reg [7:0]  data_uopIdx;
  reg        valid_REG_1;
  reg [55:0] data_1_seqNum;
  reg [7:0]  data_1_uopIdx;
  reg [55:0] res_bits_seqNum;
  reg [7:0]  res_bits_uopIdx;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      valid_REG <= 1'h0;
      valid_REG_1 <= 1'h0;
    end
    else begin
      valid_REG <= io_in_valid;
      valid_REG_1 <= valid_REG;
    end
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (io_in_valid) begin
      data_seqNum <= io_in_bits_seqNum;
      data_uopIdx <= io_in_bits_uopIdx;
    end
    if (valid_REG) begin
      data_1_seqNum <= data_seqNum;
      data_1_uopIdx <= data_uopIdx;
    end
    if (valid_REG_1) begin
      res_bits_seqNum <= data_1_seqNum;
      res_bits_uopIdx <= data_1_uopIdx;
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:6];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [2:0] i = 3'h0; i < 3'h7; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        valid_REG = _RANDOM[3'h0][0];
        data_seqNum = {_RANDOM[3'h0][31:1], _RANDOM[3'h1][24:0]};
        data_uopIdx = {_RANDOM[3'h1][31:25], _RANDOM[3'h2][0]};
        valid_REG_1 = _RANDOM[3'h2][1];
        data_1_seqNum = {_RANDOM[3'h2][31:2], _RANDOM[3'h3][25:0]};
        data_1_uopIdx = {_RANDOM[3'h3][31:26], _RANDOM[3'h4][1:0]};
        res_bits_seqNum = {_RANDOM[3'h4][31:3], _RANDOM[3'h5][26:0]};
        res_bits_uopIdx = {_RANDOM[3'h5][31:27], _RANDOM[3'h6][2:0]};
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        valid_REG = 1'h0;
        valid_REG_1 = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out_bits_seqNum = res_bits_seqNum;
  assign io_out_bits_uopIdx = res_bits_uopIdx;
endmodule

