// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module DelayNWithValid_13(
  input         clock,
  input         reset,
  input         io_in_bits_eliminatedMove,
  input  [63:0] io_in_bits_renameTime,
  input  [63:0] io_in_bits_dispatchTime,
  input  [63:0] io_in_bits_enqRsTime,
  input  [63:0] io_in_bits_selectTime,
  input  [63:0] io_in_bits_issueTime,
  input  [63:0] io_in_bits_runahead_checkpoint_id,
  input  [63:0] io_in_bits_tlbFirstReqTime,
  input  [63:0] io_in_bits_tlbRespTime,
  input         io_in_valid,
  output        io_out_bits_eliminatedMove,
  output [63:0] io_out_bits_renameTime,
  output [63:0] io_out_bits_dispatchTime,
  output [63:0] io_out_bits_enqRsTime,
  output [63:0] io_out_bits_selectTime,
  output [63:0] io_out_bits_issueTime,
  output [63:0] io_out_bits_runahead_checkpoint_id,
  output [63:0] io_out_bits_tlbFirstReqTime,
  output [63:0] io_out_bits_tlbRespTime
);

  reg        valid_REG;
  reg        data_eliminatedMove;
  reg [63:0] data_renameTime;
  reg [63:0] data_dispatchTime;
  reg [63:0] data_enqRsTime;
  reg [63:0] data_selectTime;
  reg [63:0] data_issueTime;
  reg [63:0] data_runahead_checkpoint_id;
  reg [63:0] data_tlbFirstReqTime;
  reg [63:0] data_tlbRespTime;
  reg        valid_REG_1;
  reg        data_1_eliminatedMove;
  reg [63:0] data_1_renameTime;
  reg [63:0] data_1_dispatchTime;
  reg [63:0] data_1_enqRsTime;
  reg [63:0] data_1_selectTime;
  reg [63:0] data_1_issueTime;
  reg [63:0] data_1_runahead_checkpoint_id;
  reg [63:0] data_1_tlbFirstReqTime;
  reg [63:0] data_1_tlbRespTime;
  reg        res_bits_eliminatedMove;
  reg [63:0] res_bits_renameTime;
  reg [63:0] res_bits_dispatchTime;
  reg [63:0] res_bits_enqRsTime;
  reg [63:0] res_bits_selectTime;
  reg [63:0] res_bits_issueTime;
  reg [63:0] res_bits_runahead_checkpoint_id;
  reg [63:0] res_bits_tlbFirstReqTime;
  reg [63:0] res_bits_tlbRespTime;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      valid_REG <= 1'h0;
      valid_REG_1 <= 1'h0;
    end
    else begin
      valid_REG <= io_in_valid;
      valid_REG_1 <= valid_REG;
    end
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (io_in_valid) begin
      data_eliminatedMove <= io_in_bits_eliminatedMove;
      data_renameTime <= io_in_bits_renameTime;
      data_dispatchTime <= io_in_bits_dispatchTime;
      data_enqRsTime <= io_in_bits_enqRsTime;
      data_selectTime <= io_in_bits_selectTime;
      data_issueTime <= io_in_bits_issueTime;
      data_runahead_checkpoint_id <= io_in_bits_runahead_checkpoint_id;
      data_tlbFirstReqTime <= io_in_bits_tlbFirstReqTime;
      data_tlbRespTime <= io_in_bits_tlbRespTime;
    end
    if (valid_REG) begin
      data_1_eliminatedMove <= data_eliminatedMove;
      data_1_renameTime <= data_renameTime;
      data_1_dispatchTime <= data_dispatchTime;
      data_1_enqRsTime <= data_enqRsTime;
      data_1_selectTime <= data_selectTime;
      data_1_issueTime <= data_issueTime;
      data_1_runahead_checkpoint_id <= data_runahead_checkpoint_id;
      data_1_tlbFirstReqTime <= data_tlbFirstReqTime;
      data_1_tlbRespTime <= data_tlbRespTime;
    end
    if (valid_REG_1) begin
      res_bits_eliminatedMove <= data_1_eliminatedMove;
      res_bits_renameTime <= data_1_renameTime;
      res_bits_dispatchTime <= data_1_dispatchTime;
      res_bits_enqRsTime <= data_1_enqRsTime;
      res_bits_selectTime <= data_1_selectTime;
      res_bits_issueTime <= data_1_issueTime;
      res_bits_runahead_checkpoint_id <= data_1_runahead_checkpoint_id;
      res_bits_tlbFirstReqTime <= data_1_tlbFirstReqTime;
      res_bits_tlbRespTime <= data_1_tlbRespTime;
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:54];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [5:0] i = 6'h0; i < 6'h37; i += 6'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        valid_REG = _RANDOM[6'h0][0];
        data_eliminatedMove = _RANDOM[6'h0][1];
        data_renameTime = {_RANDOM[6'h0][31:2], _RANDOM[6'h1], _RANDOM[6'h2][1:0]};
        data_dispatchTime = {_RANDOM[6'h2][31:2], _RANDOM[6'h3], _RANDOM[6'h4][1:0]};
        data_enqRsTime = {_RANDOM[6'h4][31:2], _RANDOM[6'h5], _RANDOM[6'h6][1:0]};
        data_selectTime = {_RANDOM[6'h6][31:2], _RANDOM[6'h7], _RANDOM[6'h8][1:0]};
        data_issueTime = {_RANDOM[6'h8][31:2], _RANDOM[6'h9], _RANDOM[6'hA][1:0]};
        data_runahead_checkpoint_id =
          {_RANDOM[6'hC][31:2], _RANDOM[6'hD], _RANDOM[6'hE][1:0]};
        data_tlbFirstReqTime = {_RANDOM[6'hE][31:2], _RANDOM[6'hF], _RANDOM[6'h10][1:0]};
        data_tlbRespTime = {_RANDOM[6'h10][31:2], _RANDOM[6'h11], _RANDOM[6'h12][1:0]};
        valid_REG_1 = _RANDOM[6'h12][2];
        data_1_eliminatedMove = _RANDOM[6'h12][3];
        data_1_renameTime = {_RANDOM[6'h12][31:4], _RANDOM[6'h13], _RANDOM[6'h14][3:0]};
        data_1_dispatchTime = {_RANDOM[6'h14][31:4], _RANDOM[6'h15], _RANDOM[6'h16][3:0]};
        data_1_enqRsTime = {_RANDOM[6'h16][31:4], _RANDOM[6'h17], _RANDOM[6'h18][3:0]};
        data_1_selectTime = {_RANDOM[6'h18][31:4], _RANDOM[6'h19], _RANDOM[6'h1A][3:0]};
        data_1_issueTime = {_RANDOM[6'h1A][31:4], _RANDOM[6'h1B], _RANDOM[6'h1C][3:0]};
        data_1_runahead_checkpoint_id =
          {_RANDOM[6'h1E][31:4], _RANDOM[6'h1F], _RANDOM[6'h20][3:0]};
        data_1_tlbFirstReqTime =
          {_RANDOM[6'h20][31:4], _RANDOM[6'h21], _RANDOM[6'h22][3:0]};
        data_1_tlbRespTime = {_RANDOM[6'h22][31:4], _RANDOM[6'h23], _RANDOM[6'h24][3:0]};
        res_bits_eliminatedMove = _RANDOM[6'h24][5];
        res_bits_renameTime = {_RANDOM[6'h24][31:6], _RANDOM[6'h25], _RANDOM[6'h26][5:0]};
        res_bits_dispatchTime =
          {_RANDOM[6'h26][31:6], _RANDOM[6'h27], _RANDOM[6'h28][5:0]};
        res_bits_enqRsTime = {_RANDOM[6'h28][31:6], _RANDOM[6'h29], _RANDOM[6'h2A][5:0]};
        res_bits_selectTime = {_RANDOM[6'h2A][31:6], _RANDOM[6'h2B], _RANDOM[6'h2C][5:0]};
        res_bits_issueTime = {_RANDOM[6'h2C][31:6], _RANDOM[6'h2D], _RANDOM[6'h2E][5:0]};
        res_bits_runahead_checkpoint_id =
          {_RANDOM[6'h30][31:6], _RANDOM[6'h31], _RANDOM[6'h32][5:0]};
        res_bits_tlbFirstReqTime =
          {_RANDOM[6'h32][31:6], _RANDOM[6'h33], _RANDOM[6'h34][5:0]};
        res_bits_tlbRespTime =
          {_RANDOM[6'h34][31:6], _RANDOM[6'h35], _RANDOM[6'h36][5:0]};
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        valid_REG = 1'h0;
        valid_REG_1 = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out_bits_eliminatedMove = res_bits_eliminatedMove;
  assign io_out_bits_renameTime = res_bits_renameTime;
  assign io_out_bits_dispatchTime = res_bits_dispatchTime;
  assign io_out_bits_enqRsTime = res_bits_enqRsTime;
  assign io_out_bits_selectTime = res_bits_selectTime;
  assign io_out_bits_issueTime = res_bits_issueTime;
  assign io_out_bits_runahead_checkpoint_id = res_bits_runahead_checkpoint_id;
  assign io_out_bits_tlbFirstReqTime = res_bits_tlbFirstReqTime;
  assign io_out_bits_tlbRespTime = res_bits_tlbRespTime;
endmodule

