// Generated by CIRCT firtool-1.135.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module Dispatcher_12(
  input         clock,
  input         reset,
  output        io_in_ready,
  input         io_in_valid,
  input  [35:0] io_in_bits_ctrl_fuType,
  input  [8:0]  io_in_bits_ctrl_fuOpType,
  input  [1:0]  io_in_bits_ctrl_fpu_fmt,
  input  [2:0]  io_in_bits_ctrl_fpu_rm,
  input  [63:0] io_in_bits_perfDebugInfo_enqRsTime,
  input  [63:0] io_in_bits_perfDebugInfo_selectTime,
  input  [63:0] io_in_bits_perfDebugInfo_issueTime,
  input  [63:0] io_in_bits_perfDebugInfo_tlbFirstReqTime,
  input  [63:0] io_in_bits_perfDebugInfo_tlbRespTime,
  input         io_out_0_ready,
  output        io_out_0_valid,
  output [8:0]  io_out_0_bits_ctrl_fuOpType,
  output [1:0]  io_out_0_bits_ctrl_fpu_fmt,
  output [2:0]  io_out_0_bits_ctrl_fpu_rm,
  output [63:0] io_out_0_bits_perfDebugInfo_enqRsTime,
  output [63:0] io_out_0_bits_perfDebugInfo_selectTime,
  output [63:0] io_out_0_bits_perfDebugInfo_issueTime,
  output [63:0] io_out_0_bits_perfDebugInfo_tlbFirstReqTime,
  output [63:0] io_out_0_bits_perfDebugInfo_tlbRespTime,
  input         io_out_1_ready,
  output        io_out_1_valid,
  output [8:0]  io_out_1_bits_ctrl_fuOpType,
  output [1:0]  io_out_1_bits_ctrl_fpu_fmt,
  output [2:0]  io_out_1_bits_ctrl_fpu_rm,
  output [63:0] io_out_1_bits_perfDebugInfo_enqRsTime,
  output [63:0] io_out_1_bits_perfDebugInfo_selectTime,
  output [63:0] io_out_1_bits_perfDebugInfo_issueTime,
  output [63:0] io_out_1_bits_perfDebugInfo_tlbFirstReqTime,
  output [63:0] io_out_1_bits_perfDebugInfo_tlbRespTime
);

  wire       acceptVec_0 = io_in_bits_ctrl_fuType == 36'h800;
  wire       acceptVec_1 = io_in_bits_ctrl_fuType == 36'h1000;
  wire [1:0] _GEN = 2'({1'h0, acceptVec_0} + {1'h0, acceptVec_1});
  wire       _GEN_0 = io_in_valid & _GEN[1];
  wire [1:0] data_0_probe = {acceptVec_1, acceptVec_0};
  wire       _GEN_1 = io_in_valid & _GEN == 2'h0;
  `ifndef SYNTHESIS
    always @(posedge clock) begin
      if (_GEN_0 & ~reset) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed at LogUtils.scala:133\n");
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
      if (_GEN_1 & ~reset) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed at LogUtils.scala:133\n");
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  assign io_in_ready = &{io_out_0_ready, io_out_1_ready};
  assign io_out_0_valid = acceptVec_0 & io_in_valid;
  assign io_out_0_bits_ctrl_fuOpType = io_in_bits_ctrl_fuOpType;
  assign io_out_0_bits_ctrl_fpu_fmt = io_in_bits_ctrl_fpu_fmt;
  assign io_out_0_bits_ctrl_fpu_rm = io_in_bits_ctrl_fpu_rm;
  assign io_out_0_bits_perfDebugInfo_enqRsTime = io_in_bits_perfDebugInfo_enqRsTime;
  assign io_out_0_bits_perfDebugInfo_selectTime = io_in_bits_perfDebugInfo_selectTime;
  assign io_out_0_bits_perfDebugInfo_issueTime = io_in_bits_perfDebugInfo_issueTime;
  assign io_out_0_bits_perfDebugInfo_tlbFirstReqTime =
    io_in_bits_perfDebugInfo_tlbFirstReqTime;
  assign io_out_0_bits_perfDebugInfo_tlbRespTime = io_in_bits_perfDebugInfo_tlbRespTime;
  assign io_out_1_valid = acceptVec_1 & io_in_valid;
  assign io_out_1_bits_ctrl_fuOpType = io_in_bits_ctrl_fuOpType;
  assign io_out_1_bits_ctrl_fpu_fmt = io_in_bits_ctrl_fpu_fmt;
  assign io_out_1_bits_ctrl_fpu_rm = io_in_bits_ctrl_fpu_rm;
  assign io_out_1_bits_perfDebugInfo_enqRsTime = io_in_bits_perfDebugInfo_enqRsTime;
  assign io_out_1_bits_perfDebugInfo_selectTime = io_in_bits_perfDebugInfo_selectTime;
  assign io_out_1_bits_perfDebugInfo_issueTime = io_in_bits_perfDebugInfo_issueTime;
  assign io_out_1_bits_perfDebugInfo_tlbFirstReqTime =
    io_in_bits_perfDebugInfo_tlbFirstReqTime;
  assign io_out_1_bits_perfDebugInfo_tlbRespTime = io_in_bits_perfDebugInfo_tlbRespTime;
endmodule

