// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module DivUnit(
  input         clock,
  input         reset,
  input         io_flush_valid,
  input         io_flush_bits_level,
  input         io_flush_bits_robIdx_flag,
  input  [5:0]  io_flush_bits_robIdx_value,
  output        io_in_ready,
  input         io_in_valid,
  input  [8:0]  io_in_bits_ctrl_fuOpType,
  input         io_in_bits_ctrl_toRobValid,
  input         io_in_bits_ctrl_robIdx_flag,
  input  [5:0]  io_in_bits_ctrl_robIdx_value,
  input  [7:0]  io_in_bits_ctrl_pdest,
  input         io_in_bits_ctrl_rfWen,
  input  [63:0] io_in_bits_data_src_1,
  input  [63:0] io_in_bits_data_src_0,
  input  [63:0] io_in_bits_perfDebugInfo_enqRsTime,
  input  [63:0] io_in_bits_perfDebugInfo_selectTime,
  input  [63:0] io_in_bits_perfDebugInfo_issueTime,
  input  [63:0] io_in_bits_perfDebugInfo_tlbFirstReqTime,
  input  [63:0] io_in_bits_perfDebugInfo_tlbRespTime,
  output        io_out_valid,
  output        io_out_bits_ctrl_toRobValid,
  output        io_out_bits_ctrl_robIdx_flag,
  output [5:0]  io_out_bits_ctrl_robIdx_value,
  output [7:0]  io_out_bits_ctrl_pdest,
  output        io_out_bits_ctrl_rfWen,
  output [63:0] io_out_bits_res_data,
  output [63:0] io_out_bits_perfDebugInfo_enqRsTime,
  output [63:0] io_out_bits_perfDebugInfo_selectTime,
  output [63:0] io_out_bits_perfDebugInfo_issueTime,
  output [63:0] io_out_bits_perfDebugInfo_tlbFirstReqTime,
  output [63:0] io_out_bits_perfDebugInfo_tlbRespTime,
  output        io_outValidAhead3Cycle
);

  wire        _divDataModule_io_in_ready;
  reg         robIdxReg_flag;
  reg  [5:0]  robIdxReg_value;
  reg         ctrlReg_isW;
  reg         ctrlReg_isHi;
  wire [6:0]  _kill_r_flushItself_T_2 =
    {io_flush_bits_robIdx_flag, io_flush_bits_robIdx_value};
  reg         io_out_bits_ctrl_toRobValid_r;
  reg         io_out_bits_ctrl_robIdx_r_flag;
  reg  [5:0]  io_out_bits_ctrl_robIdx_r_value;
  reg  [7:0]  io_out_bits_ctrl_pdest_r;
  reg         io_out_bits_ctrl_rfWen_r;
  reg  [63:0] io_out_bits_perfDebugInfo_r_enqRsTime;
  reg  [63:0] io_out_bits_perfDebugInfo_r_selectTime;
  reg  [63:0] io_out_bits_perfDebugInfo_r_issueTime;
  reg  [63:0] io_out_bits_perfDebugInfo_r_tlbFirstReqTime;
  reg  [63:0] io_out_bits_perfDebugInfo_r_tlbRespTime;
  always @(posedge clock) begin
    if (_divDataModule_io_in_ready & io_in_valid) begin
      robIdxReg_flag <= io_in_bits_ctrl_robIdx_flag;
      robIdxReg_value <= io_in_bits_ctrl_robIdx_value;
      ctrlReg_isW <= io_in_bits_ctrl_fuOpType[2];
      ctrlReg_isHi <= io_in_bits_ctrl_fuOpType[0];
      io_out_bits_ctrl_toRobValid_r <= io_in_bits_ctrl_toRobValid;
      io_out_bits_ctrl_robIdx_r_flag <= io_in_bits_ctrl_robIdx_flag;
      io_out_bits_ctrl_robIdx_r_value <= io_in_bits_ctrl_robIdx_value;
      io_out_bits_ctrl_pdest_r <= io_in_bits_ctrl_pdest;
      io_out_bits_ctrl_rfWen_r <= io_in_bits_ctrl_rfWen;
      io_out_bits_perfDebugInfo_r_enqRsTime <= io_in_bits_perfDebugInfo_enqRsTime;
      io_out_bits_perfDebugInfo_r_selectTime <= io_in_bits_perfDebugInfo_selectTime;
      io_out_bits_perfDebugInfo_r_issueTime <= io_in_bits_perfDebugInfo_issueTime;
      io_out_bits_perfDebugInfo_r_tlbFirstReqTime <=
        io_in_bits_perfDebugInfo_tlbFirstReqTime;
      io_out_bits_perfDebugInfo_r_tlbRespTime <= io_in_bits_perfDebugInfo_tlbRespTime;
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:18];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [4:0] i = 5'h0; i < 5'h13; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        robIdxReg_flag = _RANDOM[5'h0][0];
        robIdxReg_value = _RANDOM[5'h0][6:1];
        ctrlReg_isW = _RANDOM[5'h0][8];
        ctrlReg_isHi = _RANDOM[5'h0][9];
        io_out_bits_ctrl_toRobValid_r = _RANDOM[5'h0][10];
        io_out_bits_ctrl_robIdx_r_flag = _RANDOM[5'h0][11];
        io_out_bits_ctrl_robIdx_r_value = _RANDOM[5'h0][17:12];
        io_out_bits_ctrl_pdest_r = _RANDOM[5'h0][25:18];
        io_out_bits_ctrl_rfWen_r = _RANDOM[5'h0][26];
        io_out_bits_perfDebugInfo_r_enqRsTime =
          {_RANDOM[5'h4][31:28], _RANDOM[5'h5], _RANDOM[5'h6][27:0]};
        io_out_bits_perfDebugInfo_r_selectTime =
          {_RANDOM[5'h6][31:28], _RANDOM[5'h7], _RANDOM[5'h8][27:0]};
        io_out_bits_perfDebugInfo_r_issueTime =
          {_RANDOM[5'h8][31:28], _RANDOM[5'h9], _RANDOM[5'hA][27:0]};
        io_out_bits_perfDebugInfo_r_tlbFirstReqTime =
          {_RANDOM[5'hE][31:28], _RANDOM[5'hF], _RANDOM[5'h10][27:0]};
        io_out_bits_perfDebugInfo_r_tlbRespTime =
          {_RANDOM[5'h10][31:28], _RANDOM[5'h11], _RANDOM[5'h12][27:0]};
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  SRT16DividerDataModule divDataModule (
    .clock                  (clock),
    .reset                  (reset),
    .io_src_0
      (io_in_bits_ctrl_fuOpType[2]
         ? {{32{~(io_in_bits_ctrl_fuOpType[1]) & io_in_bits_data_src_0[31]}},
            io_in_bits_data_src_0[31:0]}
         : io_in_bits_data_src_0),
    .io_src_1
      (io_in_bits_ctrl_fuOpType[2]
         ? {{32{~(io_in_bits_ctrl_fuOpType[1]) & io_in_bits_data_src_1[31]}},
            io_in_bits_data_src_1[31:0]}
         : io_in_bits_data_src_1),
    .io_valid               (io_in_valid),
    .io_sign                (~(io_in_bits_ctrl_fuOpType[1])),
    .io_kill_w
      (io_flush_valid
       & (io_flush_bits_level
          & {io_in_bits_ctrl_robIdx_flag,
             io_in_bits_ctrl_robIdx_value} == _kill_r_flushItself_T_2
          | io_in_bits_ctrl_robIdx_flag ^ io_flush_bits_robIdx_flag
          ^ io_in_bits_ctrl_robIdx_value > io_flush_bits_robIdx_value)),
    .io_kill_r
      (~_divDataModule_io_in_ready & io_flush_valid
       & (io_flush_bits_level
          & {robIdxReg_flag, robIdxReg_value} == _kill_r_flushItself_T_2 | robIdxReg_flag
          ^ io_flush_bits_robIdx_flag ^ robIdxReg_value > io_flush_bits_robIdx_value)),
    .io_isHi                (ctrlReg_isHi),
    .io_isW                 (ctrlReg_isW),
    .io_in_ready            (_divDataModule_io_in_ready),
    .io_out_valid           (io_out_valid),
    .io_out_data            (io_out_bits_res_data),
    .io_outValidAhead3Cycle (io_outValidAhead3Cycle)
  );
  assign io_in_ready = _divDataModule_io_in_ready;
  assign io_out_bits_ctrl_toRobValid = io_out_bits_ctrl_toRobValid_r;
  assign io_out_bits_ctrl_robIdx_flag = io_out_bits_ctrl_robIdx_r_flag;
  assign io_out_bits_ctrl_robIdx_value = io_out_bits_ctrl_robIdx_r_value;
  assign io_out_bits_ctrl_pdest = io_out_bits_ctrl_pdest_r;
  assign io_out_bits_ctrl_rfWen = io_out_bits_ctrl_rfWen_r;
  assign io_out_bits_perfDebugInfo_enqRsTime = io_out_bits_perfDebugInfo_r_enqRsTime;
  assign io_out_bits_perfDebugInfo_selectTime = io_out_bits_perfDebugInfo_r_selectTime;
  assign io_out_bits_perfDebugInfo_issueTime = io_out_bits_perfDebugInfo_r_issueTime;
  assign io_out_bits_perfDebugInfo_tlbFirstReqTime =
    io_out_bits_perfDebugInfo_r_tlbFirstReqTime;
  assign io_out_bits_perfDebugInfo_tlbRespTime = io_out_bits_perfDebugInfo_r_tlbRespTime;
endmodule

