// Generated by CIRCT firtool-1.135.0
module DummyDPICWrapper_UncacheMMStoreEvent(
  input        clock,
  input        reset,
  input        control_enable,
  input        io_valid,
  input        io_bits_valid,
  input [63:0] io_bits_addr,
  input [7:0]  io_bits_data_0,
  input [7:0]  io_bits_data_1,
  input [7:0]  io_bits_data_2,
  input [7:0]  io_bits_data_3,
  input [7:0]  io_bits_data_4,
  input [7:0]  io_bits_data_5,
  input [7:0]  io_bits_data_6,
  input [7:0]  io_bits_data_7,
  input [7:0]  io_bits_mask,
  input [7:0]  io_bits_coreid,
  input [7:0]  io_bits_index
);

  DiffExtUncacheMMStoreEvent dpic (
    .clock     (clock),
    .enable    (io_valid & control_enable & ~reset),
    .io_valid  (io_bits_valid),
    .io_addr   (io_bits_addr),
    .io_data_0 (io_bits_data_0),
    .io_data_1 (io_bits_data_1),
    .io_data_2 (io_bits_data_2),
    .io_data_3 (io_bits_data_3),
    .io_data_4 (io_bits_data_4),
    .io_data_5 (io_bits_data_5),
    .io_data_6 (io_bits_data_6),
    .io_data_7 (io_bits_data_7),
    .io_mask   (io_bits_mask),
    .io_coreid (io_bits_coreid),
    .io_index  (io_bits_index)
  );
endmodule

