// Generated by CIRCT firtool-1.135.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module ExeUnitImp_9(
  input          clock,
  input          reset,
  input          io_flush_valid,
  input          io_flush_bits_level,
  input          io_flush_bits_robIdx_flag,
  input  [5:0]   io_flush_bits_robIdx_value,
  output         io_in_ready,
  input          io_in_valid,
  input  [35:0]  io_in_bits_ctrl_fuType,
  input  [8:0]   io_in_bits_ctrl_fuOpType,
  input          io_in_bits_ctrl_rfWen,
  input          io_in_bits_ctrl_fpWen,
  input          io_in_bits_ctrl_vecWen,
  input          io_in_bits_ctrl_v0Wen,
  input          io_in_bits_ctrl_fpu_wflags,
  input  [1:0]   io_in_bits_ctrl_fpu_fmt,
  input  [2:0]   io_in_bits_ctrl_fpu_rm,
  input  [63:0]  io_in_bits_data_src_0,
  input  [63:0]  io_in_bits_data_src_1,
  input  [63:0]  io_in_bits_data_src_2,
  input          io_in_bits_toRobValid,
  input          io_in_bits_robIdx_flag,
  input  [5:0]   io_in_bits_robIdx_value,
  input  [7:0]   io_in_bits_toRF_pdest,
  input  [63:0]  io_in_bits_perfDebugInfo_enqRsTime,
  input  [63:0]  io_in_bits_perfDebugInfo_selectTime,
  input  [63:0]  io_in_bits_perfDebugInfo_issueTime,
  input  [63:0]  io_in_bits_perfDebugInfo_tlbFirstReqTime,
  input  [63:0]  io_in_bits_perfDebugInfo_tlbRespTime,
  input          io_out_ready,
  output         io_out_valid,
  output         io_out_bits_toRob_valid,
  output         io_out_bits_toRob_bits_robIdx_flag,
  output [5:0]   io_out_bits_toRob_bits_robIdx_value,
  output [4:0]   io_out_bits_toRob_bits_fflags,
  output         io_out_bits_toRob_bits_wflags,
  output [7:0]   io_out_bits_pdest,
  output         io_out_bits_toIntRf_valid,
  output [127:0] io_out_bits_toIntRf_bits,
  output         io_out_bits_toFpRf_valid,
  output [127:0] io_out_bits_toFpRf_bits,
  output         io_out_bits_toVecRf_valid,
  output [127:0] io_out_bits_toVecRf_bits,
  output         io_out_bits_toV0Rf_valid,
  output [127:0] io_out_bits_toV0Rf_bits,
  output [63:0]  io_out_bits_perfDebugInfo_enqRsTime,
  output [63:0]  io_out_bits_perfDebugInfo_selectTime,
  output [63:0]  io_out_bits_perfDebugInfo_issueTime,
  output [63:0]  io_out_bits_perfDebugInfo_tlbFirstReqTime,
  output [63:0]  io_out_bits_perfDebugInfo_tlbRespTime,
  input          io_I2FDataIn_valid,
  input  [63:0]  io_I2FDataIn_bits,
  input  [2:0]   io_frm,
  input          cg_bore_cgen,
  input          cg_bore_1_cgen,
  input          cg_bore_2_cgen,
  input          cg_bore_3_cgen,
  input          cg_bore_4_cgen
);

  wire         fuRdyVec_2_3;
  wire         fuRdyVec_2_2;
  wire         fuRdyVec_2_1;
  wire         fuRdyVec_2;
  wire         _in1ToN_io_out_0_valid;
  wire [8:0]   _in1ToN_io_out_0_bits_ctrl_fuOpType;
  wire [1:0]   _in1ToN_io_out_0_bits_ctrl_fpu_fmt;
  wire [2:0]   _in1ToN_io_out_0_bits_ctrl_fpu_rm;
  wire [63:0]  _in1ToN_io_out_0_bits_perfDebugInfo_enqRsTime;
  wire [63:0]  _in1ToN_io_out_0_bits_perfDebugInfo_selectTime;
  wire [63:0]  _in1ToN_io_out_0_bits_perfDebugInfo_issueTime;
  wire [63:0]  _in1ToN_io_out_0_bits_perfDebugInfo_tlbFirstReqTime;
  wire [63:0]  _in1ToN_io_out_0_bits_perfDebugInfo_tlbRespTime;
  wire         _in1ToN_io_out_1_valid;
  wire [8:0]   _in1ToN_io_out_1_bits_ctrl_fuOpType;
  wire [1:0]   _in1ToN_io_out_1_bits_ctrl_fpu_fmt;
  wire [2:0]   _in1ToN_io_out_1_bits_ctrl_fpu_rm;
  wire [63:0]  _in1ToN_io_out_1_bits_perfDebugInfo_enqRsTime;
  wire [63:0]  _in1ToN_io_out_1_bits_perfDebugInfo_selectTime;
  wire [63:0]  _in1ToN_io_out_1_bits_perfDebugInfo_issueTime;
  wire [63:0]  _in1ToN_io_out_1_bits_perfDebugInfo_tlbFirstReqTime;
  wire [63:0]  _in1ToN_io_out_1_bits_perfDebugInfo_tlbRespTime;
  wire         _in1ToN_io_out_2_valid;
  wire [8:0]   _in1ToN_io_out_2_bits_ctrl_fuOpType;
  wire [1:0]   _in1ToN_io_out_2_bits_ctrl_fpu_fmt;
  wire [2:0]   _in1ToN_io_out_2_bits_ctrl_fpu_rm;
  wire [63:0]  _in1ToN_io_out_2_bits_perfDebugInfo_enqRsTime;
  wire [63:0]  _in1ToN_io_out_2_bits_perfDebugInfo_selectTime;
  wire [63:0]  _in1ToN_io_out_2_bits_perfDebugInfo_issueTime;
  wire [63:0]  _in1ToN_io_out_2_bits_perfDebugInfo_tlbFirstReqTime;
  wire [63:0]  _in1ToN_io_out_2_bits_perfDebugInfo_tlbRespTime;
  wire         _in1ToN_io_out_3_valid;
  wire [8:0]   _in1ToN_io_out_3_bits_ctrl_fuOpType;
  wire [1:0]   _in1ToN_io_out_3_bits_ctrl_fpu_fmt;
  wire [63:0]  _in1ToN_io_out_3_bits_perfDebugInfo_enqRsTime;
  wire [63:0]  _in1ToN_io_out_3_bits_perfDebugInfo_selectTime;
  wire [63:0]  _in1ToN_io_out_3_bits_perfDebugInfo_issueTime;
  wire [63:0]  _in1ToN_io_out_3_bits_perfDebugInfo_tlbFirstReqTime;
  wire [63:0]  _in1ToN_io_out_3_bits_perfDebugInfo_tlbRespTime;
  wire         _in1ToN_io_out_4_valid;
  wire [8:0]   _in1ToN_io_out_4_bits_ctrl_fuOpType;
  wire [63:0]  _in1ToN_io_out_4_bits_perfDebugInfo_enqRsTime;
  wire [63:0]  _in1ToN_io_out_4_bits_perfDebugInfo_selectTime;
  wire [63:0]  _in1ToN_io_out_4_bits_perfDebugInfo_issueTime;
  wire [63:0]  _in1ToN_io_out_4_bits_perfDebugInfo_tlbFirstReqTime;
  wire [63:0]  _in1ToN_io_out_4_bits_perfDebugInfo_tlbRespTime;
  wire         _ClockGate_4_Q;
  wire         _ClockGate_3_Q;
  wire         _ClockGate_2_Q;
  wire         _ClockGate_1_Q;
  wire         _ClockGate_Q;
  wire         _f2v_io_in_ready;
  wire         _f2v_io_out_bits_ctrl_toRobValid;
  wire         _f2v_io_out_bits_ctrl_robIdx_flag;
  wire [5:0]   _f2v_io_out_bits_ctrl_robIdx_value;
  wire [7:0]   _f2v_io_out_bits_ctrl_pdest;
  wire         _f2v_io_out_bits_ctrl_fpWen;
  wire         _f2v_io_out_bits_ctrl_vecWen;
  wire         _f2v_io_out_bits_ctrl_v0Wen;
  wire [127:0] _f2v_io_out_bits_res_data;
  wire [63:0]  _f2v_io_out_bits_perfDebugInfo_enqRsTime;
  wire [63:0]  _f2v_io_out_bits_perfDebugInfo_selectTime;
  wire [63:0]  _f2v_io_out_bits_perfDebugInfo_issueTime;
  wire [63:0]  _f2v_io_out_bits_perfDebugInfo_tlbFirstReqTime;
  wire [63:0]  _f2v_io_out_bits_perfDebugInfo_tlbRespTime;
  wire         _fcmp_io_in_ready;
  wire         _fcmp_io_out_bits_ctrl_toRobValid;
  wire         _fcmp_io_out_bits_ctrl_robIdx_flag;
  wire [5:0]   _fcmp_io_out_bits_ctrl_robIdx_value;
  wire [7:0]   _fcmp_io_out_bits_ctrl_pdest;
  wire         _fcmp_io_out_bits_ctrl_rfWen;
  wire         _fcmp_io_out_bits_ctrl_fpu_wflags;
  wire [63:0]  _fcmp_io_out_bits_res_data;
  wire [4:0]   _fcmp_io_out_bits_res_fflags;
  wire [63:0]  _fcmp_io_out_bits_perfDebugInfo_enqRsTime;
  wire [63:0]  _fcmp_io_out_bits_perfDebugInfo_selectTime;
  wire [63:0]  _fcmp_io_out_bits_perfDebugInfo_issueTime;
  wire [63:0]  _fcmp_io_out_bits_perfDebugInfo_tlbFirstReqTime;
  wire [63:0]  _fcmp_io_out_bits_perfDebugInfo_tlbRespTime;
  wire         _Fcvt_io_in_ready;
  wire         _Fcvt_io_out_bits_ctrl_toRobValid;
  wire         _Fcvt_io_out_bits_ctrl_robIdx_flag;
  wire [5:0]   _Fcvt_io_out_bits_ctrl_robIdx_value;
  wire [7:0]   _Fcvt_io_out_bits_ctrl_pdest;
  wire         _Fcvt_io_out_bits_ctrl_rfWen;
  wire         _Fcvt_io_out_bits_ctrl_fpWen;
  wire         _Fcvt_io_out_bits_ctrl_fpu_wflags;
  wire [63:0]  _Fcvt_io_out_bits_res_data;
  wire [4:0]   _Fcvt_io_out_bits_res_fflags;
  wire [63:0]  _Fcvt_io_out_bits_perfDebugInfo_enqRsTime;
  wire [63:0]  _Fcvt_io_out_bits_perfDebugInfo_selectTime;
  wire [63:0]  _Fcvt_io_out_bits_perfDebugInfo_issueTime;
  wire [63:0]  _Fcvt_io_out_bits_perfDebugInfo_tlbFirstReqTime;
  wire [63:0]  _Fcvt_io_out_bits_perfDebugInfo_tlbRespTime;
  wire         _Fmac_io_in_ready;
  wire         _Fmac_io_out_bits_ctrl_toRobValid;
  wire         _Fmac_io_out_bits_ctrl_robIdx_flag;
  wire [5:0]   _Fmac_io_out_bits_ctrl_robIdx_value;
  wire [7:0]   _Fmac_io_out_bits_ctrl_pdest;
  wire         _Fmac_io_out_bits_ctrl_fpWen;
  wire         _Fmac_io_out_bits_ctrl_fpu_wflags;
  wire [63:0]  _Fmac_io_out_bits_res_data;
  wire [4:0]   _Fmac_io_out_bits_res_fflags;
  wire [63:0]  _Fmac_io_out_bits_perfDebugInfo_enqRsTime;
  wire [63:0]  _Fmac_io_out_bits_perfDebugInfo_selectTime;
  wire [63:0]  _Fmac_io_out_bits_perfDebugInfo_issueTime;
  wire [63:0]  _Fmac_io_out_bits_perfDebugInfo_tlbFirstReqTime;
  wire [63:0]  _Fmac_io_out_bits_perfDebugInfo_tlbRespTime;
  wire         _Falu_io_in_ready;
  wire         _Falu_io_out_bits_ctrl_toRobValid;
  wire         _Falu_io_out_bits_ctrl_robIdx_flag;
  wire [5:0]   _Falu_io_out_bits_ctrl_robIdx_value;
  wire [7:0]   _Falu_io_out_bits_ctrl_pdest;
  wire         _Falu_io_out_bits_ctrl_fpWen;
  wire         _Falu_io_out_bits_ctrl_fpu_wflags;
  wire [63:0]  _Falu_io_out_bits_res_data;
  wire [4:0]   _Falu_io_out_bits_res_fflags;
  wire [63:0]  _Falu_io_out_bits_perfDebugInfo_enqRsTime;
  wire [63:0]  _Falu_io_out_bits_perfDebugInfo_selectTime;
  wire [63:0]  _Falu_io_out_bits_perfDebugInfo_issueTime;
  wire [63:0]  _Falu_io_out_bits_perfDebugInfo_tlbFirstReqTime;
  wire [63:0]  _Falu_io_out_bits_perfDebugInfo_tlbRespTime;
  wire         Falu_clock_te_cgen = cg_bore_cgen;
  wire         Fmac_clock_te_cgen = cg_bore_1_cgen;
  wire         Fcvt_clock_te_cgen = cg_bore_2_cgen;
  wire         fcmp_clock_te_cgen = cg_bore_3_cgen;
  wire         f2v_clock_te_cgen = cg_bore_4_cgen;
  reg          fuVld_en_reg;
  reg          fuVldVec_1;
  wire         fuVld_en = _in1ToN_io_out_0_valid | fuVldVec_1;
  wire         _GEN = fuVld_en | fuVld_en_reg;
  reg          fuVld_en_reg_1;
  reg          fuVldVec_1_1;
  reg          fuVldVec_2;
  reg          fuVldVec_3;
  wire         fuRdyVec_1 = ~fuVldVec_2 | fuRdyVec_2;
  assign fuRdyVec_2 = ~fuVldVec_3 | io_out_ready;
  wire         fuVld_en_1 =
    _in1ToN_io_out_1_valid | fuVldVec_1_1 | fuVldVec_2 | fuVldVec_3;
  wire         _GEN_0 = fuVld_en_1 | fuVld_en_reg_1;
  reg          fuVld_en_reg_2;
  reg          fuVldVec_1_2;
  reg          fuVldVec_2_1;
  reg          fuVldVec_3_1;
  wire         fuRdyVec_1_1 = ~fuVldVec_2_1 | fuRdyVec_2_1;
  assign fuRdyVec_2_1 = ~fuVldVec_3_1 | io_out_ready;
  wire         fuVld_en_2 =
    _in1ToN_io_out_2_valid | fuVldVec_1_2 | fuVldVec_2_1 | fuVldVec_3_1;
  wire         _GEN_1 = fuVld_en_2 | fuVld_en_reg_2;
  reg          fuVld_en_reg_3;
  reg          fuVldVec_1_3;
  reg          fuVldVec_2_2;
  reg          fuVldVec_3_2;
  wire         fuRdyVec_1_2 = ~fuVldVec_2_2 | fuRdyVec_2_2;
  assign fuRdyVec_2_2 = ~fuVldVec_3_2 | io_out_ready;
  wire         fuVld_en_3 =
    _in1ToN_io_out_3_valid | fuVldVec_1_3 | fuVldVec_2_2 | fuVldVec_3_2;
  wire         _GEN_2 = fuVld_en_3 | fuVld_en_reg_3;
  reg          fuVld_en_reg_4;
  reg          fuVldVec_1_4;
  reg          fuVldVec_2_3;
  reg          fuVldVec_3_3;
  wire         fuRdyVec_1_3 = ~fuVldVec_2_3 | fuRdyVec_2_3;
  assign fuRdyVec_2_3 = ~fuVldVec_3_3 | io_out_ready;
  wire         fuVld_en_4 =
    _in1ToN_io_out_4_valid | fuVldVec_1_4 | fuVldVec_2_3 | fuVldVec_3_3;
  wire         _GEN_3 = fuVld_en_4 | fuVld_en_reg_4;
  reg          inPipe_2_1;
  reg          inPipe_2_2;
  reg          inPipe_2_3;
  reg  [8:0]   inPipe_1_1_ctrl_fuOpType;
  reg          inPipe_1_1_ctrl_rfWen;
  reg          inPipe_1_1_ctrl_fpWen;
  reg          inPipe_1_1_ctrl_vecWen;
  reg          inPipe_1_1_ctrl_v0Wen;
  reg          inPipe_1_1_ctrl_fpu_wflags;
  reg          inPipe_1_1_toRobValid;
  reg          inPipe_1_1_robIdx_flag;
  reg  [5:0]   inPipe_1_1_robIdx_value;
  reg  [7:0]   inPipe_1_1_toRF_pdest;
  reg  [8:0]   inPipe_1_2_ctrl_fuOpType;
  reg          inPipe_1_2_ctrl_rfWen;
  reg          inPipe_1_2_ctrl_fpWen;
  reg          inPipe_1_2_ctrl_vecWen;
  reg          inPipe_1_2_ctrl_v0Wen;
  reg          inPipe_1_2_ctrl_fpu_wflags;
  reg          inPipe_1_2_toRobValid;
  reg          inPipe_1_2_robIdx_flag;
  reg  [5:0]   inPipe_1_2_robIdx_value;
  reg  [7:0]   inPipe_1_2_toRF_pdest;
  reg          inPipe_1_3_ctrl_rfWen;
  reg          inPipe_1_3_ctrl_fpWen;
  reg          inPipe_1_3_ctrl_vecWen;
  reg          inPipe_1_3_ctrl_v0Wen;
  reg          inPipe_1_3_ctrl_fpu_wflags;
  reg          inPipe_1_3_toRobValid;
  reg          inPipe_1_3_robIdx_flag;
  reg  [5:0]   inPipe_1_3_robIdx_value;
  reg  [7:0]   inPipe_1_3_toRF_pdest;
  reg  [63:0]  OutresVecs_2_1_data;
  reg  [4:0]   OutresVecs_2_1_fflags;
  reg  [63:0]  OutresVecs_3_1_data;
  reg  [4:0]   OutresVecs_3_1_fflags;
  reg  [63:0]  OutresVecs_3_2_data;
  reg  [4:0]   OutresVecs_3_2_fflags;
  reg  [63:0]  OutresVecs_3_3_data;
  reg  [4:0]   OutresVecs_3_3_fflags;
  reg  [127:0] OutresVecs_4_1_data;
  reg  [127:0] OutresVecs_4_2_data;
  reg  [127:0] OutresVecs_4_3_data;
  wire         fuOutValidOH_0;
  wire         fuOutValidOH_1;
  wire         fuOutValidOH_3;
  wire         fuOutValidOH_4;
  wire         fuOutValidOH_2;
  wire [2:0]   _GEN_4 =
    3'({1'h0, 2'({1'h0, fuOutValidOH_0} + {1'h0, fuOutValidOH_1})}
       + {1'h0,
          2'({1'h0, fuOutValidOH_2}
             + 2'({1'h0, fuOutValidOH_3} + {1'h0, fuOutValidOH_4}))});
  wire         _GEN_5 = |(_GEN_4[2:1]);
  wire [4:0]   data_0_probe =
    {fuOutValidOH_4, fuOutValidOH_3, fuOutValidOH_2, fuOutValidOH_1, fuOutValidOH_0};
  `ifndef SYNTHESIS
    always @(posedge clock) begin
      if ((|(_GEN_4[2:1])) & ~reset) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed at LogUtils.scala:133\n");
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire [127:0] _outFpData_T_7 =
    {64'h0,
     (~io_I2FDataIn_valid & fuOutValidOH_0 & _Falu_io_out_bits_ctrl_fpWen
        ? _Falu_io_out_bits_res_data
        : 64'h0)
       | (~io_I2FDataIn_valid & fuOutValidOH_1 & _Fmac_io_out_bits_ctrl_fpWen
            ? _Fmac_io_out_bits_res_data
            : 64'h0)
       | (~io_I2FDataIn_valid & fuOutValidOH_2 & _Fcvt_io_out_bits_ctrl_fpWen
            ? OutresVecs_2_1_data
            : 64'h0)}
    | (~io_I2FDataIn_valid & fuOutValidOH_4 & _f2v_io_out_bits_ctrl_fpWen
         ? OutresVecs_4_3_data
         : 128'h0);
  wire [6:0]   _inPipe_flushVec_flushItself_T_14 =
    {io_flush_bits_robIdx_flag, io_flush_bits_robIdx_value};
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      fuVld_en_reg <= 1'h0;
      fuVldVec_1 <= 1'h0;
      fuVld_en_reg_1 <= 1'h0;
      fuVldVec_1_1 <= 1'h0;
      fuVldVec_2 <= 1'h0;
      fuVldVec_3 <= 1'h0;
      fuVld_en_reg_2 <= 1'h0;
      fuVldVec_1_2 <= 1'h0;
      fuVldVec_2_1 <= 1'h0;
      fuVldVec_3_1 <= 1'h0;
      fuVld_en_reg_3 <= 1'h0;
      fuVldVec_1_3 <= 1'h0;
      fuVldVec_2_2 <= 1'h0;
      fuVldVec_3_2 <= 1'h0;
      fuVld_en_reg_4 <= 1'h0;
      fuVldVec_1_4 <= 1'h0;
      fuVldVec_2_3 <= 1'h0;
      fuVldVec_3_3 <= 1'h0;
      inPipe_2_1 <= 1'h0;
      inPipe_2_2 <= 1'h0;
      inPipe_2_3 <= 1'h0;
    end
    else begin
      fuVld_en_reg <= fuVld_en;
      fuVldVec_1 <=
        (~fuVldVec_1 | io_out_ready) & _in1ToN_io_out_0_valid
          ? _in1ToN_io_out_0_valid
          : ~io_out_ready & fuVldVec_1;
      fuVld_en_reg_1 <= fuVld_en_1;
      fuVldVec_1_1 <=
        (~fuVldVec_1_1 | fuRdyVec_1) & _in1ToN_io_out_1_valid
          ? _in1ToN_io_out_1_valid
          : ~fuRdyVec_1 & fuVldVec_1_1;
      fuVldVec_2 <= fuRdyVec_1 & fuVldVec_1_1 ? fuVldVec_1_1 : ~fuRdyVec_2 & fuVldVec_2;
      fuVldVec_3 <= fuRdyVec_2 & fuVldVec_2 ? fuVldVec_2 : ~io_out_ready & fuVldVec_3;
      fuVld_en_reg_2 <= fuVld_en_2;
      fuVldVec_1_2 <=
        (~fuVldVec_1_2 | fuRdyVec_1_1) & _in1ToN_io_out_2_valid
          ? _in1ToN_io_out_2_valid
          : ~fuRdyVec_1_1 & fuVldVec_1_2;
      fuVldVec_2_1 <=
        fuRdyVec_1_1 & fuVldVec_1_2 ? fuVldVec_1_2 : ~fuRdyVec_2_1 & fuVldVec_2_1;
      fuVldVec_3_1 <=
        fuRdyVec_2_1 & fuVldVec_2_1 ? fuVldVec_2_1 : ~io_out_ready & fuVldVec_3_1;
      fuVld_en_reg_3 <= fuVld_en_3;
      fuVldVec_1_3 <=
        (~fuVldVec_1_3 | fuRdyVec_1_2) & _in1ToN_io_out_3_valid
          ? _in1ToN_io_out_3_valid
          : ~fuRdyVec_1_2 & fuVldVec_1_3;
      fuVldVec_2_2 <=
        fuRdyVec_1_2 & fuVldVec_1_3 ? fuVldVec_1_3 : ~fuRdyVec_2_2 & fuVldVec_2_2;
      fuVldVec_3_2 <=
        fuRdyVec_2_2 & fuVldVec_2_2 ? fuVldVec_2_2 : ~io_out_ready & fuVldVec_3_2;
      fuVld_en_reg_4 <= fuVld_en_4;
      fuVldVec_1_4 <=
        (~fuVldVec_1_4 | fuRdyVec_1_3) & _in1ToN_io_out_4_valid
          ? _in1ToN_io_out_4_valid
          : ~fuRdyVec_1_3 & fuVldVec_1_4;
      fuVldVec_2_3 <=
        fuRdyVec_1_3 & fuVldVec_1_4 ? fuVldVec_1_4 : ~fuRdyVec_2_3 & fuVldVec_2_3;
      fuVldVec_3_3 <=
        fuRdyVec_2_3 & fuVldVec_2_3 ? fuVldVec_2_3 : ~io_out_ready & fuVldVec_3_3;
      inPipe_2_1 <=
        io_in_valid
        & ~(io_in_valid & io_flush_valid
            & (io_flush_bits_level
               & {io_in_bits_robIdx_flag,
                  io_in_bits_robIdx_value} == _inPipe_flushVec_flushItself_T_14
               | io_in_bits_robIdx_flag ^ io_flush_bits_robIdx_flag
               ^ io_in_bits_robIdx_value > io_flush_bits_robIdx_value));
      inPipe_2_2 <=
        inPipe_2_1
        & ~(inPipe_2_1 & io_flush_valid
            & (io_flush_bits_level
               & {inPipe_1_1_robIdx_flag,
                  inPipe_1_1_robIdx_value} == _inPipe_flushVec_flushItself_T_14
               | inPipe_1_1_robIdx_flag ^ io_flush_bits_robIdx_flag
               ^ inPipe_1_1_robIdx_value > io_flush_bits_robIdx_value));
      inPipe_2_3 <=
        inPipe_2_2
        & ~(inPipe_2_2 & io_flush_valid
            & (io_flush_bits_level
               & {inPipe_1_2_robIdx_flag,
                  inPipe_1_2_robIdx_value} == _inPipe_flushVec_flushItself_T_14
               | inPipe_1_2_robIdx_flag ^ io_flush_bits_robIdx_flag
               ^ inPipe_1_2_robIdx_value > io_flush_bits_robIdx_value));
    end
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    inPipe_1_1_ctrl_fuOpType <= io_in_bits_ctrl_fuOpType;
    inPipe_1_1_ctrl_rfWen <= io_in_bits_ctrl_rfWen;
    inPipe_1_1_ctrl_fpWen <= io_in_bits_ctrl_fpWen;
    inPipe_1_1_ctrl_vecWen <= io_in_bits_ctrl_vecWen;
    inPipe_1_1_ctrl_v0Wen <= io_in_bits_ctrl_v0Wen;
    inPipe_1_1_ctrl_fpu_wflags <= io_in_bits_ctrl_fpu_wflags;
    inPipe_1_1_toRobValid <= io_in_bits_toRobValid;
    inPipe_1_1_robIdx_flag <= io_in_bits_robIdx_flag;
    inPipe_1_1_robIdx_value <= io_in_bits_robIdx_value;
    inPipe_1_1_toRF_pdest <= io_in_bits_toRF_pdest;
    inPipe_1_2_ctrl_fuOpType <= inPipe_1_1_ctrl_fuOpType;
    inPipe_1_2_ctrl_rfWen <= inPipe_1_1_ctrl_rfWen;
    inPipe_1_2_ctrl_fpWen <= inPipe_1_1_ctrl_fpWen;
    inPipe_1_2_ctrl_vecWen <= inPipe_1_1_ctrl_vecWen;
    inPipe_1_2_ctrl_v0Wen <= inPipe_1_1_ctrl_v0Wen;
    inPipe_1_2_ctrl_fpu_wflags <= inPipe_1_1_ctrl_fpu_wflags;
    inPipe_1_2_toRobValid <= inPipe_1_1_toRobValid;
    inPipe_1_2_robIdx_flag <= inPipe_1_1_robIdx_flag;
    inPipe_1_2_robIdx_value <= inPipe_1_1_robIdx_value;
    inPipe_1_2_toRF_pdest <= inPipe_1_1_toRF_pdest;
    inPipe_1_3_ctrl_rfWen <= inPipe_1_2_ctrl_rfWen;
    inPipe_1_3_ctrl_fpWen <= inPipe_1_2_ctrl_fpWen;
    inPipe_1_3_ctrl_vecWen <= inPipe_1_2_ctrl_vecWen;
    inPipe_1_3_ctrl_v0Wen <= inPipe_1_2_ctrl_v0Wen;
    inPipe_1_3_ctrl_fpu_wflags <= inPipe_1_2_ctrl_fpu_wflags;
    inPipe_1_3_toRobValid <= inPipe_1_2_toRobValid;
    inPipe_1_3_robIdx_flag <= inPipe_1_2_robIdx_flag;
    inPipe_1_3_robIdx_value <= inPipe_1_2_robIdx_value;
    inPipe_1_3_toRF_pdest <= inPipe_1_2_toRF_pdest;
    OutresVecs_2_1_data <= _Fcvt_io_out_bits_res_data;
    OutresVecs_2_1_fflags <= _Fcvt_io_out_bits_res_fflags;
    OutresVecs_3_1_data <= _fcmp_io_out_bits_res_data;
    OutresVecs_3_1_fflags <= _fcmp_io_out_bits_res_fflags;
    OutresVecs_3_2_data <= OutresVecs_3_1_data;
    OutresVecs_3_2_fflags <= OutresVecs_3_1_fflags;
    OutresVecs_3_3_data <= OutresVecs_3_2_data;
    OutresVecs_3_3_fflags <= OutresVecs_3_2_fflags;
    OutresVecs_4_1_data <= _f2v_io_out_bits_res_data;
    OutresVecs_4_2_data <= OutresVecs_4_1_data;
    OutresVecs_4_3_data <= OutresVecs_4_2_data;
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:115];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [6:0] i = 7'h0; i < 7'h74; i += 7'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        fuVld_en_reg = _RANDOM[7'h0][0];
        fuVldVec_1 = _RANDOM[7'h0][2];
        fuVld_en_reg_1 = _RANDOM[7'h0][3];
        fuVldVec_1_1 = _RANDOM[7'h0][5];
        fuVldVec_2 = _RANDOM[7'h0][6];
        fuVldVec_3 = _RANDOM[7'h0][7];
        fuVld_en_reg_2 = _RANDOM[7'h0][8];
        fuVldVec_1_2 = _RANDOM[7'h0][10];
        fuVldVec_2_1 = _RANDOM[7'h0][11];
        fuVldVec_3_1 = _RANDOM[7'h0][12];
        fuVld_en_reg_3 = _RANDOM[7'h0][13];
        fuVldVec_1_3 = _RANDOM[7'h0][15];
        fuVldVec_2_2 = _RANDOM[7'h0][16];
        fuVldVec_3_2 = _RANDOM[7'h0][17];
        fuVld_en_reg_4 = _RANDOM[7'h0][18];
        fuVldVec_1_4 = _RANDOM[7'h0][20];
        fuVldVec_2_3 = _RANDOM[7'h0][21];
        fuVldVec_3_3 = _RANDOM[7'h0][22];
        inPipe_2_1 = _RANDOM[7'h0][23];
        inPipe_2_2 = _RANDOM[7'h0][24];
        inPipe_2_3 = _RANDOM[7'h0][25];
        inPipe_1_1_ctrl_fuOpType = {_RANDOM[7'h1][31:30], _RANDOM[7'h2][6:0]};
        inPipe_1_1_ctrl_rfWen = _RANDOM[7'h2][7];
        inPipe_1_1_ctrl_fpWen = _RANDOM[7'h2][8];
        inPipe_1_1_ctrl_vecWen = _RANDOM[7'h2][9];
        inPipe_1_1_ctrl_v0Wen = _RANDOM[7'h2][10];
        inPipe_1_1_ctrl_fpu_wflags = _RANDOM[7'h2][11];
        inPipe_1_1_toRobValid = _RANDOM[7'hB][12];
        inPipe_1_1_robIdx_flag = _RANDOM[7'hB][13];
        inPipe_1_1_robIdx_value = _RANDOM[7'hB][19:14];
        inPipe_1_1_toRF_pdest = _RANDOM[7'hB][27:20];
        inPipe_1_2_ctrl_fuOpType = _RANDOM[7'h21][15:7];
        inPipe_1_2_ctrl_rfWen = _RANDOM[7'h21][16];
        inPipe_1_2_ctrl_fpWen = _RANDOM[7'h21][17];
        inPipe_1_2_ctrl_vecWen = _RANDOM[7'h21][18];
        inPipe_1_2_ctrl_v0Wen = _RANDOM[7'h21][19];
        inPipe_1_2_ctrl_fpu_wflags = _RANDOM[7'h21][20];
        inPipe_1_2_toRobValid = _RANDOM[7'h2A][21];
        inPipe_1_2_robIdx_flag = _RANDOM[7'h2A][22];
        inPipe_1_2_robIdx_value = _RANDOM[7'h2A][28:23];
        inPipe_1_2_toRF_pdest = {_RANDOM[7'h2A][31:29], _RANDOM[7'h2B][4:0]};
        inPipe_1_3_ctrl_rfWen = _RANDOM[7'h40][25];
        inPipe_1_3_ctrl_fpWen = _RANDOM[7'h40][26];
        inPipe_1_3_ctrl_vecWen = _RANDOM[7'h40][27];
        inPipe_1_3_ctrl_v0Wen = _RANDOM[7'h40][28];
        inPipe_1_3_ctrl_fpu_wflags = _RANDOM[7'h40][29];
        inPipe_1_3_toRobValid = _RANDOM[7'h49][30];
        inPipe_1_3_robIdx_flag = _RANDOM[7'h49][31];
        inPipe_1_3_robIdx_value = _RANDOM[7'h4A][5:0];
        inPipe_1_3_toRF_pdest = _RANDOM[7'h4A][13:6];
        OutresVecs_2_1_data =
          {_RANDOM[7'h5E][31:21], _RANDOM[7'h5F], _RANDOM[7'h60][20:0]};
        OutresVecs_2_1_fflags = _RANDOM[7'h60][25:21];
        OutresVecs_3_1_data =
          {_RANDOM[7'h60][31:26], _RANDOM[7'h61], _RANDOM[7'h62][25:0]};
        OutresVecs_3_1_fflags = _RANDOM[7'h62][30:26];
        OutresVecs_3_2_data = {_RANDOM[7'h62][31], _RANDOM[7'h63], _RANDOM[7'h64][30:0]};
        OutresVecs_3_2_fflags = {_RANDOM[7'h64][31], _RANDOM[7'h65][3:0]};
        OutresVecs_3_3_data = {_RANDOM[7'h65][31:4], _RANDOM[7'h66], _RANDOM[7'h67][3:0]};
        OutresVecs_3_3_fflags = _RANDOM[7'h67][8:4];
        OutresVecs_4_1_data =
          {_RANDOM[7'h67][31:9],
           _RANDOM[7'h68],
           _RANDOM[7'h69],
           _RANDOM[7'h6A],
           _RANDOM[7'h6B][8:0]};
        OutresVecs_4_2_data =
          {_RANDOM[7'h6B][31:9],
           _RANDOM[7'h6C],
           _RANDOM[7'h6D],
           _RANDOM[7'h6E],
           _RANDOM[7'h6F][8:0]};
        OutresVecs_4_3_data =
          {_RANDOM[7'h6F][31:9],
           _RANDOM[7'h70],
           _RANDOM[7'h71],
           _RANDOM[7'h72],
           _RANDOM[7'h73][8:0]};
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        fuVld_en_reg = 1'h0;
        fuVldVec_1 = 1'h0;
        fuVld_en_reg_1 = 1'h0;
        fuVldVec_1_1 = 1'h0;
        fuVldVec_2 = 1'h0;
        fuVldVec_3 = 1'h0;
        fuVld_en_reg_2 = 1'h0;
        fuVldVec_1_2 = 1'h0;
        fuVldVec_2_1 = 1'h0;
        fuVldVec_3_1 = 1'h0;
        fuVld_en_reg_3 = 1'h0;
        fuVldVec_1_3 = 1'h0;
        fuVldVec_2_2 = 1'h0;
        fuVldVec_3_2 = 1'h0;
        fuVld_en_reg_4 = 1'h0;
        fuVldVec_1_4 = 1'h0;
        fuVldVec_2_3 = 1'h0;
        fuVldVec_3_3 = 1'h0;
        inPipe_2_1 = 1'h0;
        inPipe_2_2 = 1'h0;
        inPipe_2_3 = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  FAlu Falu (
    .clock                                     (_ClockGate_Q),
    .reset                                     (reset),
    .io_in_ready                               (_Falu_io_in_ready),
    .io_in_valid                               (_in1ToN_io_out_0_valid),
    .io_in_bits_ctrl_fuOpType                  (_in1ToN_io_out_0_bits_ctrl_fuOpType),
    .io_in_bits_ctrl_fpu_fmt                   (_in1ToN_io_out_0_bits_ctrl_fpu_fmt),
    .io_in_bits_ctrl_fpu_rm                    (_in1ToN_io_out_0_bits_ctrl_fpu_rm),
    .io_in_bits_ctrlPipe_1_toRobValid          (inPipe_1_1_toRobValid),
    .io_in_bits_ctrlPipe_1_robIdx_flag         (inPipe_1_1_robIdx_flag),
    .io_in_bits_ctrlPipe_1_robIdx_value        (inPipe_1_1_robIdx_value),
    .io_in_bits_ctrlPipe_1_pdest               (inPipe_1_1_toRF_pdest),
    .io_in_bits_ctrlPipe_1_fpWen               (inPipe_1_1_ctrl_fpWen),
    .io_in_bits_ctrlPipe_1_fpu_wflags          (inPipe_1_1_ctrl_fpu_wflags),
    .io_in_bits_validPipe_1                    (inPipe_2_1),
    .io_in_bits_data_src_1                     (io_in_bits_data_src_1),
    .io_in_bits_data_src_0                     (io_in_bits_data_src_0),
    .io_in_bits_perfDebugInfo_enqRsTime
      (_in1ToN_io_out_0_bits_perfDebugInfo_enqRsTime),
    .io_in_bits_perfDebugInfo_selectTime
      (_in1ToN_io_out_0_bits_perfDebugInfo_selectTime),
    .io_in_bits_perfDebugInfo_issueTime
      (_in1ToN_io_out_0_bits_perfDebugInfo_issueTime),
    .io_in_bits_perfDebugInfo_tlbFirstReqTime
      (_in1ToN_io_out_0_bits_perfDebugInfo_tlbFirstReqTime),
    .io_in_bits_perfDebugInfo_tlbRespTime
      (_in1ToN_io_out_0_bits_perfDebugInfo_tlbRespTime),
    .io_out_ready                              (io_out_ready),
    .io_out_valid                              (fuOutValidOH_0),
    .io_out_bits_ctrl_toRobValid               (_Falu_io_out_bits_ctrl_toRobValid),
    .io_out_bits_ctrl_robIdx_flag              (_Falu_io_out_bits_ctrl_robIdx_flag),
    .io_out_bits_ctrl_robIdx_value             (_Falu_io_out_bits_ctrl_robIdx_value),
    .io_out_bits_ctrl_pdest                    (_Falu_io_out_bits_ctrl_pdest),
    .io_out_bits_ctrl_fpWen                    (_Falu_io_out_bits_ctrl_fpWen),
    .io_out_bits_ctrl_fpu_wflags               (_Falu_io_out_bits_ctrl_fpu_wflags),
    .io_out_bits_res_data                      (_Falu_io_out_bits_res_data),
    .io_out_bits_res_fflags                    (_Falu_io_out_bits_res_fflags),
    .io_out_bits_perfDebugInfo_enqRsTime
      (_Falu_io_out_bits_perfDebugInfo_enqRsTime),
    .io_out_bits_perfDebugInfo_selectTime
      (_Falu_io_out_bits_perfDebugInfo_selectTime),
    .io_out_bits_perfDebugInfo_issueTime
      (_Falu_io_out_bits_perfDebugInfo_issueTime),
    .io_out_bits_perfDebugInfo_tlbFirstReqTime
      (_Falu_io_out_bits_perfDebugInfo_tlbFirstReqTime),
    .io_out_bits_perfDebugInfo_tlbRespTime
      (_Falu_io_out_bits_perfDebugInfo_tlbRespTime),
    .io_frm                                    (io_frm)
  );
  FMA Fmac (
    .clock                                     (_ClockGate_1_Q),
    .reset                                     (reset),
    .io_in_ready                               (_Fmac_io_in_ready),
    .io_in_valid                               (_in1ToN_io_out_1_valid),
    .io_in_bits_ctrl_fuOpType                  (_in1ToN_io_out_1_bits_ctrl_fuOpType),
    .io_in_bits_ctrl_fpu_fmt                   (_in1ToN_io_out_1_bits_ctrl_fpu_fmt),
    .io_in_bits_ctrl_fpu_rm                    (_in1ToN_io_out_1_bits_ctrl_fpu_rm),
    .io_in_bits_ctrlPipe_3_toRobValid          (inPipe_1_3_toRobValid),
    .io_in_bits_ctrlPipe_3_robIdx_flag         (inPipe_1_3_robIdx_flag),
    .io_in_bits_ctrlPipe_3_robIdx_value        (inPipe_1_3_robIdx_value),
    .io_in_bits_ctrlPipe_3_pdest               (inPipe_1_3_toRF_pdest),
    .io_in_bits_ctrlPipe_3_fpWen               (inPipe_1_3_ctrl_fpWen),
    .io_in_bits_ctrlPipe_3_fpu_wflags          (inPipe_1_3_ctrl_fpu_wflags),
    .io_in_bits_validPipe_3                    (inPipe_2_3),
    .io_in_bits_data_src_2                     (io_in_bits_data_src_2),
    .io_in_bits_data_src_1                     (io_in_bits_data_src_1),
    .io_in_bits_data_src_0                     (io_in_bits_data_src_0),
    .io_in_bits_perfDebugInfo_enqRsTime
      (_in1ToN_io_out_1_bits_perfDebugInfo_enqRsTime),
    .io_in_bits_perfDebugInfo_selectTime
      (_in1ToN_io_out_1_bits_perfDebugInfo_selectTime),
    .io_in_bits_perfDebugInfo_issueTime
      (_in1ToN_io_out_1_bits_perfDebugInfo_issueTime),
    .io_in_bits_perfDebugInfo_tlbFirstReqTime
      (_in1ToN_io_out_1_bits_perfDebugInfo_tlbFirstReqTime),
    .io_in_bits_perfDebugInfo_tlbRespTime
      (_in1ToN_io_out_1_bits_perfDebugInfo_tlbRespTime),
    .io_out_ready                              (io_out_ready),
    .io_out_valid                              (fuOutValidOH_1),
    .io_out_bits_ctrl_toRobValid               (_Fmac_io_out_bits_ctrl_toRobValid),
    .io_out_bits_ctrl_robIdx_flag              (_Fmac_io_out_bits_ctrl_robIdx_flag),
    .io_out_bits_ctrl_robIdx_value             (_Fmac_io_out_bits_ctrl_robIdx_value),
    .io_out_bits_ctrl_pdest                    (_Fmac_io_out_bits_ctrl_pdest),
    .io_out_bits_ctrl_fpWen                    (_Fmac_io_out_bits_ctrl_fpWen),
    .io_out_bits_ctrl_fpu_wflags               (_Fmac_io_out_bits_ctrl_fpu_wflags),
    .io_out_bits_res_data                      (_Fmac_io_out_bits_res_data),
    .io_out_bits_res_fflags                    (_Fmac_io_out_bits_res_fflags),
    .io_out_bits_perfDebugInfo_enqRsTime
      (_Fmac_io_out_bits_perfDebugInfo_enqRsTime),
    .io_out_bits_perfDebugInfo_selectTime
      (_Fmac_io_out_bits_perfDebugInfo_selectTime),
    .io_out_bits_perfDebugInfo_issueTime
      (_Fmac_io_out_bits_perfDebugInfo_issueTime),
    .io_out_bits_perfDebugInfo_tlbFirstReqTime
      (_Fmac_io_out_bits_perfDebugInfo_tlbFirstReqTime),
    .io_out_bits_perfDebugInfo_tlbRespTime
      (_Fmac_io_out_bits_perfDebugInfo_tlbRespTime),
    .io_frm                                    (io_frm)
  );
  FCVT Fcvt (
    .clock                                     (_ClockGate_2_Q),
    .reset                                     (reset),
    .io_in_ready                               (_Fcvt_io_in_ready),
    .io_in_valid                               (_in1ToN_io_out_2_valid),
    .io_in_bits_ctrl_fuOpType                  (_in1ToN_io_out_2_bits_ctrl_fuOpType),
    .io_in_bits_ctrl_fpu_fmt                   (_in1ToN_io_out_2_bits_ctrl_fpu_fmt),
    .io_in_bits_ctrl_fpu_rm                    (_in1ToN_io_out_2_bits_ctrl_fpu_rm),
    .io_in_bits_ctrlPipe_2_fuOpType            (inPipe_1_2_ctrl_fuOpType),
    .io_in_bits_ctrlPipe_3_toRobValid          (inPipe_1_3_toRobValid),
    .io_in_bits_ctrlPipe_3_robIdx_flag         (inPipe_1_3_robIdx_flag),
    .io_in_bits_ctrlPipe_3_robIdx_value        (inPipe_1_3_robIdx_value),
    .io_in_bits_ctrlPipe_3_pdest               (inPipe_1_3_toRF_pdest),
    .io_in_bits_ctrlPipe_3_rfWen               (inPipe_1_3_ctrl_rfWen),
    .io_in_bits_ctrlPipe_3_fpWen               (inPipe_1_3_ctrl_fpWen),
    .io_in_bits_ctrlPipe_3_fpu_wflags          (inPipe_1_3_ctrl_fpu_wflags),
    .io_in_bits_validPipe_2                    (inPipe_2_2),
    .io_in_bits_data_src_0                     (io_in_bits_data_src_0),
    .io_in_bits_perfDebugInfo_enqRsTime
      (_in1ToN_io_out_2_bits_perfDebugInfo_enqRsTime),
    .io_in_bits_perfDebugInfo_selectTime
      (_in1ToN_io_out_2_bits_perfDebugInfo_selectTime),
    .io_in_bits_perfDebugInfo_issueTime
      (_in1ToN_io_out_2_bits_perfDebugInfo_issueTime),
    .io_in_bits_perfDebugInfo_tlbFirstReqTime
      (_in1ToN_io_out_2_bits_perfDebugInfo_tlbFirstReqTime),
    .io_in_bits_perfDebugInfo_tlbRespTime
      (_in1ToN_io_out_2_bits_perfDebugInfo_tlbRespTime),
    .io_out_ready                              (io_out_ready),
    .io_out_valid                              (fuOutValidOH_2),
    .io_out_bits_ctrl_toRobValid               (_Fcvt_io_out_bits_ctrl_toRobValid),
    .io_out_bits_ctrl_robIdx_flag              (_Fcvt_io_out_bits_ctrl_robIdx_flag),
    .io_out_bits_ctrl_robIdx_value             (_Fcvt_io_out_bits_ctrl_robIdx_value),
    .io_out_bits_ctrl_pdest                    (_Fcvt_io_out_bits_ctrl_pdest),
    .io_out_bits_ctrl_rfWen                    (_Fcvt_io_out_bits_ctrl_rfWen),
    .io_out_bits_ctrl_fpWen                    (_Fcvt_io_out_bits_ctrl_fpWen),
    .io_out_bits_ctrl_fpu_wflags               (_Fcvt_io_out_bits_ctrl_fpu_wflags),
    .io_out_bits_res_data                      (_Fcvt_io_out_bits_res_data),
    .io_out_bits_res_fflags                    (_Fcvt_io_out_bits_res_fflags),
    .io_out_bits_perfDebugInfo_enqRsTime
      (_Fcvt_io_out_bits_perfDebugInfo_enqRsTime),
    .io_out_bits_perfDebugInfo_selectTime
      (_Fcvt_io_out_bits_perfDebugInfo_selectTime),
    .io_out_bits_perfDebugInfo_issueTime
      (_Fcvt_io_out_bits_perfDebugInfo_issueTime),
    .io_out_bits_perfDebugInfo_tlbFirstReqTime
      (_Fcvt_io_out_bits_perfDebugInfo_tlbFirstReqTime),
    .io_out_bits_perfDebugInfo_tlbRespTime
      (_Fcvt_io_out_bits_perfDebugInfo_tlbRespTime),
    .io_frm                                    (io_frm)
  );
  FCMP fcmp (
    .clock                                     (_ClockGate_3_Q),
    .reset                                     (reset),
    .io_in_ready                               (_fcmp_io_in_ready),
    .io_in_valid                               (_in1ToN_io_out_3_valid),
    .io_in_bits_ctrl_fuOpType                  (_in1ToN_io_out_3_bits_ctrl_fuOpType),
    .io_in_bits_ctrl_fpu_fmt                   (_in1ToN_io_out_3_bits_ctrl_fpu_fmt),
    .io_in_bits_ctrlPipe_3_toRobValid          (inPipe_1_3_toRobValid),
    .io_in_bits_ctrlPipe_3_robIdx_flag         (inPipe_1_3_robIdx_flag),
    .io_in_bits_ctrlPipe_3_robIdx_value        (inPipe_1_3_robIdx_value),
    .io_in_bits_ctrlPipe_3_pdest               (inPipe_1_3_toRF_pdest),
    .io_in_bits_ctrlPipe_3_rfWen               (inPipe_1_3_ctrl_rfWen),
    .io_in_bits_ctrlPipe_3_fpu_wflags          (inPipe_1_3_ctrl_fpu_wflags),
    .io_in_bits_validPipe_0                    (io_in_valid),
    .io_in_bits_data_src_1                     (io_in_bits_data_src_1),
    .io_in_bits_data_src_0                     (io_in_bits_data_src_0),
    .io_in_bits_perfDebugInfo_enqRsTime
      (_in1ToN_io_out_3_bits_perfDebugInfo_enqRsTime),
    .io_in_bits_perfDebugInfo_selectTime
      (_in1ToN_io_out_3_bits_perfDebugInfo_selectTime),
    .io_in_bits_perfDebugInfo_issueTime
      (_in1ToN_io_out_3_bits_perfDebugInfo_issueTime),
    .io_in_bits_perfDebugInfo_tlbFirstReqTime
      (_in1ToN_io_out_3_bits_perfDebugInfo_tlbFirstReqTime),
    .io_in_bits_perfDebugInfo_tlbRespTime
      (_in1ToN_io_out_3_bits_perfDebugInfo_tlbRespTime),
    .io_out_ready                              (io_out_ready),
    .io_out_valid                              (fuOutValidOH_3),
    .io_out_bits_ctrl_toRobValid               (_fcmp_io_out_bits_ctrl_toRobValid),
    .io_out_bits_ctrl_robIdx_flag              (_fcmp_io_out_bits_ctrl_robIdx_flag),
    .io_out_bits_ctrl_robIdx_value             (_fcmp_io_out_bits_ctrl_robIdx_value),
    .io_out_bits_ctrl_pdest                    (_fcmp_io_out_bits_ctrl_pdest),
    .io_out_bits_ctrl_rfWen                    (_fcmp_io_out_bits_ctrl_rfWen),
    .io_out_bits_ctrl_fpu_wflags               (_fcmp_io_out_bits_ctrl_fpu_wflags),
    .io_out_bits_res_data                      (_fcmp_io_out_bits_res_data),
    .io_out_bits_res_fflags                    (_fcmp_io_out_bits_res_fflags),
    .io_out_bits_perfDebugInfo_enqRsTime
      (_fcmp_io_out_bits_perfDebugInfo_enqRsTime),
    .io_out_bits_perfDebugInfo_selectTime
      (_fcmp_io_out_bits_perfDebugInfo_selectTime),
    .io_out_bits_perfDebugInfo_issueTime
      (_fcmp_io_out_bits_perfDebugInfo_issueTime),
    .io_out_bits_perfDebugInfo_tlbFirstReqTime
      (_fcmp_io_out_bits_perfDebugInfo_tlbFirstReqTime),
    .io_out_bits_perfDebugInfo_tlbRespTime
      (_fcmp_io_out_bits_perfDebugInfo_tlbRespTime)
  );
  IntFPToVec f2v (
    .clock                                     (_ClockGate_4_Q),
    .reset                                     (reset),
    .io_in_ready                               (_f2v_io_in_ready),
    .io_in_valid                               (_in1ToN_io_out_4_valid),
    .io_in_bits_ctrl_fuOpType                  (_in1ToN_io_out_4_bits_ctrl_fuOpType),
    .io_in_bits_ctrlPipe_3_toRobValid          (inPipe_1_3_toRobValid),
    .io_in_bits_ctrlPipe_3_robIdx_flag         (inPipe_1_3_robIdx_flag),
    .io_in_bits_ctrlPipe_3_robIdx_value        (inPipe_1_3_robIdx_value),
    .io_in_bits_ctrlPipe_3_pdest               (inPipe_1_3_toRF_pdest),
    .io_in_bits_ctrlPipe_3_fpWen               (inPipe_1_3_ctrl_fpWen),
    .io_in_bits_ctrlPipe_3_vecWen              (inPipe_1_3_ctrl_vecWen),
    .io_in_bits_ctrlPipe_3_v0Wen               (inPipe_1_3_ctrl_v0Wen),
    .io_in_bits_validPipe_0                    (io_in_valid),
    .io_in_bits_data_src_1                     (io_in_bits_data_src_1),
    .io_in_bits_data_src_0                     (io_in_bits_data_src_0),
    .io_in_bits_perfDebugInfo_enqRsTime
      (_in1ToN_io_out_4_bits_perfDebugInfo_enqRsTime),
    .io_in_bits_perfDebugInfo_selectTime
      (_in1ToN_io_out_4_bits_perfDebugInfo_selectTime),
    .io_in_bits_perfDebugInfo_issueTime
      (_in1ToN_io_out_4_bits_perfDebugInfo_issueTime),
    .io_in_bits_perfDebugInfo_tlbFirstReqTime
      (_in1ToN_io_out_4_bits_perfDebugInfo_tlbFirstReqTime),
    .io_in_bits_perfDebugInfo_tlbRespTime
      (_in1ToN_io_out_4_bits_perfDebugInfo_tlbRespTime),
    .io_out_ready                              (io_out_ready),
    .io_out_valid                              (fuOutValidOH_4),
    .io_out_bits_ctrl_toRobValid               (_f2v_io_out_bits_ctrl_toRobValid),
    .io_out_bits_ctrl_robIdx_flag              (_f2v_io_out_bits_ctrl_robIdx_flag),
    .io_out_bits_ctrl_robIdx_value             (_f2v_io_out_bits_ctrl_robIdx_value),
    .io_out_bits_ctrl_pdest                    (_f2v_io_out_bits_ctrl_pdest),
    .io_out_bits_ctrl_fpWen                    (_f2v_io_out_bits_ctrl_fpWen),
    .io_out_bits_ctrl_vecWen                   (_f2v_io_out_bits_ctrl_vecWen),
    .io_out_bits_ctrl_v0Wen                    (_f2v_io_out_bits_ctrl_v0Wen),
    .io_out_bits_res_data                      (_f2v_io_out_bits_res_data),
    .io_out_bits_perfDebugInfo_enqRsTime       (_f2v_io_out_bits_perfDebugInfo_enqRsTime),
    .io_out_bits_perfDebugInfo_selectTime
      (_f2v_io_out_bits_perfDebugInfo_selectTime),
    .io_out_bits_perfDebugInfo_issueTime       (_f2v_io_out_bits_perfDebugInfo_issueTime),
    .io_out_bits_perfDebugInfo_tlbFirstReqTime
      (_f2v_io_out_bits_perfDebugInfo_tlbFirstReqTime),
    .io_out_bits_perfDebugInfo_tlbRespTime
      (_f2v_io_out_bits_perfDebugInfo_tlbRespTime)
  );
  ClockGate ClockGate (
    .TE (Falu_clock_te_cgen),
    .E  (_GEN),
    .CK (clock),
    .Q  (_ClockGate_Q)
  );
  ClockGate ClockGate_1 (
    .TE (Fmac_clock_te_cgen),
    .E  (_GEN_0),
    .CK (clock),
    .Q  (_ClockGate_1_Q)
  );
  ClockGate ClockGate_2 (
    .TE (Fcvt_clock_te_cgen),
    .E  (_GEN_1),
    .CK (clock),
    .Q  (_ClockGate_2_Q)
  );
  ClockGate ClockGate_3 (
    .TE (fcmp_clock_te_cgen),
    .E  (_GEN_2),
    .CK (clock),
    .Q  (_ClockGate_3_Q)
  );
  ClockGate ClockGate_4 (
    .TE (f2v_clock_te_cgen),
    .E  (_GEN_3),
    .CK (clock),
    .Q  (_ClockGate_4_Q)
  );
  Dispatcher_9 in1ToN (
    .clock                                       (clock),
    .reset                                       (reset),
    .io_in_ready                                 (io_in_ready),
    .io_in_valid                                 (io_in_valid),
    .io_in_bits_ctrl_fuType                      (io_in_bits_ctrl_fuType),
    .io_in_bits_ctrl_fuOpType                    (io_in_bits_ctrl_fuOpType),
    .io_in_bits_ctrl_fpu_fmt                     (io_in_bits_ctrl_fpu_fmt),
    .io_in_bits_ctrl_fpu_rm                      (io_in_bits_ctrl_fpu_rm),
    .io_in_bits_perfDebugInfo_enqRsTime          (io_in_bits_perfDebugInfo_enqRsTime),
    .io_in_bits_perfDebugInfo_selectTime         (io_in_bits_perfDebugInfo_selectTime),
    .io_in_bits_perfDebugInfo_issueTime          (io_in_bits_perfDebugInfo_issueTime),
    .io_in_bits_perfDebugInfo_tlbFirstReqTime
      (io_in_bits_perfDebugInfo_tlbFirstReqTime),
    .io_in_bits_perfDebugInfo_tlbRespTime        (io_in_bits_perfDebugInfo_tlbRespTime),
    .io_out_0_ready                              (_Falu_io_in_ready),
    .io_out_0_valid                              (_in1ToN_io_out_0_valid),
    .io_out_0_bits_ctrl_fuOpType                 (_in1ToN_io_out_0_bits_ctrl_fuOpType),
    .io_out_0_bits_ctrl_fpu_fmt                  (_in1ToN_io_out_0_bits_ctrl_fpu_fmt),
    .io_out_0_bits_ctrl_fpu_rm                   (_in1ToN_io_out_0_bits_ctrl_fpu_rm),
    .io_out_0_bits_perfDebugInfo_enqRsTime
      (_in1ToN_io_out_0_bits_perfDebugInfo_enqRsTime),
    .io_out_0_bits_perfDebugInfo_selectTime
      (_in1ToN_io_out_0_bits_perfDebugInfo_selectTime),
    .io_out_0_bits_perfDebugInfo_issueTime
      (_in1ToN_io_out_0_bits_perfDebugInfo_issueTime),
    .io_out_0_bits_perfDebugInfo_tlbFirstReqTime
      (_in1ToN_io_out_0_bits_perfDebugInfo_tlbFirstReqTime),
    .io_out_0_bits_perfDebugInfo_tlbRespTime
      (_in1ToN_io_out_0_bits_perfDebugInfo_tlbRespTime),
    .io_out_1_ready                              (_Fmac_io_in_ready),
    .io_out_1_valid                              (_in1ToN_io_out_1_valid),
    .io_out_1_bits_ctrl_fuOpType                 (_in1ToN_io_out_1_bits_ctrl_fuOpType),
    .io_out_1_bits_ctrl_fpu_fmt                  (_in1ToN_io_out_1_bits_ctrl_fpu_fmt),
    .io_out_1_bits_ctrl_fpu_rm                   (_in1ToN_io_out_1_bits_ctrl_fpu_rm),
    .io_out_1_bits_perfDebugInfo_enqRsTime
      (_in1ToN_io_out_1_bits_perfDebugInfo_enqRsTime),
    .io_out_1_bits_perfDebugInfo_selectTime
      (_in1ToN_io_out_1_bits_perfDebugInfo_selectTime),
    .io_out_1_bits_perfDebugInfo_issueTime
      (_in1ToN_io_out_1_bits_perfDebugInfo_issueTime),
    .io_out_1_bits_perfDebugInfo_tlbFirstReqTime
      (_in1ToN_io_out_1_bits_perfDebugInfo_tlbFirstReqTime),
    .io_out_1_bits_perfDebugInfo_tlbRespTime
      (_in1ToN_io_out_1_bits_perfDebugInfo_tlbRespTime),
    .io_out_2_ready                              (_Fcvt_io_in_ready),
    .io_out_2_valid                              (_in1ToN_io_out_2_valid),
    .io_out_2_bits_ctrl_fuOpType                 (_in1ToN_io_out_2_bits_ctrl_fuOpType),
    .io_out_2_bits_ctrl_fpu_fmt                  (_in1ToN_io_out_2_bits_ctrl_fpu_fmt),
    .io_out_2_bits_ctrl_fpu_rm                   (_in1ToN_io_out_2_bits_ctrl_fpu_rm),
    .io_out_2_bits_perfDebugInfo_enqRsTime
      (_in1ToN_io_out_2_bits_perfDebugInfo_enqRsTime),
    .io_out_2_bits_perfDebugInfo_selectTime
      (_in1ToN_io_out_2_bits_perfDebugInfo_selectTime),
    .io_out_2_bits_perfDebugInfo_issueTime
      (_in1ToN_io_out_2_bits_perfDebugInfo_issueTime),
    .io_out_2_bits_perfDebugInfo_tlbFirstReqTime
      (_in1ToN_io_out_2_bits_perfDebugInfo_tlbFirstReqTime),
    .io_out_2_bits_perfDebugInfo_tlbRespTime
      (_in1ToN_io_out_2_bits_perfDebugInfo_tlbRespTime),
    .io_out_3_ready                              (_fcmp_io_in_ready),
    .io_out_3_valid                              (_in1ToN_io_out_3_valid),
    .io_out_3_bits_ctrl_fuOpType                 (_in1ToN_io_out_3_bits_ctrl_fuOpType),
    .io_out_3_bits_ctrl_fpu_fmt                  (_in1ToN_io_out_3_bits_ctrl_fpu_fmt),
    .io_out_3_bits_perfDebugInfo_enqRsTime
      (_in1ToN_io_out_3_bits_perfDebugInfo_enqRsTime),
    .io_out_3_bits_perfDebugInfo_selectTime
      (_in1ToN_io_out_3_bits_perfDebugInfo_selectTime),
    .io_out_3_bits_perfDebugInfo_issueTime
      (_in1ToN_io_out_3_bits_perfDebugInfo_issueTime),
    .io_out_3_bits_perfDebugInfo_tlbFirstReqTime
      (_in1ToN_io_out_3_bits_perfDebugInfo_tlbFirstReqTime),
    .io_out_3_bits_perfDebugInfo_tlbRespTime
      (_in1ToN_io_out_3_bits_perfDebugInfo_tlbRespTime),
    .io_out_4_ready                              (_f2v_io_in_ready),
    .io_out_4_valid                              (_in1ToN_io_out_4_valid),
    .io_out_4_bits_ctrl_fuOpType                 (_in1ToN_io_out_4_bits_ctrl_fuOpType),
    .io_out_4_bits_perfDebugInfo_enqRsTime
      (_in1ToN_io_out_4_bits_perfDebugInfo_enqRsTime),
    .io_out_4_bits_perfDebugInfo_selectTime
      (_in1ToN_io_out_4_bits_perfDebugInfo_selectTime),
    .io_out_4_bits_perfDebugInfo_issueTime
      (_in1ToN_io_out_4_bits_perfDebugInfo_issueTime),
    .io_out_4_bits_perfDebugInfo_tlbFirstReqTime
      (_in1ToN_io_out_4_bits_perfDebugInfo_tlbFirstReqTime),
    .io_out_4_bits_perfDebugInfo_tlbRespTime
      (_in1ToN_io_out_4_bits_perfDebugInfo_tlbRespTime)
  );
  assign io_out_valid =
    |{fuOutValidOH_0, fuOutValidOH_1, fuOutValidOH_2, fuOutValidOH_3, fuOutValidOH_4};
  assign io_out_bits_toRob_valid =
    fuOutValidOH_0 & _Falu_io_out_bits_ctrl_toRobValid | fuOutValidOH_1
    & _Fmac_io_out_bits_ctrl_toRobValid | fuOutValidOH_2
    & _Fcvt_io_out_bits_ctrl_toRobValid | fuOutValidOH_3
    & _fcmp_io_out_bits_ctrl_toRobValid | fuOutValidOH_4
    & _f2v_io_out_bits_ctrl_toRobValid;
  assign io_out_bits_toRob_bits_robIdx_flag =
    fuOutValidOH_0 & _Falu_io_out_bits_ctrl_robIdx_flag | fuOutValidOH_1
    & _Fmac_io_out_bits_ctrl_robIdx_flag | fuOutValidOH_2
    & _Fcvt_io_out_bits_ctrl_robIdx_flag | fuOutValidOH_3
    & _fcmp_io_out_bits_ctrl_robIdx_flag | fuOutValidOH_4
    & _f2v_io_out_bits_ctrl_robIdx_flag;
  assign io_out_bits_toRob_bits_robIdx_value =
    (fuOutValidOH_0 ? _Falu_io_out_bits_ctrl_robIdx_value : 6'h0)
    | (fuOutValidOH_1 ? _Fmac_io_out_bits_ctrl_robIdx_value : 6'h0)
    | (fuOutValidOH_2 ? _Fcvt_io_out_bits_ctrl_robIdx_value : 6'h0)
    | (fuOutValidOH_3 ? _fcmp_io_out_bits_ctrl_robIdx_value : 6'h0)
    | (fuOutValidOH_4 ? _f2v_io_out_bits_ctrl_robIdx_value : 6'h0);
  assign io_out_bits_toRob_bits_fflags =
    (fuOutValidOH_0 ? _Falu_io_out_bits_res_fflags : 5'h0)
    | (fuOutValidOH_1 ? _Fmac_io_out_bits_res_fflags : 5'h0)
    | (fuOutValidOH_2 ? OutresVecs_2_1_fflags : 5'h0)
    | (fuOutValidOH_3 ? OutresVecs_3_3_fflags : 5'h0);
  assign io_out_bits_toRob_bits_wflags =
    fuOutValidOH_0 & _Falu_io_out_bits_ctrl_fpu_wflags | fuOutValidOH_1
    & _Fmac_io_out_bits_ctrl_fpu_wflags | fuOutValidOH_2
    & _Fcvt_io_out_bits_ctrl_fpu_wflags | fuOutValidOH_3
    & _fcmp_io_out_bits_ctrl_fpu_wflags;
  assign io_out_bits_pdest =
    (fuOutValidOH_0 ? _Falu_io_out_bits_ctrl_pdest : 8'h0)
    | (fuOutValidOH_1 ? _Fmac_io_out_bits_ctrl_pdest : 8'h0)
    | (fuOutValidOH_2 ? _Fcvt_io_out_bits_ctrl_pdest : 8'h0)
    | (fuOutValidOH_3 ? _fcmp_io_out_bits_ctrl_pdest : 8'h0)
    | (fuOutValidOH_4 ? _f2v_io_out_bits_ctrl_pdest : 8'h0);
  assign io_out_bits_toIntRf_valid =
    fuOutValidOH_2 & _Fcvt_io_out_bits_ctrl_rfWen | fuOutValidOH_3
    & _fcmp_io_out_bits_ctrl_rfWen;
  assign io_out_bits_toIntRf_bits =
    {64'h0,
     (fuOutValidOH_2 & _Fcvt_io_out_bits_ctrl_rfWen ? OutresVecs_2_1_data : 64'h0)
       | (fuOutValidOH_3 & _fcmp_io_out_bits_ctrl_rfWen ? OutresVecs_3_3_data : 64'h0)};
  assign io_out_bits_toFpRf_valid =
    fuOutValidOH_0 & _Falu_io_out_bits_ctrl_fpWen | fuOutValidOH_1
    & _Fmac_io_out_bits_ctrl_fpWen | fuOutValidOH_2 & _Fcvt_io_out_bits_ctrl_fpWen
    | fuOutValidOH_4 & _f2v_io_out_bits_ctrl_fpWen;
  assign io_out_bits_toFpRf_bits =
    {_outFpData_T_7[127:64],
     _outFpData_T_7[63:0] | (io_I2FDataIn_valid ? io_I2FDataIn_bits : 64'h0)};
  assign io_out_bits_toVecRf_valid = fuOutValidOH_4 & _f2v_io_out_bits_ctrl_vecWen;
  assign io_out_bits_toVecRf_bits = OutresVecs_4_3_data;
  assign io_out_bits_toV0Rf_valid = fuOutValidOH_4 & _f2v_io_out_bits_ctrl_v0Wen;
  assign io_out_bits_toV0Rf_bits = OutresVecs_4_3_data;
  assign io_out_bits_perfDebugInfo_enqRsTime =
    (fuOutValidOH_0 ? _Falu_io_out_bits_perfDebugInfo_enqRsTime : 64'h0)
    | (fuOutValidOH_1 ? _Fmac_io_out_bits_perfDebugInfo_enqRsTime : 64'h0)
    | (fuOutValidOH_2 ? _Fcvt_io_out_bits_perfDebugInfo_enqRsTime : 64'h0)
    | (fuOutValidOH_3 ? _fcmp_io_out_bits_perfDebugInfo_enqRsTime : 64'h0)
    | (fuOutValidOH_4 ? _f2v_io_out_bits_perfDebugInfo_enqRsTime : 64'h0);
  assign io_out_bits_perfDebugInfo_selectTime =
    (fuOutValidOH_0 ? _Falu_io_out_bits_perfDebugInfo_selectTime : 64'h0)
    | (fuOutValidOH_1 ? _Fmac_io_out_bits_perfDebugInfo_selectTime : 64'h0)
    | (fuOutValidOH_2 ? _Fcvt_io_out_bits_perfDebugInfo_selectTime : 64'h0)
    | (fuOutValidOH_3 ? _fcmp_io_out_bits_perfDebugInfo_selectTime : 64'h0)
    | (fuOutValidOH_4 ? _f2v_io_out_bits_perfDebugInfo_selectTime : 64'h0);
  assign io_out_bits_perfDebugInfo_issueTime =
    (fuOutValidOH_0 ? _Falu_io_out_bits_perfDebugInfo_issueTime : 64'h0)
    | (fuOutValidOH_1 ? _Fmac_io_out_bits_perfDebugInfo_issueTime : 64'h0)
    | (fuOutValidOH_2 ? _Fcvt_io_out_bits_perfDebugInfo_issueTime : 64'h0)
    | (fuOutValidOH_3 ? _fcmp_io_out_bits_perfDebugInfo_issueTime : 64'h0)
    | (fuOutValidOH_4 ? _f2v_io_out_bits_perfDebugInfo_issueTime : 64'h0);
  assign io_out_bits_perfDebugInfo_tlbFirstReqTime =
    (fuOutValidOH_0 ? _Falu_io_out_bits_perfDebugInfo_tlbFirstReqTime : 64'h0)
    | (fuOutValidOH_1 ? _Fmac_io_out_bits_perfDebugInfo_tlbFirstReqTime : 64'h0)
    | (fuOutValidOH_2 ? _Fcvt_io_out_bits_perfDebugInfo_tlbFirstReqTime : 64'h0)
    | (fuOutValidOH_3 ? _fcmp_io_out_bits_perfDebugInfo_tlbFirstReqTime : 64'h0)
    | (fuOutValidOH_4 ? _f2v_io_out_bits_perfDebugInfo_tlbFirstReqTime : 64'h0);
  assign io_out_bits_perfDebugInfo_tlbRespTime =
    (fuOutValidOH_0 ? _Falu_io_out_bits_perfDebugInfo_tlbRespTime : 64'h0)
    | (fuOutValidOH_1 ? _Fmac_io_out_bits_perfDebugInfo_tlbRespTime : 64'h0)
    | (fuOutValidOH_2 ? _Fcvt_io_out_bits_perfDebugInfo_tlbRespTime : 64'h0)
    | (fuOutValidOH_3 ? _fcmp_io_out_bits_perfDebugInfo_tlbRespTime : 64'h0)
    | (fuOutValidOH_4 ? _f2v_io_out_bits_perfDebugInfo_tlbRespTime : 64'h0);
endmodule

