// Generated by CIRCT firtool-1.135.0
module FastArbiter_9(
  output       io_in_0_ready,
  input        io_in_0_valid,
  input  [4:0] io_in_0_bits_pfSource,
  input        io_out_ready,
  output       io_out_valid,
  output [4:0] io_out_bits_pfSource
);

  assign io_in_0_ready = io_in_0_valid & io_out_ready;
  assign io_out_valid = io_in_0_valid;
  assign io_out_bits_pfSource = io_in_0_bits_pfSource;
endmodule

