// Generated by CIRCT firtool-1.135.0
module PlruStateGen_1(
  input  [2:0] io_state,
  input        io_touches_0_valid,
  input  [1:0] io_touches_0_bits,
  output [2:0] io_nextState
);

  assign io_nextState =
    io_touches_0_valid
      ? {~(io_touches_0_bits[1]),
         io_touches_0_bits[1] ? ~(io_touches_0_bits[0]) : io_state[1],
         io_touches_0_bits[1] ? io_state[0] : ~(io_touches_0_bits[0])}
      : io_state;
endmodule

