// Generated by CIRCT firtool-1.135.0
module RealWBArbiter_3(
  output        io_in_0_ready,
  input         io_in_0_valid,
  input         io_in_0_bits_rfWen,
  input         io_in_0_bits_fpWen,
  input  [5:0]  io_in_0_bits_pdest,
  input  [63:0] io_in_0_bits_data,
  output        io_in_1_ready,
  input         io_in_1_valid,
  input         io_in_1_bits_rfWen,
  input         io_in_1_bits_fpWen,
  input  [5:0]  io_in_1_bits_pdest,
  input  [63:0] io_in_1_bits_data,
  output        io_out_valid,
  output        io_out_bits_rfWen,
  output        io_out_bits_fpWen,
  output [5:0]  io_out_bits_pdest,
  output [63:0] io_out_bits_data
);

  assign io_in_0_ready = 1'h1;
  assign io_in_1_ready = ~io_in_0_valid | ~io_in_1_valid;
  assign io_out_valid = io_in_0_valid | io_in_1_valid;
  assign io_out_bits_rfWen = io_in_0_valid ? io_in_0_bits_rfWen : io_in_1_bits_rfWen;
  assign io_out_bits_fpWen = io_in_0_valid ? io_in_0_bits_fpWen : io_in_1_bits_fpWen;
  assign io_out_bits_pdest = io_in_0_valid ? io_in_0_bits_pdest : io_in_1_bits_pdest;
  assign io_out_bits_data = io_in_0_valid ? io_in_0_bits_data : io_in_1_bits_data;
endmodule

