// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module StoreUnitS2(
  input         clock,
  input         reset,
  input         io_pipeIn_valid,
  input  [2:0]  io_pipeIn_bits_accessType_instrType,
  input         io_pipeIn_bits_accessType_isCbo,
  input         io_pipeIn_bits_accessType_isCboNoZero,
  input         io_pipeIn_bits_uop_exceptionVec_23,
  input         io_pipeIn_bits_uop_exceptionVec_19,
  input         io_pipeIn_bits_uop_exceptionVec_15,
  input         io_pipeIn_bits_uop_exceptionVec_7,
  input         io_pipeIn_bits_uop_exceptionVec_3,
  input  [3:0]  io_pipeIn_bits_uop_trigger,
  input         io_pipeIn_bits_uop_robIdx_flag,
  input  [5:0]  io_pipeIn_bits_uop_robIdx_value,
  input         io_pipeIn_bits_uop_perfDebugInfo_eliminatedMove,
  input  [63:0] io_pipeIn_bits_uop_perfDebugInfo_renameTime,
  input  [63:0] io_pipeIn_bits_uop_perfDebugInfo_dispatchTime,
  input  [63:0] io_pipeIn_bits_uop_perfDebugInfo_enqRsTime,
  input  [63:0] io_pipeIn_bits_uop_perfDebugInfo_selectTime,
  input  [63:0] io_pipeIn_bits_uop_perfDebugInfo_issueTime,
  input  [63:0] io_pipeIn_bits_uop_perfDebugInfo_runahead_checkpoint_id,
  input  [63:0] io_pipeIn_bits_uop_perfDebugInfo_tlbFirstReqTime,
  input  [63:0] io_pipeIn_bits_uop_perfDebugInfo_tlbRespTime,
  input  [55:0] io_pipeIn_bits_uop_debug_seqNum_seqNum,
  input  [7:0]  io_pipeIn_bits_uop_debug_seqNum_uopIdx,
  input         io_pipeIn_bits_uop_sqIdx_first_flag,
  input         io_pipeIn_bits_uop_sqIdx_second_flag,
  input  [3:0]  io_pipeIn_bits_uop_sqIdx_value,
  input  [49:0] io_pipeIn_bits_vaddr,
  input  [63:0] io_pipeIn_bits_fullva,
  input  [15:0] io_pipeIn_bits_mask,
  input         io_pipeIn_bits_align,
  input         io_pipeIn_bits_unalignHead,
  input         io_pipeIn_bits_tlbHit,
  input         io_pipeIn_bits_tlbException_vaNeedExt,
  input         io_pipeIn_bits_tlbException_isHyper,
  input  [1:0]  io_pipeIn_bits_pbmt,
  input         io_pipeIn_bits_isForVSnonLeafPTE,
  input  [47:0] io_pipeIn_bits_paddr,
  input  [63:0] io_pipeIn_bits_gpaddr,
  input         io_pipeIn_bits_hasException,
  input         io_pipeIn_bits_needRSReplay,
  input  [7:0]  io_pipeIn_bits_elemIdx,
  input  [3:0]  io_pipeIn_bits_mbIndex,
  output        io_pipeOut_valid,
  output [2:0]  io_pipeOut_bits_accessType_instrType,
  output        io_pipeOut_bits_accessType_isCbo,
  output        io_pipeOut_bits_uop_exceptionVec_23,
  output        io_pipeOut_bits_uop_exceptionVec_19,
  output        io_pipeOut_bits_uop_exceptionVec_15,
  output        io_pipeOut_bits_uop_exceptionVec_7,
  output        io_pipeOut_bits_uop_exceptionVec_6,
  output        io_pipeOut_bits_uop_exceptionVec_3,
  output [3:0]  io_pipeOut_bits_uop_trigger,
  output        io_pipeOut_bits_uop_robIdx_flag,
  output [5:0]  io_pipeOut_bits_uop_robIdx_value,
  output        io_pipeOut_bits_uop_perfDebugInfo_eliminatedMove,
  output [63:0] io_pipeOut_bits_uop_perfDebugInfo_renameTime,
  output [63:0] io_pipeOut_bits_uop_perfDebugInfo_dispatchTime,
  output [63:0] io_pipeOut_bits_uop_perfDebugInfo_enqRsTime,
  output [63:0] io_pipeOut_bits_uop_perfDebugInfo_selectTime,
  output [63:0] io_pipeOut_bits_uop_perfDebugInfo_issueTime,
  output [63:0] io_pipeOut_bits_uop_perfDebugInfo_runahead_checkpoint_id,
  output [63:0] io_pipeOut_bits_uop_perfDebugInfo_tlbFirstReqTime,
  output [63:0] io_pipeOut_bits_uop_perfDebugInfo_tlbRespTime,
  output [55:0] io_pipeOut_bits_uop_debug_seqNum_seqNum,
  output [7:0]  io_pipeOut_bits_uop_debug_seqNum_uopIdx,
  output        io_pipeOut_bits_uop_sqIdx_first_flag,
  output        io_pipeOut_bits_uop_sqIdx_second_flag,
  output [3:0]  io_pipeOut_bits_uop_sqIdx_value,
  output [49:0] io_pipeOut_bits_vaddr,
  output [63:0] io_pipeOut_bits_fullva,
  output [15:0] io_pipeOut_bits_mask,
  output        io_pipeOut_bits_unalignHead,
  output        io_pipeOut_bits_tlbHit,
  output        io_pipeOut_bits_tlbException_vaNeedExt,
  output        io_pipeOut_bits_tlbException_isHyper,
  output        io_pipeOut_bits_isForVSnonLeafPTE,
  output [47:0] io_pipeOut_bits_paddr,
  output [63:0] io_pipeOut_bits_gpaddr,
  output        io_pipeOut_bits_hasException,
  output        io_pipeOut_bits_needRSReplay,
  output        io_pipeOut_bits_nc,
  output        io_pipeOut_bits_mmio,
  output        io_pipeOut_bits_memBackTypeMM,
  output [7:0]  io_pipeOut_bits_elemIdx,
  output [3:0]  io_pipeOut_bits_mbIndex,
  input         io_redirect_valid,
  input         io_redirect_bits_level,
  input         io_redirect_bits_robIdx_flag,
  input  [5:0]  io_redirect_bits_robIdx_value,
  input         io_pmp_ld,
  input         io_pmp_st,
  input         io_pmp_mmio,
  output        io_toSqAddrRe_nc,
  output        io_toSqAddrRe_mmio,
  output        io_toSqAddrRe_memBackTypeMM,
  output        io_toSqAddrRe_hasException,
  output        io_toSqAddrRe_isLastRequest,
  output        io_unalignHeadTlbHit
);

  wire        tlbHit = io_pipeIn_valid & io_pipeIn_bits_tlbHit;
  wire        kill =
    io_redirect_valid
    & (io_redirect_bits_level
       & {io_pipeIn_bits_uop_robIdx_flag,
          io_pipeIn_bits_uop_robIdx_value} == {io_redirect_bits_robIdx_flag,
                                               io_redirect_bits_robIdx_value}
       | io_pipeIn_bits_uop_robIdx_flag ^ io_redirect_bits_robIdx_flag
       ^ io_pipeIn_bits_uop_robIdx_value > io_redirect_bits_robIdx_value);
  wire        fire = io_pipeIn_valid & ~kill;
  wire        fire_probe;
  assign fire_probe = fire;
  wire        fire_probe_0;
  assign fire_probe_0 = fire;
  wire        pmpInaccessible =
    tlbHit & (io_pmp_st | io_pmp_ld & io_pipeIn_bits_accessType_isCboNoZero);
  wire        tlbInaccessible =
    io_pipeIn_bits_uop_exceptionVec_7 | io_pipeIn_bits_uop_exceptionVec_15
    | io_pipeIn_bits_uop_exceptionVec_23;
  wire        _isMMIO_T = tlbHit & ~tlbInaccessible;
  wire        isNC = _isMMIO_T & io_pipeIn_bits_pbmt == 2'h1;
  wire        isMMIO =
    _isMMIO_T & (io_pipeIn_bits_pbmt == 2'h2 | io_pipeIn_bits_pbmt == 2'h0 & io_pmp_mmio);
  wire        isUncache = isNC | isMMIO;
  wire        _memBackTypeMM_T = io_pmp_mmio & ~tlbInaccessible;
  wire        af =
    io_pipeIn_bits_uop_exceptionVec_7 | pmpInaccessible
    | io_pipeIn_bits_accessType_instrType[1] & isUncache | io_pipeIn_bits_accessType_isCbo
    & isUncache | isMMIO & ~io_pipeIn_bits_align;
  wire        am =
    ~io_pipeIn_bits_align & io_pipeIn_bits_accessType_instrType[0] & isNC
    & ~pmpInaccessible;
  wire        hasException = io_pipeIn_bits_hasException | af | am;
  reg         pipeOutValid;
  reg  [2:0]  pipeOutBits_accessType_instrType;
  reg         pipeOutBits_accessType_isCbo;
  reg         pipeOutBits_uop_exceptionVec_23;
  reg         pipeOutBits_uop_exceptionVec_19;
  reg         pipeOutBits_uop_exceptionVec_15;
  reg         pipeOutBits_uop_exceptionVec_7;
  reg         pipeOutBits_uop_exceptionVec_6;
  reg         pipeOutBits_uop_exceptionVec_3;
  reg  [3:0]  pipeOutBits_uop_trigger;
  reg         pipeOutBits_uop_robIdx_flag;
  reg  [5:0]  pipeOutBits_uop_robIdx_value;
  reg         pipeOutBits_uop_perfDebugInfo_eliminatedMove;
  reg  [63:0] pipeOutBits_uop_perfDebugInfo_renameTime;
  reg  [63:0] pipeOutBits_uop_perfDebugInfo_dispatchTime;
  reg  [63:0] pipeOutBits_uop_perfDebugInfo_enqRsTime;
  reg  [63:0] pipeOutBits_uop_perfDebugInfo_selectTime;
  reg  [63:0] pipeOutBits_uop_perfDebugInfo_issueTime;
  reg  [63:0] pipeOutBits_uop_perfDebugInfo_runahead_checkpoint_id;
  reg  [63:0] pipeOutBits_uop_perfDebugInfo_tlbFirstReqTime;
  reg  [63:0] pipeOutBits_uop_perfDebugInfo_tlbRespTime;
  reg  [55:0] pipeOutBits_uop_debug_seqNum_seqNum;
  reg  [7:0]  pipeOutBits_uop_debug_seqNum_uopIdx;
  reg         pipeOutBits_uop_sqIdx_first_flag;
  reg         pipeOutBits_uop_sqIdx_second_flag;
  reg  [3:0]  pipeOutBits_uop_sqIdx_value;
  reg  [49:0] pipeOutBits_vaddr;
  reg  [63:0] pipeOutBits_fullva;
  reg  [15:0] pipeOutBits_mask;
  reg         pipeOutBits_unalignHead;
  reg         pipeOutBits_tlbHit;
  reg         pipeOutBits_tlbException_vaNeedExt;
  reg         pipeOutBits_tlbException_isHyper;
  reg         pipeOutBits_isForVSnonLeafPTE;
  reg  [47:0] pipeOutBits_paddr;
  reg  [63:0] pipeOutBits_gpaddr;
  reg         pipeOutBits_hasException;
  reg         pipeOutBits_needRSReplay;
  reg         pipeOutBits_nc;
  reg         pipeOutBits_mmio;
  reg         pipeOutBits_memBackTypeMM;
  reg  [7:0]  pipeOutBits_elemIdx;
  reg  [3:0]  pipeOutBits_mbIndex;
  always @(posedge clock or posedge reset) begin
    if (reset)
      pipeOutValid <= 1'h0;
    else
      pipeOutValid <= ~kill & io_pipeIn_valid;
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (io_pipeIn_valid) begin
      pipeOutBits_accessType_instrType <= io_pipeIn_bits_accessType_instrType;
      pipeOutBits_accessType_isCbo <= io_pipeIn_bits_accessType_isCbo;
      pipeOutBits_uop_exceptionVec_23 <= io_pipeIn_bits_uop_exceptionVec_23;
      pipeOutBits_uop_exceptionVec_19 <= io_pipeIn_bits_uop_exceptionVec_19;
      pipeOutBits_uop_exceptionVec_15 <= io_pipeIn_bits_uop_exceptionVec_15;
      pipeOutBits_uop_exceptionVec_7 <= af;
      pipeOutBits_uop_exceptionVec_6 <= am;
      pipeOutBits_uop_exceptionVec_3 <= io_pipeIn_bits_uop_exceptionVec_3;
      pipeOutBits_uop_trigger <= io_pipeIn_bits_uop_trigger;
      pipeOutBits_uop_robIdx_flag <= io_pipeIn_bits_uop_robIdx_flag;
      pipeOutBits_uop_robIdx_value <= io_pipeIn_bits_uop_robIdx_value;
      pipeOutBits_uop_perfDebugInfo_eliminatedMove <=
        io_pipeIn_bits_uop_perfDebugInfo_eliminatedMove;
      pipeOutBits_uop_perfDebugInfo_renameTime <=
        io_pipeIn_bits_uop_perfDebugInfo_renameTime;
      pipeOutBits_uop_perfDebugInfo_dispatchTime <=
        io_pipeIn_bits_uop_perfDebugInfo_dispatchTime;
      pipeOutBits_uop_perfDebugInfo_enqRsTime <=
        io_pipeIn_bits_uop_perfDebugInfo_enqRsTime;
      pipeOutBits_uop_perfDebugInfo_selectTime <=
        io_pipeIn_bits_uop_perfDebugInfo_selectTime;
      pipeOutBits_uop_perfDebugInfo_issueTime <=
        io_pipeIn_bits_uop_perfDebugInfo_issueTime;
      pipeOutBits_uop_perfDebugInfo_runahead_checkpoint_id <=
        io_pipeIn_bits_uop_perfDebugInfo_runahead_checkpoint_id;
      pipeOutBits_uop_perfDebugInfo_tlbFirstReqTime <=
        io_pipeIn_bits_uop_perfDebugInfo_tlbFirstReqTime;
      pipeOutBits_uop_perfDebugInfo_tlbRespTime <=
        io_pipeIn_bits_uop_perfDebugInfo_tlbRespTime;
      pipeOutBits_uop_debug_seqNum_seqNum <= io_pipeIn_bits_uop_debug_seqNum_seqNum;
      pipeOutBits_uop_debug_seqNum_uopIdx <= io_pipeIn_bits_uop_debug_seqNum_uopIdx;
      pipeOutBits_uop_sqIdx_first_flag <= io_pipeIn_bits_uop_sqIdx_first_flag;
      pipeOutBits_uop_sqIdx_second_flag <= io_pipeIn_bits_uop_sqIdx_second_flag;
      pipeOutBits_uop_sqIdx_value <= io_pipeIn_bits_uop_sqIdx_value;
      pipeOutBits_vaddr <= io_pipeIn_bits_vaddr;
      pipeOutBits_fullva <= io_pipeIn_bits_fullva;
      pipeOutBits_mask <= io_pipeIn_bits_mask;
      pipeOutBits_unalignHead <= io_pipeIn_bits_unalignHead;
      pipeOutBits_tlbHit <= io_pipeIn_bits_tlbHit;
      pipeOutBits_tlbException_vaNeedExt <= io_pipeIn_bits_tlbException_vaNeedExt;
      pipeOutBits_tlbException_isHyper <= io_pipeIn_bits_tlbException_isHyper;
      pipeOutBits_isForVSnonLeafPTE <= io_pipeIn_bits_isForVSnonLeafPTE;
      pipeOutBits_paddr <= io_pipeIn_bits_paddr;
      pipeOutBits_gpaddr <= io_pipeIn_bits_gpaddr;
      pipeOutBits_hasException <= hasException;
      pipeOutBits_needRSReplay <= io_pipeIn_bits_needRSReplay;
      pipeOutBits_nc <= isNC;
      pipeOutBits_mmio <= isMMIO;
      pipeOutBits_memBackTypeMM <= ~_memBackTypeMM_T;
      pipeOutBits_elemIdx <= io_pipeIn_bits_elemIdx;
      pipeOutBits_mbIndex <= io_pipeIn_bits_mbIndex;
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:52];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [5:0] i = 6'h0; i < 6'h35; i += 6'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        pipeOutValid = _RANDOM[6'h0][0];
        pipeOutBits_accessType_instrType = _RANDOM[6'h0][7:5];
        pipeOutBits_accessType_isCbo = _RANDOM[6'h0][8];
        pipeOutBits_uop_exceptionVec_23 = _RANDOM[6'h3][6];
        pipeOutBits_uop_exceptionVec_19 = _RANDOM[6'h3][10];
        pipeOutBits_uop_exceptionVec_15 = _RANDOM[6'h3][13];
        pipeOutBits_uop_exceptionVec_7 = _RANDOM[6'h3][20];
        pipeOutBits_uop_exceptionVec_6 = _RANDOM[6'h3][21];
        pipeOutBits_uop_exceptionVec_3 = _RANDOM[6'h3][24];
        pipeOutBits_uop_trigger = {_RANDOM[6'h3][31:30], _RANDOM[6'h4][1:0]};
        pipeOutBits_uop_robIdx_flag = _RANDOM[6'h12][26];
        pipeOutBits_uop_robIdx_value = {_RANDOM[6'h12][31:27], _RANDOM[6'h13][0]};
        pipeOutBits_uop_perfDebugInfo_eliminatedMove = _RANDOM[6'h13][15];
        pipeOutBits_uop_perfDebugInfo_renameTime =
          {_RANDOM[6'h13][31:16], _RANDOM[6'h14], _RANDOM[6'h15][15:0]};
        pipeOutBits_uop_perfDebugInfo_dispatchTime =
          {_RANDOM[6'h15][31:16], _RANDOM[6'h16], _RANDOM[6'h17][15:0]};
        pipeOutBits_uop_perfDebugInfo_enqRsTime =
          {_RANDOM[6'h17][31:16], _RANDOM[6'h18], _RANDOM[6'h19][15:0]};
        pipeOutBits_uop_perfDebugInfo_selectTime =
          {_RANDOM[6'h19][31:16], _RANDOM[6'h1A], _RANDOM[6'h1B][15:0]};
        pipeOutBits_uop_perfDebugInfo_issueTime =
          {_RANDOM[6'h1B][31:16], _RANDOM[6'h1C], _RANDOM[6'h1D][15:0]};
        pipeOutBits_uop_perfDebugInfo_runahead_checkpoint_id =
          {_RANDOM[6'h1F][31:16], _RANDOM[6'h20], _RANDOM[6'h21][15:0]};
        pipeOutBits_uop_perfDebugInfo_tlbFirstReqTime =
          {_RANDOM[6'h21][31:16], _RANDOM[6'h22], _RANDOM[6'h23][15:0]};
        pipeOutBits_uop_perfDebugInfo_tlbRespTime =
          {_RANDOM[6'h23][31:16], _RANDOM[6'h24], _RANDOM[6'h25][15:0]};
        pipeOutBits_uop_debug_seqNum_seqNum =
          {_RANDOM[6'h25][31:16], _RANDOM[6'h26], _RANDOM[6'h27][7:0]};
        pipeOutBits_uop_debug_seqNum_uopIdx = _RANDOM[6'h27][15:8];
        pipeOutBits_uop_sqIdx_first_flag = _RANDOM[6'h28][8];
        pipeOutBits_uop_sqIdx_second_flag = _RANDOM[6'h28][9];
        pipeOutBits_uop_sqIdx_value = _RANDOM[6'h28][13:10];
        pipeOutBits_vaddr = {_RANDOM[6'h29][31:26], _RANDOM[6'h2A], _RANDOM[6'h2B][11:0]};
        pipeOutBits_fullva =
          {_RANDOM[6'h2B][31:12], _RANDOM[6'h2C], _RANDOM[6'h2D][11:0]};
        pipeOutBits_mask = _RANDOM[6'h2D][30:15];
        pipeOutBits_unalignHead = _RANDOM[6'h2E][8];
        pipeOutBits_tlbHit = _RANDOM[6'h2E][10];
        pipeOutBits_tlbException_vaNeedExt = _RANDOM[6'h2E][11];
        pipeOutBits_tlbException_isHyper = _RANDOM[6'h2E][12];
        pipeOutBits_isForVSnonLeafPTE = _RANDOM[6'h2E][24];
        pipeOutBits_paddr = {_RANDOM[6'h2E][31:25], _RANDOM[6'h2F], _RANDOM[6'h30][8:0]};
        pipeOutBits_gpaddr = {_RANDOM[6'h30][31:9], _RANDOM[6'h31], _RANDOM[6'h32][8:0]};
        pipeOutBits_hasException = _RANDOM[6'h32][9];
        pipeOutBits_needRSReplay = _RANDOM[6'h32][10];
        pipeOutBits_nc = _RANDOM[6'h32][11];
        pipeOutBits_mmio = _RANDOM[6'h32][12];
        pipeOutBits_memBackTypeMM = _RANDOM[6'h32][13];
        pipeOutBits_elemIdx = _RANDOM[6'h34][8:1];
        pipeOutBits_mbIndex = _RANDOM[6'h34][12:9];
      `endif // RANDOMIZE_REG_INIT
      if (reset)
        pipeOutValid = 1'h0;
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_pipeOut_valid = pipeOutValid;
  assign io_pipeOut_bits_accessType_instrType = pipeOutBits_accessType_instrType;
  assign io_pipeOut_bits_accessType_isCbo = pipeOutBits_accessType_isCbo;
  assign io_pipeOut_bits_uop_exceptionVec_23 = pipeOutBits_uop_exceptionVec_23;
  assign io_pipeOut_bits_uop_exceptionVec_19 = pipeOutBits_uop_exceptionVec_19;
  assign io_pipeOut_bits_uop_exceptionVec_15 = pipeOutBits_uop_exceptionVec_15;
  assign io_pipeOut_bits_uop_exceptionVec_7 = pipeOutBits_uop_exceptionVec_7;
  assign io_pipeOut_bits_uop_exceptionVec_6 = pipeOutBits_uop_exceptionVec_6;
  assign io_pipeOut_bits_uop_exceptionVec_3 = pipeOutBits_uop_exceptionVec_3;
  assign io_pipeOut_bits_uop_trigger = pipeOutBits_uop_trigger;
  assign io_pipeOut_bits_uop_robIdx_flag = pipeOutBits_uop_robIdx_flag;
  assign io_pipeOut_bits_uop_robIdx_value = pipeOutBits_uop_robIdx_value;
  assign io_pipeOut_bits_uop_perfDebugInfo_eliminatedMove =
    pipeOutBits_uop_perfDebugInfo_eliminatedMove;
  assign io_pipeOut_bits_uop_perfDebugInfo_renameTime =
    pipeOutBits_uop_perfDebugInfo_renameTime;
  assign io_pipeOut_bits_uop_perfDebugInfo_dispatchTime =
    pipeOutBits_uop_perfDebugInfo_dispatchTime;
  assign io_pipeOut_bits_uop_perfDebugInfo_enqRsTime =
    pipeOutBits_uop_perfDebugInfo_enqRsTime;
  assign io_pipeOut_bits_uop_perfDebugInfo_selectTime =
    pipeOutBits_uop_perfDebugInfo_selectTime;
  assign io_pipeOut_bits_uop_perfDebugInfo_issueTime =
    pipeOutBits_uop_perfDebugInfo_issueTime;
  assign io_pipeOut_bits_uop_perfDebugInfo_runahead_checkpoint_id =
    pipeOutBits_uop_perfDebugInfo_runahead_checkpoint_id;
  assign io_pipeOut_bits_uop_perfDebugInfo_tlbFirstReqTime =
    pipeOutBits_uop_perfDebugInfo_tlbFirstReqTime;
  assign io_pipeOut_bits_uop_perfDebugInfo_tlbRespTime =
    pipeOutBits_uop_perfDebugInfo_tlbRespTime;
  assign io_pipeOut_bits_uop_debug_seqNum_seqNum = pipeOutBits_uop_debug_seqNum_seqNum;
  assign io_pipeOut_bits_uop_debug_seqNum_uopIdx = pipeOutBits_uop_debug_seqNum_uopIdx;
  assign io_pipeOut_bits_uop_sqIdx_first_flag = pipeOutBits_uop_sqIdx_first_flag;
  assign io_pipeOut_bits_uop_sqIdx_second_flag = pipeOutBits_uop_sqIdx_second_flag;
  assign io_pipeOut_bits_uop_sqIdx_value = pipeOutBits_uop_sqIdx_value;
  assign io_pipeOut_bits_vaddr = pipeOutBits_vaddr;
  assign io_pipeOut_bits_fullva = pipeOutBits_fullva;
  assign io_pipeOut_bits_mask = pipeOutBits_mask;
  assign io_pipeOut_bits_unalignHead = pipeOutBits_unalignHead;
  assign io_pipeOut_bits_tlbHit = pipeOutBits_tlbHit;
  assign io_pipeOut_bits_tlbException_vaNeedExt = pipeOutBits_tlbException_vaNeedExt;
  assign io_pipeOut_bits_tlbException_isHyper = pipeOutBits_tlbException_isHyper;
  assign io_pipeOut_bits_isForVSnonLeafPTE = pipeOutBits_isForVSnonLeafPTE;
  assign io_pipeOut_bits_paddr = pipeOutBits_paddr;
  assign io_pipeOut_bits_gpaddr = pipeOutBits_gpaddr;
  assign io_pipeOut_bits_hasException = pipeOutBits_hasException;
  assign io_pipeOut_bits_needRSReplay = pipeOutBits_needRSReplay;
  assign io_pipeOut_bits_nc = pipeOutBits_nc;
  assign io_pipeOut_bits_mmio = pipeOutBits_mmio;
  assign io_pipeOut_bits_memBackTypeMM = pipeOutBits_memBackTypeMM;
  assign io_pipeOut_bits_elemIdx = pipeOutBits_elemIdx;
  assign io_pipeOut_bits_mbIndex = pipeOutBits_mbIndex;
  assign io_toSqAddrRe_nc = isNC;
  assign io_toSqAddrRe_mmio = isMMIO;
  assign io_toSqAddrRe_memBackTypeMM = ~_memBackTypeMM_T;
  assign io_toSqAddrRe_hasException = fire & hasException;
  assign io_toSqAddrRe_isLastRequest = ~io_pipeIn_bits_unalignHead;
  assign io_unalignHeadTlbHit = fire & io_pipeIn_bits_unalignHead & tlbHit;
endmodule

