// Generated by CIRCT firtool-1.135.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module VIPU(
  input          clock,
  input          reset,
  output         io_in_ready,
  input          io_in_valid,
  input  [8:0]   io_in_bits_ctrl_fuOpType,
  input          io_in_bits_ctrl_vpu_vma,
  input          io_in_bits_ctrl_vpu_vta,
  input  [1:0]   io_in_bits_ctrl_vpu_vsew,
  input  [2:0]   io_in_bits_ctrl_vpu_vlmul,
  input          io_in_bits_ctrl_vpu_vm,
  input  [7:0]   io_in_bits_ctrl_vpu_vstart,
  input  [6:0]   io_in_bits_ctrl_vpu_vuopIdx,
  input          io_in_bits_ctrlPipe_2_toRobValid,
  input          io_in_bits_ctrlPipe_2_robIdx_flag,
  input  [5:0]   io_in_bits_ctrlPipe_2_robIdx_value,
  input  [7:0]   io_in_bits_ctrlPipe_2_pdest,
  input          io_in_bits_ctrlPipe_2_rfWen,
  input          io_in_bits_ctrlPipe_2_vecWen,
  input          io_in_bits_ctrlPipe_2_v0Wen,
  input  [7:0]   io_in_bits_ctrlPipe_2_vpu_vstart,
  input          io_in_bits_validPipe_2,
  input  [127:0] io_in_bits_data_src_3,
  input  [127:0] io_in_bits_data_src_2,
  input  [127:0] io_in_bits_data_src_1,
  input  [127:0] io_in_bits_data_src_0,
  input  [7:0]   io_in_bits_data_vl,
  input          io_in_bits_perfDebugInfo_eliminatedMove,
  input  [63:0]  io_in_bits_perfDebugInfo_renameTime,
  input  [63:0]  io_in_bits_perfDebugInfo_dispatchTime,
  input  [63:0]  io_in_bits_perfDebugInfo_enqRsTime,
  input  [63:0]  io_in_bits_perfDebugInfo_selectTime,
  input  [63:0]  io_in_bits_perfDebugInfo_issueTime,
  input  [63:0]  io_in_bits_perfDebugInfo_runahead_checkpoint_id,
  input  [63:0]  io_in_bits_perfDebugInfo_tlbFirstReqTime,
  input  [63:0]  io_in_bits_perfDebugInfo_tlbRespTime,
  input  [55:0]  io_in_bits_debug_seqNum_seqNum,
  input  [7:0]   io_in_bits_debug_seqNum_uopIdx,
  input          io_out_ready,
  output         io_out_valid,
  output         io_out_bits_ctrl_toRobValid,
  output         io_out_bits_ctrl_robIdx_flag,
  output [5:0]   io_out_bits_ctrl_robIdx_value,
  output [7:0]   io_out_bits_ctrl_pdest,
  output         io_out_bits_ctrl_rfWen,
  output         io_out_bits_ctrl_vecWen,
  output         io_out_bits_ctrl_v0Wen,
  output         io_out_bits_ctrl_exceptionVec_2,
  output [127:0] io_out_bits_res_data,
  output         io_out_bits_perfDebugInfo_eliminatedMove,
  output [63:0]  io_out_bits_perfDebugInfo_renameTime,
  output [63:0]  io_out_bits_perfDebugInfo_dispatchTime,
  output [63:0]  io_out_bits_perfDebugInfo_enqRsTime,
  output [63:0]  io_out_bits_perfDebugInfo_selectTime,
  output [63:0]  io_out_bits_perfDebugInfo_issueTime,
  output [63:0]  io_out_bits_perfDebugInfo_runahead_checkpoint_id,
  output [63:0]  io_out_bits_perfDebugInfo_tlbFirstReqTime,
  output [63:0]  io_out_bits_perfDebugInfo_tlbRespTime,
  output [55:0]  io_out_bits_debug_seqNum_seqNum,
  output [7:0]   io_out_bits_debug_seqNum_uopIdx
);

  wire        rdyVec_1;
  wire [5:0]  _decoder_io_out_opcode;
  wire [2:0]  _decoder_io_out_srcType2;
  wire [2:0]  _decoder_io_out_vdType;
  reg         validVecThisFu_1;
  reg         validVecThisFu_2;
  reg         perfVec_1_eliminatedMove;
  reg  [63:0] perfVec_1_renameTime;
  reg  [63:0] perfVec_1_dispatchTime;
  reg  [63:0] perfVec_1_enqRsTime;
  reg  [63:0] perfVec_1_selectTime;
  reg  [63:0] perfVec_1_issueTime;
  reg  [63:0] perfVec_1_runahead_checkpoint_id;
  reg  [63:0] perfVec_1_tlbFirstReqTime;
  reg  [63:0] perfVec_1_tlbRespTime;
  reg         perfVec_2_eliminatedMove;
  reg  [63:0] perfVec_2_renameTime;
  reg  [63:0] perfVec_2_dispatchTime;
  reg  [63:0] perfVec_2_enqRsTime;
  reg  [63:0] perfVec_2_selectTime;
  reg  [63:0] perfVec_2_issueTime;
  reg  [63:0] perfVec_2_runahead_checkpoint_id;
  reg  [63:0] perfVec_2_tlbFirstReqTime;
  reg  [63:0] perfVec_2_tlbRespTime;
  reg  [55:0] seqNumVec_1_seqNum;
  reg  [7:0]  seqNumVec_1_uopIdx;
  reg  [55:0] seqNumVec_2_seqNum;
  reg  [7:0]  seqNumVec_2_uopIdx;
  wire        rdyVec_0 = ~validVecThisFu_1 | rdyVec_1;
  assign rdyVec_1 = ~validVecThisFu_2 | io_out_ready;
  wire        _GEN = io_in_valid & io_in_bits_ctrl_fuOpType == 9'hFF;
  `ifndef SYNTHESIS
    always @(posedge clock) begin
      if (_GEN & ~reset) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed at LogUtils.scala:133\n");
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire        needShiftVs1 =
    (io_in_bits_ctrl_fuOpType == 9'h41 | io_in_bits_ctrl_fuOpType == 9'h42)
    & io_in_bits_ctrl_vpu_vuopIdx < {3'h0,
                                     io_in_bits_ctrl_vpu_vlmul == 3'h3
                                       ? 4'h8
                                       : io_in_bits_ctrl_vpu_vlmul == 3'h2
                                           ? 4'h4
                                           : io_in_bits_ctrl_vpu_vlmul == 3'h1
                                               ? 4'h2
                                               : 4'h1};
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      validVecThisFu_1 <= 1'h0;
      validVecThisFu_2 <= 1'h0;
    end
    else begin
      validVecThisFu_1 <= io_in_valid;
      validVecThisFu_2 <= validVecThisFu_1;
    end
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (rdyVec_0 & io_in_valid) begin
      perfVec_1_eliminatedMove <= io_in_bits_perfDebugInfo_eliminatedMove;
      perfVec_1_renameTime <= io_in_bits_perfDebugInfo_renameTime;
      perfVec_1_dispatchTime <= io_in_bits_perfDebugInfo_dispatchTime;
      perfVec_1_enqRsTime <= io_in_bits_perfDebugInfo_enqRsTime;
      perfVec_1_selectTime <= io_in_bits_perfDebugInfo_selectTime;
      perfVec_1_issueTime <= io_in_bits_perfDebugInfo_issueTime;
      perfVec_1_runahead_checkpoint_id <= io_in_bits_perfDebugInfo_runahead_checkpoint_id;
      perfVec_1_tlbFirstReqTime <= io_in_bits_perfDebugInfo_tlbFirstReqTime;
      perfVec_1_tlbRespTime <= io_in_bits_perfDebugInfo_tlbRespTime;
      seqNumVec_1_seqNum <= io_in_bits_debug_seqNum_seqNum;
      seqNumVec_1_uopIdx <= io_in_bits_debug_seqNum_uopIdx;
    end
    if (rdyVec_1 & validVecThisFu_1) begin
      perfVec_2_eliminatedMove <= perfVec_1_eliminatedMove;
      perfVec_2_renameTime <= perfVec_1_renameTime;
      perfVec_2_dispatchTime <= perfVec_1_dispatchTime;
      perfVec_2_enqRsTime <= perfVec_1_enqRsTime;
      perfVec_2_selectTime <= perfVec_1_selectTime;
      perfVec_2_issueTime <= perfVec_1_issueTime;
      perfVec_2_runahead_checkpoint_id <= perfVec_1_runahead_checkpoint_id;
      perfVec_2_tlbFirstReqTime <= perfVec_1_tlbFirstReqTime;
      perfVec_2_tlbRespTime <= perfVec_1_tlbRespTime;
      seqNumVec_2_seqNum <= seqNumVec_1_seqNum;
      seqNumVec_2_uopIdx <= seqNumVec_1_uopIdx;
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:95];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [6:0] i = 7'h0; i < 7'h60; i += 7'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        validVecThisFu_1 = _RANDOM[7'h0][0];
        validVecThisFu_2 = _RANDOM[7'h0][1];
        perfVec_1_eliminatedMove = _RANDOM[7'h37][24];
        perfVec_1_renameTime =
          {_RANDOM[7'h37][31:25], _RANDOM[7'h38], _RANDOM[7'h39][24:0]};
        perfVec_1_dispatchTime =
          {_RANDOM[7'h39][31:25], _RANDOM[7'h3A], _RANDOM[7'h3B][24:0]};
        perfVec_1_enqRsTime =
          {_RANDOM[7'h3B][31:25], _RANDOM[7'h3C], _RANDOM[7'h3D][24:0]};
        perfVec_1_selectTime =
          {_RANDOM[7'h3D][31:25], _RANDOM[7'h3E], _RANDOM[7'h3F][24:0]};
        perfVec_1_issueTime =
          {_RANDOM[7'h3F][31:25], _RANDOM[7'h40], _RANDOM[7'h41][24:0]};
        perfVec_1_runahead_checkpoint_id =
          {_RANDOM[7'h43][31:25], _RANDOM[7'h44], _RANDOM[7'h45][24:0]};
        perfVec_1_tlbFirstReqTime =
          {_RANDOM[7'h45][31:25], _RANDOM[7'h46], _RANDOM[7'h47][24:0]};
        perfVec_1_tlbRespTime =
          {_RANDOM[7'h47][31:25], _RANDOM[7'h48], _RANDOM[7'h49][24:0]};
        perfVec_2_eliminatedMove = _RANDOM[7'h49][25];
        perfVec_2_renameTime =
          {_RANDOM[7'h49][31:26], _RANDOM[7'h4A], _RANDOM[7'h4B][25:0]};
        perfVec_2_dispatchTime =
          {_RANDOM[7'h4B][31:26], _RANDOM[7'h4C], _RANDOM[7'h4D][25:0]};
        perfVec_2_enqRsTime =
          {_RANDOM[7'h4D][31:26], _RANDOM[7'h4E], _RANDOM[7'h4F][25:0]};
        perfVec_2_selectTime =
          {_RANDOM[7'h4F][31:26], _RANDOM[7'h50], _RANDOM[7'h51][25:0]};
        perfVec_2_issueTime =
          {_RANDOM[7'h51][31:26], _RANDOM[7'h52], _RANDOM[7'h53][25:0]};
        perfVec_2_runahead_checkpoint_id =
          {_RANDOM[7'h55][31:26], _RANDOM[7'h56], _RANDOM[7'h57][25:0]};
        perfVec_2_tlbFirstReqTime =
          {_RANDOM[7'h57][31:26], _RANDOM[7'h58], _RANDOM[7'h59][25:0]};
        perfVec_2_tlbRespTime =
          {_RANDOM[7'h59][31:26], _RANDOM[7'h5A], _RANDOM[7'h5B][25:0]};
        seqNumVec_1_seqNum =
          {_RANDOM[7'h5B][31:26], _RANDOM[7'h5C], _RANDOM[7'h5D][17:0]};
        seqNumVec_1_uopIdx = _RANDOM[7'h5D][25:18];
        seqNumVec_2_seqNum =
          {_RANDOM[7'h5D][31:26], _RANDOM[7'h5E], _RANDOM[7'h5F][17:0]};
        seqNumVec_2_uopIdx = _RANDOM[7'h5F][25:18];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        validVecThisFu_1 = 1'h0;
        validVecThisFu_2 = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  VIAluDecoder decoder (
    .io_in_fuOpType  (io_in_bits_ctrl_fuOpType[7:0]),
    .io_out_opcode   (_decoder_io_out_opcode),
    .io_out_srcType2 (_decoder_io_out_srcType2),
    .io_out_vdType   (_decoder_io_out_vdType)
  );
  VIAlu vialu (
    .clock                  (clock),
    .reset                  (reset),
    .io_in_valid            (io_in_valid),
    .io_in_bits_opcode_op   (_decoder_io_out_opcode),
    .io_in_bits_info_vm     (io_in_bits_ctrl_vpu_vm),
    .io_in_bits_info_ma     (io_in_bits_ctrl_vpu_vma),
    .io_in_bits_info_ta     (io_in_bits_ctrl_vpu_vta),
    .io_in_bits_info_vlmul  (io_in_bits_ctrl_vpu_vlmul),
    .io_in_bits_info_vl     (io_in_bits_data_vl),
    .io_in_bits_info_vstart (io_in_bits_ctrl_vpu_vstart[6:0]),
    .io_in_bits_info_uopIdx (io_in_bits_ctrl_vpu_vuopIdx[5:0]),
    .io_in_bits_srcType_0
      ({_decoder_io_out_srcType2[2],
        _decoder_io_out_srcType2[1] | _decoder_io_out_srcType2[2],
        {2{_decoder_io_out_srcType2[2]}}
          | 2'(io_in_bits_ctrl_vpu_vsew + {1'h0, _decoder_io_out_srcType2[0]})}),
    .io_in_bits_vdType
      ({_decoder_io_out_vdType[2],
        _decoder_io_out_vdType[1] | _decoder_io_out_vdType[2],
        {2{_decoder_io_out_vdType[2]}}
          | 2'(io_in_bits_ctrl_vpu_vsew + {1'h0, _decoder_io_out_vdType[0]})}),
    .io_in_bits_vs1
      ((needShiftVs1 ? {64'h0, io_in_bits_data_src_0[127:64]} : 128'h0)
       | (io_in_bits_ctrl_fuOpType == 9'h4B & io_in_bits_ctrl_vpu_vuopIdx == 7'h0
          | io_in_bits_ctrl_fuOpType == 9'h50 & ~(|(io_in_bits_ctrl_vpu_vuopIdx[6:1]))
          | io_in_bits_ctrl_fuOpType == 9'h51 & ~(|(io_in_bits_ctrl_vpu_vuopIdx[6:1]))
          | needShiftVs1
            ? 128'h0
            : io_in_bits_data_src_0)),
    .io_in_bits_vs2         (io_in_bits_data_src_1),
    .io_in_bits_old_vd      (io_in_bits_data_src_2),
    .io_in_bits_mask
      (io_in_bits_ctrl_vpu_vm
         ? 128'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
         : io_in_bits_data_src_3),
    .io_out_bits_vd         (io_out_bits_res_data)
  );
  assign io_in_ready = rdyVec_0;
  assign io_out_valid = io_in_bits_validPipe_2 & validVecThisFu_2;
  assign io_out_bits_ctrl_toRobValid = io_in_bits_ctrlPipe_2_toRobValid;
  assign io_out_bits_ctrl_robIdx_flag = io_in_bits_ctrlPipe_2_robIdx_flag;
  assign io_out_bits_ctrl_robIdx_value = io_in_bits_ctrlPipe_2_robIdx_value;
  assign io_out_bits_ctrl_pdest = io_in_bits_ctrlPipe_2_pdest;
  assign io_out_bits_ctrl_rfWen = io_in_bits_ctrlPipe_2_rfWen;
  assign io_out_bits_ctrl_vecWen = io_in_bits_ctrlPipe_2_vecWen;
  assign io_out_bits_ctrl_v0Wen = io_in_bits_ctrlPipe_2_v0Wen;
  assign io_out_bits_ctrl_exceptionVec_2 = |io_in_bits_ctrlPipe_2_vpu_vstart;
  assign io_out_bits_perfDebugInfo_eliminatedMove = perfVec_2_eliminatedMove;
  assign io_out_bits_perfDebugInfo_renameTime = perfVec_2_renameTime;
  assign io_out_bits_perfDebugInfo_dispatchTime = perfVec_2_dispatchTime;
  assign io_out_bits_perfDebugInfo_enqRsTime = perfVec_2_enqRsTime;
  assign io_out_bits_perfDebugInfo_selectTime = perfVec_2_selectTime;
  assign io_out_bits_perfDebugInfo_issueTime = perfVec_2_issueTime;
  assign io_out_bits_perfDebugInfo_runahead_checkpoint_id =
    perfVec_2_runahead_checkpoint_id;
  assign io_out_bits_perfDebugInfo_tlbFirstReqTime = perfVec_2_tlbFirstReqTime;
  assign io_out_bits_perfDebugInfo_tlbRespTime = perfVec_2_tlbRespTime;
  assign io_out_bits_debug_seqNum_seqNum = seqNumVec_2_seqNum;
  assign io_out_bits_debug_seqNum_uopIdx = seqNumVec_2_uopIdx;
endmodule

