// Generated by CIRCT firtool-1.135.0
module VLSplitImp(
  input          clock,
  input          reset,
  input          io_redirect_valid,
  input          io_redirect_bits_level,
  input          io_redirect_bits_robIdx_flag,
  input  [5:0]   io_redirect_bits_robIdx_value,
  output         io_in_ready,
  input          io_in_valid,
  input  [35:0]  io_in_bits_fuType,
  input  [8:0]   io_in_bits_fuOpType,
  input  [127:0] io_in_bits_src_0,
  input  [127:0] io_in_bits_src_1,
  input  [127:0] io_in_bits_src_2,
  input  [127:0] io_in_bits_src_3,
  input  [7:0]   io_in_bits_vl,
  input          io_in_bits_robIdx_flag,
  input  [5:0]   io_in_bits_robIdx_value,
  input  [7:0]   io_in_bits_pdest,
  input  [4:0]   io_in_bits_pdestVl,
  input          io_in_bits_vecWen,
  input          io_in_bits_v0Wen,
  input          io_in_bits_vlWen,
  input          io_in_bits_vpu_vill,
  input          io_in_bits_vpu_vma,
  input          io_in_bits_vpu_vta,
  input  [1:0]   io_in_bits_vpu_vsew,
  input  [2:0]   io_in_bits_vpu_vlmul,
  input          io_in_bits_vpu_specVill,
  input          io_in_bits_vpu_specVma,
  input          io_in_bits_vpu_specVta,
  input  [1:0]   io_in_bits_vpu_specVsew,
  input  [2:0]   io_in_bits_vpu_specVlmul,
  input          io_in_bits_vpu_vm,
  input  [7:0]   io_in_bits_vpu_vstart,
  input  [2:0]   io_in_bits_vpu_frm,
  input          io_in_bits_vpu_fpu_isFpToVecInst,
  input          io_in_bits_vpu_fpu_isFP32Instr,
  input          io_in_bits_vpu_fpu_isFP64Instr,
  input          io_in_bits_vpu_fpu_isReduction,
  input          io_in_bits_vpu_fpu_isFoldTo1_2,
  input          io_in_bits_vpu_fpu_isFoldTo1_4,
  input          io_in_bits_vpu_fpu_isFoldTo1_8,
  input  [1:0]   io_in_bits_vpu_vxrm,
  input  [6:0]   io_in_bits_vpu_vuopIdx,
  input          io_in_bits_vpu_lastUop,
  input  [127:0] io_in_bits_vpu_vmask,
  input  [2:0]   io_in_bits_vpu_nf,
  input  [1:0]   io_in_bits_vpu_veew,
  input          io_in_bits_vpu_isReverse,
  input          io_in_bits_vpu_isExt,
  input          io_in_bits_vpu_isNarrow,
  input          io_in_bits_vpu_isDstMask,
  input          io_in_bits_vpu_isOpMask,
  input          io_in_bits_vpu_isMove,
  input          io_in_bits_vpu_isDependOldVd,
  input          io_in_bits_vpu_isWritePartVd,
  input          io_in_bits_vpu_isVleff,
  input  [15:0]  io_in_bits_vpu_maskVecGen,
  input          io_in_bits_vpu_sew8,
  input          io_in_bits_vpu_sew16,
  input          io_in_bits_vpu_sew32,
  input          io_in_bits_vpu_sew64,
  input          io_in_bits_ftqIdx_flag,
  input  [2:0]   io_in_bits_ftqIdx_value,
  input  [3:0]   io_in_bits_ftqOffset,
  input  [4:0]   io_in_bits_numLsElem,
  input          io_in_bits_lqIdx_flag,
  input  [4:0]   io_in_bits_lqIdx_value,
  input          io_in_bits_sqIdx_first_flag,
  input          io_in_bits_sqIdx_second_flag,
  input  [3:0]   io_in_bits_sqIdx_value,
  input          io_in_bits_perfDebugInfo_eliminatedMove,
  input  [63:0]  io_in_bits_perfDebugInfo_renameTime,
  input  [63:0]  io_in_bits_perfDebugInfo_dispatchTime,
  input  [63:0]  io_in_bits_perfDebugInfo_enqRsTime,
  input  [63:0]  io_in_bits_perfDebugInfo_selectTime,
  input  [63:0]  io_in_bits_perfDebugInfo_issueTime,
  input  [63:0]  io_in_bits_perfDebugInfo_writebackTime,
  input  [63:0]  io_in_bits_perfDebugInfo_runahead_checkpoint_id,
  input  [63:0]  io_in_bits_perfDebugInfo_tlbFirstReqTime,
  input  [63:0]  io_in_bits_perfDebugInfo_tlbRespTime,
  input  [55:0]  io_in_bits_debug_seqNum_seqNum,
  input  [7:0]   io_in_bits_debug_seqNum_uopIdx,
  input          io_toMergeBuffer_req_ready,
  output         io_toMergeBuffer_req_valid,
  output [15:0]  io_toMergeBuffer_req_bits_mask,
  output [49:0]  io_toMergeBuffer_req_bits_vaddr,
  output [4:0]   io_toMergeBuffer_req_bits_flowNum,
  output [8:0]   io_toMergeBuffer_req_bits_uop_fuOpType,
  output         io_toMergeBuffer_req_bits_uop_vecWen,
  output         io_toMergeBuffer_req_bits_uop_v0Wen,
  output         io_toMergeBuffer_req_bits_uop_vlWen,
  output         io_toMergeBuffer_req_bits_uop_vpu_vill,
  output         io_toMergeBuffer_req_bits_uop_vpu_vma,
  output         io_toMergeBuffer_req_bits_uop_vpu_vta,
  output [1:0]   io_toMergeBuffer_req_bits_uop_vpu_vsew,
  output [2:0]   io_toMergeBuffer_req_bits_uop_vpu_vlmul,
  output         io_toMergeBuffer_req_bits_uop_vpu_specVill,
  output         io_toMergeBuffer_req_bits_uop_vpu_specVma,
  output         io_toMergeBuffer_req_bits_uop_vpu_specVta,
  output [1:0]   io_toMergeBuffer_req_bits_uop_vpu_specVsew,
  output [2:0]   io_toMergeBuffer_req_bits_uop_vpu_specVlmul,
  output         io_toMergeBuffer_req_bits_uop_vpu_vm,
  output [2:0]   io_toMergeBuffer_req_bits_uop_vpu_frm,
  output         io_toMergeBuffer_req_bits_uop_vpu_fpu_isFpToVecInst,
  output         io_toMergeBuffer_req_bits_uop_vpu_fpu_isFP32Instr,
  output         io_toMergeBuffer_req_bits_uop_vpu_fpu_isFP64Instr,
  output         io_toMergeBuffer_req_bits_uop_vpu_fpu_isReduction,
  output         io_toMergeBuffer_req_bits_uop_vpu_fpu_isFoldTo1_2,
  output         io_toMergeBuffer_req_bits_uop_vpu_fpu_isFoldTo1_4,
  output         io_toMergeBuffer_req_bits_uop_vpu_fpu_isFoldTo1_8,
  output [1:0]   io_toMergeBuffer_req_bits_uop_vpu_vxrm,
  output [6:0]   io_toMergeBuffer_req_bits_uop_vpu_vuopIdx,
  output         io_toMergeBuffer_req_bits_uop_vpu_lastUop,
  output [7:0]   io_toMergeBuffer_req_bits_uop_vpu_vl,
  output [2:0]   io_toMergeBuffer_req_bits_uop_vpu_nf,
  output [1:0]   io_toMergeBuffer_req_bits_uop_vpu_veew,
  output         io_toMergeBuffer_req_bits_uop_vpu_isReverse,
  output         io_toMergeBuffer_req_bits_uop_vpu_isExt,
  output         io_toMergeBuffer_req_bits_uop_vpu_isNarrow,
  output         io_toMergeBuffer_req_bits_uop_vpu_isDstMask,
  output         io_toMergeBuffer_req_bits_uop_vpu_isOpMask,
  output         io_toMergeBuffer_req_bits_uop_vpu_isMove,
  output         io_toMergeBuffer_req_bits_uop_vpu_isDependOldVd,
  output         io_toMergeBuffer_req_bits_uop_vpu_isWritePartVd,
  output         io_toMergeBuffer_req_bits_uop_vpu_isVleff,
  output [15:0]  io_toMergeBuffer_req_bits_uop_vpu_maskVecGen,
  output         io_toMergeBuffer_req_bits_uop_vpu_sew8,
  output         io_toMergeBuffer_req_bits_uop_vpu_sew16,
  output         io_toMergeBuffer_req_bits_uop_vpu_sew32,
  output         io_toMergeBuffer_req_bits_uop_vpu_sew64,
  output [6:0]   io_toMergeBuffer_req_bits_uop_uopIdx,
  output [7:0]   io_toMergeBuffer_req_bits_uop_pdest,
  output         io_toMergeBuffer_req_bits_uop_robIdx_flag,
  output [5:0]   io_toMergeBuffer_req_bits_uop_robIdx_value,
  output         io_toMergeBuffer_req_bits_uop_perfDebugInfo_eliminatedMove,
  output [63:0]  io_toMergeBuffer_req_bits_uop_perfDebugInfo_renameTime,
  output [63:0]  io_toMergeBuffer_req_bits_uop_perfDebugInfo_dispatchTime,
  output [63:0]  io_toMergeBuffer_req_bits_uop_perfDebugInfo_enqRsTime,
  output [63:0]  io_toMergeBuffer_req_bits_uop_perfDebugInfo_selectTime,
  output [63:0]  io_toMergeBuffer_req_bits_uop_perfDebugInfo_issueTime,
  output [63:0]  io_toMergeBuffer_req_bits_uop_perfDebugInfo_runahead_checkpoint_id,
  output [63:0]  io_toMergeBuffer_req_bits_uop_perfDebugInfo_tlbFirstReqTime,
  output [63:0]  io_toMergeBuffer_req_bits_uop_perfDebugInfo_tlbRespTime,
  output [55:0]  io_toMergeBuffer_req_bits_uop_debug_seqNum_seqNum,
  output [7:0]   io_toMergeBuffer_req_bits_uop_debug_seqNum_uopIdx,
  output [127:0] io_toMergeBuffer_req_bits_data,
  output [2:0]   io_toMergeBuffer_req_bits_vdIdx,
  output         io_toMergeBuffer_req_bits_fof,
  output [7:0]   io_toMergeBuffer_req_bits_vlmax,
  input          io_toMergeBuffer_resp_valid,
  input  [3:0]   io_toMergeBuffer_resp_bits_mBIndex,
  input          io_out_ready,
  output         io_out_valid,
  output [63:0]  io_out_bits_vaddr,
  output [15:0]  io_out_bits_mask,
  output [3:0]   io_out_bits_reg_offset,
  output [2:0]   io_out_bits_alignedType,
  output         io_out_bits_uop_exceptionVec_19,
  output         io_out_bits_uop_isRVC,
  output         io_out_bits_uop_ftqPtr_flag,
  output [2:0]   io_out_bits_uop_ftqPtr_value,
  output [3:0]   io_out_bits_uop_ftqOffset,
  output [8:0]   io_out_bits_uop_fuOpType,
  output         io_out_bits_uop_rfWen,
  output         io_out_bits_uop_fpWen,
  output [7:0]   io_out_bits_uop_vpu_vstart,
  output [1:0]   io_out_bits_uop_vpu_veew,
  output [6:0]   io_out_bits_uop_uopIdx,
  output [7:0]   io_out_bits_uop_pdest,
  output         io_out_bits_uop_robIdx_flag,
  output [5:0]   io_out_bits_uop_robIdx_value,
  output         io_out_bits_uop_perfDebugInfo_eliminatedMove,
  output [63:0]  io_out_bits_uop_perfDebugInfo_renameTime,
  output [63:0]  io_out_bits_uop_perfDebugInfo_dispatchTime,
  output [63:0]  io_out_bits_uop_perfDebugInfo_enqRsTime,
  output [63:0]  io_out_bits_uop_perfDebugInfo_selectTime,
  output [63:0]  io_out_bits_uop_perfDebugInfo_issueTime,
  output [63:0]  io_out_bits_uop_perfDebugInfo_runahead_checkpoint_id,
  output [63:0]  io_out_bits_uop_perfDebugInfo_tlbFirstReqTime,
  output [63:0]  io_out_bits_uop_perfDebugInfo_tlbRespTime,
  output [55:0]  io_out_bits_uop_debug_seqNum_seqNum,
  output [7:0]   io_out_bits_uop_debug_seqNum_uopIdx,
  output         io_out_bits_uop_storeSetHit,
  output         io_out_bits_uop_waitForRobIdx_flag,
  output [5:0]   io_out_bits_uop_waitForRobIdx_value,
  output         io_out_bits_uop_loadWaitBit,
  output         io_out_bits_uop_loadWaitStrict,
  output [5:0]   io_out_bits_uop_ssid,
  output         io_out_bits_uop_lqIdx_flag,
  output [4:0]   io_out_bits_uop_lqIdx_value,
  output         io_out_bits_uop_sqIdx_first_flag,
  output         io_out_bits_uop_sqIdx_second_flag,
  output [3:0]   io_out_bits_uop_sqIdx_value,
  output [3:0]   io_out_bits_mBIndex,
  output [7:0]   io_out_bits_elemIdx,
  output [7:0]   io_out_bits_elemIdxInsideVd,
  input          io_threshold_valid,
  input          io_threshold_bits_flag,
  input  [4:0]   io_threshold_bits_value
);

  wire         _VSSplitSkidBuffer_io_in_ready;
  wire         _VSSplitSkidBuffer_io_out_valid;
  wire [15:0]  _VSSplitSkidBuffer_io_out_bits_flowMask;
  wire [63:0]  _VSSplitSkidBuffer_io_out_bits_uopAddr;
  wire [127:0] _VSSplitSkidBuffer_io_out_bits_stride;
  wire [4:0]   _VSSplitSkidBuffer_io_out_bits_flowNum;
  wire [1:0]   _VSSplitSkidBuffer_io_out_bits_eew;
  wire [2:0]   _VSSplitSkidBuffer_io_out_bits_sew;
  wire [2:0]   _VSSplitSkidBuffer_io_out_bits_emul;
  wire [2:0]   _VSSplitSkidBuffer_io_out_bits_lmul;
  wire [2:0]   _VSSplitSkidBuffer_io_out_bits_instType;
  wire [4:0]   _VSSplitSkidBuffer_io_out_bits_indexedSplitOffset;
  wire         _VSSplitSkidBuffer_io_out_bits_uop_ftqPtr_flag;
  wire [2:0]   _VSSplitSkidBuffer_io_out_bits_uop_ftqPtr_value;
  wire [3:0]   _VSSplitSkidBuffer_io_out_bits_uop_ftqOffset;
  wire [8:0]   _VSSplitSkidBuffer_io_out_bits_uop_fuOpType;
  wire [7:0]   _VSSplitSkidBuffer_io_out_bits_uop_vpu_vstart;
  wire [6:0]   _VSSplitSkidBuffer_io_out_bits_uop_vpu_vuopIdx;
  wire [1:0]   _VSSplitSkidBuffer_io_out_bits_uop_vpu_veew;
  wire [6:0]   _VSSplitSkidBuffer_io_out_bits_uop_uopIdx;
  wire [7:0]   _VSSplitSkidBuffer_io_out_bits_uop_pdest;
  wire         _VSSplitSkidBuffer_io_out_bits_uop_robIdx_flag;
  wire [5:0]   _VSSplitSkidBuffer_io_out_bits_uop_robIdx_value;
  wire         _VSSplitSkidBuffer_io_out_bits_uop_perfDebugInfo_eliminatedMove;
  wire [63:0]  _VSSplitSkidBuffer_io_out_bits_uop_perfDebugInfo_renameTime;
  wire [63:0]  _VSSplitSkidBuffer_io_out_bits_uop_perfDebugInfo_dispatchTime;
  wire [63:0]  _VSSplitSkidBuffer_io_out_bits_uop_perfDebugInfo_enqRsTime;
  wire [63:0]  _VSSplitSkidBuffer_io_out_bits_uop_perfDebugInfo_selectTime;
  wire [63:0]  _VSSplitSkidBuffer_io_out_bits_uop_perfDebugInfo_issueTime;
  wire [63:0]  _VSSplitSkidBuffer_io_out_bits_uop_perfDebugInfo_runahead_checkpoint_id;
  wire [63:0]  _VSSplitSkidBuffer_io_out_bits_uop_perfDebugInfo_tlbFirstReqTime;
  wire [63:0]  _VSSplitSkidBuffer_io_out_bits_uop_perfDebugInfo_tlbRespTime;
  wire [55:0]  _VSSplitSkidBuffer_io_out_bits_uop_debug_seqNum_seqNum;
  wire [7:0]   _VSSplitSkidBuffer_io_out_bits_uop_debug_seqNum_uopIdx;
  wire         _VSSplitSkidBuffer_io_out_bits_uop_lqIdx_flag;
  wire [4:0]   _VSSplitSkidBuffer_io_out_bits_uop_lqIdx_value;
  wire         _VSSplitSkidBuffer_io_out_bits_uop_sqIdx_first_flag;
  wire         _VSSplitSkidBuffer_io_out_bits_uop_sqIdx_second_flag;
  wire [3:0]   _VSSplitSkidBuffer_io_out_bits_uop_sqIdx_value;
  wire         _VSSplitSkidBuffer_io_out_bits_preIsSplit;
  wire [3:0]   _VSSplitSkidBuffer_io_out_bits_mBIndex;
  wire [2:0]   _VSSplitSkidBuffer_io_out_bits_alignedType;
  wire [7:0]   _VSSplitSkidBuffer_io_out_bits_indexVlMaxInVd;
  wire [3:0]   _VSSplitSkidBuffer_io_out_bits_usLowBitsAddr;
  wire         _VSSplitSkidBuffer_io_out_bits_usAligned128;
  wire [31:0]  _VSSplitSkidBuffer_io_out_bits_usMask;
  wire         _splitBuffer_io_in_ready;
  wire         _splitBuffer_io_out_valid;
  wire         _splitPipeline_io_in_ready;
  wire         _splitPipeline_io_out_valid;
  wire [15:0]  _splitPipeline_io_out_bits_flowMask;
  wire [127:0] _splitPipeline_io_out_bits_data;
  wire [63:0]  _splitPipeline_io_out_bits_uopAddr;
  wire [127:0] _splitPipeline_io_out_bits_stride;
  wire [4:0]   _splitPipeline_io_out_bits_flowNum;
  wire [1:0]   _splitPipeline_io_out_bits_eew;
  wire [2:0]   _splitPipeline_io_out_bits_sew;
  wire [2:0]   _splitPipeline_io_out_bits_emul;
  wire [2:0]   _splitPipeline_io_out_bits_lmul;
  wire [2:0]   _splitPipeline_io_out_bits_instType;
  wire [4:0]   _splitPipeline_io_out_bits_indexedSplitOffset;
  wire [49:0]  _splitPipeline_io_out_bits_uop_pc;
  wire         _splitPipeline_io_out_bits_uop_ftqPtr_flag;
  wire [2:0]   _splitPipeline_io_out_bits_uop_ftqPtr_value;
  wire [3:0]   _splitPipeline_io_out_bits_uop_ftqOffset;
  wire [35:0]  _splitPipeline_io_out_bits_uop_fuType;
  wire [8:0]   _splitPipeline_io_out_bits_uop_fuOpType;
  wire         _splitPipeline_io_out_bits_uop_vecWen;
  wire         _splitPipeline_io_out_bits_uop_v0Wen;
  wire         _splitPipeline_io_out_bits_uop_vlWen;
  wire         _splitPipeline_io_out_bits_uop_vpu_vill;
  wire         _splitPipeline_io_out_bits_uop_vpu_vma;
  wire         _splitPipeline_io_out_bits_uop_vpu_vta;
  wire [1:0]   _splitPipeline_io_out_bits_uop_vpu_vsew;
  wire [2:0]   _splitPipeline_io_out_bits_uop_vpu_vlmul;
  wire         _splitPipeline_io_out_bits_uop_vpu_specVill;
  wire         _splitPipeline_io_out_bits_uop_vpu_specVma;
  wire         _splitPipeline_io_out_bits_uop_vpu_specVta;
  wire [1:0]   _splitPipeline_io_out_bits_uop_vpu_specVsew;
  wire [2:0]   _splitPipeline_io_out_bits_uop_vpu_specVlmul;
  wire         _splitPipeline_io_out_bits_uop_vpu_vm;
  wire [7:0]   _splitPipeline_io_out_bits_uop_vpu_vstart;
  wire [2:0]   _splitPipeline_io_out_bits_uop_vpu_frm;
  wire         _splitPipeline_io_out_bits_uop_vpu_fpu_isFpToVecInst;
  wire         _splitPipeline_io_out_bits_uop_vpu_fpu_isFP32Instr;
  wire         _splitPipeline_io_out_bits_uop_vpu_fpu_isFP64Instr;
  wire         _splitPipeline_io_out_bits_uop_vpu_fpu_isReduction;
  wire         _splitPipeline_io_out_bits_uop_vpu_fpu_isFoldTo1_2;
  wire         _splitPipeline_io_out_bits_uop_vpu_fpu_isFoldTo1_4;
  wire         _splitPipeline_io_out_bits_uop_vpu_fpu_isFoldTo1_8;
  wire [1:0]   _splitPipeline_io_out_bits_uop_vpu_vxrm;
  wire [6:0]   _splitPipeline_io_out_bits_uop_vpu_vuopIdx;
  wire         _splitPipeline_io_out_bits_uop_vpu_lastUop;
  wire [127:0] _splitPipeline_io_out_bits_uop_vpu_vmask;
  wire [7:0]   _splitPipeline_io_out_bits_uop_vpu_vl;
  wire [2:0]   _splitPipeline_io_out_bits_uop_vpu_nf;
  wire [1:0]   _splitPipeline_io_out_bits_uop_vpu_veew;
  wire         _splitPipeline_io_out_bits_uop_vpu_isReverse;
  wire         _splitPipeline_io_out_bits_uop_vpu_isExt;
  wire         _splitPipeline_io_out_bits_uop_vpu_isNarrow;
  wire         _splitPipeline_io_out_bits_uop_vpu_isDstMask;
  wire         _splitPipeline_io_out_bits_uop_vpu_isOpMask;
  wire         _splitPipeline_io_out_bits_uop_vpu_isMove;
  wire         _splitPipeline_io_out_bits_uop_vpu_isDependOldVd;
  wire         _splitPipeline_io_out_bits_uop_vpu_isWritePartVd;
  wire         _splitPipeline_io_out_bits_uop_vpu_isVleff;
  wire [15:0]  _splitPipeline_io_out_bits_uop_vpu_maskVecGen;
  wire         _splitPipeline_io_out_bits_uop_vpu_sew8;
  wire         _splitPipeline_io_out_bits_uop_vpu_sew16;
  wire         _splitPipeline_io_out_bits_uop_vpu_sew32;
  wire         _splitPipeline_io_out_bits_uop_vpu_sew64;
  wire [6:0]   _splitPipeline_io_out_bits_uop_uopIdx;
  wire         _splitPipeline_io_out_bits_uop_lastUop;
  wire [6:0]   _splitPipeline_io_out_bits_uop_numUops;
  wire [7:0]   _splitPipeline_io_out_bits_uop_pdest;
  wire [4:0]   _splitPipeline_io_out_bits_uop_pdestVl;
  wire         _splitPipeline_io_out_bits_uop_robIdx_flag;
  wire [5:0]   _splitPipeline_io_out_bits_uop_robIdx_value;
  wire         _splitPipeline_io_out_bits_uop_perfDebugInfo_eliminatedMove;
  wire [63:0]  _splitPipeline_io_out_bits_uop_perfDebugInfo_renameTime;
  wire [63:0]  _splitPipeline_io_out_bits_uop_perfDebugInfo_dispatchTime;
  wire [63:0]  _splitPipeline_io_out_bits_uop_perfDebugInfo_enqRsTime;
  wire [63:0]  _splitPipeline_io_out_bits_uop_perfDebugInfo_selectTime;
  wire [63:0]  _splitPipeline_io_out_bits_uop_perfDebugInfo_issueTime;
  wire [63:0]  _splitPipeline_io_out_bits_uop_perfDebugInfo_writebackTime;
  wire [63:0]  _splitPipeline_io_out_bits_uop_perfDebugInfo_runahead_checkpoint_id;
  wire [63:0]  _splitPipeline_io_out_bits_uop_perfDebugInfo_tlbFirstReqTime;
  wire [63:0]  _splitPipeline_io_out_bits_uop_perfDebugInfo_tlbRespTime;
  wire [55:0]  _splitPipeline_io_out_bits_uop_debug_seqNum_seqNum;
  wire [7:0]   _splitPipeline_io_out_bits_uop_debug_seqNum_uopIdx;
  wire         _splitPipeline_io_out_bits_uop_lqIdx_flag;
  wire [4:0]   _splitPipeline_io_out_bits_uop_lqIdx_value;
  wire         _splitPipeline_io_out_bits_uop_sqIdx_first_flag;
  wire         _splitPipeline_io_out_bits_uop_sqIdx_second_flag;
  wire [3:0]   _splitPipeline_io_out_bits_uop_sqIdx_value;
  wire [4:0]   _splitPipeline_io_out_bits_uop_numLsElem;
  wire         _splitPipeline_io_out_bits_preIsSplit;
  wire [3:0]   _splitPipeline_io_out_bits_mBIndex;
  wire [2:0]   _splitPipeline_io_out_bits_alignedType;
  wire [7:0]   _splitPipeline_io_out_bits_indexVlMaxInVd;
  wire [3:0]   _splitPipeline_io_out_bits_usLowBitsAddr;
  wire         _splitPipeline_io_out_bits_usAligned128;
  wire [31:0]  _splitPipeline_io_out_bits_usMask;
  wire [6:0]   _flushItself_T_6 =
    {io_redirect_bits_robIdx_flag, io_redirect_bits_robIdx_value};
  VLSplitPipelineImp splitPipeline (
    .clock                                                              (clock),
    .reset                                                              (reset),
    .io_redirect_valid
      (io_redirect_valid),
    .io_redirect_bits_level
      (io_redirect_bits_level),
    .io_redirect_bits_robIdx_flag
      (io_redirect_bits_robIdx_flag),
    .io_redirect_bits_robIdx_value
      (io_redirect_bits_robIdx_value),
    .io_in_ready
      (_splitPipeline_io_in_ready),
    .io_in_valid                                                        (io_in_valid),
    .io_in_bits_fuType
      (io_in_bits_fuType),
    .io_in_bits_fuOpType
      (io_in_bits_fuOpType),
    .io_in_bits_src_0
      (io_in_bits_src_0),
    .io_in_bits_src_1
      (io_in_bits_src_1),
    .io_in_bits_src_2
      (io_in_bits_src_2),
    .io_in_bits_src_3
      (io_in_bits_src_3),
    .io_in_bits_vl                                                      (io_in_bits_vl),
    .io_in_bits_robIdx_flag
      (io_in_bits_robIdx_flag),
    .io_in_bits_robIdx_value
      (io_in_bits_robIdx_value),
    .io_in_bits_pdest
      (io_in_bits_pdest),
    .io_in_bits_pdestVl
      (io_in_bits_pdestVl),
    .io_in_bits_vecWen
      (io_in_bits_vecWen),
    .io_in_bits_v0Wen
      (io_in_bits_v0Wen),
    .io_in_bits_vlWen
      (io_in_bits_vlWen),
    .io_in_bits_vpu_vill
      (io_in_bits_vpu_vill),
    .io_in_bits_vpu_vma
      (io_in_bits_vpu_vma),
    .io_in_bits_vpu_vta
      (io_in_bits_vpu_vta),
    .io_in_bits_vpu_vsew
      (io_in_bits_vpu_vsew),
    .io_in_bits_vpu_vlmul
      (io_in_bits_vpu_vlmul),
    .io_in_bits_vpu_specVill
      (io_in_bits_vpu_specVill),
    .io_in_bits_vpu_specVma
      (io_in_bits_vpu_specVma),
    .io_in_bits_vpu_specVta
      (io_in_bits_vpu_specVta),
    .io_in_bits_vpu_specVsew
      (io_in_bits_vpu_specVsew),
    .io_in_bits_vpu_specVlmul
      (io_in_bits_vpu_specVlmul),
    .io_in_bits_vpu_vm
      (io_in_bits_vpu_vm),
    .io_in_bits_vpu_vstart
      (io_in_bits_vpu_vstart),
    .io_in_bits_vpu_frm
      (io_in_bits_vpu_frm),
    .io_in_bits_vpu_fpu_isFpToVecInst
      (io_in_bits_vpu_fpu_isFpToVecInst),
    .io_in_bits_vpu_fpu_isFP32Instr
      (io_in_bits_vpu_fpu_isFP32Instr),
    .io_in_bits_vpu_fpu_isFP64Instr
      (io_in_bits_vpu_fpu_isFP64Instr),
    .io_in_bits_vpu_fpu_isReduction
      (io_in_bits_vpu_fpu_isReduction),
    .io_in_bits_vpu_fpu_isFoldTo1_2
      (io_in_bits_vpu_fpu_isFoldTo1_2),
    .io_in_bits_vpu_fpu_isFoldTo1_4
      (io_in_bits_vpu_fpu_isFoldTo1_4),
    .io_in_bits_vpu_fpu_isFoldTo1_8
      (io_in_bits_vpu_fpu_isFoldTo1_8),
    .io_in_bits_vpu_vxrm
      (io_in_bits_vpu_vxrm),
    .io_in_bits_vpu_vuopIdx
      (io_in_bits_vpu_vuopIdx),
    .io_in_bits_vpu_lastUop
      (io_in_bits_vpu_lastUop),
    .io_in_bits_vpu_vmask
      (io_in_bits_vpu_vmask),
    .io_in_bits_vpu_nf
      (io_in_bits_vpu_nf),
    .io_in_bits_vpu_veew
      (io_in_bits_vpu_veew),
    .io_in_bits_vpu_isReverse
      (io_in_bits_vpu_isReverse),
    .io_in_bits_vpu_isExt
      (io_in_bits_vpu_isExt),
    .io_in_bits_vpu_isNarrow
      (io_in_bits_vpu_isNarrow),
    .io_in_bits_vpu_isDstMask
      (io_in_bits_vpu_isDstMask),
    .io_in_bits_vpu_isOpMask
      (io_in_bits_vpu_isOpMask),
    .io_in_bits_vpu_isMove
      (io_in_bits_vpu_isMove),
    .io_in_bits_vpu_isDependOldVd
      (io_in_bits_vpu_isDependOldVd),
    .io_in_bits_vpu_isWritePartVd
      (io_in_bits_vpu_isWritePartVd),
    .io_in_bits_vpu_isVleff
      (io_in_bits_vpu_isVleff),
    .io_in_bits_vpu_maskVecGen
      (io_in_bits_vpu_maskVecGen),
    .io_in_bits_vpu_sew8
      (io_in_bits_vpu_sew8),
    .io_in_bits_vpu_sew16
      (io_in_bits_vpu_sew16),
    .io_in_bits_vpu_sew32
      (io_in_bits_vpu_sew32),
    .io_in_bits_vpu_sew64
      (io_in_bits_vpu_sew64),
    .io_in_bits_ftqIdx_flag
      (io_in_bits_ftqIdx_flag),
    .io_in_bits_ftqIdx_value
      (io_in_bits_ftqIdx_value),
    .io_in_bits_ftqOffset
      (io_in_bits_ftqOffset),
    .io_in_bits_numLsElem
      (io_in_bits_numLsElem),
    .io_in_bits_lqIdx_flag
      (io_in_bits_lqIdx_flag),
    .io_in_bits_lqIdx_value
      (io_in_bits_lqIdx_value),
    .io_in_bits_sqIdx_first_flag
      (io_in_bits_sqIdx_first_flag),
    .io_in_bits_sqIdx_second_flag
      (io_in_bits_sqIdx_second_flag),
    .io_in_bits_sqIdx_value
      (io_in_bits_sqIdx_value),
    .io_in_bits_perfDebugInfo_eliminatedMove
      (io_in_bits_perfDebugInfo_eliminatedMove),
    .io_in_bits_perfDebugInfo_renameTime
      (io_in_bits_perfDebugInfo_renameTime),
    .io_in_bits_perfDebugInfo_dispatchTime
      (io_in_bits_perfDebugInfo_dispatchTime),
    .io_in_bits_perfDebugInfo_enqRsTime
      (io_in_bits_perfDebugInfo_enqRsTime),
    .io_in_bits_perfDebugInfo_selectTime
      (io_in_bits_perfDebugInfo_selectTime),
    .io_in_bits_perfDebugInfo_issueTime
      (io_in_bits_perfDebugInfo_issueTime),
    .io_in_bits_perfDebugInfo_writebackTime
      (io_in_bits_perfDebugInfo_writebackTime),
    .io_in_bits_perfDebugInfo_runahead_checkpoint_id
      (io_in_bits_perfDebugInfo_runahead_checkpoint_id),
    .io_in_bits_perfDebugInfo_tlbFirstReqTime
      (io_in_bits_perfDebugInfo_tlbFirstReqTime),
    .io_in_bits_perfDebugInfo_tlbRespTime
      (io_in_bits_perfDebugInfo_tlbRespTime),
    .io_in_bits_debug_seqNum_seqNum
      (io_in_bits_debug_seqNum_seqNum),
    .io_in_bits_debug_seqNum_uopIdx
      (io_in_bits_debug_seqNum_uopIdx),
    .io_toMergeBuffer_req_ready
      (io_toMergeBuffer_req_ready),
    .io_toMergeBuffer_req_valid
      (io_toMergeBuffer_req_valid),
    .io_toMergeBuffer_req_bits_mask
      (io_toMergeBuffer_req_bits_mask),
    .io_toMergeBuffer_req_bits_vaddr
      (io_toMergeBuffer_req_bits_vaddr),
    .io_toMergeBuffer_req_bits_flowNum
      (io_toMergeBuffer_req_bits_flowNum),
    .io_toMergeBuffer_req_bits_uop_fuOpType
      (io_toMergeBuffer_req_bits_uop_fuOpType),
    .io_toMergeBuffer_req_bits_uop_vecWen
      (io_toMergeBuffer_req_bits_uop_vecWen),
    .io_toMergeBuffer_req_bits_uop_v0Wen
      (io_toMergeBuffer_req_bits_uop_v0Wen),
    .io_toMergeBuffer_req_bits_uop_vlWen
      (io_toMergeBuffer_req_bits_uop_vlWen),
    .io_toMergeBuffer_req_bits_uop_vpu_vill
      (io_toMergeBuffer_req_bits_uop_vpu_vill),
    .io_toMergeBuffer_req_bits_uop_vpu_vma
      (io_toMergeBuffer_req_bits_uop_vpu_vma),
    .io_toMergeBuffer_req_bits_uop_vpu_vta
      (io_toMergeBuffer_req_bits_uop_vpu_vta),
    .io_toMergeBuffer_req_bits_uop_vpu_vsew
      (io_toMergeBuffer_req_bits_uop_vpu_vsew),
    .io_toMergeBuffer_req_bits_uop_vpu_vlmul
      (io_toMergeBuffer_req_bits_uop_vpu_vlmul),
    .io_toMergeBuffer_req_bits_uop_vpu_specVill
      (io_toMergeBuffer_req_bits_uop_vpu_specVill),
    .io_toMergeBuffer_req_bits_uop_vpu_specVma
      (io_toMergeBuffer_req_bits_uop_vpu_specVma),
    .io_toMergeBuffer_req_bits_uop_vpu_specVta
      (io_toMergeBuffer_req_bits_uop_vpu_specVta),
    .io_toMergeBuffer_req_bits_uop_vpu_specVsew
      (io_toMergeBuffer_req_bits_uop_vpu_specVsew),
    .io_toMergeBuffer_req_bits_uop_vpu_specVlmul
      (io_toMergeBuffer_req_bits_uop_vpu_specVlmul),
    .io_toMergeBuffer_req_bits_uop_vpu_vm
      (io_toMergeBuffer_req_bits_uop_vpu_vm),
    .io_toMergeBuffer_req_bits_uop_vpu_frm
      (io_toMergeBuffer_req_bits_uop_vpu_frm),
    .io_toMergeBuffer_req_bits_uop_vpu_fpu_isFpToVecInst
      (io_toMergeBuffer_req_bits_uop_vpu_fpu_isFpToVecInst),
    .io_toMergeBuffer_req_bits_uop_vpu_fpu_isFP32Instr
      (io_toMergeBuffer_req_bits_uop_vpu_fpu_isFP32Instr),
    .io_toMergeBuffer_req_bits_uop_vpu_fpu_isFP64Instr
      (io_toMergeBuffer_req_bits_uop_vpu_fpu_isFP64Instr),
    .io_toMergeBuffer_req_bits_uop_vpu_fpu_isReduction
      (io_toMergeBuffer_req_bits_uop_vpu_fpu_isReduction),
    .io_toMergeBuffer_req_bits_uop_vpu_fpu_isFoldTo1_2
      (io_toMergeBuffer_req_bits_uop_vpu_fpu_isFoldTo1_2),
    .io_toMergeBuffer_req_bits_uop_vpu_fpu_isFoldTo1_4
      (io_toMergeBuffer_req_bits_uop_vpu_fpu_isFoldTo1_4),
    .io_toMergeBuffer_req_bits_uop_vpu_fpu_isFoldTo1_8
      (io_toMergeBuffer_req_bits_uop_vpu_fpu_isFoldTo1_8),
    .io_toMergeBuffer_req_bits_uop_vpu_vxrm
      (io_toMergeBuffer_req_bits_uop_vpu_vxrm),
    .io_toMergeBuffer_req_bits_uop_vpu_vuopIdx
      (io_toMergeBuffer_req_bits_uop_vpu_vuopIdx),
    .io_toMergeBuffer_req_bits_uop_vpu_lastUop
      (io_toMergeBuffer_req_bits_uop_vpu_lastUop),
    .io_toMergeBuffer_req_bits_uop_vpu_vl
      (io_toMergeBuffer_req_bits_uop_vpu_vl),
    .io_toMergeBuffer_req_bits_uop_vpu_nf
      (io_toMergeBuffer_req_bits_uop_vpu_nf),
    .io_toMergeBuffer_req_bits_uop_vpu_veew
      (io_toMergeBuffer_req_bits_uop_vpu_veew),
    .io_toMergeBuffer_req_bits_uop_vpu_isReverse
      (io_toMergeBuffer_req_bits_uop_vpu_isReverse),
    .io_toMergeBuffer_req_bits_uop_vpu_isExt
      (io_toMergeBuffer_req_bits_uop_vpu_isExt),
    .io_toMergeBuffer_req_bits_uop_vpu_isNarrow
      (io_toMergeBuffer_req_bits_uop_vpu_isNarrow),
    .io_toMergeBuffer_req_bits_uop_vpu_isDstMask
      (io_toMergeBuffer_req_bits_uop_vpu_isDstMask),
    .io_toMergeBuffer_req_bits_uop_vpu_isOpMask
      (io_toMergeBuffer_req_bits_uop_vpu_isOpMask),
    .io_toMergeBuffer_req_bits_uop_vpu_isMove
      (io_toMergeBuffer_req_bits_uop_vpu_isMove),
    .io_toMergeBuffer_req_bits_uop_vpu_isDependOldVd
      (io_toMergeBuffer_req_bits_uop_vpu_isDependOldVd),
    .io_toMergeBuffer_req_bits_uop_vpu_isWritePartVd
      (io_toMergeBuffer_req_bits_uop_vpu_isWritePartVd),
    .io_toMergeBuffer_req_bits_uop_vpu_isVleff
      (io_toMergeBuffer_req_bits_uop_vpu_isVleff),
    .io_toMergeBuffer_req_bits_uop_vpu_maskVecGen
      (io_toMergeBuffer_req_bits_uop_vpu_maskVecGen),
    .io_toMergeBuffer_req_bits_uop_vpu_sew8
      (io_toMergeBuffer_req_bits_uop_vpu_sew8),
    .io_toMergeBuffer_req_bits_uop_vpu_sew16
      (io_toMergeBuffer_req_bits_uop_vpu_sew16),
    .io_toMergeBuffer_req_bits_uop_vpu_sew32
      (io_toMergeBuffer_req_bits_uop_vpu_sew32),
    .io_toMergeBuffer_req_bits_uop_vpu_sew64
      (io_toMergeBuffer_req_bits_uop_vpu_sew64),
    .io_toMergeBuffer_req_bits_uop_uopIdx
      (io_toMergeBuffer_req_bits_uop_uopIdx),
    .io_toMergeBuffer_req_bits_uop_pdest
      (io_toMergeBuffer_req_bits_uop_pdest),
    .io_toMergeBuffer_req_bits_uop_robIdx_flag
      (io_toMergeBuffer_req_bits_uop_robIdx_flag),
    .io_toMergeBuffer_req_bits_uop_robIdx_value
      (io_toMergeBuffer_req_bits_uop_robIdx_value),
    .io_toMergeBuffer_req_bits_uop_perfDebugInfo_eliminatedMove
      (io_toMergeBuffer_req_bits_uop_perfDebugInfo_eliminatedMove),
    .io_toMergeBuffer_req_bits_uop_perfDebugInfo_renameTime
      (io_toMergeBuffer_req_bits_uop_perfDebugInfo_renameTime),
    .io_toMergeBuffer_req_bits_uop_perfDebugInfo_dispatchTime
      (io_toMergeBuffer_req_bits_uop_perfDebugInfo_dispatchTime),
    .io_toMergeBuffer_req_bits_uop_perfDebugInfo_enqRsTime
      (io_toMergeBuffer_req_bits_uop_perfDebugInfo_enqRsTime),
    .io_toMergeBuffer_req_bits_uop_perfDebugInfo_selectTime
      (io_toMergeBuffer_req_bits_uop_perfDebugInfo_selectTime),
    .io_toMergeBuffer_req_bits_uop_perfDebugInfo_issueTime
      (io_toMergeBuffer_req_bits_uop_perfDebugInfo_issueTime),
    .io_toMergeBuffer_req_bits_uop_perfDebugInfo_runahead_checkpoint_id
      (io_toMergeBuffer_req_bits_uop_perfDebugInfo_runahead_checkpoint_id),
    .io_toMergeBuffer_req_bits_uop_perfDebugInfo_tlbFirstReqTime
      (io_toMergeBuffer_req_bits_uop_perfDebugInfo_tlbFirstReqTime),
    .io_toMergeBuffer_req_bits_uop_perfDebugInfo_tlbRespTime
      (io_toMergeBuffer_req_bits_uop_perfDebugInfo_tlbRespTime),
    .io_toMergeBuffer_req_bits_uop_debug_seqNum_seqNum
      (io_toMergeBuffer_req_bits_uop_debug_seqNum_seqNum),
    .io_toMergeBuffer_req_bits_uop_debug_seqNum_uopIdx
      (io_toMergeBuffer_req_bits_uop_debug_seqNum_uopIdx),
    .io_toMergeBuffer_req_bits_data
      (io_toMergeBuffer_req_bits_data),
    .io_toMergeBuffer_req_bits_vdIdx
      (io_toMergeBuffer_req_bits_vdIdx),
    .io_toMergeBuffer_req_bits_fof
      (io_toMergeBuffer_req_bits_fof),
    .io_toMergeBuffer_req_bits_vlmax
      (io_toMergeBuffer_req_bits_vlmax),
    .io_toMergeBuffer_resp_valid
      (io_toMergeBuffer_resp_valid),
    .io_toMergeBuffer_resp_bits_mBIndex
      (io_toMergeBuffer_resp_bits_mBIndex),
    .io_out_ready
      (_VSSplitSkidBuffer_io_in_ready),
    .io_out_valid
      (_splitPipeline_io_out_valid),
    .io_out_bits_flowMask
      (_splitPipeline_io_out_bits_flowMask),
    .io_out_bits_data
      (_splitPipeline_io_out_bits_data),
    .io_out_bits_uopAddr
      (_splitPipeline_io_out_bits_uopAddr),
    .io_out_bits_stride
      (_splitPipeline_io_out_bits_stride),
    .io_out_bits_flowNum
      (_splitPipeline_io_out_bits_flowNum),
    .io_out_bits_eew
      (_splitPipeline_io_out_bits_eew),
    .io_out_bits_sew
      (_splitPipeline_io_out_bits_sew),
    .io_out_bits_emul
      (_splitPipeline_io_out_bits_emul),
    .io_out_bits_lmul
      (_splitPipeline_io_out_bits_lmul),
    .io_out_bits_instType
      (_splitPipeline_io_out_bits_instType),
    .io_out_bits_indexedSplitOffset
      (_splitPipeline_io_out_bits_indexedSplitOffset),
    .io_out_bits_uop_pc
      (_splitPipeline_io_out_bits_uop_pc),
    .io_out_bits_uop_ftqPtr_flag
      (_splitPipeline_io_out_bits_uop_ftqPtr_flag),
    .io_out_bits_uop_ftqPtr_value
      (_splitPipeline_io_out_bits_uop_ftqPtr_value),
    .io_out_bits_uop_ftqOffset
      (_splitPipeline_io_out_bits_uop_ftqOffset),
    .io_out_bits_uop_fuType
      (_splitPipeline_io_out_bits_uop_fuType),
    .io_out_bits_uop_fuOpType
      (_splitPipeline_io_out_bits_uop_fuOpType),
    .io_out_bits_uop_vecWen
      (_splitPipeline_io_out_bits_uop_vecWen),
    .io_out_bits_uop_v0Wen
      (_splitPipeline_io_out_bits_uop_v0Wen),
    .io_out_bits_uop_vlWen
      (_splitPipeline_io_out_bits_uop_vlWen),
    .io_out_bits_uop_vpu_vill
      (_splitPipeline_io_out_bits_uop_vpu_vill),
    .io_out_bits_uop_vpu_vma
      (_splitPipeline_io_out_bits_uop_vpu_vma),
    .io_out_bits_uop_vpu_vta
      (_splitPipeline_io_out_bits_uop_vpu_vta),
    .io_out_bits_uop_vpu_vsew
      (_splitPipeline_io_out_bits_uop_vpu_vsew),
    .io_out_bits_uop_vpu_vlmul
      (_splitPipeline_io_out_bits_uop_vpu_vlmul),
    .io_out_bits_uop_vpu_specVill
      (_splitPipeline_io_out_bits_uop_vpu_specVill),
    .io_out_bits_uop_vpu_specVma
      (_splitPipeline_io_out_bits_uop_vpu_specVma),
    .io_out_bits_uop_vpu_specVta
      (_splitPipeline_io_out_bits_uop_vpu_specVta),
    .io_out_bits_uop_vpu_specVsew
      (_splitPipeline_io_out_bits_uop_vpu_specVsew),
    .io_out_bits_uop_vpu_specVlmul
      (_splitPipeline_io_out_bits_uop_vpu_specVlmul),
    .io_out_bits_uop_vpu_vm
      (_splitPipeline_io_out_bits_uop_vpu_vm),
    .io_out_bits_uop_vpu_vstart
      (_splitPipeline_io_out_bits_uop_vpu_vstart),
    .io_out_bits_uop_vpu_frm
      (_splitPipeline_io_out_bits_uop_vpu_frm),
    .io_out_bits_uop_vpu_fpu_isFpToVecInst
      (_splitPipeline_io_out_bits_uop_vpu_fpu_isFpToVecInst),
    .io_out_bits_uop_vpu_fpu_isFP32Instr
      (_splitPipeline_io_out_bits_uop_vpu_fpu_isFP32Instr),
    .io_out_bits_uop_vpu_fpu_isFP64Instr
      (_splitPipeline_io_out_bits_uop_vpu_fpu_isFP64Instr),
    .io_out_bits_uop_vpu_fpu_isReduction
      (_splitPipeline_io_out_bits_uop_vpu_fpu_isReduction),
    .io_out_bits_uop_vpu_fpu_isFoldTo1_2
      (_splitPipeline_io_out_bits_uop_vpu_fpu_isFoldTo1_2),
    .io_out_bits_uop_vpu_fpu_isFoldTo1_4
      (_splitPipeline_io_out_bits_uop_vpu_fpu_isFoldTo1_4),
    .io_out_bits_uop_vpu_fpu_isFoldTo1_8
      (_splitPipeline_io_out_bits_uop_vpu_fpu_isFoldTo1_8),
    .io_out_bits_uop_vpu_vxrm
      (_splitPipeline_io_out_bits_uop_vpu_vxrm),
    .io_out_bits_uop_vpu_vuopIdx
      (_splitPipeline_io_out_bits_uop_vpu_vuopIdx),
    .io_out_bits_uop_vpu_lastUop
      (_splitPipeline_io_out_bits_uop_vpu_lastUop),
    .io_out_bits_uop_vpu_vmask
      (_splitPipeline_io_out_bits_uop_vpu_vmask),
    .io_out_bits_uop_vpu_vl
      (_splitPipeline_io_out_bits_uop_vpu_vl),
    .io_out_bits_uop_vpu_nf
      (_splitPipeline_io_out_bits_uop_vpu_nf),
    .io_out_bits_uop_vpu_veew
      (_splitPipeline_io_out_bits_uop_vpu_veew),
    .io_out_bits_uop_vpu_isReverse
      (_splitPipeline_io_out_bits_uop_vpu_isReverse),
    .io_out_bits_uop_vpu_isExt
      (_splitPipeline_io_out_bits_uop_vpu_isExt),
    .io_out_bits_uop_vpu_isNarrow
      (_splitPipeline_io_out_bits_uop_vpu_isNarrow),
    .io_out_bits_uop_vpu_isDstMask
      (_splitPipeline_io_out_bits_uop_vpu_isDstMask),
    .io_out_bits_uop_vpu_isOpMask
      (_splitPipeline_io_out_bits_uop_vpu_isOpMask),
    .io_out_bits_uop_vpu_isMove
      (_splitPipeline_io_out_bits_uop_vpu_isMove),
    .io_out_bits_uop_vpu_isDependOldVd
      (_splitPipeline_io_out_bits_uop_vpu_isDependOldVd),
    .io_out_bits_uop_vpu_isWritePartVd
      (_splitPipeline_io_out_bits_uop_vpu_isWritePartVd),
    .io_out_bits_uop_vpu_isVleff
      (_splitPipeline_io_out_bits_uop_vpu_isVleff),
    .io_out_bits_uop_vpu_maskVecGen
      (_splitPipeline_io_out_bits_uop_vpu_maskVecGen),
    .io_out_bits_uop_vpu_sew8
      (_splitPipeline_io_out_bits_uop_vpu_sew8),
    .io_out_bits_uop_vpu_sew16
      (_splitPipeline_io_out_bits_uop_vpu_sew16),
    .io_out_bits_uop_vpu_sew32
      (_splitPipeline_io_out_bits_uop_vpu_sew32),
    .io_out_bits_uop_vpu_sew64
      (_splitPipeline_io_out_bits_uop_vpu_sew64),
    .io_out_bits_uop_uopIdx
      (_splitPipeline_io_out_bits_uop_uopIdx),
    .io_out_bits_uop_lastUop
      (_splitPipeline_io_out_bits_uop_lastUop),
    .io_out_bits_uop_numUops
      (_splitPipeline_io_out_bits_uop_numUops),
    .io_out_bits_uop_pdest
      (_splitPipeline_io_out_bits_uop_pdest),
    .io_out_bits_uop_pdestVl
      (_splitPipeline_io_out_bits_uop_pdestVl),
    .io_out_bits_uop_robIdx_flag
      (_splitPipeline_io_out_bits_uop_robIdx_flag),
    .io_out_bits_uop_robIdx_value
      (_splitPipeline_io_out_bits_uop_robIdx_value),
    .io_out_bits_uop_perfDebugInfo_eliminatedMove
      (_splitPipeline_io_out_bits_uop_perfDebugInfo_eliminatedMove),
    .io_out_bits_uop_perfDebugInfo_renameTime
      (_splitPipeline_io_out_bits_uop_perfDebugInfo_renameTime),
    .io_out_bits_uop_perfDebugInfo_dispatchTime
      (_splitPipeline_io_out_bits_uop_perfDebugInfo_dispatchTime),
    .io_out_bits_uop_perfDebugInfo_enqRsTime
      (_splitPipeline_io_out_bits_uop_perfDebugInfo_enqRsTime),
    .io_out_bits_uop_perfDebugInfo_selectTime
      (_splitPipeline_io_out_bits_uop_perfDebugInfo_selectTime),
    .io_out_bits_uop_perfDebugInfo_issueTime
      (_splitPipeline_io_out_bits_uop_perfDebugInfo_issueTime),
    .io_out_bits_uop_perfDebugInfo_writebackTime
      (_splitPipeline_io_out_bits_uop_perfDebugInfo_writebackTime),
    .io_out_bits_uop_perfDebugInfo_runahead_checkpoint_id
      (_splitPipeline_io_out_bits_uop_perfDebugInfo_runahead_checkpoint_id),
    .io_out_bits_uop_perfDebugInfo_tlbFirstReqTime
      (_splitPipeline_io_out_bits_uop_perfDebugInfo_tlbFirstReqTime),
    .io_out_bits_uop_perfDebugInfo_tlbRespTime
      (_splitPipeline_io_out_bits_uop_perfDebugInfo_tlbRespTime),
    .io_out_bits_uop_debug_seqNum_seqNum
      (_splitPipeline_io_out_bits_uop_debug_seqNum_seqNum),
    .io_out_bits_uop_debug_seqNum_uopIdx
      (_splitPipeline_io_out_bits_uop_debug_seqNum_uopIdx),
    .io_out_bits_uop_lqIdx_flag
      (_splitPipeline_io_out_bits_uop_lqIdx_flag),
    .io_out_bits_uop_lqIdx_value
      (_splitPipeline_io_out_bits_uop_lqIdx_value),
    .io_out_bits_uop_sqIdx_first_flag
      (_splitPipeline_io_out_bits_uop_sqIdx_first_flag),
    .io_out_bits_uop_sqIdx_second_flag
      (_splitPipeline_io_out_bits_uop_sqIdx_second_flag),
    .io_out_bits_uop_sqIdx_value
      (_splitPipeline_io_out_bits_uop_sqIdx_value),
    .io_out_bits_uop_numLsElem
      (_splitPipeline_io_out_bits_uop_numLsElem),
    .io_out_bits_preIsSplit
      (_splitPipeline_io_out_bits_preIsSplit),
    .io_out_bits_mBIndex
      (_splitPipeline_io_out_bits_mBIndex),
    .io_out_bits_alignedType
      (_splitPipeline_io_out_bits_alignedType),
    .io_out_bits_indexVlMaxInVd
      (_splitPipeline_io_out_bits_indexVlMaxInVd),
    .io_out_bits_usLowBitsAddr
      (_splitPipeline_io_out_bits_usLowBitsAddr),
    .io_out_bits_usAligned128
      (_splitPipeline_io_out_bits_usAligned128),
    .io_out_bits_usMask
      (_splitPipeline_io_out_bits_usMask)
  );
  VLSplitBufferImp splitBuffer (
    .clock                                                (clock),
    .reset                                                (reset),
    .io_redirect_valid                                    (io_redirect_valid),
    .io_redirect_bits_level                               (io_redirect_bits_level),
    .io_redirect_bits_robIdx_flag                         (io_redirect_bits_robIdx_flag),
    .io_redirect_bits_robIdx_value                        (io_redirect_bits_robIdx_value),
    .io_in_ready                                          (_splitBuffer_io_in_ready),
    .io_in_valid
      (_VSSplitSkidBuffer_io_out_valid),
    .io_in_bits_flowMask
      (_VSSplitSkidBuffer_io_out_bits_flowMask),
    .io_in_bits_uopAddr
      (_VSSplitSkidBuffer_io_out_bits_uopAddr),
    .io_in_bits_stride
      (_VSSplitSkidBuffer_io_out_bits_stride),
    .io_in_bits_flowNum
      (_VSSplitSkidBuffer_io_out_bits_flowNum),
    .io_in_bits_eew
      (_VSSplitSkidBuffer_io_out_bits_eew),
    .io_in_bits_sew
      (_VSSplitSkidBuffer_io_out_bits_sew),
    .io_in_bits_emul
      (_VSSplitSkidBuffer_io_out_bits_emul),
    .io_in_bits_lmul
      (_VSSplitSkidBuffer_io_out_bits_lmul),
    .io_in_bits_instType
      (_VSSplitSkidBuffer_io_out_bits_instType),
    .io_in_bits_indexedSplitOffset
      (_VSSplitSkidBuffer_io_out_bits_indexedSplitOffset),
    .io_in_bits_uop_ftqPtr_flag
      (_VSSplitSkidBuffer_io_out_bits_uop_ftqPtr_flag),
    .io_in_bits_uop_ftqPtr_value
      (_VSSplitSkidBuffer_io_out_bits_uop_ftqPtr_value),
    .io_in_bits_uop_ftqOffset
      (_VSSplitSkidBuffer_io_out_bits_uop_ftqOffset),
    .io_in_bits_uop_fuOpType
      (_VSSplitSkidBuffer_io_out_bits_uop_fuOpType),
    .io_in_bits_uop_vpu_vstart
      (_VSSplitSkidBuffer_io_out_bits_uop_vpu_vstart),
    .io_in_bits_uop_vpu_vuopIdx
      (_VSSplitSkidBuffer_io_out_bits_uop_vpu_vuopIdx),
    .io_in_bits_uop_vpu_veew
      (_VSSplitSkidBuffer_io_out_bits_uop_vpu_veew),
    .io_in_bits_uop_uopIdx
      (_VSSplitSkidBuffer_io_out_bits_uop_uopIdx),
    .io_in_bits_uop_pdest
      (_VSSplitSkidBuffer_io_out_bits_uop_pdest),
    .io_in_bits_uop_robIdx_flag
      (_VSSplitSkidBuffer_io_out_bits_uop_robIdx_flag),
    .io_in_bits_uop_robIdx_value
      (_VSSplitSkidBuffer_io_out_bits_uop_robIdx_value),
    .io_in_bits_uop_perfDebugInfo_eliminatedMove
      (_VSSplitSkidBuffer_io_out_bits_uop_perfDebugInfo_eliminatedMove),
    .io_in_bits_uop_perfDebugInfo_renameTime
      (_VSSplitSkidBuffer_io_out_bits_uop_perfDebugInfo_renameTime),
    .io_in_bits_uop_perfDebugInfo_dispatchTime
      (_VSSplitSkidBuffer_io_out_bits_uop_perfDebugInfo_dispatchTime),
    .io_in_bits_uop_perfDebugInfo_enqRsTime
      (_VSSplitSkidBuffer_io_out_bits_uop_perfDebugInfo_enqRsTime),
    .io_in_bits_uop_perfDebugInfo_selectTime
      (_VSSplitSkidBuffer_io_out_bits_uop_perfDebugInfo_selectTime),
    .io_in_bits_uop_perfDebugInfo_issueTime
      (_VSSplitSkidBuffer_io_out_bits_uop_perfDebugInfo_issueTime),
    .io_in_bits_uop_perfDebugInfo_runahead_checkpoint_id
      (_VSSplitSkidBuffer_io_out_bits_uop_perfDebugInfo_runahead_checkpoint_id),
    .io_in_bits_uop_perfDebugInfo_tlbFirstReqTime
      (_VSSplitSkidBuffer_io_out_bits_uop_perfDebugInfo_tlbFirstReqTime),
    .io_in_bits_uop_perfDebugInfo_tlbRespTime
      (_VSSplitSkidBuffer_io_out_bits_uop_perfDebugInfo_tlbRespTime),
    .io_in_bits_uop_debug_seqNum_seqNum
      (_VSSplitSkidBuffer_io_out_bits_uop_debug_seqNum_seqNum),
    .io_in_bits_uop_debug_seqNum_uopIdx
      (_VSSplitSkidBuffer_io_out_bits_uop_debug_seqNum_uopIdx),
    .io_in_bits_uop_lqIdx_flag
      (_VSSplitSkidBuffer_io_out_bits_uop_lqIdx_flag),
    .io_in_bits_uop_lqIdx_value
      (_VSSplitSkidBuffer_io_out_bits_uop_lqIdx_value),
    .io_in_bits_uop_sqIdx_first_flag
      (_VSSplitSkidBuffer_io_out_bits_uop_sqIdx_first_flag),
    .io_in_bits_uop_sqIdx_second_flag
      (_VSSplitSkidBuffer_io_out_bits_uop_sqIdx_second_flag),
    .io_in_bits_uop_sqIdx_value
      (_VSSplitSkidBuffer_io_out_bits_uop_sqIdx_value),
    .io_in_bits_preIsSplit
      (_VSSplitSkidBuffer_io_out_bits_preIsSplit),
    .io_in_bits_mBIndex
      (_VSSplitSkidBuffer_io_out_bits_mBIndex),
    .io_in_bits_alignedType
      (_VSSplitSkidBuffer_io_out_bits_alignedType),
    .io_in_bits_indexVlMaxInVd
      (_VSSplitSkidBuffer_io_out_bits_indexVlMaxInVd),
    .io_in_bits_usLowBitsAddr
      (_VSSplitSkidBuffer_io_out_bits_usLowBitsAddr),
    .io_in_bits_usAligned128
      (_VSSplitSkidBuffer_io_out_bits_usAligned128),
    .io_in_bits_usMask
      (_VSSplitSkidBuffer_io_out_bits_usMask),
    .io_out_ready                                         (io_out_ready),
    .io_out_valid                                         (_splitBuffer_io_out_valid),
    .io_out_bits_vaddr                                    (io_out_bits_vaddr),
    .io_out_bits_mask                                     (io_out_bits_mask),
    .io_out_bits_reg_offset                               (io_out_bits_reg_offset),
    .io_out_bits_alignedType                              (io_out_bits_alignedType),
    .io_out_bits_uop_ftqPtr_flag                          (io_out_bits_uop_ftqPtr_flag),
    .io_out_bits_uop_ftqPtr_value                         (io_out_bits_uop_ftqPtr_value),
    .io_out_bits_uop_ftqOffset                            (io_out_bits_uop_ftqOffset),
    .io_out_bits_uop_fuOpType                             (io_out_bits_uop_fuOpType),
    .io_out_bits_uop_vpu_vstart                           (io_out_bits_uop_vpu_vstart),
    .io_out_bits_uop_vpu_veew                             (io_out_bits_uop_vpu_veew),
    .io_out_bits_uop_uopIdx                               (io_out_bits_uop_uopIdx),
    .io_out_bits_uop_pdest                                (io_out_bits_uop_pdest),
    .io_out_bits_uop_robIdx_flag                          (io_out_bits_uop_robIdx_flag),
    .io_out_bits_uop_robIdx_value                         (io_out_bits_uop_robIdx_value),
    .io_out_bits_uop_perfDebugInfo_eliminatedMove
      (io_out_bits_uop_perfDebugInfo_eliminatedMove),
    .io_out_bits_uop_perfDebugInfo_renameTime
      (io_out_bits_uop_perfDebugInfo_renameTime),
    .io_out_bits_uop_perfDebugInfo_dispatchTime
      (io_out_bits_uop_perfDebugInfo_dispatchTime),
    .io_out_bits_uop_perfDebugInfo_enqRsTime
      (io_out_bits_uop_perfDebugInfo_enqRsTime),
    .io_out_bits_uop_perfDebugInfo_selectTime
      (io_out_bits_uop_perfDebugInfo_selectTime),
    .io_out_bits_uop_perfDebugInfo_issueTime
      (io_out_bits_uop_perfDebugInfo_issueTime),
    .io_out_bits_uop_perfDebugInfo_runahead_checkpoint_id
      (io_out_bits_uop_perfDebugInfo_runahead_checkpoint_id),
    .io_out_bits_uop_perfDebugInfo_tlbFirstReqTime
      (io_out_bits_uop_perfDebugInfo_tlbFirstReqTime),
    .io_out_bits_uop_perfDebugInfo_tlbRespTime
      (io_out_bits_uop_perfDebugInfo_tlbRespTime),
    .io_out_bits_uop_debug_seqNum_seqNum
      (io_out_bits_uop_debug_seqNum_seqNum),
    .io_out_bits_uop_debug_seqNum_uopIdx
      (io_out_bits_uop_debug_seqNum_uopIdx),
    .io_out_bits_uop_lqIdx_flag                           (io_out_bits_uop_lqIdx_flag),
    .io_out_bits_uop_lqIdx_value                          (io_out_bits_uop_lqIdx_value),
    .io_out_bits_uop_sqIdx_first_flag
      (io_out_bits_uop_sqIdx_first_flag),
    .io_out_bits_uop_sqIdx_second_flag
      (io_out_bits_uop_sqIdx_second_flag),
    .io_out_bits_uop_sqIdx_value                          (io_out_bits_uop_sqIdx_value),
    .io_out_bits_mBIndex                                  (io_out_bits_mBIndex),
    .io_out_bits_elemIdx                                  (io_out_bits_elemIdx),
    .io_out_bits_elemIdxInsideVd                          (io_out_bits_elemIdxInsideVd)
  );
  wire         splitBuffer_io_out_valid_probe;
  assign splitBuffer_io_out_valid_probe = _splitBuffer_io_out_valid;
  skidBufferConnect VSSplitSkidBuffer (
    .clock                                                (clock),
    .reset                                                (reset),
    .io_in_ready
      (_VSSplitSkidBuffer_io_in_ready),
    .io_in_valid                                          (_splitPipeline_io_out_valid),
    .io_in_bits_flowMask
      (_splitPipeline_io_out_bits_flowMask),
    .io_in_bits_data
      (_splitPipeline_io_out_bits_data),
    .io_in_bits_uopAddr
      (_splitPipeline_io_out_bits_uopAddr),
    .io_in_bits_stride
      (_splitPipeline_io_out_bits_stride),
    .io_in_bits_flowNum
      (_splitPipeline_io_out_bits_flowNum),
    .io_in_bits_eew
      (_splitPipeline_io_out_bits_eew),
    .io_in_bits_sew
      (_splitPipeline_io_out_bits_sew),
    .io_in_bits_emul
      (_splitPipeline_io_out_bits_emul),
    .io_in_bits_lmul
      (_splitPipeline_io_out_bits_lmul),
    .io_in_bits_instType
      (_splitPipeline_io_out_bits_instType),
    .io_in_bits_indexedSplitOffset
      (_splitPipeline_io_out_bits_indexedSplitOffset),
    .io_in_bits_uop_pc
      (_splitPipeline_io_out_bits_uop_pc),
    .io_in_bits_uop_ftqPtr_flag
      (_splitPipeline_io_out_bits_uop_ftqPtr_flag),
    .io_in_bits_uop_ftqPtr_value
      (_splitPipeline_io_out_bits_uop_ftqPtr_value),
    .io_in_bits_uop_ftqOffset
      (_splitPipeline_io_out_bits_uop_ftqOffset),
    .io_in_bits_uop_fuType
      (_splitPipeline_io_out_bits_uop_fuType),
    .io_in_bits_uop_fuOpType
      (_splitPipeline_io_out_bits_uop_fuOpType),
    .io_in_bits_uop_vecWen
      (_splitPipeline_io_out_bits_uop_vecWen),
    .io_in_bits_uop_v0Wen
      (_splitPipeline_io_out_bits_uop_v0Wen),
    .io_in_bits_uop_vlWen
      (_splitPipeline_io_out_bits_uop_vlWen),
    .io_in_bits_uop_vpu_vill
      (_splitPipeline_io_out_bits_uop_vpu_vill),
    .io_in_bits_uop_vpu_vma
      (_splitPipeline_io_out_bits_uop_vpu_vma),
    .io_in_bits_uop_vpu_vta
      (_splitPipeline_io_out_bits_uop_vpu_vta),
    .io_in_bits_uop_vpu_vsew
      (_splitPipeline_io_out_bits_uop_vpu_vsew),
    .io_in_bits_uop_vpu_vlmul
      (_splitPipeline_io_out_bits_uop_vpu_vlmul),
    .io_in_bits_uop_vpu_specVill
      (_splitPipeline_io_out_bits_uop_vpu_specVill),
    .io_in_bits_uop_vpu_specVma
      (_splitPipeline_io_out_bits_uop_vpu_specVma),
    .io_in_bits_uop_vpu_specVta
      (_splitPipeline_io_out_bits_uop_vpu_specVta),
    .io_in_bits_uop_vpu_specVsew
      (_splitPipeline_io_out_bits_uop_vpu_specVsew),
    .io_in_bits_uop_vpu_specVlmul
      (_splitPipeline_io_out_bits_uop_vpu_specVlmul),
    .io_in_bits_uop_vpu_vm
      (_splitPipeline_io_out_bits_uop_vpu_vm),
    .io_in_bits_uop_vpu_vstart
      (_splitPipeline_io_out_bits_uop_vpu_vstart),
    .io_in_bits_uop_vpu_frm
      (_splitPipeline_io_out_bits_uop_vpu_frm),
    .io_in_bits_uop_vpu_fpu_isFpToVecInst
      (_splitPipeline_io_out_bits_uop_vpu_fpu_isFpToVecInst),
    .io_in_bits_uop_vpu_fpu_isFP32Instr
      (_splitPipeline_io_out_bits_uop_vpu_fpu_isFP32Instr),
    .io_in_bits_uop_vpu_fpu_isFP64Instr
      (_splitPipeline_io_out_bits_uop_vpu_fpu_isFP64Instr),
    .io_in_bits_uop_vpu_fpu_isReduction
      (_splitPipeline_io_out_bits_uop_vpu_fpu_isReduction),
    .io_in_bits_uop_vpu_fpu_isFoldTo1_2
      (_splitPipeline_io_out_bits_uop_vpu_fpu_isFoldTo1_2),
    .io_in_bits_uop_vpu_fpu_isFoldTo1_4
      (_splitPipeline_io_out_bits_uop_vpu_fpu_isFoldTo1_4),
    .io_in_bits_uop_vpu_fpu_isFoldTo1_8
      (_splitPipeline_io_out_bits_uop_vpu_fpu_isFoldTo1_8),
    .io_in_bits_uop_vpu_vxrm
      (_splitPipeline_io_out_bits_uop_vpu_vxrm),
    .io_in_bits_uop_vpu_vuopIdx
      (_splitPipeline_io_out_bits_uop_vpu_vuopIdx),
    .io_in_bits_uop_vpu_lastUop
      (_splitPipeline_io_out_bits_uop_vpu_lastUop),
    .io_in_bits_uop_vpu_vmask
      (_splitPipeline_io_out_bits_uop_vpu_vmask),
    .io_in_bits_uop_vpu_vl
      (_splitPipeline_io_out_bits_uop_vpu_vl),
    .io_in_bits_uop_vpu_nf
      (_splitPipeline_io_out_bits_uop_vpu_nf),
    .io_in_bits_uop_vpu_veew
      (_splitPipeline_io_out_bits_uop_vpu_veew),
    .io_in_bits_uop_vpu_isReverse
      (_splitPipeline_io_out_bits_uop_vpu_isReverse),
    .io_in_bits_uop_vpu_isExt
      (_splitPipeline_io_out_bits_uop_vpu_isExt),
    .io_in_bits_uop_vpu_isNarrow
      (_splitPipeline_io_out_bits_uop_vpu_isNarrow),
    .io_in_bits_uop_vpu_isDstMask
      (_splitPipeline_io_out_bits_uop_vpu_isDstMask),
    .io_in_bits_uop_vpu_isOpMask
      (_splitPipeline_io_out_bits_uop_vpu_isOpMask),
    .io_in_bits_uop_vpu_isMove
      (_splitPipeline_io_out_bits_uop_vpu_isMove),
    .io_in_bits_uop_vpu_isDependOldVd
      (_splitPipeline_io_out_bits_uop_vpu_isDependOldVd),
    .io_in_bits_uop_vpu_isWritePartVd
      (_splitPipeline_io_out_bits_uop_vpu_isWritePartVd),
    .io_in_bits_uop_vpu_isVleff
      (_splitPipeline_io_out_bits_uop_vpu_isVleff),
    .io_in_bits_uop_vpu_maskVecGen
      (_splitPipeline_io_out_bits_uop_vpu_maskVecGen),
    .io_in_bits_uop_vpu_sew8
      (_splitPipeline_io_out_bits_uop_vpu_sew8),
    .io_in_bits_uop_vpu_sew16
      (_splitPipeline_io_out_bits_uop_vpu_sew16),
    .io_in_bits_uop_vpu_sew32
      (_splitPipeline_io_out_bits_uop_vpu_sew32),
    .io_in_bits_uop_vpu_sew64
      (_splitPipeline_io_out_bits_uop_vpu_sew64),
    .io_in_bits_uop_uopIdx
      (_splitPipeline_io_out_bits_uop_uopIdx),
    .io_in_bits_uop_lastUop
      (_splitPipeline_io_out_bits_uop_lastUop),
    .io_in_bits_uop_numUops
      (_splitPipeline_io_out_bits_uop_numUops),
    .io_in_bits_uop_pdest
      (_splitPipeline_io_out_bits_uop_pdest),
    .io_in_bits_uop_pdestVl
      (_splitPipeline_io_out_bits_uop_pdestVl),
    .io_in_bits_uop_robIdx_flag
      (_splitPipeline_io_out_bits_uop_robIdx_flag),
    .io_in_bits_uop_robIdx_value
      (_splitPipeline_io_out_bits_uop_robIdx_value),
    .io_in_bits_uop_perfDebugInfo_eliminatedMove
      (_splitPipeline_io_out_bits_uop_perfDebugInfo_eliminatedMove),
    .io_in_bits_uop_perfDebugInfo_renameTime
      (_splitPipeline_io_out_bits_uop_perfDebugInfo_renameTime),
    .io_in_bits_uop_perfDebugInfo_dispatchTime
      (_splitPipeline_io_out_bits_uop_perfDebugInfo_dispatchTime),
    .io_in_bits_uop_perfDebugInfo_enqRsTime
      (_splitPipeline_io_out_bits_uop_perfDebugInfo_enqRsTime),
    .io_in_bits_uop_perfDebugInfo_selectTime
      (_splitPipeline_io_out_bits_uop_perfDebugInfo_selectTime),
    .io_in_bits_uop_perfDebugInfo_issueTime
      (_splitPipeline_io_out_bits_uop_perfDebugInfo_issueTime),
    .io_in_bits_uop_perfDebugInfo_writebackTime
      (_splitPipeline_io_out_bits_uop_perfDebugInfo_writebackTime),
    .io_in_bits_uop_perfDebugInfo_runahead_checkpoint_id
      (_splitPipeline_io_out_bits_uop_perfDebugInfo_runahead_checkpoint_id),
    .io_in_bits_uop_perfDebugInfo_tlbFirstReqTime
      (_splitPipeline_io_out_bits_uop_perfDebugInfo_tlbFirstReqTime),
    .io_in_bits_uop_perfDebugInfo_tlbRespTime
      (_splitPipeline_io_out_bits_uop_perfDebugInfo_tlbRespTime),
    .io_in_bits_uop_debug_seqNum_seqNum
      (_splitPipeline_io_out_bits_uop_debug_seqNum_seqNum),
    .io_in_bits_uop_debug_seqNum_uopIdx
      (_splitPipeline_io_out_bits_uop_debug_seqNum_uopIdx),
    .io_in_bits_uop_lqIdx_flag
      (_splitPipeline_io_out_bits_uop_lqIdx_flag),
    .io_in_bits_uop_lqIdx_value
      (_splitPipeline_io_out_bits_uop_lqIdx_value),
    .io_in_bits_uop_sqIdx_first_flag
      (_splitPipeline_io_out_bits_uop_sqIdx_first_flag),
    .io_in_bits_uop_sqIdx_second_flag
      (_splitPipeline_io_out_bits_uop_sqIdx_second_flag),
    .io_in_bits_uop_sqIdx_value
      (_splitPipeline_io_out_bits_uop_sqIdx_value),
    .io_in_bits_uop_numLsElem
      (_splitPipeline_io_out_bits_uop_numLsElem),
    .io_in_bits_preIsSplit
      (_splitPipeline_io_out_bits_preIsSplit),
    .io_in_bits_mBIndex
      (_splitPipeline_io_out_bits_mBIndex),
    .io_in_bits_alignedType
      (_splitPipeline_io_out_bits_alignedType),
    .io_in_bits_indexVlMaxInVd
      (_splitPipeline_io_out_bits_indexVlMaxInVd),
    .io_in_bits_usLowBitsAddr
      (_splitPipeline_io_out_bits_usLowBitsAddr),
    .io_in_bits_usAligned128
      (_splitPipeline_io_out_bits_usAligned128),
    .io_in_bits_usMask
      (_splitPipeline_io_out_bits_usMask),
    .io_flush
      (_VSSplitSkidBuffer_io_in_ready & _splitPipeline_io_out_valid
         ? io_redirect_valid
           & (io_redirect_bits_level
              & {_splitPipeline_io_out_bits_uop_robIdx_flag,
                 _splitPipeline_io_out_bits_uop_robIdx_value} == _flushItself_T_6
              | _splitPipeline_io_out_bits_uop_robIdx_flag ^ io_redirect_bits_robIdx_flag
              ^ _splitPipeline_io_out_bits_uop_robIdx_value > io_redirect_bits_robIdx_value)
         : io_redirect_valid
           & (io_redirect_bits_level
              & {_VSSplitSkidBuffer_io_out_bits_uop_robIdx_flag,
                 _VSSplitSkidBuffer_io_out_bits_uop_robIdx_value} == _flushItself_T_6
              | _VSSplitSkidBuffer_io_out_bits_uop_robIdx_flag
              ^ io_redirect_bits_robIdx_flag
              ^ _VSSplitSkidBuffer_io_out_bits_uop_robIdx_value > io_redirect_bits_robIdx_value)),
    .io_out_ready                                         (_splitBuffer_io_in_ready),
    .io_out_valid
      (_VSSplitSkidBuffer_io_out_valid),
    .io_out_bits_flowMask
      (_VSSplitSkidBuffer_io_out_bits_flowMask),
    .io_out_bits_data                                     (/* unused */),
    .io_out_bits_uopAddr
      (_VSSplitSkidBuffer_io_out_bits_uopAddr),
    .io_out_bits_stride
      (_VSSplitSkidBuffer_io_out_bits_stride),
    .io_out_bits_flowNum
      (_VSSplitSkidBuffer_io_out_bits_flowNum),
    .io_out_bits_eew
      (_VSSplitSkidBuffer_io_out_bits_eew),
    .io_out_bits_sew
      (_VSSplitSkidBuffer_io_out_bits_sew),
    .io_out_bits_emul
      (_VSSplitSkidBuffer_io_out_bits_emul),
    .io_out_bits_lmul
      (_VSSplitSkidBuffer_io_out_bits_lmul),
    .io_out_bits_instType
      (_VSSplitSkidBuffer_io_out_bits_instType),
    .io_out_bits_indexedSplitOffset
      (_VSSplitSkidBuffer_io_out_bits_indexedSplitOffset),
    .io_out_bits_uop_pc                                   (/* unused */),
    .io_out_bits_uop_ftqPtr_flag
      (_VSSplitSkidBuffer_io_out_bits_uop_ftqPtr_flag),
    .io_out_bits_uop_ftqPtr_value
      (_VSSplitSkidBuffer_io_out_bits_uop_ftqPtr_value),
    .io_out_bits_uop_ftqOffset
      (_VSSplitSkidBuffer_io_out_bits_uop_ftqOffset),
    .io_out_bits_uop_fuType                               (/* unused */),
    .io_out_bits_uop_fuOpType
      (_VSSplitSkidBuffer_io_out_bits_uop_fuOpType),
    .io_out_bits_uop_vecWen                               (/* unused */),
    .io_out_bits_uop_v0Wen                                (/* unused */),
    .io_out_bits_uop_vlWen                                (/* unused */),
    .io_out_bits_uop_vpu_vill                             (/* unused */),
    .io_out_bits_uop_vpu_vma                              (/* unused */),
    .io_out_bits_uop_vpu_vta                              (/* unused */),
    .io_out_bits_uop_vpu_vsew                             (/* unused */),
    .io_out_bits_uop_vpu_vlmul                            (/* unused */),
    .io_out_bits_uop_vpu_specVill                         (/* unused */),
    .io_out_bits_uop_vpu_specVma                          (/* unused */),
    .io_out_bits_uop_vpu_specVta                          (/* unused */),
    .io_out_bits_uop_vpu_specVsew                         (/* unused */),
    .io_out_bits_uop_vpu_specVlmul                        (/* unused */),
    .io_out_bits_uop_vpu_vm                               (/* unused */),
    .io_out_bits_uop_vpu_vstart
      (_VSSplitSkidBuffer_io_out_bits_uop_vpu_vstart),
    .io_out_bits_uop_vpu_frm                              (/* unused */),
    .io_out_bits_uop_vpu_fpu_isFpToVecInst                (/* unused */),
    .io_out_bits_uop_vpu_fpu_isFP32Instr                  (/* unused */),
    .io_out_bits_uop_vpu_fpu_isFP64Instr                  (/* unused */),
    .io_out_bits_uop_vpu_fpu_isReduction                  (/* unused */),
    .io_out_bits_uop_vpu_fpu_isFoldTo1_2                  (/* unused */),
    .io_out_bits_uop_vpu_fpu_isFoldTo1_4                  (/* unused */),
    .io_out_bits_uop_vpu_fpu_isFoldTo1_8                  (/* unused */),
    .io_out_bits_uop_vpu_vxrm                             (/* unused */),
    .io_out_bits_uop_vpu_vuopIdx
      (_VSSplitSkidBuffer_io_out_bits_uop_vpu_vuopIdx),
    .io_out_bits_uop_vpu_lastUop                          (/* unused */),
    .io_out_bits_uop_vpu_vmask                            (/* unused */),
    .io_out_bits_uop_vpu_vl                               (/* unused */),
    .io_out_bits_uop_vpu_nf                               (/* unused */),
    .io_out_bits_uop_vpu_veew
      (_VSSplitSkidBuffer_io_out_bits_uop_vpu_veew),
    .io_out_bits_uop_vpu_isReverse                        (/* unused */),
    .io_out_bits_uop_vpu_isExt                            (/* unused */),
    .io_out_bits_uop_vpu_isNarrow                         (/* unused */),
    .io_out_bits_uop_vpu_isDstMask                        (/* unused */),
    .io_out_bits_uop_vpu_isOpMask                         (/* unused */),
    .io_out_bits_uop_vpu_isMove                           (/* unused */),
    .io_out_bits_uop_vpu_isDependOldVd                    (/* unused */),
    .io_out_bits_uop_vpu_isWritePartVd                    (/* unused */),
    .io_out_bits_uop_vpu_isVleff                          (/* unused */),
    .io_out_bits_uop_vpu_maskVecGen                       (/* unused */),
    .io_out_bits_uop_vpu_sew8                             (/* unused */),
    .io_out_bits_uop_vpu_sew16                            (/* unused */),
    .io_out_bits_uop_vpu_sew32                            (/* unused */),
    .io_out_bits_uop_vpu_sew64                            (/* unused */),
    .io_out_bits_uop_uopIdx
      (_VSSplitSkidBuffer_io_out_bits_uop_uopIdx),
    .io_out_bits_uop_lastUop                              (/* unused */),
    .io_out_bits_uop_numUops                              (/* unused */),
    .io_out_bits_uop_pdest
      (_VSSplitSkidBuffer_io_out_bits_uop_pdest),
    .io_out_bits_uop_pdestVl                              (/* unused */),
    .io_out_bits_uop_robIdx_flag
      (_VSSplitSkidBuffer_io_out_bits_uop_robIdx_flag),
    .io_out_bits_uop_robIdx_value
      (_VSSplitSkidBuffer_io_out_bits_uop_robIdx_value),
    .io_out_bits_uop_perfDebugInfo_eliminatedMove
      (_VSSplitSkidBuffer_io_out_bits_uop_perfDebugInfo_eliminatedMove),
    .io_out_bits_uop_perfDebugInfo_renameTime
      (_VSSplitSkidBuffer_io_out_bits_uop_perfDebugInfo_renameTime),
    .io_out_bits_uop_perfDebugInfo_dispatchTime
      (_VSSplitSkidBuffer_io_out_bits_uop_perfDebugInfo_dispatchTime),
    .io_out_bits_uop_perfDebugInfo_enqRsTime
      (_VSSplitSkidBuffer_io_out_bits_uop_perfDebugInfo_enqRsTime),
    .io_out_bits_uop_perfDebugInfo_selectTime
      (_VSSplitSkidBuffer_io_out_bits_uop_perfDebugInfo_selectTime),
    .io_out_bits_uop_perfDebugInfo_issueTime
      (_VSSplitSkidBuffer_io_out_bits_uop_perfDebugInfo_issueTime),
    .io_out_bits_uop_perfDebugInfo_writebackTime          (/* unused */),
    .io_out_bits_uop_perfDebugInfo_runahead_checkpoint_id
      (_VSSplitSkidBuffer_io_out_bits_uop_perfDebugInfo_runahead_checkpoint_id),
    .io_out_bits_uop_perfDebugInfo_tlbFirstReqTime
      (_VSSplitSkidBuffer_io_out_bits_uop_perfDebugInfo_tlbFirstReqTime),
    .io_out_bits_uop_perfDebugInfo_tlbRespTime
      (_VSSplitSkidBuffer_io_out_bits_uop_perfDebugInfo_tlbRespTime),
    .io_out_bits_uop_debug_seqNum_seqNum
      (_VSSplitSkidBuffer_io_out_bits_uop_debug_seqNum_seqNum),
    .io_out_bits_uop_debug_seqNum_uopIdx
      (_VSSplitSkidBuffer_io_out_bits_uop_debug_seqNum_uopIdx),
    .io_out_bits_uop_lqIdx_flag
      (_VSSplitSkidBuffer_io_out_bits_uop_lqIdx_flag),
    .io_out_bits_uop_lqIdx_value
      (_VSSplitSkidBuffer_io_out_bits_uop_lqIdx_value),
    .io_out_bits_uop_sqIdx_first_flag
      (_VSSplitSkidBuffer_io_out_bits_uop_sqIdx_first_flag),
    .io_out_bits_uop_sqIdx_second_flag
      (_VSSplitSkidBuffer_io_out_bits_uop_sqIdx_second_flag),
    .io_out_bits_uop_sqIdx_value
      (_VSSplitSkidBuffer_io_out_bits_uop_sqIdx_value),
    .io_out_bits_uop_numLsElem                            (/* unused */),
    .io_out_bits_preIsSplit
      (_VSSplitSkidBuffer_io_out_bits_preIsSplit),
    .io_out_bits_mBIndex
      (_VSSplitSkidBuffer_io_out_bits_mBIndex),
    .io_out_bits_alignedType
      (_VSSplitSkidBuffer_io_out_bits_alignedType),
    .io_out_bits_indexVlMaxInVd
      (_VSSplitSkidBuffer_io_out_bits_indexVlMaxInVd),
    .io_out_bits_usLowBitsAddr
      (_VSSplitSkidBuffer_io_out_bits_usLowBitsAddr),
    .io_out_bits_usAligned128
      (_VSSplitSkidBuffer_io_out_bits_usAligned128),
    .io_out_bits_usMask
      (_VSSplitSkidBuffer_io_out_bits_usMask)
  );
  assign io_in_ready =
    _splitPipeline_io_in_ready
    & ~(io_threshold_valid
        & {io_threshold_bits_flag,
           io_threshold_bits_value} != {io_in_bits_lqIdx_flag, io_in_bits_lqIdx_value});
  assign io_out_valid = _splitBuffer_io_out_valid;
  assign io_out_bits_uop_exceptionVec_19 = 1'h0;
  assign io_out_bits_uop_isRVC = 1'h0;
  assign io_out_bits_uop_rfWen = 1'h0;
  assign io_out_bits_uop_fpWen = 1'h0;
  assign io_out_bits_uop_storeSetHit = 1'h0;
  assign io_out_bits_uop_waitForRobIdx_flag = 1'h0;
  assign io_out_bits_uop_waitForRobIdx_value = 6'h0;
  assign io_out_bits_uop_loadWaitBit = 1'h0;
  assign io_out_bits_uop_loadWaitStrict = 1'h0;
  assign io_out_bits_uop_ssid = 6'h0;
endmodule

