// Generated by CIRCT firtool-1.75.0
module rob_compact_uop_mem_0(	// @[generators/boom/src/main/scala/v4/exu/rob.scala:337:40]
  input  [4:0]  R0_addr,
  input         R0_clk,
  output [26:0] R0_data,
  input  [4:0]  W0_addr,
  input         W0_en,
  input         W0_clk,
  input  [26:0] W0_data
);

  rob_compact_uop_mem_0_ext rob_compact_uop_mem_0_ext (	// @[generators/boom/src/main/scala/v4/exu/rob.scala:337:40]
    .R0_addr (R0_addr),
    .R0_en   (1'h1),	// @[generators/boom/src/main/scala/v4/exu/rob.scala:337:40]
    .R0_clk  (R0_clk),
    .R0_data (R0_data),
    .W0_addr (W0_addr),
    .W0_en   (W0_en),
    .W0_clk  (W0_clk),
    .W0_data (W0_data)
  );	// @[generators/boom/src/main/scala/v4/exu/rob.scala:337:40]
endmodule

