// Generated by CIRCT firtool-1.135.0
module PlruStateGen(
  input  [2:0] io_state,
  input        io_touches_0_valid,
  input        io_touches_1_valid,
  input        io_touches_2_valid,
  input        io_touches_3_valid,
  output [2:0] io_nextState
);

  wire [2:0] _io_nextState_T_9 =
    io_touches_0_valid ? {1'h1, io_state[1], 1'h1} : io_state;
  wire [2:0] _io_nextState_T_19 =
    io_touches_1_valid ? {1'h1, _io_nextState_T_9[1], 1'h0} : _io_nextState_T_9;
  wire [2:0] _io_nextState_T_29 =
    io_touches_2_valid ? {2'h1, _io_nextState_T_19[0]} : _io_nextState_T_19;
  assign io_nextState =
    io_touches_3_valid ? {2'h0, _io_nextState_T_29[0]} : _io_nextState_T_29;
endmodule

