// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module RenameTable_3(
  input        clock,
  input        reset,
  input        io_redirect,
  output [7:0] io_readPorts_0_data,
  output [7:0] io_readPorts_1_data,
  output [7:0] io_readPorts_2_data,
  output [7:0] io_readPorts_3_data,
  output [7:0] io_readPorts_4_data,
  output [7:0] io_readPorts_5_data,
  output [7:0] io_readPorts_6_data,
  output [7:0] io_readPorts_7_data,
  input        io_specWritePorts_0_wen,
  input  [7:0] io_specWritePorts_0_data,
  input        io_specWritePorts_1_wen,
  input  [7:0] io_specWritePorts_1_data,
  input        io_specWritePorts_2_wen,
  input  [7:0] io_specWritePorts_2_data,
  input        io_specWritePorts_3_wen,
  input  [7:0] io_specWritePorts_3_data,
  input        io_specWritePorts_4_wen,
  input  [7:0] io_specWritePorts_4_data,
  input        io_specWritePorts_5_wen,
  input  [7:0] io_specWritePorts_5_data,
  input        io_specWritePorts_6_wen,
  input  [7:0] io_specWritePorts_6_data,
  input        io_specWritePorts_7_wen,
  input  [7:0] io_specWritePorts_7_data,
  input        io_archWritePorts_0_wen,
  input  [7:0] io_archWritePorts_0_data,
  input        io_archWritePorts_1_wen,
  input  [7:0] io_archWritePorts_1_data,
  input        io_archWritePorts_2_wen,
  input  [7:0] io_archWritePorts_2_data,
  input        io_archWritePorts_3_wen,
  input  [7:0] io_archWritePorts_3_data,
  input        io_archWritePorts_4_wen,
  input  [7:0] io_archWritePorts_4_data,
  input        io_archWritePorts_5_wen,
  input  [7:0] io_archWritePorts_5_data,
  input        io_archWritePorts_6_wen,
  input  [7:0] io_archWritePorts_6_data,
  input        io_archWritePorts_7_wen,
  input  [7:0] io_archWritePorts_7_data,
  output [7:0] io_old_pdest_0,
  output [7:0] io_old_pdest_1,
  output [7:0] io_old_pdest_2,
  output [7:0] io_old_pdest_3,
  output [7:0] io_old_pdest_4,
  output [7:0] io_old_pdest_5,
  output [7:0] io_old_pdest_6,
  output [7:0] io_old_pdest_7,
  input        io_snpt_snptEnq,
  input        io_snpt_snptDeq,
  input        io_snpt_useSnpt,
  input  [1:0] io_snpt_snptSelect,
  input        io_snpt_flushVec_0,
  input        io_snpt_flushVec_1,
  input        io_snpt_flushVec_2,
  input        io_snpt_flushVec_3,
  input        io_diffWritePorts_0_wen,
  input  [7:0] io_diffWritePorts_0_data,
  input        io_diffWritePorts_1_wen,
  input  [7:0] io_diffWritePorts_1_data,
  input        io_diffWritePorts_2_wen,
  input  [7:0] io_diffWritePorts_2_data,
  input        io_diffWritePorts_3_wen,
  input  [7:0] io_diffWritePorts_3_data,
  input        io_diffWritePorts_4_wen,
  input  [7:0] io_diffWritePorts_4_data,
  input        io_diffWritePorts_5_wen,
  input  [7:0] io_diffWritePorts_5_data,
  input        io_diffWritePorts_6_wen,
  input  [7:0] io_diffWritePorts_6_data,
  input        io_diffWritePorts_7_wen,
  input  [7:0] io_diffWritePorts_7_data,
  input        io_diffWritePorts_8_wen,
  input  [7:0] io_diffWritePorts_8_data,
  input        io_diffWritePorts_9_wen,
  input  [7:0] io_diffWritePorts_9_data,
  input        io_diffWritePorts_10_wen,
  input  [7:0] io_diffWritePorts_10_data,
  input        io_diffWritePorts_11_wen,
  input  [7:0] io_diffWritePorts_11_data,
  input        io_diffWritePorts_12_wen,
  input  [7:0] io_diffWritePorts_12_data,
  input        io_diffWritePorts_13_wen,
  input  [7:0] io_diffWritePorts_13_data,
  input        io_diffWritePorts_14_wen,
  input  [7:0] io_diffWritePorts_14_data,
  input        io_diffWritePorts_15_wen,
  input  [7:0] io_diffWritePorts_15_data,
  input        io_diffWritePorts_16_wen,
  input  [7:0] io_diffWritePorts_16_data,
  input        io_diffWritePorts_17_wen,
  input  [7:0] io_diffWritePorts_17_data,
  input        io_diffWritePorts_18_wen,
  input  [7:0] io_diffWritePorts_18_data,
  input        io_diffWritePorts_19_wen,
  input  [7:0] io_diffWritePorts_19_data,
  input        io_diffWritePorts_20_wen,
  input  [7:0] io_diffWritePorts_20_data,
  input        io_diffWritePorts_21_wen,
  input  [7:0] io_diffWritePorts_21_data,
  input        io_diffWritePorts_22_wen,
  input  [7:0] io_diffWritePorts_22_data,
  input        io_diffWritePorts_23_wen,
  input  [7:0] io_diffWritePorts_23_data,
  input        io_diffWritePorts_24_wen,
  input  [7:0] io_diffWritePorts_24_data,
  input        io_diffWritePorts_25_wen,
  input  [7:0] io_diffWritePorts_25_data,
  input        io_diffWritePorts_26_wen,
  input  [7:0] io_diffWritePorts_26_data,
  input        io_diffWritePorts_27_wen,
  input  [7:0] io_diffWritePorts_27_data,
  input        io_diffWritePorts_28_wen,
  input  [7:0] io_diffWritePorts_28_data,
  input        io_diffWritePorts_29_wen,
  input  [7:0] io_diffWritePorts_29_data,
  input        io_diffWritePorts_30_wen,
  input  [7:0] io_diffWritePorts_30_data,
  input        io_diffWritePorts_31_wen,
  input  [7:0] io_diffWritePorts_31_data,
  input        io_diffWritePorts_32_wen,
  input  [7:0] io_diffWritePorts_32_data,
  input        io_diffWritePorts_33_wen,
  input  [7:0] io_diffWritePorts_33_data,
  input        io_diffWritePorts_34_wen,
  input  [7:0] io_diffWritePorts_34_data,
  input        io_diffWritePorts_35_wen,
  input  [7:0] io_diffWritePorts_35_data,
  input        io_diffWritePorts_36_wen,
  input  [7:0] io_diffWritePorts_36_data,
  input        io_diffWritePorts_37_wen,
  input  [7:0] io_diffWritePorts_37_data,
  input        io_diffWritePorts_38_wen,
  input  [7:0] io_diffWritePorts_38_data,
  input        io_diffWritePorts_39_wen,
  input  [7:0] io_diffWritePorts_39_data,
  input        io_diffWritePorts_40_wen,
  input  [7:0] io_diffWritePorts_40_data,
  input        io_diffWritePorts_41_wen,
  input  [7:0] io_diffWritePorts_41_data,
  input        io_diffWritePorts_42_wen,
  input  [7:0] io_diffWritePorts_42_data,
  input        io_diffWritePorts_43_wen,
  input  [7:0] io_diffWritePorts_43_data,
  input        io_diffWritePorts_44_wen,
  input  [7:0] io_diffWritePorts_44_data,
  input        io_diffWritePorts_45_wen,
  input  [7:0] io_diffWritePorts_45_data,
  input        io_diffWritePorts_46_wen,
  input  [7:0] io_diffWritePorts_46_data,
  input        io_diffWritePorts_47_wen,
  input  [7:0] io_diffWritePorts_47_data,
  input        io_diffWritePorts_48_wen,
  input  [7:0] io_diffWritePorts_48_data,
  input        io_diffWritePorts_49_wen,
  input  [7:0] io_diffWritePorts_49_data,
  input        io_diffWritePorts_50_wen,
  input  [7:0] io_diffWritePorts_50_data,
  input        io_diffWritePorts_51_wen,
  input  [7:0] io_diffWritePorts_51_data,
  input        io_diffWritePorts_52_wen,
  input  [7:0] io_diffWritePorts_52_data,
  input        io_diffWritePorts_53_wen,
  input  [7:0] io_diffWritePorts_53_data,
  input        io_diffWritePorts_54_wen,
  input  [7:0] io_diffWritePorts_54_data,
  input        io_diffWritePorts_55_wen,
  input  [7:0] io_diffWritePorts_55_data,
  input        io_diffWritePorts_56_wen,
  input  [7:0] io_diffWritePorts_56_data,
  input        io_diffWritePorts_57_wen,
  input  [7:0] io_diffWritePorts_57_data,
  input        io_diffWritePorts_58_wen,
  input  [7:0] io_diffWritePorts_58_data,
  input        io_diffWritePorts_59_wen,
  input  [7:0] io_diffWritePorts_59_data,
  input        io_diffWritePorts_60_wen,
  input  [7:0] io_diffWritePorts_60_data,
  input        io_diffWritePorts_61_wen,
  input  [7:0] io_diffWritePorts_61_data,
  input        io_diffWritePorts_62_wen,
  input  [7:0] io_diffWritePorts_62_data,
  input        io_diffWritePorts_63_wen,
  input  [7:0] io_diffWritePorts_63_data,
  input        io_diffWritePorts_64_wen,
  input  [7:0] io_diffWritePorts_64_data,
  input        io_diffWritePorts_65_wen,
  input  [7:0] io_diffWritePorts_65_data,
  input        io_diffWritePorts_66_wen,
  input  [7:0] io_diffWritePorts_66_data,
  input        io_diffWritePorts_67_wen,
  input  [7:0] io_diffWritePorts_67_data,
  input        io_diffWritePorts_68_wen,
  input  [7:0] io_diffWritePorts_68_data,
  input        io_diffWritePorts_69_wen,
  input  [7:0] io_diffWritePorts_69_data,
  input        io_diffWritePorts_70_wen,
  input  [7:0] io_diffWritePorts_70_data,
  input        io_diffWritePorts_71_wen,
  input  [7:0] io_diffWritePorts_71_data,
  input        io_diffWritePorts_72_wen,
  input  [7:0] io_diffWritePorts_72_data,
  input        io_diffWritePorts_73_wen,
  input  [7:0] io_diffWritePorts_73_data,
  input        io_diffWritePorts_74_wen,
  input  [7:0] io_diffWritePorts_74_data,
  input        io_diffWritePorts_75_wen,
  input  [7:0] io_diffWritePorts_75_data,
  input        io_diffWritePorts_76_wen,
  input  [7:0] io_diffWritePorts_76_data,
  input        io_diffWritePorts_77_wen,
  input  [7:0] io_diffWritePorts_77_data,
  input        io_diffWritePorts_78_wen,
  input  [7:0] io_diffWritePorts_78_data,
  input        io_diffWritePorts_79_wen,
  input  [7:0] io_diffWritePorts_79_data,
  input        io_diffWritePorts_80_wen,
  input  [7:0] io_diffWritePorts_80_data,
  input        io_diffWritePorts_81_wen,
  input  [7:0] io_diffWritePorts_81_data,
  input        io_diffWritePorts_82_wen,
  input  [7:0] io_diffWritePorts_82_data,
  input        io_diffWritePorts_83_wen,
  input  [7:0] io_diffWritePorts_83_data,
  input        io_diffWritePorts_84_wen,
  input  [7:0] io_diffWritePorts_84_data,
  input        io_diffWritePorts_85_wen,
  input  [7:0] io_diffWritePorts_85_data,
  input        io_diffWritePorts_86_wen,
  input  [7:0] io_diffWritePorts_86_data,
  input        io_diffWritePorts_87_wen,
  input  [7:0] io_diffWritePorts_87_data,
  input        io_diffWritePorts_88_wen,
  input  [7:0] io_diffWritePorts_88_data,
  input        io_diffWritePorts_89_wen,
  input  [7:0] io_diffWritePorts_89_data,
  input        io_diffWritePorts_90_wen,
  input  [7:0] io_diffWritePorts_90_data,
  input        io_diffWritePorts_91_wen,
  input  [7:0] io_diffWritePorts_91_data,
  input        io_diffWritePorts_92_wen,
  input  [7:0] io_diffWritePorts_92_data,
  input        io_diffWritePorts_93_wen,
  input  [7:0] io_diffWritePorts_93_data,
  input        io_diffWritePorts_94_wen,
  input  [7:0] io_diffWritePorts_94_data,
  input        io_diffWritePorts_95_wen,
  input  [7:0] io_diffWritePorts_95_data,
  input        io_diffWritePorts_96_wen,
  input  [7:0] io_diffWritePorts_96_data,
  input        io_diffWritePorts_97_wen,
  input  [7:0] io_diffWritePorts_97_data,
  input        io_diffWritePorts_98_wen,
  input  [7:0] io_diffWritePorts_98_data,
  input        io_diffWritePorts_99_wen,
  input  [7:0] io_diffWritePorts_99_data,
  input        io_diffWritePorts_100_wen,
  input  [7:0] io_diffWritePorts_100_data,
  input        io_diffWritePorts_101_wen,
  input  [7:0] io_diffWritePorts_101_data,
  input        io_diffWritePorts_102_wen,
  input  [7:0] io_diffWritePorts_102_data,
  input        io_diffWritePorts_103_wen,
  input  [7:0] io_diffWritePorts_103_data,
  input        io_diffWritePorts_104_wen,
  input  [7:0] io_diffWritePorts_104_data,
  input        io_diffWritePorts_105_wen,
  input  [7:0] io_diffWritePorts_105_data,
  input        io_diffWritePorts_106_wen,
  input  [7:0] io_diffWritePorts_106_data,
  input        io_diffWritePorts_107_wen,
  input  [7:0] io_diffWritePorts_107_data,
  input        io_diffWritePorts_108_wen,
  input  [7:0] io_diffWritePorts_108_data,
  input        io_diffWritePorts_109_wen,
  input  [7:0] io_diffWritePorts_109_data,
  input        io_diffWritePorts_110_wen,
  input  [7:0] io_diffWritePorts_110_data,
  input        io_diffWritePorts_111_wen,
  input  [7:0] io_diffWritePorts_111_data,
  input        io_diffWritePorts_112_wen,
  input  [7:0] io_diffWritePorts_112_data,
  input        io_diffWritePorts_113_wen,
  input  [7:0] io_diffWritePorts_113_data,
  input        io_diffWritePorts_114_wen,
  input  [7:0] io_diffWritePorts_114_data,
  input        io_diffWritePorts_115_wen,
  input  [7:0] io_diffWritePorts_115_data,
  input        io_diffWritePorts_116_wen,
  input  [7:0] io_diffWritePorts_116_data,
  input        io_diffWritePorts_117_wen,
  input  [7:0] io_diffWritePorts_117_data,
  input        io_diffWritePorts_118_wen,
  input  [7:0] io_diffWritePorts_118_data,
  input        io_diffWritePorts_119_wen,
  input  [7:0] io_diffWritePorts_119_data,
  input        io_diffWritePorts_120_wen,
  input  [7:0] io_diffWritePorts_120_data,
  input        io_diffWritePorts_121_wen,
  input  [7:0] io_diffWritePorts_121_data,
  input        io_diffWritePorts_122_wen,
  input  [7:0] io_diffWritePorts_122_data,
  input        io_diffWritePorts_123_wen,
  input  [7:0] io_diffWritePorts_123_data,
  input        io_diffWritePorts_124_wen,
  input  [7:0] io_diffWritePorts_124_data,
  input        io_diffWritePorts_125_wen,
  input  [7:0] io_diffWritePorts_125_data,
  input        io_diffWritePorts_126_wen,
  input  [7:0] io_diffWritePorts_126_data,
  output [7:0] io_diff_rdata_0
);

  wire [7:0]      _snapshots_snapshotGen_io_snapshots_0_0;
  wire [7:0]      _snapshots_snapshotGen_io_snapshots_1_0;
  wire [7:0]      _snapshots_snapshotGen_io_snapshots_2_0;
  wire [7:0]      _snapshots_snapshotGen_io_snapshots_3_0;
  reg  [7:0]      spec_table_0;
  reg  [7:0]      arch_table_0;
  reg  [7:0]      old_pdest_0;
  reg  [7:0]      old_pdest_1;
  reg  [7:0]      old_pdest_2;
  reg  [7:0]      old_pdest_3;
  reg  [7:0]      old_pdest_4;
  reg  [7:0]      old_pdest_5;
  reg  [7:0]      old_pdest_6;
  reg  [7:0]      old_pdest_7;
  reg             t1_redirect_last_REG;
  reg             t1_wSpec_0_wen;
  reg  [7:0]      t1_wSpec_0_data;
  reg             t1_wSpec_1_wen;
  reg  [7:0]      t1_wSpec_1_data;
  reg             t1_wSpec_2_wen;
  reg  [7:0]      t1_wSpec_2_data;
  reg             t1_wSpec_3_wen;
  reg  [7:0]      t1_wSpec_3_data;
  reg             t1_wSpec_4_wen;
  reg  [7:0]      t1_wSpec_4_data;
  reg             t1_wSpec_5_wen;
  reg  [7:0]      t1_wSpec_5_data;
  reg             t1_wSpec_6_wen;
  reg  [7:0]      t1_wSpec_6_data;
  reg             t1_wSpec_7_wen;
  reg  [7:0]      t1_wSpec_7_data;
  reg             t1_snpt_snptEnq;
  reg             t1_snpt_snptDeq;
  reg             t1_snpt_useSnpt;
  reg  [1:0]      t1_snpt_snptSelect;
  reg             t1_snpt_flushVec_0;
  reg             t1_snpt_flushVec_1;
  reg             t1_snpt_flushVec_2;
  reg             t1_snpt_flushVec_3;
  reg             t2_snpt_useSnpt;
  reg  [1:0]      t2_snpt_snptSelect;
  reg             spec_table_next_0_REG;
  reg             t1_bypass_0;
  reg             t1_bypass_1;
  reg             t1_bypass_2;
  reg             t1_bypass_3;
  reg             t1_bypass_4;
  reg             t1_bypass_5;
  reg             t1_bypass_6;
  reg             t1_bypass_7;
  wire            _bypass_data_T = t1_bypass_7 | t1_bypass_6;
  reg             t1_bypass_1_0;
  reg             t1_bypass_1_1;
  reg             t1_bypass_1_2;
  reg             t1_bypass_1_3;
  reg             t1_bypass_1_4;
  reg             t1_bypass_1_5;
  reg             t1_bypass_1_6;
  reg             t1_bypass_1_7;
  wire            _bypass_data_T_13 = t1_bypass_1_7 | t1_bypass_1_6;
  reg             t1_bypass_2_0;
  reg             t1_bypass_2_1;
  reg             t1_bypass_2_2;
  reg             t1_bypass_2_3;
  reg             t1_bypass_2_4;
  reg             t1_bypass_2_5;
  reg             t1_bypass_2_6;
  reg             t1_bypass_2_7;
  wire            _bypass_data_T_26 = t1_bypass_2_7 | t1_bypass_2_6;
  reg             t1_bypass_3_0;
  reg             t1_bypass_3_1;
  reg             t1_bypass_3_2;
  reg             t1_bypass_3_3;
  reg             t1_bypass_3_4;
  reg             t1_bypass_3_5;
  reg             t1_bypass_3_6;
  reg             t1_bypass_3_7;
  wire            _bypass_data_T_39 = t1_bypass_3_7 | t1_bypass_3_6;
  reg             t1_bypass_4_0;
  reg             t1_bypass_4_1;
  reg             t1_bypass_4_2;
  reg             t1_bypass_4_3;
  reg             t1_bypass_4_4;
  reg             t1_bypass_4_5;
  reg             t1_bypass_4_6;
  reg             t1_bypass_4_7;
  wire            _bypass_data_T_52 = t1_bypass_4_7 | t1_bypass_4_6;
  reg             t1_bypass_5_0;
  reg             t1_bypass_5_1;
  reg             t1_bypass_5_2;
  reg             t1_bypass_5_3;
  reg             t1_bypass_5_4;
  reg             t1_bypass_5_5;
  reg             t1_bypass_5_6;
  reg             t1_bypass_5_7;
  wire            _bypass_data_T_65 = t1_bypass_5_7 | t1_bypass_5_6;
  reg             t1_bypass_6_0;
  reg             t1_bypass_6_1;
  reg             t1_bypass_6_2;
  reg             t1_bypass_6_3;
  reg             t1_bypass_6_4;
  reg             t1_bypass_6_5;
  reg             t1_bypass_6_6;
  reg             t1_bypass_6_7;
  wire            _bypass_data_T_78 = t1_bypass_6_7 | t1_bypass_6_6;
  reg             t1_bypass_7_0;
  reg             t1_bypass_7_1;
  reg             t1_bypass_7_2;
  reg             t1_bypass_7_3;
  reg             t1_bypass_7_4;
  reg             t1_bypass_7_5;
  reg             t1_bypass_7_6;
  reg             t1_bypass_7_7;
  wire            _bypass_data_T_91 = t1_bypass_7_7 | t1_bypass_7_6;
  reg  [7:0]      difftest_table_0;
  wire [3:0][7:0] _GEN =
    {{_snapshots_snapshotGen_io_snapshots_3_0},
     {_snapshots_snapshotGen_io_snapshots_2_0},
     {_snapshots_snapshotGen_io_snapshots_1_0},
     {_snapshots_snapshotGen_io_snapshots_0_0}};
  wire            _wMatch_T = t1_wSpec_7_wen | t1_wSpec_6_wen;
  wire [7:0]      arch_mask_1 = {8{io_archWritePorts_1_wen}};
  wire [7:0]      arch_mask_2 = {8{io_archWritePorts_2_wen}};
  wire [7:0]      arch_mask_3 = {8{io_archWritePorts_3_wen}};
  wire [7:0]      arch_mask_4 = {8{io_archWritePorts_4_wen}};
  wire [7:0]      arch_mask_5 = {8{io_archWritePorts_5_wen}};
  wire [7:0]      arch_mask_6 = {8{io_archWritePorts_6_wen}};
  wire [7:0]      arch_mask_7 = {8{io_archWritePorts_7_wen}};
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      spec_table_0 <= 8'h0;
      arch_table_0 <= 8'h0;
      old_pdest_0 <= 8'h0;
      old_pdest_1 <= 8'h0;
      old_pdest_2 <= 8'h0;
      old_pdest_3 <= 8'h0;
      old_pdest_4 <= 8'h0;
      old_pdest_5 <= 8'h0;
      old_pdest_6 <= 8'h0;
      old_pdest_7 <= 8'h0;
      t1_redirect_last_REG <= 1'h0;
      t1_snpt_snptEnq <= 1'h0;
      t1_snpt_snptDeq <= 1'h0;
      t1_snpt_useSnpt <= 1'h0;
      t1_snpt_snptSelect <= 2'h0;
      t1_snpt_flushVec_0 <= 1'h0;
      t1_snpt_flushVec_1 <= 1'h0;
      t1_snpt_flushVec_2 <= 1'h0;
      t1_snpt_flushVec_3 <= 1'h0;
      t2_snpt_useSnpt <= 1'h0;
      t2_snpt_snptSelect <= 2'h0;
      difftest_table_0 <= 8'h0;
    end
    else begin
      if (spec_table_next_0_REG)
        spec_table_0 <= t2_snpt_useSnpt ? _GEN[t2_snpt_snptSelect] : arch_table_0;
      else if (|{t1_wSpec_7_wen,
                 t1_wSpec_6_wen,
                 t1_wSpec_5_wen,
                 t1_wSpec_4_wen,
                 t1_wSpec_3_wen,
                 t1_wSpec_2_wen,
                 t1_wSpec_1_wen,
                 t1_wSpec_0_wen})
        spec_table_0 <=
          _wMatch_T | t1_wSpec_5_wen | t1_wSpec_4_wen
            ? (_wMatch_T
                 ? (t1_wSpec_7_wen ? t1_wSpec_7_data : t1_wSpec_6_data)
                 : t1_wSpec_5_wen ? t1_wSpec_5_data : t1_wSpec_4_data)
            : t1_wSpec_3_wen | t1_wSpec_2_wen
                ? (t1_wSpec_3_wen ? t1_wSpec_3_data : t1_wSpec_2_data)
                : t1_wSpec_1_wen ? t1_wSpec_1_data : t1_wSpec_0_data;
      if (io_archWritePorts_7_wen)
        arch_table_0 <= io_archWritePorts_7_data;
      else if (io_archWritePorts_6_wen)
        arch_table_0 <= io_archWritePorts_6_data;
      else if (io_archWritePorts_5_wen)
        arch_table_0 <= io_archWritePorts_5_data;
      else if (io_archWritePorts_4_wen)
        arch_table_0 <= io_archWritePorts_4_data;
      else if (io_archWritePorts_3_wen)
        arch_table_0 <= io_archWritePorts_3_data;
      else if (io_archWritePorts_2_wen)
        arch_table_0 <= io_archWritePorts_2_data;
      else if (io_archWritePorts_1_wen)
        arch_table_0 <= io_archWritePorts_1_data;
      else if (io_archWritePorts_0_wen)
        arch_table_0 <= io_archWritePorts_0_data;
      old_pdest_0 <= arch_table_0 & {8{io_archWritePorts_0_wen}};
      old_pdest_1 <=
        io_archWritePorts_0_wen
          ? io_archWritePorts_0_data & arch_mask_1
          : arch_table_0 & arch_mask_1;
      old_pdest_2 <=
        io_archWritePorts_1_wen
          ? io_archWritePorts_1_data & arch_mask_2
          : io_archWritePorts_0_wen
              ? io_archWritePorts_0_data & arch_mask_2
              : arch_table_0 & arch_mask_2;
      old_pdest_3 <=
        io_archWritePorts_2_wen
          ? io_archWritePorts_2_data & arch_mask_3
          : io_archWritePorts_1_wen
              ? io_archWritePorts_1_data & arch_mask_3
              : io_archWritePorts_0_wen
                  ? io_archWritePorts_0_data & arch_mask_3
                  : arch_table_0 & arch_mask_3;
      old_pdest_4 <=
        io_archWritePorts_3_wen
          ? io_archWritePorts_3_data & arch_mask_4
          : io_archWritePorts_2_wen
              ? io_archWritePorts_2_data & arch_mask_4
              : io_archWritePorts_1_wen
                  ? io_archWritePorts_1_data & arch_mask_4
                  : io_archWritePorts_0_wen
                      ? io_archWritePorts_0_data & arch_mask_4
                      : arch_table_0 & arch_mask_4;
      old_pdest_5 <=
        io_archWritePorts_4_wen
          ? io_archWritePorts_4_data & arch_mask_5
          : io_archWritePorts_3_wen
              ? io_archWritePorts_3_data & arch_mask_5
              : io_archWritePorts_2_wen
                  ? io_archWritePorts_2_data & arch_mask_5
                  : io_archWritePorts_1_wen
                      ? io_archWritePorts_1_data & arch_mask_5
                      : io_archWritePorts_0_wen
                          ? io_archWritePorts_0_data & arch_mask_5
                          : arch_table_0 & arch_mask_5;
      old_pdest_6 <=
        io_archWritePorts_5_wen
          ? io_archWritePorts_5_data & arch_mask_6
          : io_archWritePorts_4_wen
              ? io_archWritePorts_4_data & arch_mask_6
              : io_archWritePorts_3_wen
                  ? io_archWritePorts_3_data & arch_mask_6
                  : io_archWritePorts_2_wen
                      ? io_archWritePorts_2_data & arch_mask_6
                      : io_archWritePorts_1_wen
                          ? io_archWritePorts_1_data & arch_mask_6
                          : io_archWritePorts_0_wen
                              ? io_archWritePorts_0_data & arch_mask_6
                              : arch_table_0 & arch_mask_6;
      old_pdest_7 <=
        io_archWritePorts_6_wen
          ? io_archWritePorts_6_data & arch_mask_7
          : io_archWritePorts_5_wen
              ? io_archWritePorts_5_data & arch_mask_7
              : io_archWritePorts_4_wen
                  ? io_archWritePorts_4_data & arch_mask_7
                  : io_archWritePorts_3_wen
                      ? io_archWritePorts_3_data & arch_mask_7
                      : io_archWritePorts_2_wen
                          ? io_archWritePorts_2_data & arch_mask_7
                          : io_archWritePorts_1_wen
                              ? io_archWritePorts_1_data & arch_mask_7
                              : io_archWritePorts_0_wen
                                  ? io_archWritePorts_0_data & arch_mask_7
                                  : arch_table_0 & arch_mask_7;
      t1_redirect_last_REG <= io_redirect;
      t1_snpt_snptEnq <= io_snpt_snptEnq;
      t1_snpt_snptDeq <= io_snpt_snptDeq;
      t1_snpt_useSnpt <= io_snpt_useSnpt;
      t1_snpt_snptSelect <= io_snpt_snptSelect;
      t1_snpt_flushVec_0 <= io_snpt_flushVec_0;
      t1_snpt_flushVec_1 <= io_snpt_flushVec_1;
      t1_snpt_flushVec_2 <= io_snpt_flushVec_2;
      t1_snpt_flushVec_3 <= io_snpt_flushVec_3;
      t2_snpt_useSnpt <= t1_snpt_useSnpt;
      t2_snpt_snptSelect <= t1_snpt_snptSelect;
      if (io_diffWritePorts_126_wen)
        difftest_table_0 <= io_diffWritePorts_126_data;
      else if (io_diffWritePorts_125_wen)
        difftest_table_0 <= io_diffWritePorts_125_data;
      else if (io_diffWritePorts_124_wen)
        difftest_table_0 <= io_diffWritePorts_124_data;
      else if (io_diffWritePorts_123_wen)
        difftest_table_0 <= io_diffWritePorts_123_data;
      else if (io_diffWritePorts_122_wen)
        difftest_table_0 <= io_diffWritePorts_122_data;
      else if (io_diffWritePorts_121_wen)
        difftest_table_0 <= io_diffWritePorts_121_data;
      else if (io_diffWritePorts_120_wen)
        difftest_table_0 <= io_diffWritePorts_120_data;
      else if (io_diffWritePorts_119_wen)
        difftest_table_0 <= io_diffWritePorts_119_data;
      else if (io_diffWritePorts_118_wen)
        difftest_table_0 <= io_diffWritePorts_118_data;
      else if (io_diffWritePorts_117_wen)
        difftest_table_0 <= io_diffWritePorts_117_data;
      else if (io_diffWritePorts_116_wen)
        difftest_table_0 <= io_diffWritePorts_116_data;
      else if (io_diffWritePorts_115_wen)
        difftest_table_0 <= io_diffWritePorts_115_data;
      else if (io_diffWritePorts_114_wen)
        difftest_table_0 <= io_diffWritePorts_114_data;
      else if (io_diffWritePorts_113_wen)
        difftest_table_0 <= io_diffWritePorts_113_data;
      else if (io_diffWritePorts_112_wen)
        difftest_table_0 <= io_diffWritePorts_112_data;
      else if (io_diffWritePorts_111_wen)
        difftest_table_0 <= io_diffWritePorts_111_data;
      else if (io_diffWritePorts_110_wen)
        difftest_table_0 <= io_diffWritePorts_110_data;
      else if (io_diffWritePorts_109_wen)
        difftest_table_0 <= io_diffWritePorts_109_data;
      else if (io_diffWritePorts_108_wen)
        difftest_table_0 <= io_diffWritePorts_108_data;
      else if (io_diffWritePorts_107_wen)
        difftest_table_0 <= io_diffWritePorts_107_data;
      else if (io_diffWritePorts_106_wen)
        difftest_table_0 <= io_diffWritePorts_106_data;
      else if (io_diffWritePorts_105_wen)
        difftest_table_0 <= io_diffWritePorts_105_data;
      else if (io_diffWritePorts_104_wen)
        difftest_table_0 <= io_diffWritePorts_104_data;
      else if (io_diffWritePorts_103_wen)
        difftest_table_0 <= io_diffWritePorts_103_data;
      else if (io_diffWritePorts_102_wen)
        difftest_table_0 <= io_diffWritePorts_102_data;
      else if (io_diffWritePorts_101_wen)
        difftest_table_0 <= io_diffWritePorts_101_data;
      else if (io_diffWritePorts_100_wen)
        difftest_table_0 <= io_diffWritePorts_100_data;
      else if (io_diffWritePorts_99_wen)
        difftest_table_0 <= io_diffWritePorts_99_data;
      else if (io_diffWritePorts_98_wen)
        difftest_table_0 <= io_diffWritePorts_98_data;
      else if (io_diffWritePorts_97_wen)
        difftest_table_0 <= io_diffWritePorts_97_data;
      else if (io_diffWritePorts_96_wen)
        difftest_table_0 <= io_diffWritePorts_96_data;
      else if (io_diffWritePorts_95_wen)
        difftest_table_0 <= io_diffWritePorts_95_data;
      else if (io_diffWritePorts_94_wen)
        difftest_table_0 <= io_diffWritePorts_94_data;
      else if (io_diffWritePorts_93_wen)
        difftest_table_0 <= io_diffWritePorts_93_data;
      else if (io_diffWritePorts_92_wen)
        difftest_table_0 <= io_diffWritePorts_92_data;
      else if (io_diffWritePorts_91_wen)
        difftest_table_0 <= io_diffWritePorts_91_data;
      else if (io_diffWritePorts_90_wen)
        difftest_table_0 <= io_diffWritePorts_90_data;
      else if (io_diffWritePorts_89_wen)
        difftest_table_0 <= io_diffWritePorts_89_data;
      else if (io_diffWritePorts_88_wen)
        difftest_table_0 <= io_diffWritePorts_88_data;
      else if (io_diffWritePorts_87_wen)
        difftest_table_0 <= io_diffWritePorts_87_data;
      else if (io_diffWritePorts_86_wen)
        difftest_table_0 <= io_diffWritePorts_86_data;
      else if (io_diffWritePorts_85_wen)
        difftest_table_0 <= io_diffWritePorts_85_data;
      else if (io_diffWritePorts_84_wen)
        difftest_table_0 <= io_diffWritePorts_84_data;
      else if (io_diffWritePorts_83_wen)
        difftest_table_0 <= io_diffWritePorts_83_data;
      else if (io_diffWritePorts_82_wen)
        difftest_table_0 <= io_diffWritePorts_82_data;
      else if (io_diffWritePorts_81_wen)
        difftest_table_0 <= io_diffWritePorts_81_data;
      else if (io_diffWritePorts_80_wen)
        difftest_table_0 <= io_diffWritePorts_80_data;
      else if (io_diffWritePorts_79_wen)
        difftest_table_0 <= io_diffWritePorts_79_data;
      else if (io_diffWritePorts_78_wen)
        difftest_table_0 <= io_diffWritePorts_78_data;
      else if (io_diffWritePorts_77_wen)
        difftest_table_0 <= io_diffWritePorts_77_data;
      else if (io_diffWritePorts_76_wen)
        difftest_table_0 <= io_diffWritePorts_76_data;
      else if (io_diffWritePorts_75_wen)
        difftest_table_0 <= io_diffWritePorts_75_data;
      else if (io_diffWritePorts_74_wen)
        difftest_table_0 <= io_diffWritePorts_74_data;
      else if (io_diffWritePorts_73_wen)
        difftest_table_0 <= io_diffWritePorts_73_data;
      else if (io_diffWritePorts_72_wen)
        difftest_table_0 <= io_diffWritePorts_72_data;
      else if (io_diffWritePorts_71_wen)
        difftest_table_0 <= io_diffWritePorts_71_data;
      else if (io_diffWritePorts_70_wen)
        difftest_table_0 <= io_diffWritePorts_70_data;
      else if (io_diffWritePorts_69_wen)
        difftest_table_0 <= io_diffWritePorts_69_data;
      else if (io_diffWritePorts_68_wen)
        difftest_table_0 <= io_diffWritePorts_68_data;
      else if (io_diffWritePorts_67_wen)
        difftest_table_0 <= io_diffWritePorts_67_data;
      else if (io_diffWritePorts_66_wen)
        difftest_table_0 <= io_diffWritePorts_66_data;
      else if (io_diffWritePorts_65_wen)
        difftest_table_0 <= io_diffWritePorts_65_data;
      else if (io_diffWritePorts_64_wen)
        difftest_table_0 <= io_diffWritePorts_64_data;
      else if (io_diffWritePorts_63_wen)
        difftest_table_0 <= io_diffWritePorts_63_data;
      else if (io_diffWritePorts_62_wen)
        difftest_table_0 <= io_diffWritePorts_62_data;
      else if (io_diffWritePorts_61_wen)
        difftest_table_0 <= io_diffWritePorts_61_data;
      else if (io_diffWritePorts_60_wen)
        difftest_table_0 <= io_diffWritePorts_60_data;
      else if (io_diffWritePorts_59_wen)
        difftest_table_0 <= io_diffWritePorts_59_data;
      else if (io_diffWritePorts_58_wen)
        difftest_table_0 <= io_diffWritePorts_58_data;
      else if (io_diffWritePorts_57_wen)
        difftest_table_0 <= io_diffWritePorts_57_data;
      else if (io_diffWritePorts_56_wen)
        difftest_table_0 <= io_diffWritePorts_56_data;
      else if (io_diffWritePorts_55_wen)
        difftest_table_0 <= io_diffWritePorts_55_data;
      else if (io_diffWritePorts_54_wen)
        difftest_table_0 <= io_diffWritePorts_54_data;
      else if (io_diffWritePorts_53_wen)
        difftest_table_0 <= io_diffWritePorts_53_data;
      else if (io_diffWritePorts_52_wen)
        difftest_table_0 <= io_diffWritePorts_52_data;
      else if (io_diffWritePorts_51_wen)
        difftest_table_0 <= io_diffWritePorts_51_data;
      else if (io_diffWritePorts_50_wen)
        difftest_table_0 <= io_diffWritePorts_50_data;
      else if (io_diffWritePorts_49_wen)
        difftest_table_0 <= io_diffWritePorts_49_data;
      else if (io_diffWritePorts_48_wen)
        difftest_table_0 <= io_diffWritePorts_48_data;
      else if (io_diffWritePorts_47_wen)
        difftest_table_0 <= io_diffWritePorts_47_data;
      else if (io_diffWritePorts_46_wen)
        difftest_table_0 <= io_diffWritePorts_46_data;
      else if (io_diffWritePorts_45_wen)
        difftest_table_0 <= io_diffWritePorts_45_data;
      else if (io_diffWritePorts_44_wen)
        difftest_table_0 <= io_diffWritePorts_44_data;
      else if (io_diffWritePorts_43_wen)
        difftest_table_0 <= io_diffWritePorts_43_data;
      else if (io_diffWritePorts_42_wen)
        difftest_table_0 <= io_diffWritePorts_42_data;
      else if (io_diffWritePorts_41_wen)
        difftest_table_0 <= io_diffWritePorts_41_data;
      else if (io_diffWritePorts_40_wen)
        difftest_table_0 <= io_diffWritePorts_40_data;
      else if (io_diffWritePorts_39_wen)
        difftest_table_0 <= io_diffWritePorts_39_data;
      else if (io_diffWritePorts_38_wen)
        difftest_table_0 <= io_diffWritePorts_38_data;
      else if (io_diffWritePorts_37_wen)
        difftest_table_0 <= io_diffWritePorts_37_data;
      else if (io_diffWritePorts_36_wen)
        difftest_table_0 <= io_diffWritePorts_36_data;
      else if (io_diffWritePorts_35_wen)
        difftest_table_0 <= io_diffWritePorts_35_data;
      else if (io_diffWritePorts_34_wen)
        difftest_table_0 <= io_diffWritePorts_34_data;
      else if (io_diffWritePorts_33_wen)
        difftest_table_0 <= io_diffWritePorts_33_data;
      else if (io_diffWritePorts_32_wen)
        difftest_table_0 <= io_diffWritePorts_32_data;
      else if (io_diffWritePorts_31_wen)
        difftest_table_0 <= io_diffWritePorts_31_data;
      else if (io_diffWritePorts_30_wen)
        difftest_table_0 <= io_diffWritePorts_30_data;
      else if (io_diffWritePorts_29_wen)
        difftest_table_0 <= io_diffWritePorts_29_data;
      else if (io_diffWritePorts_28_wen)
        difftest_table_0 <= io_diffWritePorts_28_data;
      else if (io_diffWritePorts_27_wen)
        difftest_table_0 <= io_diffWritePorts_27_data;
      else if (io_diffWritePorts_26_wen)
        difftest_table_0 <= io_diffWritePorts_26_data;
      else if (io_diffWritePorts_25_wen)
        difftest_table_0 <= io_diffWritePorts_25_data;
      else if (io_diffWritePorts_24_wen)
        difftest_table_0 <= io_diffWritePorts_24_data;
      else if (io_diffWritePorts_23_wen)
        difftest_table_0 <= io_diffWritePorts_23_data;
      else if (io_diffWritePorts_22_wen)
        difftest_table_0 <= io_diffWritePorts_22_data;
      else if (io_diffWritePorts_21_wen)
        difftest_table_0 <= io_diffWritePorts_21_data;
      else if (io_diffWritePorts_20_wen)
        difftest_table_0 <= io_diffWritePorts_20_data;
      else if (io_diffWritePorts_19_wen)
        difftest_table_0 <= io_diffWritePorts_19_data;
      else if (io_diffWritePorts_18_wen)
        difftest_table_0 <= io_diffWritePorts_18_data;
      else if (io_diffWritePorts_17_wen)
        difftest_table_0 <= io_diffWritePorts_17_data;
      else if (io_diffWritePorts_16_wen)
        difftest_table_0 <= io_diffWritePorts_16_data;
      else if (io_diffWritePorts_15_wen)
        difftest_table_0 <= io_diffWritePorts_15_data;
      else if (io_diffWritePorts_14_wen)
        difftest_table_0 <= io_diffWritePorts_14_data;
      else if (io_diffWritePorts_13_wen)
        difftest_table_0 <= io_diffWritePorts_13_data;
      else if (io_diffWritePorts_12_wen)
        difftest_table_0 <= io_diffWritePorts_12_data;
      else if (io_diffWritePorts_11_wen)
        difftest_table_0 <= io_diffWritePorts_11_data;
      else if (io_diffWritePorts_10_wen)
        difftest_table_0 <= io_diffWritePorts_10_data;
      else if (io_diffWritePorts_9_wen)
        difftest_table_0 <= io_diffWritePorts_9_data;
      else if (io_diffWritePorts_8_wen)
        difftest_table_0 <= io_diffWritePorts_8_data;
      else if (io_diffWritePorts_7_wen)
        difftest_table_0 <= io_diffWritePorts_7_data;
      else if (io_diffWritePorts_6_wen)
        difftest_table_0 <= io_diffWritePorts_6_data;
      else if (io_diffWritePorts_5_wen)
        difftest_table_0 <= io_diffWritePorts_5_data;
      else if (io_diffWritePorts_4_wen)
        difftest_table_0 <= io_diffWritePorts_4_data;
      else if (io_diffWritePorts_3_wen)
        difftest_table_0 <= io_diffWritePorts_3_data;
      else if (io_diffWritePorts_2_wen)
        difftest_table_0 <= io_diffWritePorts_2_data;
      else if (io_diffWritePorts_1_wen)
        difftest_table_0 <= io_diffWritePorts_1_data;
      else if (io_diffWritePorts_0_wen)
        difftest_table_0 <= io_diffWritePorts_0_data;
    end
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (io_redirect) begin
      t1_wSpec_0_wen <= 1'h0;
      t1_wSpec_0_data <= 8'h0;
      t1_wSpec_1_wen <= 1'h0;
      t1_wSpec_1_data <= 8'h0;
      t1_wSpec_2_wen <= 1'h0;
      t1_wSpec_2_data <= 8'h0;
      t1_wSpec_3_wen <= 1'h0;
      t1_wSpec_3_data <= 8'h0;
      t1_wSpec_4_wen <= 1'h0;
      t1_wSpec_4_data <= 8'h0;
      t1_wSpec_5_wen <= 1'h0;
      t1_wSpec_5_data <= 8'h0;
      t1_wSpec_6_wen <= 1'h0;
      t1_wSpec_6_data <= 8'h0;
      t1_wSpec_7_wen <= 1'h0;
      t1_wSpec_7_data <= 8'h0;
      t1_bypass_0 <= 1'h0;
      t1_bypass_1 <= 1'h0;
      t1_bypass_2 <= 1'h0;
      t1_bypass_3 <= 1'h0;
      t1_bypass_4 <= 1'h0;
      t1_bypass_5 <= 1'h0;
      t1_bypass_6 <= 1'h0;
      t1_bypass_7 <= 1'h0;
      t1_bypass_1_0 <= 1'h0;
      t1_bypass_1_1 <= 1'h0;
      t1_bypass_1_2 <= 1'h0;
      t1_bypass_1_3 <= 1'h0;
      t1_bypass_1_4 <= 1'h0;
      t1_bypass_1_5 <= 1'h0;
      t1_bypass_1_6 <= 1'h0;
      t1_bypass_1_7 <= 1'h0;
      t1_bypass_2_0 <= 1'h0;
      t1_bypass_2_1 <= 1'h0;
      t1_bypass_2_2 <= 1'h0;
      t1_bypass_2_3 <= 1'h0;
      t1_bypass_2_4 <= 1'h0;
      t1_bypass_2_5 <= 1'h0;
      t1_bypass_2_6 <= 1'h0;
      t1_bypass_2_7 <= 1'h0;
      t1_bypass_3_0 <= 1'h0;
      t1_bypass_3_1 <= 1'h0;
      t1_bypass_3_2 <= 1'h0;
      t1_bypass_3_3 <= 1'h0;
      t1_bypass_3_4 <= 1'h0;
      t1_bypass_3_5 <= 1'h0;
      t1_bypass_3_6 <= 1'h0;
      t1_bypass_3_7 <= 1'h0;
      t1_bypass_4_0 <= 1'h0;
      t1_bypass_4_1 <= 1'h0;
      t1_bypass_4_2 <= 1'h0;
      t1_bypass_4_3 <= 1'h0;
      t1_bypass_4_4 <= 1'h0;
      t1_bypass_4_5 <= 1'h0;
      t1_bypass_4_6 <= 1'h0;
      t1_bypass_4_7 <= 1'h0;
      t1_bypass_5_0 <= 1'h0;
      t1_bypass_5_1 <= 1'h0;
      t1_bypass_5_2 <= 1'h0;
      t1_bypass_5_3 <= 1'h0;
      t1_bypass_5_4 <= 1'h0;
      t1_bypass_5_5 <= 1'h0;
      t1_bypass_5_6 <= 1'h0;
      t1_bypass_5_7 <= 1'h0;
      t1_bypass_6_0 <= 1'h0;
      t1_bypass_6_1 <= 1'h0;
      t1_bypass_6_2 <= 1'h0;
      t1_bypass_6_3 <= 1'h0;
      t1_bypass_6_4 <= 1'h0;
      t1_bypass_6_5 <= 1'h0;
      t1_bypass_6_6 <= 1'h0;
      t1_bypass_6_7 <= 1'h0;
      t1_bypass_7_0 <= 1'h0;
      t1_bypass_7_1 <= 1'h0;
      t1_bypass_7_2 <= 1'h0;
      t1_bypass_7_3 <= 1'h0;
      t1_bypass_7_4 <= 1'h0;
      t1_bypass_7_5 <= 1'h0;
      t1_bypass_7_6 <= 1'h0;
      t1_bypass_7_7 <= 1'h0;
    end
    else begin
      t1_wSpec_0_wen <= io_specWritePorts_0_wen;
      t1_wSpec_0_data <= io_specWritePorts_0_data;
      t1_wSpec_1_wen <= io_specWritePorts_1_wen;
      t1_wSpec_1_data <= io_specWritePorts_1_data;
      t1_wSpec_2_wen <= io_specWritePorts_2_wen;
      t1_wSpec_2_data <= io_specWritePorts_2_data;
      t1_wSpec_3_wen <= io_specWritePorts_3_wen;
      t1_wSpec_3_data <= io_specWritePorts_3_data;
      t1_wSpec_4_wen <= io_specWritePorts_4_wen;
      t1_wSpec_4_data <= io_specWritePorts_4_data;
      t1_wSpec_5_wen <= io_specWritePorts_5_wen;
      t1_wSpec_5_data <= io_specWritePorts_5_data;
      t1_wSpec_6_wen <= io_specWritePorts_6_wen;
      t1_wSpec_6_data <= io_specWritePorts_6_data;
      t1_wSpec_7_wen <= io_specWritePorts_7_wen;
      t1_wSpec_7_data <= io_specWritePorts_7_data;
      t1_bypass_0 <= io_specWritePorts_0_wen;
      t1_bypass_1 <= io_specWritePorts_1_wen;
      t1_bypass_2 <= io_specWritePorts_2_wen;
      t1_bypass_3 <= io_specWritePorts_3_wen;
      t1_bypass_4 <= io_specWritePorts_4_wen;
      t1_bypass_5 <= io_specWritePorts_5_wen;
      t1_bypass_6 <= io_specWritePorts_6_wen;
      t1_bypass_7 <= io_specWritePorts_7_wen;
      t1_bypass_1_0 <= io_specWritePorts_0_wen;
      t1_bypass_1_1 <= io_specWritePorts_1_wen;
      t1_bypass_1_2 <= io_specWritePorts_2_wen;
      t1_bypass_1_3 <= io_specWritePorts_3_wen;
      t1_bypass_1_4 <= io_specWritePorts_4_wen;
      t1_bypass_1_5 <= io_specWritePorts_5_wen;
      t1_bypass_1_6 <= io_specWritePorts_6_wen;
      t1_bypass_1_7 <= io_specWritePorts_7_wen;
      t1_bypass_2_0 <= io_specWritePorts_0_wen;
      t1_bypass_2_1 <= io_specWritePorts_1_wen;
      t1_bypass_2_2 <= io_specWritePorts_2_wen;
      t1_bypass_2_3 <= io_specWritePorts_3_wen;
      t1_bypass_2_4 <= io_specWritePorts_4_wen;
      t1_bypass_2_5 <= io_specWritePorts_5_wen;
      t1_bypass_2_6 <= io_specWritePorts_6_wen;
      t1_bypass_2_7 <= io_specWritePorts_7_wen;
      t1_bypass_3_0 <= io_specWritePorts_0_wen;
      t1_bypass_3_1 <= io_specWritePorts_1_wen;
      t1_bypass_3_2 <= io_specWritePorts_2_wen;
      t1_bypass_3_3 <= io_specWritePorts_3_wen;
      t1_bypass_3_4 <= io_specWritePorts_4_wen;
      t1_bypass_3_5 <= io_specWritePorts_5_wen;
      t1_bypass_3_6 <= io_specWritePorts_6_wen;
      t1_bypass_3_7 <= io_specWritePorts_7_wen;
      t1_bypass_4_0 <= io_specWritePorts_0_wen;
      t1_bypass_4_1 <= io_specWritePorts_1_wen;
      t1_bypass_4_2 <= io_specWritePorts_2_wen;
      t1_bypass_4_3 <= io_specWritePorts_3_wen;
      t1_bypass_4_4 <= io_specWritePorts_4_wen;
      t1_bypass_4_5 <= io_specWritePorts_5_wen;
      t1_bypass_4_6 <= io_specWritePorts_6_wen;
      t1_bypass_4_7 <= io_specWritePorts_7_wen;
      t1_bypass_5_0 <= io_specWritePorts_0_wen;
      t1_bypass_5_1 <= io_specWritePorts_1_wen;
      t1_bypass_5_2 <= io_specWritePorts_2_wen;
      t1_bypass_5_3 <= io_specWritePorts_3_wen;
      t1_bypass_5_4 <= io_specWritePorts_4_wen;
      t1_bypass_5_5 <= io_specWritePorts_5_wen;
      t1_bypass_5_6 <= io_specWritePorts_6_wen;
      t1_bypass_5_7 <= io_specWritePorts_7_wen;
      t1_bypass_6_0 <= io_specWritePorts_0_wen;
      t1_bypass_6_1 <= io_specWritePorts_1_wen;
      t1_bypass_6_2 <= io_specWritePorts_2_wen;
      t1_bypass_6_3 <= io_specWritePorts_3_wen;
      t1_bypass_6_4 <= io_specWritePorts_4_wen;
      t1_bypass_6_5 <= io_specWritePorts_5_wen;
      t1_bypass_6_6 <= io_specWritePorts_6_wen;
      t1_bypass_6_7 <= io_specWritePorts_7_wen;
      t1_bypass_7_0 <= io_specWritePorts_0_wen;
      t1_bypass_7_1 <= io_specWritePorts_1_wen;
      t1_bypass_7_2 <= io_specWritePorts_2_wen;
      t1_bypass_7_3 <= io_specWritePorts_3_wen;
      t1_bypass_7_4 <= io_specWritePorts_4_wen;
      t1_bypass_7_5 <= io_specWritePorts_5_wen;
      t1_bypass_7_6 <= io_specWritePorts_6_wen;
      t1_bypass_7_7 <= io_specWritePorts_7_wen;
    end
    spec_table_next_0_REG <= t1_redirect_last_REG;
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:7];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [3:0] i = 4'h0; i < 4'h8; i += 4'h1) begin
          _RANDOM[i[2:0]] = `RANDOM;
        end
        spec_table_0 = _RANDOM[3'h0][7:0];
        arch_table_0 = _RANDOM[3'h0][15:8];
        old_pdest_0 = _RANDOM[3'h0][23:16];
        old_pdest_1 = _RANDOM[3'h0][31:24];
        old_pdest_2 = _RANDOM[3'h1][7:0];
        old_pdest_3 = _RANDOM[3'h1][15:8];
        old_pdest_4 = _RANDOM[3'h1][23:16];
        old_pdest_5 = _RANDOM[3'h1][31:24];
        old_pdest_6 = _RANDOM[3'h2][7:0];
        old_pdest_7 = _RANDOM[3'h2][15:8];
        t1_redirect_last_REG = _RANDOM[3'h2][24];
        t1_wSpec_0_wen = _RANDOM[3'h2][25];
        t1_wSpec_0_data = {_RANDOM[3'h2][31:26], _RANDOM[3'h3][1:0]};
        t1_wSpec_1_wen = _RANDOM[3'h3][2];
        t1_wSpec_1_data = _RANDOM[3'h3][10:3];
        t1_wSpec_2_wen = _RANDOM[3'h3][11];
        t1_wSpec_2_data = _RANDOM[3'h3][19:12];
        t1_wSpec_3_wen = _RANDOM[3'h3][20];
        t1_wSpec_3_data = _RANDOM[3'h3][28:21];
        t1_wSpec_4_wen = _RANDOM[3'h3][29];
        t1_wSpec_4_data = {_RANDOM[3'h3][31:30], _RANDOM[3'h4][5:0]};
        t1_wSpec_5_wen = _RANDOM[3'h4][6];
        t1_wSpec_5_data = _RANDOM[3'h4][14:7];
        t1_wSpec_6_wen = _RANDOM[3'h4][15];
        t1_wSpec_6_data = _RANDOM[3'h4][23:16];
        t1_wSpec_7_wen = _RANDOM[3'h4][24];
        t1_wSpec_7_data = {_RANDOM[3'h4][31:25], _RANDOM[3'h5][0]};
        t1_snpt_snptEnq = _RANDOM[3'h5][1];
        t1_snpt_snptDeq = _RANDOM[3'h5][2];
        t1_snpt_useSnpt = _RANDOM[3'h5][3];
        t1_snpt_snptSelect = _RANDOM[3'h5][5:4];
        t1_snpt_flushVec_0 = _RANDOM[3'h5][6];
        t1_snpt_flushVec_1 = _RANDOM[3'h5][7];
        t1_snpt_flushVec_2 = _RANDOM[3'h5][8];
        t1_snpt_flushVec_3 = _RANDOM[3'h5][9];
        t2_snpt_useSnpt = _RANDOM[3'h5][12];
        t2_snpt_snptSelect = _RANDOM[3'h5][14:13];
        spec_table_next_0_REG = _RANDOM[3'h5][19];
        t1_bypass_0 = _RANDOM[3'h5][20];
        t1_bypass_1 = _RANDOM[3'h5][21];
        t1_bypass_2 = _RANDOM[3'h5][22];
        t1_bypass_3 = _RANDOM[3'h5][23];
        t1_bypass_4 = _RANDOM[3'h5][24];
        t1_bypass_5 = _RANDOM[3'h5][25];
        t1_bypass_6 = _RANDOM[3'h5][26];
        t1_bypass_7 = _RANDOM[3'h5][27];
        t1_bypass_1_0 = _RANDOM[3'h5][28];
        t1_bypass_1_1 = _RANDOM[3'h5][29];
        t1_bypass_1_2 = _RANDOM[3'h5][30];
        t1_bypass_1_3 = _RANDOM[3'h5][31];
        t1_bypass_1_4 = _RANDOM[3'h6][0];
        t1_bypass_1_5 = _RANDOM[3'h6][1];
        t1_bypass_1_6 = _RANDOM[3'h6][2];
        t1_bypass_1_7 = _RANDOM[3'h6][3];
        t1_bypass_2_0 = _RANDOM[3'h6][4];
        t1_bypass_2_1 = _RANDOM[3'h6][5];
        t1_bypass_2_2 = _RANDOM[3'h6][6];
        t1_bypass_2_3 = _RANDOM[3'h6][7];
        t1_bypass_2_4 = _RANDOM[3'h6][8];
        t1_bypass_2_5 = _RANDOM[3'h6][9];
        t1_bypass_2_6 = _RANDOM[3'h6][10];
        t1_bypass_2_7 = _RANDOM[3'h6][11];
        t1_bypass_3_0 = _RANDOM[3'h6][12];
        t1_bypass_3_1 = _RANDOM[3'h6][13];
        t1_bypass_3_2 = _RANDOM[3'h6][14];
        t1_bypass_3_3 = _RANDOM[3'h6][15];
        t1_bypass_3_4 = _RANDOM[3'h6][16];
        t1_bypass_3_5 = _RANDOM[3'h6][17];
        t1_bypass_3_6 = _RANDOM[3'h6][18];
        t1_bypass_3_7 = _RANDOM[3'h6][19];
        t1_bypass_4_0 = _RANDOM[3'h6][20];
        t1_bypass_4_1 = _RANDOM[3'h6][21];
        t1_bypass_4_2 = _RANDOM[3'h6][22];
        t1_bypass_4_3 = _RANDOM[3'h6][23];
        t1_bypass_4_4 = _RANDOM[3'h6][24];
        t1_bypass_4_5 = _RANDOM[3'h6][25];
        t1_bypass_4_6 = _RANDOM[3'h6][26];
        t1_bypass_4_7 = _RANDOM[3'h6][27];
        t1_bypass_5_0 = _RANDOM[3'h6][28];
        t1_bypass_5_1 = _RANDOM[3'h6][29];
        t1_bypass_5_2 = _RANDOM[3'h6][30];
        t1_bypass_5_3 = _RANDOM[3'h6][31];
        t1_bypass_5_4 = _RANDOM[3'h7][0];
        t1_bypass_5_5 = _RANDOM[3'h7][1];
        t1_bypass_5_6 = _RANDOM[3'h7][2];
        t1_bypass_5_7 = _RANDOM[3'h7][3];
        t1_bypass_6_0 = _RANDOM[3'h7][4];
        t1_bypass_6_1 = _RANDOM[3'h7][5];
        t1_bypass_6_2 = _RANDOM[3'h7][6];
        t1_bypass_6_3 = _RANDOM[3'h7][7];
        t1_bypass_6_4 = _RANDOM[3'h7][8];
        t1_bypass_6_5 = _RANDOM[3'h7][9];
        t1_bypass_6_6 = _RANDOM[3'h7][10];
        t1_bypass_6_7 = _RANDOM[3'h7][11];
        t1_bypass_7_0 = _RANDOM[3'h7][12];
        t1_bypass_7_1 = _RANDOM[3'h7][13];
        t1_bypass_7_2 = _RANDOM[3'h7][14];
        t1_bypass_7_3 = _RANDOM[3'h7][15];
        t1_bypass_7_4 = _RANDOM[3'h7][16];
        t1_bypass_7_5 = _RANDOM[3'h7][17];
        t1_bypass_7_6 = _RANDOM[3'h7][18];
        t1_bypass_7_7 = _RANDOM[3'h7][19];
        difftest_table_0 = _RANDOM[3'h7][27:20];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        spec_table_0 = 8'h0;
        arch_table_0 = 8'h0;
        old_pdest_0 = 8'h0;
        old_pdest_1 = 8'h0;
        old_pdest_2 = 8'h0;
        old_pdest_3 = 8'h0;
        old_pdest_4 = 8'h0;
        old_pdest_5 = 8'h0;
        old_pdest_6 = 8'h0;
        old_pdest_7 = 8'h0;
        t1_redirect_last_REG = 1'h0;
        t1_snpt_snptEnq = 1'h0;
        t1_snpt_snptDeq = 1'h0;
        t1_snpt_useSnpt = 1'h0;
        t1_snpt_snptSelect = 2'h0;
        t1_snpt_flushVec_0 = 1'h0;
        t1_snpt_flushVec_1 = 1'h0;
        t1_snpt_flushVec_2 = 1'h0;
        t1_snpt_flushVec_3 = 1'h0;
        t2_snpt_useSnpt = 1'h0;
        t2_snpt_snptSelect = 2'h0;
        difftest_table_0 = 8'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  SnapshotGenerator_12 snapshots_snapshotGen (
    .clock            (clock),
    .reset            (reset),
    .io_enq           (t1_snpt_snptEnq),
    .io_enqData_0     (spec_table_0),
    .io_deq           (t1_snpt_snptDeq),
    .io_redirect      (t1_redirect_last_REG),
    .io_flushVec_0    (t1_snpt_flushVec_0),
    .io_flushVec_1    (t1_snpt_flushVec_1),
    .io_flushVec_2    (t1_snpt_flushVec_2),
    .io_flushVec_3    (t1_snpt_flushVec_3),
    .io_snapshots_0_0 (_snapshots_snapshotGen_io_snapshots_0_0),
    .io_snapshots_1_0 (_snapshots_snapshotGen_io_snapshots_1_0),
    .io_snapshots_2_0 (_snapshots_snapshotGen_io_snapshots_2_0),
    .io_snapshots_3_0 (_snapshots_snapshotGen_io_snapshots_3_0)
  );
  assign io_readPorts_0_data =
    (|{t1_bypass_7,
       t1_bypass_6,
       t1_bypass_5,
       t1_bypass_4,
       t1_bypass_3,
       t1_bypass_2,
       t1_bypass_1,
       t1_bypass_0})
      ? (_bypass_data_T | t1_bypass_5 | t1_bypass_4
           ? (_bypass_data_T
                ? (t1_bypass_7 ? t1_wSpec_7_data : t1_wSpec_6_data)
                : t1_bypass_5 ? t1_wSpec_5_data : t1_wSpec_4_data)
           : t1_bypass_3 | t1_bypass_2
               ? (t1_bypass_3 ? t1_wSpec_3_data : t1_wSpec_2_data)
               : t1_bypass_1 ? t1_wSpec_1_data : t1_wSpec_0_data)
      : spec_table_0;
  assign io_readPorts_1_data =
    (|{t1_bypass_1_7,
       t1_bypass_1_6,
       t1_bypass_1_5,
       t1_bypass_1_4,
       t1_bypass_1_3,
       t1_bypass_1_2,
       t1_bypass_1_1,
       t1_bypass_1_0})
      ? (_bypass_data_T_13 | t1_bypass_1_5 | t1_bypass_1_4
           ? (_bypass_data_T_13
                ? (t1_bypass_1_7 ? t1_wSpec_7_data : t1_wSpec_6_data)
                : t1_bypass_1_5 ? t1_wSpec_5_data : t1_wSpec_4_data)
           : t1_bypass_1_3 | t1_bypass_1_2
               ? (t1_bypass_1_3 ? t1_wSpec_3_data : t1_wSpec_2_data)
               : t1_bypass_1_1 ? t1_wSpec_1_data : t1_wSpec_0_data)
      : spec_table_0;
  assign io_readPorts_2_data =
    (|{t1_bypass_2_7,
       t1_bypass_2_6,
       t1_bypass_2_5,
       t1_bypass_2_4,
       t1_bypass_2_3,
       t1_bypass_2_2,
       t1_bypass_2_1,
       t1_bypass_2_0})
      ? (_bypass_data_T_26 | t1_bypass_2_5 | t1_bypass_2_4
           ? (_bypass_data_T_26
                ? (t1_bypass_2_7 ? t1_wSpec_7_data : t1_wSpec_6_data)
                : t1_bypass_2_5 ? t1_wSpec_5_data : t1_wSpec_4_data)
           : t1_bypass_2_3 | t1_bypass_2_2
               ? (t1_bypass_2_3 ? t1_wSpec_3_data : t1_wSpec_2_data)
               : t1_bypass_2_1 ? t1_wSpec_1_data : t1_wSpec_0_data)
      : spec_table_0;
  assign io_readPorts_3_data =
    (|{t1_bypass_3_7,
       t1_bypass_3_6,
       t1_bypass_3_5,
       t1_bypass_3_4,
       t1_bypass_3_3,
       t1_bypass_3_2,
       t1_bypass_3_1,
       t1_bypass_3_0})
      ? (_bypass_data_T_39 | t1_bypass_3_5 | t1_bypass_3_4
           ? (_bypass_data_T_39
                ? (t1_bypass_3_7 ? t1_wSpec_7_data : t1_wSpec_6_data)
                : t1_bypass_3_5 ? t1_wSpec_5_data : t1_wSpec_4_data)
           : t1_bypass_3_3 | t1_bypass_3_2
               ? (t1_bypass_3_3 ? t1_wSpec_3_data : t1_wSpec_2_data)
               : t1_bypass_3_1 ? t1_wSpec_1_data : t1_wSpec_0_data)
      : spec_table_0;
  assign io_readPorts_4_data =
    (|{t1_bypass_4_7,
       t1_bypass_4_6,
       t1_bypass_4_5,
       t1_bypass_4_4,
       t1_bypass_4_3,
       t1_bypass_4_2,
       t1_bypass_4_1,
       t1_bypass_4_0})
      ? (_bypass_data_T_52 | t1_bypass_4_5 | t1_bypass_4_4
           ? (_bypass_data_T_52
                ? (t1_bypass_4_7 ? t1_wSpec_7_data : t1_wSpec_6_data)
                : t1_bypass_4_5 ? t1_wSpec_5_data : t1_wSpec_4_data)
           : t1_bypass_4_3 | t1_bypass_4_2
               ? (t1_bypass_4_3 ? t1_wSpec_3_data : t1_wSpec_2_data)
               : t1_bypass_4_1 ? t1_wSpec_1_data : t1_wSpec_0_data)
      : spec_table_0;
  assign io_readPorts_5_data =
    (|{t1_bypass_5_7,
       t1_bypass_5_6,
       t1_bypass_5_5,
       t1_bypass_5_4,
       t1_bypass_5_3,
       t1_bypass_5_2,
       t1_bypass_5_1,
       t1_bypass_5_0})
      ? (_bypass_data_T_65 | t1_bypass_5_5 | t1_bypass_5_4
           ? (_bypass_data_T_65
                ? (t1_bypass_5_7 ? t1_wSpec_7_data : t1_wSpec_6_data)
                : t1_bypass_5_5 ? t1_wSpec_5_data : t1_wSpec_4_data)
           : t1_bypass_5_3 | t1_bypass_5_2
               ? (t1_bypass_5_3 ? t1_wSpec_3_data : t1_wSpec_2_data)
               : t1_bypass_5_1 ? t1_wSpec_1_data : t1_wSpec_0_data)
      : spec_table_0;
  assign io_readPorts_6_data =
    (|{t1_bypass_6_7,
       t1_bypass_6_6,
       t1_bypass_6_5,
       t1_bypass_6_4,
       t1_bypass_6_3,
       t1_bypass_6_2,
       t1_bypass_6_1,
       t1_bypass_6_0})
      ? (_bypass_data_T_78 | t1_bypass_6_5 | t1_bypass_6_4
           ? (_bypass_data_T_78
                ? (t1_bypass_6_7 ? t1_wSpec_7_data : t1_wSpec_6_data)
                : t1_bypass_6_5 ? t1_wSpec_5_data : t1_wSpec_4_data)
           : t1_bypass_6_3 | t1_bypass_6_2
               ? (t1_bypass_6_3 ? t1_wSpec_3_data : t1_wSpec_2_data)
               : t1_bypass_6_1 ? t1_wSpec_1_data : t1_wSpec_0_data)
      : spec_table_0;
  assign io_readPorts_7_data =
    (|{t1_bypass_7_7,
       t1_bypass_7_6,
       t1_bypass_7_5,
       t1_bypass_7_4,
       t1_bypass_7_3,
       t1_bypass_7_2,
       t1_bypass_7_1,
       t1_bypass_7_0})
      ? (_bypass_data_T_91 | t1_bypass_7_5 | t1_bypass_7_4
           ? (_bypass_data_T_91
                ? (t1_bypass_7_7 ? t1_wSpec_7_data : t1_wSpec_6_data)
                : t1_bypass_7_5 ? t1_wSpec_5_data : t1_wSpec_4_data)
           : t1_bypass_7_3 | t1_bypass_7_2
               ? (t1_bypass_7_3 ? t1_wSpec_3_data : t1_wSpec_2_data)
               : t1_bypass_7_1 ? t1_wSpec_1_data : t1_wSpec_0_data)
      : spec_table_0;
  assign io_old_pdest_0 = old_pdest_0;
  assign io_old_pdest_1 = old_pdest_1;
  assign io_old_pdest_2 = old_pdest_2;
  assign io_old_pdest_3 = old_pdest_3;
  assign io_old_pdest_4 = old_pdest_4;
  assign io_old_pdest_5 = old_pdest_5;
  assign io_old_pdest_6 = old_pdest_6;
  assign io_old_pdest_7 = old_pdest_7;
  assign io_diff_rdata_0 = difftest_table_0;
endmodule

