// Generated by CIRCT firtool-1.135.0
module SplittedSRAMTemplate_2(
  input          clock,
  input          reset,
  input          io_r_req_valid,
  input  [5:0]   io_r_req_bits_setIdx,
  output         io_r_resp_data_0_valid,
  output [23:0]  io_r_resp_data_0_tag,
  output [3:0]   io_r_resp_data_0_position,
  output [1:0]   io_r_resp_data_0_attribute_branchType,
  output [1:0]   io_r_resp_data_0_attribute_rasAction,
  output [21:0]  io_r_resp_data_0_targetLowerBits,
  output         io_r_resp_data_1_valid,
  output [23:0]  io_r_resp_data_1_tag,
  output [3:0]   io_r_resp_data_1_position,
  output [1:0]   io_r_resp_data_1_attribute_branchType,
  output [1:0]   io_r_resp_data_1_attribute_rasAction,
  output [21:0]  io_r_resp_data_1_targetLowerBits,
  output         io_r_resp_data_2_valid,
  output [23:0]  io_r_resp_data_2_tag,
  output [3:0]   io_r_resp_data_2_position,
  output [1:0]   io_r_resp_data_2_attribute_branchType,
  output [1:0]   io_r_resp_data_2_attribute_rasAction,
  output [21:0]  io_r_resp_data_2_targetLowerBits,
  output         io_r_resp_data_3_valid,
  output [23:0]  io_r_resp_data_3_tag,
  output [3:0]   io_r_resp_data_3_position,
  output [1:0]   io_r_resp_data_3_attribute_branchType,
  output [1:0]   io_r_resp_data_3_attribute_rasAction,
  output [21:0]  io_r_resp_data_3_targetLowerBits,
  output         io_w_req_ready,
  input          io_w_req_valid,
  input  [5:0]   io_w_req_bits_setIdx,
  input          io_w_req_bits_data_0_valid,
  input  [23:0]  io_w_req_bits_data_0_tag,
  input  [3:0]   io_w_req_bits_data_0_position,
  input  [1:0]   io_w_req_bits_data_0_attribute_branchType,
  input  [1:0]   io_w_req_bits_data_0_attribute_rasAction,
  input  [21:0]  io_w_req_bits_data_0_targetLowerBits,
  input          io_w_req_bits_data_1_valid,
  input  [23:0]  io_w_req_bits_data_1_tag,
  input  [3:0]   io_w_req_bits_data_1_position,
  input  [1:0]   io_w_req_bits_data_1_attribute_branchType,
  input  [1:0]   io_w_req_bits_data_1_attribute_rasAction,
  input  [21:0]  io_w_req_bits_data_1_targetLowerBits,
  input          io_w_req_bits_data_2_valid,
  input  [23:0]  io_w_req_bits_data_2_tag,
  input  [3:0]   io_w_req_bits_data_2_position,
  input  [1:0]   io_w_req_bits_data_2_attribute_branchType,
  input  [1:0]   io_w_req_bits_data_2_attribute_rasAction,
  input  [21:0]  io_w_req_bits_data_2_targetLowerBits,
  input          io_w_req_bits_data_3_valid,
  input  [23:0]  io_w_req_bits_data_3_tag,
  input  [3:0]   io_w_req_bits_data_3_position,
  input  [1:0]   io_w_req_bits_data_3_attribute_branchType,
  input  [1:0]   io_w_req_bits_data_3_attribute_rasAction,
  input  [21:0]  io_w_req_bits_data_3_targetLowerBits,
  input  [3:0]   io_w_req_bits_waymask,
  output         io_resetDone,
  input  [6:0]   boreChildrenBd_bore_addr,
  input  [6:0]   boreChildrenBd_bore_addr_rd,
  input  [109:0] boreChildrenBd_bore_wdata,
  input  [1:0]   boreChildrenBd_bore_wmask,
  input          boreChildrenBd_bore_re,
  input          boreChildrenBd_bore_we,
  output [109:0] boreChildrenBd_bore_rdata,
  input          boreChildrenBd_bore_ack,
  input          boreChildrenBd_bore_selectedOH,
  input  [5:0]   boreChildrenBd_bore_array,
  input  [6:0]   boreChildrenBd_bore_1_addr,
  input  [6:0]   boreChildrenBd_bore_1_addr_rd,
  input  [109:0] boreChildrenBd_bore_1_wdata,
  input  [1:0]   boreChildrenBd_bore_1_wmask,
  input          boreChildrenBd_bore_1_re,
  input          boreChildrenBd_bore_1_we,
  output [109:0] boreChildrenBd_bore_1_rdata,
  input          boreChildrenBd_bore_1_ack,
  input          boreChildrenBd_bore_1_selectedOH,
  input  [5:0]   boreChildrenBd_bore_1_array,
  input          sigFromSrams_bore_ram_hold,
  input          sigFromSrams_bore_ram_bypass,
  input          sigFromSrams_bore_ram_bp_clken,
  input          sigFromSrams_bore_ram_aux_clk,
  input          sigFromSrams_bore_ram_aux_ckbp,
  input          sigFromSrams_bore_ram_mcp_hold,
  input          sigFromSrams_bore_cgen,
  input          sigFromSrams_bore_1_ram_hold,
  input          sigFromSrams_bore_1_ram_bypass,
  input          sigFromSrams_bore_1_ram_bp_clken,
  input          sigFromSrams_bore_1_ram_aux_clk,
  input          sigFromSrams_bore_1_ram_aux_ckbp,
  input          sigFromSrams_bore_1_ram_mcp_hold,
  input          sigFromSrams_bore_1_cgen
);

  wire [54:0] _array_0_1_0_io_r_resp_data_0;
  wire [54:0] _array_0_1_0_io_r_resp_data_1;
  wire        _array_0_1_0_io_resetDone;
  wire [54:0] _array_0_0_0_io_r_resp_data_0;
  wire [54:0] _array_0_0_0_io_r_resp_data_1;
  wire        _array_0_0_0_io_resetDone;
  SRAMTemplate_36 array_0_0_0 (
    .clock                          (clock),
    .reset                          (reset),
    .io_r_req_valid                 (io_r_req_valid),
    .io_r_req_bits_setIdx           (io_r_req_bits_setIdx),
    .io_r_resp_data_0               (_array_0_0_0_io_r_resp_data_0),
    .io_r_resp_data_1               (_array_0_0_0_io_r_resp_data_1),
    .io_w_req_ready                 (io_w_req_ready),
    .io_w_req_valid                 (io_w_req_valid),
    .io_w_req_bits_setIdx           (io_w_req_bits_setIdx),
    .io_w_req_bits_data_0
      ({io_w_req_bits_data_0_valid,
        io_w_req_bits_data_0_tag,
        io_w_req_bits_data_0_position,
        io_w_req_bits_data_0_attribute_branchType,
        io_w_req_bits_data_0_attribute_rasAction,
        io_w_req_bits_data_0_targetLowerBits}),
    .io_w_req_bits_data_1
      ({io_w_req_bits_data_1_valid,
        io_w_req_bits_data_1_tag,
        io_w_req_bits_data_1_position,
        io_w_req_bits_data_1_attribute_branchType,
        io_w_req_bits_data_1_attribute_rasAction,
        io_w_req_bits_data_1_targetLowerBits}),
    .io_w_req_bits_waymask          (io_w_req_bits_waymask[1:0]),
    .io_broadcast_ram_hold          (sigFromSrams_bore_ram_hold),
    .io_broadcast_ram_bypass        (sigFromSrams_bore_ram_bypass),
    .io_broadcast_ram_bp_clken      (sigFromSrams_bore_ram_bp_clken),
    .io_broadcast_ram_aux_clk       (sigFromSrams_bore_ram_aux_clk),
    .io_broadcast_ram_aux_ckbp      (sigFromSrams_bore_ram_aux_ckbp),
    .io_broadcast_ram_mcp_hold      (sigFromSrams_bore_ram_mcp_hold),
    .io_broadcast_ram_ctl           (64'h0),
    .io_broadcast_cgen              (sigFromSrams_bore_cgen),
    .io_resetDone                   (_array_0_0_0_io_resetDone),
    .boreChildrenBd_bore_addr       (boreChildrenBd_bore_addr),
    .boreChildrenBd_bore_addr_rd    (boreChildrenBd_bore_addr_rd),
    .boreChildrenBd_bore_wdata      (boreChildrenBd_bore_wdata),
    .boreChildrenBd_bore_wmask      (boreChildrenBd_bore_wmask),
    .boreChildrenBd_bore_re         (boreChildrenBd_bore_re),
    .boreChildrenBd_bore_we         (boreChildrenBd_bore_we),
    .boreChildrenBd_bore_rdata      (boreChildrenBd_bore_rdata),
    .boreChildrenBd_bore_ack        (boreChildrenBd_bore_ack),
    .boreChildrenBd_bore_selectedOH (boreChildrenBd_bore_selectedOH),
    .boreChildrenBd_bore_array      (boreChildrenBd_bore_array)
  );
  SRAMTemplate_36 array_0_1_0 (
    .clock                          (clock),
    .reset                          (reset),
    .io_r_req_valid                 (io_r_req_valid),
    .io_r_req_bits_setIdx           (io_r_req_bits_setIdx),
    .io_r_resp_data_0               (_array_0_1_0_io_r_resp_data_0),
    .io_r_resp_data_1               (_array_0_1_0_io_r_resp_data_1),
    .io_w_req_ready                 (/* unused */),
    .io_w_req_valid                 (io_w_req_valid),
    .io_w_req_bits_setIdx           (io_w_req_bits_setIdx),
    .io_w_req_bits_data_0
      ({io_w_req_bits_data_2_valid,
        io_w_req_bits_data_2_tag,
        io_w_req_bits_data_2_position,
        io_w_req_bits_data_2_attribute_branchType,
        io_w_req_bits_data_2_attribute_rasAction,
        io_w_req_bits_data_2_targetLowerBits}),
    .io_w_req_bits_data_1
      ({io_w_req_bits_data_3_valid,
        io_w_req_bits_data_3_tag,
        io_w_req_bits_data_3_position,
        io_w_req_bits_data_3_attribute_branchType,
        io_w_req_bits_data_3_attribute_rasAction,
        io_w_req_bits_data_3_targetLowerBits}),
    .io_w_req_bits_waymask          (io_w_req_bits_waymask[3:2]),
    .io_broadcast_ram_hold          (sigFromSrams_bore_1_ram_hold),
    .io_broadcast_ram_bypass        (sigFromSrams_bore_1_ram_bypass),
    .io_broadcast_ram_bp_clken      (sigFromSrams_bore_1_ram_bp_clken),
    .io_broadcast_ram_aux_clk       (sigFromSrams_bore_1_ram_aux_clk),
    .io_broadcast_ram_aux_ckbp      (sigFromSrams_bore_1_ram_aux_ckbp),
    .io_broadcast_ram_mcp_hold      (sigFromSrams_bore_1_ram_mcp_hold),
    .io_broadcast_ram_ctl           (64'h0),
    .io_broadcast_cgen              (sigFromSrams_bore_1_cgen),
    .io_resetDone                   (_array_0_1_0_io_resetDone),
    .boreChildrenBd_bore_addr       (boreChildrenBd_bore_1_addr),
    .boreChildrenBd_bore_addr_rd    (boreChildrenBd_bore_1_addr_rd),
    .boreChildrenBd_bore_wdata      (boreChildrenBd_bore_1_wdata),
    .boreChildrenBd_bore_wmask      (boreChildrenBd_bore_1_wmask),
    .boreChildrenBd_bore_re         (boreChildrenBd_bore_1_re),
    .boreChildrenBd_bore_we         (boreChildrenBd_bore_1_we),
    .boreChildrenBd_bore_rdata      (boreChildrenBd_bore_1_rdata),
    .boreChildrenBd_bore_ack        (boreChildrenBd_bore_1_ack),
    .boreChildrenBd_bore_selectedOH (boreChildrenBd_bore_1_selectedOH),
    .boreChildrenBd_bore_array      (boreChildrenBd_bore_1_array)
  );
  assign io_r_resp_data_0_valid = _array_0_0_0_io_r_resp_data_0[54];
  assign io_r_resp_data_0_tag = _array_0_0_0_io_r_resp_data_0[53:30];
  assign io_r_resp_data_0_position = _array_0_0_0_io_r_resp_data_0[29:26];
  assign io_r_resp_data_0_attribute_branchType = _array_0_0_0_io_r_resp_data_0[25:24];
  assign io_r_resp_data_0_attribute_rasAction = _array_0_0_0_io_r_resp_data_0[23:22];
  assign io_r_resp_data_0_targetLowerBits = _array_0_0_0_io_r_resp_data_0[21:0];
  assign io_r_resp_data_1_valid = _array_0_0_0_io_r_resp_data_1[54];
  assign io_r_resp_data_1_tag = _array_0_0_0_io_r_resp_data_1[53:30];
  assign io_r_resp_data_1_position = _array_0_0_0_io_r_resp_data_1[29:26];
  assign io_r_resp_data_1_attribute_branchType = _array_0_0_0_io_r_resp_data_1[25:24];
  assign io_r_resp_data_1_attribute_rasAction = _array_0_0_0_io_r_resp_data_1[23:22];
  assign io_r_resp_data_1_targetLowerBits = _array_0_0_0_io_r_resp_data_1[21:0];
  assign io_r_resp_data_2_valid = _array_0_1_0_io_r_resp_data_0[54];
  assign io_r_resp_data_2_tag = _array_0_1_0_io_r_resp_data_0[53:30];
  assign io_r_resp_data_2_position = _array_0_1_0_io_r_resp_data_0[29:26];
  assign io_r_resp_data_2_attribute_branchType = _array_0_1_0_io_r_resp_data_0[25:24];
  assign io_r_resp_data_2_attribute_rasAction = _array_0_1_0_io_r_resp_data_0[23:22];
  assign io_r_resp_data_2_targetLowerBits = _array_0_1_0_io_r_resp_data_0[21:0];
  assign io_r_resp_data_3_valid = _array_0_1_0_io_r_resp_data_1[54];
  assign io_r_resp_data_3_tag = _array_0_1_0_io_r_resp_data_1[53:30];
  assign io_r_resp_data_3_position = _array_0_1_0_io_r_resp_data_1[29:26];
  assign io_r_resp_data_3_attribute_branchType = _array_0_1_0_io_r_resp_data_1[25:24];
  assign io_r_resp_data_3_attribute_rasAction = _array_0_1_0_io_r_resp_data_1[23:22];
  assign io_r_resp_data_3_targetLowerBits = _array_0_1_0_io_r_resp_data_1[21:0];
  assign io_resetDone = _array_0_0_0_io_resetDone & _array_0_1_0_io_resetDone;
endmodule

