// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module ForwardingAgeLogic(	// @[generators/boom/src/main/scala/v4/lsu/lsu.scala:2014:7]
  input         clock,	// @[generators/boom/src/main/scala/v4/lsu/lsu.scala:2014:7]
  input  [23:0] io_matches,	// @[generators/boom/src/main/scala/v4/lsu/lsu.scala:2016:14]
  input  [4:0]  io_youngest,	// @[generators/boom/src/main/scala/v4/lsu/lsu.scala:2016:14]
  output        io_found,	// @[generators/boom/src/main/scala/v4/lsu/lsu.scala:2016:14]
  output [4:0]  io_found_idx	// @[generators/boom/src/main/scala/v4/lsu/lsu.scala:2016:14]
);

  reg         found_match;	// @[generators/boom/src/main/scala/v4/lsu/lsu.scala:2042:24]
  reg  [4:0]  found_idx;	// @[generators/boom/src/main/scala/v4/lsu/lsu.scala:2043:22]
  wire [23:0] _matches_T_1 = io_matches & {io_youngest > 5'h17, io_youngest > 5'h16, io_youngest > 5'h15, io_youngest > 5'h14, io_youngest > 5'h13, io_youngest > 5'h12, io_youngest > 5'h11, io_youngest > 5'h10, io_youngest[4], io_youngest > 5'hE, io_youngest > 5'hD, io_youngest > 5'hC, io_youngest > 5'hB, io_youngest > 5'hA, io_youngest > 5'h9, io_youngest > 5'h8, |(io_youngest[4:3]), io_youngest > 5'h6, io_youngest > 5'h5, io_youngest > 5'h4, |(io_youngest[4:2]), io_youngest > 5'h2, |(io_youngest[4:1]), |io_youngest};	// @[generators/boom/src/main/scala/v4/lsu/lsu.scala:2030:17, :2031:15, :2032:5, :2033:19, :2039:{29,40}]
  always @(posedge clock) begin	// @[generators/boom/src/main/scala/v4/lsu/lsu.scala:2014:7]
    found_match <= _matches_T_1[23] | _matches_T_1[22] | _matches_T_1[21] | _matches_T_1[20] | _matches_T_1[19] | _matches_T_1[18] | _matches_T_1[17] | _matches_T_1[16] | _matches_T_1[15] | _matches_T_1[14] | _matches_T_1[13] | _matches_T_1[12] | _matches_T_1[11] | _matches_T_1[10] | _matches_T_1[9] | _matches_T_1[8] | _matches_T_1[7] | _matches_T_1[6] | _matches_T_1[5] | _matches_T_1[4] | _matches_T_1[3] | _matches_T_1[2] | _matches_T_1[1] | _matches_T_1[0] | io_matches[23] | io_matches[22] | io_matches[21] | io_matches[20] | io_matches[19] | io_matches[18] | io_matches[17] | io_matches[16] | io_matches[15] | io_matches[14] | io_matches[13] | io_matches[12] | io_matches[11] | io_matches[10] | io_matches[9] | io_matches[8] | io_matches[7] | io_matches[6] | io_matches[5] | io_matches[4] | io_matches[3] | io_matches[2] | io_matches[1] | io_matches[0];	// @[generators/boom/src/main/scala/v4/lsu/lsu.scala:2039:29, :2042:24, :2053:20, :2054:7, :2055:22]
    found_idx <= _matches_T_1[23] ? 5'h17 : _matches_T_1[22] ? 5'h16 : _matches_T_1[21] ? 5'h15 : _matches_T_1[20] ? 5'h14 : _matches_T_1[19] ? 5'h13 : _matches_T_1[18] ? 5'h12 : _matches_T_1[17] ? 5'h11 : _matches_T_1[16] ? 5'h10 : _matches_T_1[15] ? 5'hF : _matches_T_1[14] ? 5'hE : _matches_T_1[13] ? 5'hD : _matches_T_1[12] ? 5'hC : _matches_T_1[11] ? 5'hB : _matches_T_1[10] ? 5'hA : _matches_T_1[9] ? 5'h9 : _matches_T_1[8] ? 5'h8 : _matches_T_1[7] ? 5'h7 : _matches_T_1[6] ? 5'h6 : _matches_T_1[5] ? 5'h5 : _matches_T_1[4] ? 5'h4 : _matches_T_1[3] ? 5'h3 : _matches_T_1[2] ? 5'h2 : _matches_T_1[1] ? 5'h1 : _matches_T_1[0] ? 5'h0 : io_matches[23] ? 5'h17 : io_matches[22] ? 5'h16 : io_matches[21] ? 5'h15 : io_matches[20] ? 5'h14 : io_matches[19] ? 5'h13 : io_matches[18] ? 5'h12 : io_matches[17] ? 5'h11 : io_matches[16] ? 5'h10 : io_matches[15] ? 5'hF : io_matches[14] ? 5'hE : io_matches[13] ? 5'hD : io_matches[12] ? 5'hC : io_matches[11] ? 5'hB : io_matches[10] ? 5'hA : io_matches[9] ? 5'h9 : io_matches[8] ? 5'h8 : io_matches[7] ? 5'h7 : io_matches[6] ? 5'h6 : io_matches[5] ? 5'h5 : io_matches[4] ? 5'h4 : io_matches[3] ? 5'h3 : io_matches[2] ? 5'h2 : {4'h0, io_matches[1]};	// @[generators/boom/src/main/scala/v4/lsu/lsu.scala:2030:17, :2031:15, :2032:5, :2033:19, :2039:29, :2043:22, :2053:20, :2054:7, :2056:20]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/boom/src/main/scala/v4/lsu/lsu.scala:2014:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v4/lsu/lsu.scala:2014:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v4/lsu/lsu.scala:2014:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[generators/boom/src/main/scala/v4/lsu/lsu.scala:2014:7]
    initial begin	// @[generators/boom/src/main/scala/v4/lsu/lsu.scala:2014:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v4/lsu/lsu.scala:2014:7]
        `INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v4/lsu/lsu.scala:2014:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/boom/src/main/scala/v4/lsu/lsu.scala:2014:7]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[generators/boom/src/main/scala/v4/lsu/lsu.scala:2014:7]
        found_match = _RANDOM[/*Zero width*/ 1'b0][0];	// @[generators/boom/src/main/scala/v4/lsu/lsu.scala:2014:7, :2042:24]
        found_idx = _RANDOM[/*Zero width*/ 1'b0][5:1];	// @[generators/boom/src/main/scala/v4/lsu/lsu.scala:2014:7, :2042:24, :2043:22]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v4/lsu/lsu.scala:2014:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v4/lsu/lsu.scala:2014:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_found = found_match;	// @[generators/boom/src/main/scala/v4/lsu/lsu.scala:2014:7, :2042:24]
  assign io_found_idx = found_idx;	// @[generators/boom/src/main/scala/v4/lsu/lsu.scala:2014:7, :2043:22]
endmodule

