// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module ICache(	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7]
  input          clock,	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7]
  input          reset,	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7]
  input          auto_master_out_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output         auto_master_out_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [31:0]  auto_master_out_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input          auto_master_out_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]   auto_master_out_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]   auto_master_out_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [127:0] auto_master_out_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input          io_req_valid,	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:100:14]
  input  [38:0]  io_req_bits_addr,	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:100:14]
  input  [31:0]  io_s1_paddr,	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:100:14]
  input          io_s1_kill,	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:100:14]
  input          io_s2_kill,	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:100:14]
  output         io_resp_valid,	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:100:14]
  output [127:0] io_resp_bits_data,	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:100:14]
  input          io_invalidate,	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:100:14]
  output         io_perf_acquire	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:100:14]
);

  wire         masterNodeOut_a_valid;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:296:{29,46}]
  wire         dataArrayB1_MPORT_4_en;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:260:56]
  wire [63:0]  wdata_1_7;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:243:51]
  wire [63:0]  wdata_0_7;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:242:51]
  wire         wen;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:225:32]
  wire         tag_array_MPORT_mask_7;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:149:100]
  wire         tag_array_MPORT_mask_6;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:149:100]
  wire         tag_array_MPORT_mask_5;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:149:100]
  wire         tag_array_MPORT_mask_4;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:149:100]
  wire         tag_array_MPORT_mask_3;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:149:100]
  wire         tag_array_MPORT_mask_2;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:149:100]
  wire         tag_array_MPORT_mask_1;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:149:100]
  wire         tag_array_MPORT_mask_0;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:149:100]
  wire         tag_array_tag_rdata_en;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:143:70]
  wire [5:0]   _tag_rdata_T;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:143:28]
  wire         io_req_ready;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:132:19]
  wire [511:0] _dataArrayB1_RW0_rdata;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire [511:0] _dataArrayB0_RW0_rdata;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  wire [159:0] _tag_array_RW0_rdata;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:141:30]
  wire         _repl_way_prng_io_out_0;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire         _repl_way_prng_io_out_1;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire         _repl_way_prng_io_out_2;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire         s0_valid = io_req_ready & io_req_valid;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:132:19, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  reg          s1_valid;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:116:25]
  reg          s2_valid;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:119:25]
  reg          s2_hit;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:120:23]
  reg          invalidated;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:123:24]
  reg          refill_valid;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:124:29]
  wire         refill_fire = auto_master_out_a_ready & masterNodeOut_a_valid;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:296:{29,46}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  reg          s2_miss_REG;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:126:48]
  wire         s2_miss = s2_valid & ~s2_hit & ~s2_miss_REG;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:119:25, :120:23, :126:{26,29,37,40,48}]
  reg  [31:0]  refill_paddr;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:127:31]
  wire         refill_one_beat = auto_master_out_d_valid & auto_master_out_d_bits_opcode[0];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:130:39, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:106:36]
  assign io_req_ready = ~refill_one_beat;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:130:39, :132:19]
  wire [26:0]  _r_beats1_decode_T = 27'hFFF << auto_master_out_d_bits_size;	// @[generators/rocket-chip/src/main/scala/util/package.scala:244:71]
  wire [7:0]   r_beats1 = auto_master_out_d_bits_opcode[0] ? ~(_r_beats1_decode_T[11:4]) : 8'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:106:36, :221:14, generators/rocket-chip/src/main/scala/util/package.scala:244:{46,71,76}]
  reg  [7:0]   r_counter;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
  wire [7:0]   _r_counter1_T = r_counter - 8'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :230:28]
  wire         refill_done = refill_one_beat & (r_counter == 8'h1 | r_beats1 == 8'h0);	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:130:39, :135:37, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:221:14, :229:27, :232:{25,33,43}, :233:22]
  wire [2:0]   repl_way = {_repl_way_prng_io_out_2, _repl_way_prng_io_out_1, _repl_way_prng_io_out_0};	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:139:58, src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  assign _tag_rdata_T = io_req_bits_addr[11:6];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:143:28]
  assign tag_array_tag_rdata_en = ~refill_done & s0_valid;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:135:37, :143:{57,70}, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:233:22, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  assign tag_array_MPORT_mask_0 = repl_way == 3'h0;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:139:58, :149:100]
  assign tag_array_MPORT_mask_1 = repl_way == 3'h1;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:139:58, :149:100]
  assign tag_array_MPORT_mask_2 = repl_way == 3'h2;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:139:58, :149:100]
  assign tag_array_MPORT_mask_3 = repl_way == 3'h3;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:139:58, :149:100]
  assign tag_array_MPORT_mask_4 = repl_way == 3'h4;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:139:58, :149:100]
  assign tag_array_MPORT_mask_5 = repl_way == 3'h5;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:139:58, :149:100]
  assign tag_array_MPORT_mask_6 = repl_way == 3'h6;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:139:58, :149:100]
  assign tag_array_MPORT_mask_7 = &repl_way;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:139:58, :149:100]
  reg  [511:0] vb_array;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:152:25]
  wire [511:0] _s1_vb_T_1 = vb_array >> io_s1_paddr[11:6];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:152:25, :166:29, :168:25]
  wire         s1_tag_hit_0 = _s1_vb_T_1[0] & _tag_array_RW0_rdata[19:0] == io_s1_paddr[31:12];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:141:30, :167:29, :168:25, :170:{28,35}]
  wire [511:0] _s1_vb_T_3 = vb_array >> {506'h1, io_s1_paddr[11:6]};	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:152:25, :166:29, :168:25]
  wire         s1_tag_hit_1 = _s1_vb_T_3[0] & _tag_array_RW0_rdata[39:20] == io_s1_paddr[31:12];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:141:30, :167:29, :168:25, :170:{28,35}]
  wire [511:0] _s1_vb_T_5 = vb_array >> {506'h2, io_s1_paddr[11:6]};	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:152:25, :166:29, :168:25]
  wire         s1_tag_hit_2 = _s1_vb_T_5[0] & _tag_array_RW0_rdata[59:40] == io_s1_paddr[31:12];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:141:30, :167:29, :168:25, :170:{28,35}]
  wire [511:0] _s1_vb_T_7 = vb_array >> {506'h3, io_s1_paddr[11:6]};	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:152:25, :166:29, :168:25]
  wire         s1_tag_hit_3 = _s1_vb_T_7[0] & _tag_array_RW0_rdata[79:60] == io_s1_paddr[31:12];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:141:30, :167:29, :168:25, :170:{28,35}]
  wire [511:0] _s1_vb_T_9 = vb_array >> {506'h4, io_s1_paddr[11:6]};	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:152:25, :166:29, :168:25]
  wire         s1_tag_hit_4 = _s1_vb_T_9[0] & _tag_array_RW0_rdata[99:80] == io_s1_paddr[31:12];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:141:30, :167:29, :168:25, :170:{28,35}]
  wire [511:0] _s1_vb_T_11 = vb_array >> {506'h5, io_s1_paddr[11:6]};	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:152:25, :166:29, :168:25]
  wire         s1_tag_hit_5 = _s1_vb_T_11[0] & _tag_array_RW0_rdata[119:100] == io_s1_paddr[31:12];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:141:30, :167:29, :168:25, :170:{28,35}]
  wire [511:0] _s1_vb_T_13 = vb_array >> {506'h6, io_s1_paddr[11:6]};	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:152:25, :166:29, :168:25]
  wire         s1_tag_hit_6 = _s1_vb_T_13[0] & _tag_array_RW0_rdata[139:120] == io_s1_paddr[31:12];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:141:30, :167:29, :168:25, :170:{28,35}]
  wire [511:0] _s1_vb_T_15 = vb_array >> {506'h7, io_s1_paddr[11:6]};	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:152:25, :166:29, :168:25]
  wire         s1_tag_hit_7 = _s1_vb_T_15[0] & _tag_array_RW0_rdata[159:140] == io_s1_paddr[31:12];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:141:30, :167:29, :168:25, :170:{28,35}]
  `ifndef SYNTHESIS	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:172:9]
    always @(posedge clock) begin	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:172:9]
      if (~reset & ~({1'h0, {1'h0, {1'h0, s1_tag_hit_0} + {1'h0, s1_tag_hit_1}} + {1'h0, {1'h0, s1_tag_hit_2} + {1'h0, s1_tag_hit_3}}} + {1'h0, {1'h0, {1'h0, s1_tag_hit_4} + {1'h0, s1_tag_hit_5}} + {1'h0, {1'h0, s1_tag_hit_6} + {1'h0, s1_tag_hit_7}}} < 4'h2 | ~s1_valid)) begin	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:116:25, :170:28, :172:{9,18,31,38,41}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:172:9]
          $error("Assertion failed\n    at icache.scala:172 assert(PopCount(s1_tag_hit) <= 1.U || !s1_valid)\n");	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:172:9]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:172:9]
          $fatal;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:172:9]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire         _GEN = dataArrayB1_MPORT_4_en | wen;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:225:32, :260:56, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  reg          s1_bankid_REG;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:222:25]
  assign wen = refill_one_beat & ~invalidated;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:123:24, :130:39, :225:{32,35}]
  wire [7:0]   _wmask_T_1 = 8'h1 << {5'h0, _repl_way_prng_io_out_2, _repl_way_prng_io_out_1, _repl_way_prng_io_out_0};	// @[src/main/scala/chisel3/util/OneHot.scala:58:35, src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire [7:0]   _GEN_0 = {refill_paddr[11:6], 2'h0} | r_beats1 & ~_r_counter1_T;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:127:31, :129:32, :234:{40,67}, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:221:14, :230:28, :234:{25,27}]
  assign wdata_0_7 = auto_master_out_d_bits_data[63:0];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:242:51]
  assign wdata_1_7 = auto_master_out_d_bits_data[127:64];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:243:51]
  assign dataArrayB1_MPORT_4_en = ~wen & s0_valid;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:225:32, :260:{51,56}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  reg  [63:0]  REG_0;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:260:27]
  reg  [63:0]  REG_1;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:260:27]
  reg  [63:0]  REG_2;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:260:27]
  reg  [63:0]  REG_3;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:260:27]
  reg  [63:0]  REG_4;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:260:27]
  reg  [63:0]  REG_5;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:260:27]
  reg  [63:0]  REG_6;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:260:27]
  reg  [63:0]  REG_7;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:260:27]
  reg  [63:0]  REG_1_0;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:261:27]
  reg  [63:0]  REG_1_1;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:261:27]
  reg  [63:0]  REG_1_2;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:261:27]
  reg  [63:0]  REG_1_3;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:261:27]
  reg  [63:0]  REG_1_4;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:261:27]
  reg  [63:0]  REG_1_5;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:261:27]
  reg  [63:0]  REG_1_6;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:261:27]
  reg  [63:0]  REG_1_7;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:261:27]
  reg          s2_tag_hit_0;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:272:27]
  reg          s2_tag_hit_1;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:272:27]
  reg          s2_tag_hit_2;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:272:27]
  reg          s2_tag_hit_3;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:272:27]
  reg          s2_tag_hit_4;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:272:27]
  reg          s2_tag_hit_5;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:272:27]
  reg          s2_tag_hit_6;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:272:27]
  reg          s2_tag_hit_7;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:272:27]
  reg          s2_bankid;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:274:26]
  wire [127:0] s2_way_mux = (s2_tag_hit_0 ? {REG_1_0, REG_0} : 128'h0) | (s2_tag_hit_1 ? {REG_1_1, REG_1} : 128'h0) | (s2_tag_hit_2 ? {REG_1_2, REG_2} : 128'h0) | (s2_tag_hit_3 ? {REG_1_3, REG_3} : 128'h0) | (s2_tag_hit_4 ? {REG_1_4, REG_4} : 128'h0) | (s2_tag_hit_5 ? {REG_1_5, REG_5} : 128'h0) | (s2_tag_hit_6 ? {REG_1_6, REG_6} : 128'h0) | (s2_tag_hit_7 ? {REG_1_7, REG_7} : 128'h0);	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:260:27, :261:27, :269:24, :272:27, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign masterNodeOut_a_valid = s2_miss & ~refill_valid & ~io_s2_kill;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:124:29, :126:{26,37}, :296:{29,32,46,49}]
  wire [511:0] _vb_array_T_3 = 512'h1 << {503'h0, _repl_way_prng_io_out_2, _repl_way_prng_io_out_1, _repl_way_prng_io_out_0, refill_paddr[11:6]};	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:127:31, :129:32, :154:32, src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  always @(posedge clock) begin	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7]
    if (reset) begin	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7]
      s1_valid <= 1'h0;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:116:25]
      s2_valid <= 1'h0;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:119:25]
      refill_valid <= 1'h0;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:124:29]
      r_counter <= 8'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
      vb_array <= 512'h0;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:152:25]
    end
    else begin	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7]
      s1_valid <= s0_valid;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:116:25, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      s2_valid <= s1_valid & ~io_s1_kill;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:116:25, :119:{25,35,38}]
      refill_valid <= ~refill_done & (refill_fire | refill_valid);	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:124:29, :135:37, :308:{22,37}, :309:{22,37}, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:233:22, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      if (auto_master_out_d_valid)	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
        r_counter <= r_counter == 8'h0 ? r_beats1 : _r_counter1_T;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:221:14, :229:27, :230:28, :231:25, :236:21]
      if (io_invalidate)	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:100:14]
        vb_array <= 512'h0;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:152:25]
      else if (refill_one_beat)	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:130:39]
        vb_array <= refill_done & ~invalidated ? vb_array | _vb_array_T_3 : ~(~vb_array | _vb_array_T_3);	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:123:24, :135:37, :152:25, :154:{32,72,75}, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:233:22]
    end
    s2_hit <= s1_tag_hit_0 | s1_tag_hit_1 | s1_tag_hit_2 | s1_tag_hit_3 | s1_tag_hit_4 | s1_tag_hit_5 | s1_tag_hit_6 | s1_tag_hit_7;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:118:35, :120:23, :170:28]
    invalidated <= refill_valid & (io_invalidate | invalidated);	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:123:24, :124:29, :157:24, :159:17, :307:{24,38}]
    s2_miss_REG <= refill_valid;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:124:29, :126:48]
    if (s1_valid & ~(refill_valid | s2_miss))	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:116:25, :124:29, :126:{26,37}, :127:{54,57,72}]
      refill_paddr <= io_s1_paddr;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:127:31]
    s1_bankid_REG <= io_req_bits_addr[3];	// @[generators/boom/src/main/scala/v4/ifu/frontend.scala:137:47, generators/boom/src/main/scala/v4/ifu/icache.scala:222:25]
    REG_0 <= _dataArrayB0_RW0_rdata[63:0];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:260:27, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    REG_1 <= _dataArrayB0_RW0_rdata[127:64];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:260:27, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    REG_2 <= _dataArrayB0_RW0_rdata[191:128];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:260:27, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    REG_3 <= _dataArrayB0_RW0_rdata[255:192];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:260:27, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    REG_4 <= _dataArrayB0_RW0_rdata[319:256];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:260:27, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    REG_5 <= _dataArrayB0_RW0_rdata[383:320];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:260:27, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    REG_6 <= _dataArrayB0_RW0_rdata[447:384];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:260:27, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    REG_7 <= _dataArrayB0_RW0_rdata[511:448];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:260:27, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    REG_1_0 <= _dataArrayB1_RW0_rdata[63:0];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:261:27, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    REG_1_1 <= _dataArrayB1_RW0_rdata[127:64];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:261:27, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    REG_1_2 <= _dataArrayB1_RW0_rdata[191:128];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:261:27, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    REG_1_3 <= _dataArrayB1_RW0_rdata[255:192];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:261:27, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    REG_1_4 <= _dataArrayB1_RW0_rdata[319:256];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:261:27, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    REG_1_5 <= _dataArrayB1_RW0_rdata[383:320];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:261:27, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    REG_1_6 <= _dataArrayB1_RW0_rdata[447:384];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:261:27, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    REG_1_7 <= _dataArrayB1_RW0_rdata[511:448];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:261:27, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    s2_tag_hit_0 <= s1_tag_hit_0;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:170:28, :272:27]
    s2_tag_hit_1 <= s1_tag_hit_1;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:170:28, :272:27]
    s2_tag_hit_2 <= s1_tag_hit_2;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:170:28, :272:27]
    s2_tag_hit_3 <= s1_tag_hit_3;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:170:28, :272:27]
    s2_tag_hit_4 <= s1_tag_hit_4;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:170:28, :272:27]
    s2_tag_hit_5 <= s1_tag_hit_5;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:170:28, :272:27]
    s2_tag_hit_6 <= s1_tag_hit_6;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:170:28, :272:27]
    s2_tag_hit_7 <= s1_tag_hit_7;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:170:28, :272:27]
    s2_bankid <= s1_bankid_REG;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:222:25, :274:26]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:49];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7]
    initial begin	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7]
        `INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7]
        for (logic [5:0] i = 6'h0; i < 6'h32; i += 6'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7]
        end	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7]
        s1_valid = _RANDOM[6'h0][0];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :116:25]
        s2_valid = _RANDOM[6'h0][1];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :116:25, :119:25]
        s2_hit = _RANDOM[6'h0][2];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :116:25, :120:23]
        invalidated = _RANDOM[6'h0][3];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :116:25, :123:24]
        refill_valid = _RANDOM[6'h0][4];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :116:25, :124:29]
        s2_miss_REG = _RANDOM[6'h0][5];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :116:25, :126:48]
        refill_paddr = {_RANDOM[6'h0][31:6], _RANDOM[6'h1][5:0]};	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :116:25, :127:31]
        r_counter = _RANDOM[6'h1][13:6];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :127:31, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
        vb_array = {_RANDOM[6'h1][31:14], _RANDOM[6'h2], _RANDOM[6'h3], _RANDOM[6'h4], _RANDOM[6'h5], _RANDOM[6'h6], _RANDOM[6'h7], _RANDOM[6'h8], _RANDOM[6'h9], _RANDOM[6'hA], _RANDOM[6'hB], _RANDOM[6'hC], _RANDOM[6'hD], _RANDOM[6'hE], _RANDOM[6'hF], _RANDOM[6'h10], _RANDOM[6'h11][13:0]};	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :127:31, :152:25]
        s1_bankid_REG = _RANDOM[6'h11][14];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :152:25, :222:25]
        REG_0 = {_RANDOM[6'h11][31:15], _RANDOM[6'h12], _RANDOM[6'h13][14:0]};	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :152:25, :260:27]
        REG_1 = {_RANDOM[6'h13][31:15], _RANDOM[6'h14], _RANDOM[6'h15][14:0]};	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :260:27]
        REG_2 = {_RANDOM[6'h15][31:15], _RANDOM[6'h16], _RANDOM[6'h17][14:0]};	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :260:27]
        REG_3 = {_RANDOM[6'h17][31:15], _RANDOM[6'h18], _RANDOM[6'h19][14:0]};	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :260:27]
        REG_4 = {_RANDOM[6'h19][31:15], _RANDOM[6'h1A], _RANDOM[6'h1B][14:0]};	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :260:27]
        REG_5 = {_RANDOM[6'h1B][31:15], _RANDOM[6'h1C], _RANDOM[6'h1D][14:0]};	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :260:27]
        REG_6 = {_RANDOM[6'h1D][31:15], _RANDOM[6'h1E], _RANDOM[6'h1F][14:0]};	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :260:27]
        REG_7 = {_RANDOM[6'h1F][31:15], _RANDOM[6'h20], _RANDOM[6'h21][14:0]};	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :260:27]
        REG_1_0 = {_RANDOM[6'h21][31:15], _RANDOM[6'h22], _RANDOM[6'h23][14:0]};	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :260:27, :261:27]
        REG_1_1 = {_RANDOM[6'h23][31:15], _RANDOM[6'h24], _RANDOM[6'h25][14:0]};	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :261:27]
        REG_1_2 = {_RANDOM[6'h25][31:15], _RANDOM[6'h26], _RANDOM[6'h27][14:0]};	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :261:27]
        REG_1_3 = {_RANDOM[6'h27][31:15], _RANDOM[6'h28], _RANDOM[6'h29][14:0]};	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :261:27]
        REG_1_4 = {_RANDOM[6'h29][31:15], _RANDOM[6'h2A], _RANDOM[6'h2B][14:0]};	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :261:27]
        REG_1_5 = {_RANDOM[6'h2B][31:15], _RANDOM[6'h2C], _RANDOM[6'h2D][14:0]};	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :261:27]
        REG_1_6 = {_RANDOM[6'h2D][31:15], _RANDOM[6'h2E], _RANDOM[6'h2F][14:0]};	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :261:27]
        REG_1_7 = {_RANDOM[6'h2F][31:15], _RANDOM[6'h30], _RANDOM[6'h31][14:0]};	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :261:27]
        s2_tag_hit_0 = _RANDOM[6'h31][15];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :261:27, :272:27]
        s2_tag_hit_1 = _RANDOM[6'h31][16];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :261:27, :272:27]
        s2_tag_hit_2 = _RANDOM[6'h31][17];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :261:27, :272:27]
        s2_tag_hit_3 = _RANDOM[6'h31][18];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :261:27, :272:27]
        s2_tag_hit_4 = _RANDOM[6'h31][19];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :261:27, :272:27]
        s2_tag_hit_5 = _RANDOM[6'h31][20];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :261:27, :272:27]
        s2_tag_hit_6 = _RANDOM[6'h31][21];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :261:27, :272:27]
        s2_tag_hit_7 = _RANDOM[6'h31][22];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :261:27, :272:27]
        s2_bankid = _RANDOM[6'h31][23];	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :261:27, :274:26]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  MaxPeriodFibonacciLFSR repl_way_prng (	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
    .clock        (clock),
    .reset        (reset),
    .io_increment (refill_fire),	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
    .io_out_0     (_repl_way_prng_io_out_0),
    .io_out_1     (_repl_way_prng_io_out_1),
    .io_out_2     (_repl_way_prng_io_out_2),
    .io_out_3     (/* unused */),
    .io_out_4     (/* unused */),
    .io_out_5     (/* unused */),
    .io_out_6     (/* unused */),
    .io_out_7     (/* unused */),
    .io_out_8     (/* unused */),
    .io_out_9     (/* unused */),
    .io_out_10    (/* unused */),
    .io_out_11    (/* unused */),
    .io_out_12    (/* unused */),
    .io_out_13    (/* unused */),
    .io_out_14    (/* unused */),
    .io_out_15    (/* unused */)
  );	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  tag_array_0 tag_array (	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:141:30]
    .RW0_addr  (refill_done ? refill_paddr[11:6] : _tag_rdata_T),	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:127:31, :129:32, :135:37, :141:30, :143:28, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:233:22]
    .RW0_en    (tag_array_tag_rdata_en | refill_done),	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:135:37, :141:30, :143:70, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:233:22]
    .RW0_clk   (clock),
    .RW0_wmode (refill_one_beat),	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:130:39]
    .RW0_wdata ({8{refill_paddr[31:12]}}),	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:127:31, :128:32, :141:30]
    .RW0_rdata (_tag_array_RW0_rdata),
    .RW0_wmask ({tag_array_MPORT_mask_7, tag_array_MPORT_mask_6, tag_array_MPORT_mask_5, tag_array_MPORT_mask_4, tag_array_MPORT_mask_3, tag_array_MPORT_mask_2, tag_array_MPORT_mask_1, tag_array_MPORT_mask_0})	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:141:30, :149:100]
  );	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:141:30]
  dataArrayB0 dataArrayB0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_addr  (refill_one_beat ? _GEN_0 : io_req_bits_addr[11:4] + {7'h0, io_req_bits_addr[3]}),	// @[generators/boom/src/main/scala/v4/ifu/frontend.scala:137:47, generators/boom/src/main/scala/v4/ifu/icache.scala:130:39, :217:{11,62}, :234:{10,67}]
    .RW0_en    (_GEN),	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_clk   (clock),
    .RW0_wmode (refill_one_beat),	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:130:39]
    .RW0_wdata ({8{wdata_0_7}}),	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:242:51, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_rdata (_dataArrayB0_RW0_rdata),
    .RW0_wmask (_wmask_T_1)	// @[src/main/scala/chisel3/util/OneHot.scala:58:35]
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  dataArrayB1 dataArrayB1 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_addr  (refill_one_beat ? _GEN_0 : io_req_bits_addr[11:4]),	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:130:39, :217:11, :234:67, :237:10]
    .RW0_en    (_GEN),	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_clk   (clock),
    .RW0_wmode (refill_one_beat),	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:130:39]
    .RW0_wdata ({8{wdata_1_7}}),	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:243:51, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_rdata (_dataArrayB1_RW0_rdata),
    .RW0_wmask (_wmask_T_1)	// @[src/main/scala/chisel3/util/OneHot.scala:58:35]
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  assign auto_master_out_a_valid = masterNodeOut_a_valid;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :296:{29,46}]
  assign auto_master_out_a_bits_address = {refill_paddr[31:6], 6'h0};	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :127:31, :299:{31,48}]
  assign io_resp_valid = s2_valid & s2_hit;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :119:25, :120:23, :294:29]
  assign io_resp_bits_data = s2_bankid ? {s2_way_mux[63:0], s2_way_mux[127:64]} : s2_way_mux;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, :274:26, :279:33, :280:33, :284:10, :285:12, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_perf_acquire = refill_fire;	// @[generators/boom/src/main/scala/v4/ifu/icache.scala:93:7, src/main/scala/chisel3/util/Decoupled.scala:51:35]
endmodule

