// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module PartiallyPortedRF_1(	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7]
  input         clock,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7]
  input         reset,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7]
  input         io_arb_read_reqs_0_valid,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input  [5:0]  io_arb_read_reqs_0_bits,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input         io_arb_read_reqs_1_valid,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input  [5:0]  io_arb_read_reqs_1_bits,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input         io_arb_read_reqs_2_valid,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input  [5:0]  io_arb_read_reqs_2_bits,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input         io_arb_read_reqs_3_valid,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input  [5:0]  io_arb_read_reqs_3_bits,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  output        io_arb_read_reqs_4_ready,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input         io_arb_read_reqs_4_valid,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input  [5:0]  io_arb_read_reqs_4_bits,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  output        io_arb_read_reqs_5_ready,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input         io_arb_read_reqs_5_valid,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input  [5:0]  io_arb_read_reqs_5_bits,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  output        io_arb_read_reqs_6_ready,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input         io_arb_read_reqs_6_valid,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input  [5:0]  io_arb_read_reqs_6_bits,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  output        io_arb_read_reqs_7_ready,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input         io_arb_read_reqs_7_valid,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input  [5:0]  io_arb_read_reqs_7_bits,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  output        io_arb_read_reqs_8_ready,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input         io_arb_read_reqs_8_valid,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input  [5:0]  io_arb_read_reqs_8_bits,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  output        io_arb_read_reqs_9_ready,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input         io_arb_read_reqs_9_valid,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input  [5:0]  io_arb_read_reqs_9_bits,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  output [63:0] io_rrd_read_resps_0,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  output [63:0] io_rrd_read_resps_1,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  output [63:0] io_rrd_read_resps_2,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  output [63:0] io_rrd_read_resps_3,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  output [63:0] io_rrd_read_resps_4,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  output [63:0] io_rrd_read_resps_5,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  output [63:0] io_rrd_read_resps_6,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  output [63:0] io_rrd_read_resps_7,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  output [63:0] io_rrd_read_resps_8,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  output [63:0] io_rrd_read_resps_9,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input         io_write_ports_0_valid,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input  [6:0]  io_write_ports_0_bits_addr,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input  [63:0] io_write_ports_0_bits_data,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input         io_write_ports_1_valid,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input  [6:0]  io_write_ports_1_bits_addr,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input  [63:0] io_write_ports_1_bits_data,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input         io_write_ports_2_valid,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input  [6:0]  io_write_ports_2_bits_addr,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input  [63:0] io_write_ports_2_bits_data,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input         io_write_ports_3_valid,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input  [6:0]  io_write_ports_3_bits_addr,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input  [63:0] io_write_ports_3_bits_data,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input         io_write_ports_4_valid,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input  [6:0]  io_write_ports_4_bits_addr,	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
  input  [63:0] io_write_ports_4_bits_data	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14]
);

  wire [63:0] _rf_io_rrd_read_resps_0;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:138:18]
  wire [63:0] _rf_io_rrd_read_resps_1;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:138:18]
  wire [63:0] _rf_io_rrd_read_resps_2;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:138:18]
  wire [63:0] _rf_io_rrd_read_resps_3;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:138:18]
  wire [63:0] _rf_io_rrd_read_resps_4;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:138:18]
  wire [63:0] _rf_io_rrd_read_resps_5;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:138:18]
  wire        use_port_6 = ~io_arb_read_reqs_0_valid & io_arb_read_reqs_1_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:45, :164:66]
  wire        _GEN = use_port_6 | io_arb_read_reqs_0_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:45, :163:33]
  wire        use_port_7 = ~use_port_6 & io_arb_read_reqs_1_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:45, :164:66]
  wire        _GEN_0 = use_port_7 | use_port_6;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:45, :165:32]
  wire        use_port_8 = ~_GEN_0 & io_arb_read_reqs_1_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,45}, :165:32]
  wire        _GEN_1 = use_port_8 | _GEN_0;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:45, :165:32]
  wire        use_port_9 = ~_GEN_1 & io_arb_read_reqs_1_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,45}, :165:32]
  wire        _GEN_2 = use_port_9 | _GEN_1;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:45, :165:32]
  wire        use_port_10 = ~_GEN_2 & io_arb_read_reqs_1_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,45}, :165:32]
  wire        _GEN_3 = use_port_10 | _GEN_2;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:45, :165:32]
  wire        use_port_11 = ~_GEN_3 & io_arb_read_reqs_1_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,45}, :165:32]
  wire        use_port_12 = ~_GEN & io_arb_read_reqs_2_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{29,45}, :163:33]
  wire        _GEN_4 = use_port_12 | _GEN;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:45, :163:33]
  wire        use_port_13 = ~use_port_12 & ~use_port_7 & io_arb_read_reqs_2_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,29,45}, :164:66]
  wire        _GEN_5 = use_port_13 | use_port_7;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire        _GEN_6 = use_port_13 | use_port_12;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :165:32]
  wire        use_port_14 = ~_GEN_6 & ~use_port_8 & io_arb_read_reqs_2_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,26,29,45}, :165:32]
  wire        _GEN_7 = use_port_14 | use_port_8;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire        _GEN_8 = use_port_14 | _GEN_6;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :165:32]
  wire        use_port_15 = ~_GEN_8 & ~use_port_9 & io_arb_read_reqs_2_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,26,29,45}, :165:32]
  wire        _GEN_9 = use_port_15 | use_port_9;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire        _GEN_10 = use_port_15 | _GEN_8;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :165:32]
  wire        use_port_16 = ~_GEN_10 & ~use_port_10 & io_arb_read_reqs_2_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,26,29,45}, :165:32]
  wire        _GEN_11 = use_port_16 | use_port_10;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire        _GEN_12 = use_port_16 | _GEN_10;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :165:32]
  wire        use_port_17 = ~_GEN_12 & ~use_port_11 & io_arb_read_reqs_2_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,26,29,45}, :165:32]
  wire        _GEN_13 = use_port_17 | use_port_11;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire [1:0]  _GEN_14 = {1'h0, io_arb_read_reqs_0_valid};	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:167:42]
  wire [1:0]  _GEN_15 = {1'h0, io_arb_read_reqs_1_valid};	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:167:42]
  wire        use_port_18 = ~_GEN_4 & io_arb_read_reqs_3_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{29,45}, :163:33]
  wire        _GEN_16 = use_port_18 | _GEN_4;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:45, :163:33]
  wire        use_port_19 = ~use_port_18 & ~_GEN_5 & io_arb_read_reqs_3_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,29,45}, :163:33, :164:66]
  wire        _GEN_17 = use_port_19 | _GEN_5;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire        _GEN_18 = use_port_19 | use_port_18;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :165:32]
  wire        use_port_20 = ~_GEN_18 & ~_GEN_7 & io_arb_read_reqs_3_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,26,29,45}, :163:33, :165:32]
  wire        _GEN_19 = use_port_20 | _GEN_7;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire        _GEN_20 = use_port_20 | _GEN_18;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :165:32]
  wire        use_port_21 = ~_GEN_20 & ~_GEN_9 & io_arb_read_reqs_3_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,26,29,45}, :163:33, :165:32]
  wire        _GEN_21 = use_port_21 | _GEN_9;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire        _GEN_22 = use_port_21 | _GEN_20;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :165:32]
  wire        use_port_22 = ~_GEN_22 & ~_GEN_11 & io_arb_read_reqs_3_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,26,29,45}, :163:33, :165:32]
  wire        _GEN_23 = use_port_22 | _GEN_11;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire        _GEN_24 = use_port_22 | _GEN_22;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :165:32]
  wire        use_port_23 = ~_GEN_24 & ~_GEN_13 & io_arb_read_reqs_3_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,26,29,45}, :163:33, :165:32]
  wire        _GEN_25 = use_port_23 | _GEN_13;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire [1:0]  _GEN_26 = {1'h0, io_arb_read_reqs_2_valid};	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:167:42]
  wire [1:0]  _io_arb_read_reqs_7_ready_T_1 = _GEN_15 + _GEN_26;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:167:42]
  wire        use_port_24 = ~_GEN_16 & io_arb_read_reqs_4_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{29,45}, :163:33]
  wire        _GEN_27 = use_port_24 | _GEN_16;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:45, :163:33]
  wire        use_port_25 = ~use_port_24 & ~_GEN_17 & io_arb_read_reqs_4_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,29,45}, :163:33, :164:66]
  wire        _GEN_28 = use_port_25 | _GEN_17;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire        _GEN_29 = use_port_25 | use_port_24;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :165:32]
  wire        use_port_26 = ~_GEN_29 & ~_GEN_19 & io_arb_read_reqs_4_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,26,29,45}, :163:33, :165:32]
  wire        _GEN_30 = use_port_26 | _GEN_19;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire        _GEN_31 = use_port_26 | _GEN_29;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :165:32]
  wire        use_port_27 = ~_GEN_31 & ~_GEN_21 & io_arb_read_reqs_4_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,26,29,45}, :163:33, :165:32]
  wire        _GEN_32 = use_port_27 | _GEN_21;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire        _GEN_33 = use_port_27 | _GEN_31;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :165:32]
  wire        use_port_28 = ~_GEN_33 & ~_GEN_23 & io_arb_read_reqs_4_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,26,29,45}, :163:33, :165:32]
  wire        _GEN_34 = use_port_28 | _GEN_23;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire        _GEN_35 = use_port_28 | _GEN_33;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :165:32]
  wire        use_port_29 = ~_GEN_35 & ~_GEN_25 & io_arb_read_reqs_4_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,26,29,45}, :163:33, :165:32]
  wire        _GEN_36 = use_port_29 | _GEN_25;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire [1:0]  _GEN_37 = {1'h0, io_arb_read_reqs_3_valid};	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:167:42]
  wire [2:0]  _GEN_38 = {1'h0, _GEN_14 + _GEN_15};	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:167:42]
  wire [2:0]  _GEN_39 = {1'h0, _GEN_26 + _GEN_37};	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:167:42]
  wire [2:0]  _io_arb_read_reqs_4_ready_T_5 = _GEN_38 + _GEN_39;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:167:42]
  wire        io_arb_read_reqs_4_ready_0 = _io_arb_read_reqs_4_ready_T_5[2:1] != 2'h3;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:167:{42,82}]
  wire        use_port_30 = ~_GEN_27 & io_arb_read_reqs_5_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{29,45}, :163:33]
  wire        _GEN_40 = use_port_30 | _GEN_27;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:45, :163:33]
  wire        use_port_31 = ~use_port_30 & ~_GEN_28 & io_arb_read_reqs_5_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,29,45}, :163:33, :164:66]
  wire        _GEN_41 = use_port_31 | _GEN_28;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire        _GEN_42 = use_port_31 | use_port_30;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :165:32]
  wire        use_port_32 = ~_GEN_42 & ~_GEN_30 & io_arb_read_reqs_5_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,26,29,45}, :163:33, :165:32]
  wire        _GEN_43 = use_port_32 | _GEN_30;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire        _GEN_44 = use_port_32 | _GEN_42;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :165:32]
  wire        use_port_33 = ~_GEN_44 & ~_GEN_32 & io_arb_read_reqs_5_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,26,29,45}, :163:33, :165:32]
  wire        _GEN_45 = use_port_33 | _GEN_32;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire        _GEN_46 = use_port_33 | _GEN_44;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :165:32]
  wire        use_port_34 = ~_GEN_46 & ~_GEN_34 & io_arb_read_reqs_5_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,26,29,45}, :163:33, :165:32]
  wire        _GEN_47 = use_port_34 | _GEN_34;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire        _GEN_48 = use_port_34 | _GEN_46;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :165:32]
  wire        use_port_35 = ~_GEN_48 & ~_GEN_36 & io_arb_read_reqs_5_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,26,29,45}, :163:33, :165:32]
  wire        _GEN_49 = use_port_35 | _GEN_36;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire [1:0]  _GEN_50 = {1'h0, io_arb_read_reqs_4_valid};	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:167:42]
  wire [1:0]  _io_arb_read_reqs_7_ready_T_5 = _GEN_37 + _GEN_50;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:167:42]
  wire [2:0]  _io_arb_read_reqs_5_ready_T_7 = _GEN_38 + {1'h0, _GEN_26 + _io_arb_read_reqs_7_ready_T_5};	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:167:42]
  wire        io_arb_read_reqs_5_ready_0 = _io_arb_read_reqs_5_ready_T_7[2:1] != 2'h3;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:167:{42,82}]
  wire        use_port_36 = ~_GEN_40 & io_arb_read_reqs_6_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{29,45}, :163:33]
  wire        _GEN_51 = use_port_36 | _GEN_40;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:45, :163:33]
  wire        use_port_37 = ~use_port_36 & ~_GEN_41 & io_arb_read_reqs_6_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,29,45}, :163:33, :164:66]
  wire        _GEN_52 = use_port_37 | _GEN_41;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire        _GEN_53 = use_port_37 | use_port_36;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :165:32]
  wire        use_port_38 = ~_GEN_53 & ~_GEN_43 & io_arb_read_reqs_6_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,26,29,45}, :163:33, :165:32]
  wire        _GEN_54 = use_port_38 | _GEN_43;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire        _GEN_55 = use_port_38 | _GEN_53;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :165:32]
  wire        use_port_39 = ~_GEN_55 & ~_GEN_45 & io_arb_read_reqs_6_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,26,29,45}, :163:33, :165:32]
  wire        _GEN_56 = use_port_39 | _GEN_45;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire        _GEN_57 = use_port_39 | _GEN_55;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :165:32]
  wire        use_port_40 = ~_GEN_57 & ~_GEN_47 & io_arb_read_reqs_6_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,26,29,45}, :163:33, :165:32]
  wire        _GEN_58 = use_port_40 | _GEN_47;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire        _GEN_59 = use_port_40 | _GEN_57;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :165:32]
  wire        use_port_41 = ~_GEN_59 & ~_GEN_49 & io_arb_read_reqs_6_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,26,29,45}, :163:33, :165:32]
  wire        _GEN_60 = use_port_41 | _GEN_49;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire [1:0]  _GEN_61 = {1'h0, io_arb_read_reqs_5_valid};	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:167:42]
  wire [1:0]  _io_arb_read_reqs_9_ready_T_7 = _GEN_50 + _GEN_61;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:167:42]
  wire [2:0]  _GEN_62 = {1'h0, _io_arb_read_reqs_9_ready_T_7};	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:167:42]
  wire [2:0]  _io_arb_read_reqs_6_ready_T_9 = {1'h0, _GEN_14 + _io_arb_read_reqs_7_ready_T_1} + {1'h0, _GEN_37 + _io_arb_read_reqs_9_ready_T_7};	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:167:42]
  wire        io_arb_read_reqs_6_ready_0 = _io_arb_read_reqs_6_ready_T_9[2:1] != 2'h3;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:167:{42,82}]
  wire        use_port_42 = ~_GEN_51 & io_arb_read_reqs_7_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{29,45}, :163:33]
  wire        _GEN_63 = use_port_42 | _GEN_51;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:45, :163:33]
  wire        use_port_43 = ~use_port_42 & ~_GEN_52 & io_arb_read_reqs_7_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,29,45}, :163:33, :164:66]
  wire        _GEN_64 = use_port_43 | _GEN_52;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire        _GEN_65 = use_port_43 | use_port_42;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :165:32]
  wire        use_port_44 = ~_GEN_65 & ~_GEN_54 & io_arb_read_reqs_7_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,26,29,45}, :163:33, :165:32]
  wire        _GEN_66 = use_port_44 | _GEN_54;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire        _GEN_67 = use_port_44 | _GEN_65;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :165:32]
  wire        use_port_45 = ~_GEN_67 & ~_GEN_56 & io_arb_read_reqs_7_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,26,29,45}, :163:33, :165:32]
  wire        _GEN_68 = use_port_45 | _GEN_56;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire        _GEN_69 = use_port_45 | _GEN_67;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :165:32]
  wire        use_port_46 = ~_GEN_69 & ~_GEN_58 & io_arb_read_reqs_7_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,26,29,45}, :163:33, :165:32]
  wire        _GEN_70 = use_port_46 | _GEN_58;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire        _GEN_71 = use_port_46 | _GEN_69;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :165:32]
  wire        use_port_47 = ~_GEN_71 & ~_GEN_60 & io_arb_read_reqs_7_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,26,29,45}, :163:33, :165:32]
  wire        _GEN_72 = use_port_47 | _GEN_60;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire [1:0]  _GEN_73 = {1'h0, io_arb_read_reqs_6_valid};	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:167:42]
  wire [2:0]  _io_arb_read_reqs_7_ready_T_10 = {1'h0, _GEN_14 + _io_arb_read_reqs_7_ready_T_1} + {1'h0, _io_arb_read_reqs_7_ready_T_5} + {1'h0, _GEN_61 + _GEN_73};	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:167:42]
  wire        io_arb_read_reqs_7_ready_0 = _io_arb_read_reqs_7_ready_T_10[2:1] != 2'h3;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:167:{42,82}]
  wire        use_port_48 = ~_GEN_63 & io_arb_read_reqs_8_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{29,45}, :163:33]
  wire        _GEN_74 = use_port_48 | _GEN_63;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:45, :163:33]
  wire        use_port_49 = ~use_port_48 & ~_GEN_64 & io_arb_read_reqs_8_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,29,45}, :163:33, :164:66]
  wire        _GEN_75 = use_port_49 | _GEN_64;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire        _GEN_76 = use_port_49 | use_port_48;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :165:32]
  wire        use_port_50 = ~_GEN_76 & ~_GEN_66 & io_arb_read_reqs_8_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,26,29,45}, :163:33, :165:32]
  wire        _GEN_77 = use_port_50 | _GEN_66;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire        _GEN_78 = use_port_50 | _GEN_76;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :165:32]
  wire        use_port_51 = ~_GEN_78 & ~_GEN_68 & io_arb_read_reqs_8_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,26,29,45}, :163:33, :165:32]
  wire        _GEN_79 = use_port_51 | _GEN_68;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire        _GEN_80 = use_port_51 | _GEN_78;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :165:32]
  wire        use_port_52 = ~_GEN_80 & ~_GEN_70 & io_arb_read_reqs_8_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,26,29,45}, :163:33, :165:32]
  wire        _GEN_81 = use_port_52 | _GEN_70;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire        _GEN_82 = use_port_52 | _GEN_80;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :165:32]
  wire        use_port_53 = ~_GEN_82 & ~_GEN_72 & io_arb_read_reqs_8_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,26,29,45}, :163:33, :165:32]
  wire        _GEN_83 = use_port_53 | _GEN_72;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33]
  wire [1:0]  _GEN_84 = {1'h0, io_arb_read_reqs_7_valid};	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:167:42]
  wire        io_arb_read_reqs_8_ready_0 = {1'h0, _GEN_38 + _GEN_39} + {1'h0, _GEN_62 + {1'h0, _GEN_73 + _GEN_84}} < 4'h6;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:167:{42,82}]
  wire        use_port_54 = ~_GEN_74 & io_arb_read_reqs_9_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{29,45}, :163:33]
  wire        use_port_55 = ~use_port_54 & ~_GEN_75 & io_arb_read_reqs_9_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,29,45}, :163:33, :164:66]
  wire        _GEN_85 = use_port_55 | use_port_54;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :165:32]
  wire        use_port_56 = ~_GEN_85 & ~_GEN_77 & io_arb_read_reqs_9_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,26,29,45}, :163:33, :165:32]
  wire        _GEN_86 = use_port_56 | _GEN_85;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :165:32]
  wire        use_port_57 = ~_GEN_86 & ~_GEN_79 & io_arb_read_reqs_9_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,26,29,45}, :163:33, :165:32]
  wire        _GEN_87 = use_port_57 | _GEN_86;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :165:32]
  wire        use_port_58 = ~_GEN_87 & ~_GEN_81 & io_arb_read_reqs_9_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,26,29,45}, :163:33, :165:32]
  wire        _GEN_88 = use_port_58 | _GEN_87;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :165:32]
  wire        use_port_59 = ~_GEN_88 & ~_GEN_83 & io_arb_read_reqs_9_valid;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,26,29,45}, :163:33, :165:32]
  wire        io_arb_read_reqs_9_ready_0 = {1'h0, _GEN_38 + _GEN_39} + {1'h0, _GEN_62 + {1'h0, _GEN_73 + _GEN_84 + {1'h0, io_arb_read_reqs_8_valid}}} < 4'h6;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:167:{42,82}]
  `ifndef SYNTHESIS	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
    always @(posedge clock) begin	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
      if (~reset & ~(~io_write_ports_0_valid | ~io_write_ports_1_valid | io_write_ports_0_bits_addr != io_write_ports_1_bits_addr)) begin	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:{15,16,41}, :46:{16,41}, :47:45]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
          $error("Assertion failed: [regfile] too many writers a register\n    at regfile.scala:45 assert(!io.write_ports(i).valid ||\n");	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
          $fatal;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
      end
      if (~reset & ~(~io_write_ports_0_valid | ~io_write_ports_2_valid | io_write_ports_0_bits_addr != io_write_ports_2_bits_addr)) begin	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:{15,16,41}, :46:{16,41}, :47:45]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
          $error("Assertion failed: [regfile] too many writers a register\n    at regfile.scala:45 assert(!io.write_ports(i).valid ||\n");	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
          $fatal;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
      end
      if (~reset & ~(~io_write_ports_0_valid | ~io_write_ports_3_valid | io_write_ports_0_bits_addr != io_write_ports_3_bits_addr)) begin	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:{15,16,41}, :46:{16,41}, :47:45]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
          $error("Assertion failed: [regfile] too many writers a register\n    at regfile.scala:45 assert(!io.write_ports(i).valid ||\n");	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
          $fatal;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
      end
      if (~reset & ~(~io_write_ports_0_valid | ~io_write_ports_4_valid | io_write_ports_0_bits_addr != io_write_ports_4_bits_addr)) begin	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:{15,16,41}, :46:{16,41}, :47:45]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
          $error("Assertion failed: [regfile] too many writers a register\n    at regfile.scala:45 assert(!io.write_ports(i).valid ||\n");	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
          $fatal;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
      end
      if (~reset & ~(~io_write_ports_1_valid | ~io_write_ports_2_valid | io_write_ports_1_bits_addr != io_write_ports_2_bits_addr)) begin	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:{15,41}, :46:{16,41}, :47:45]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
          $error("Assertion failed: [regfile] too many writers a register\n    at regfile.scala:45 assert(!io.write_ports(i).valid ||\n");	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
          $fatal;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
      end
      if (~reset & ~(~io_write_ports_1_valid | ~io_write_ports_3_valid | io_write_ports_1_bits_addr != io_write_ports_3_bits_addr)) begin	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:{15,41}, :46:{16,41}, :47:45]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
          $error("Assertion failed: [regfile] too many writers a register\n    at regfile.scala:45 assert(!io.write_ports(i).valid ||\n");	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
          $fatal;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
      end
      if (~reset & ~(~io_write_ports_1_valid | ~io_write_ports_4_valid | io_write_ports_1_bits_addr != io_write_ports_4_bits_addr)) begin	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:{15,41}, :46:{16,41}, :47:45]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
          $error("Assertion failed: [regfile] too many writers a register\n    at regfile.scala:45 assert(!io.write_ports(i).valid ||\n");	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
          $fatal;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
      end
      if (~reset & ~(~io_write_ports_2_valid | ~io_write_ports_3_valid | io_write_ports_2_bits_addr != io_write_ports_3_bits_addr)) begin	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:{15,41}, :46:{16,41}, :47:45]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
          $error("Assertion failed: [regfile] too many writers a register\n    at regfile.scala:45 assert(!io.write_ports(i).valid ||\n");	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
          $fatal;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
      end
      if (~reset & ~(~io_write_ports_2_valid | ~io_write_ports_4_valid | io_write_ports_2_bits_addr != io_write_ports_4_bits_addr)) begin	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:{15,41}, :46:{16,41}, :47:45]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
          $error("Assertion failed: [regfile] too many writers a register\n    at regfile.scala:45 assert(!io.write_ports(i).valid ||\n");	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
          $fatal;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
      end
      if (~reset & ~(~io_write_ports_3_valid | ~io_write_ports_4_valid | io_write_ports_3_bits_addr != io_write_ports_4_bits_addr)) begin	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:{15,41}, :46:{16,41}, :47:45]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
          $error("Assertion failed: [regfile] too many writers a register\n    at regfile.scala:45 assert(!io.write_ports(i).valid ||\n");	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
          $fatal;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15]
      end
      if (~reset & io_arb_read_reqs_1_valid & ~(use_port_11 | _GEN_3)) begin	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15, :157:45, :165:32, :168:{11,39,42}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
          $error("Assertion failed\n    at regfile.scala:168 assert(!(io.arb_read_reqs(i).fire && !read_issued))\n");	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
          $fatal;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
      end
      if (~reset & io_arb_read_reqs_2_valid & ~(use_port_17 | _GEN_12)) begin	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15, :157:{26,45}, :165:32, :168:{11,39,42}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
          $error("Assertion failed\n    at regfile.scala:168 assert(!(io.arb_read_reqs(i).fire && !read_issued))\n");	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
          $fatal;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
      end
      if (~reset & io_arb_read_reqs_3_valid & ~(use_port_23 | _GEN_24)) begin	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15, :157:{26,45}, :165:32, :168:{11,39,42}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
          $error("Assertion failed\n    at regfile.scala:168 assert(!(io.arb_read_reqs(i).fire && !read_issued))\n");	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
          $fatal;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
      end
      if (~reset & io_arb_read_reqs_4_ready_0 & io_arb_read_reqs_4_valid & ~(use_port_29 | _GEN_35)) begin	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15, :157:{26,45}, :165:32, :167:82, :168:{11,39,42}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
          $error("Assertion failed\n    at regfile.scala:168 assert(!(io.arb_read_reqs(i).fire && !read_issued))\n");	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
          $fatal;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
      end
      if (~reset & io_arb_read_reqs_5_ready_0 & io_arb_read_reqs_5_valid & ~(use_port_35 | _GEN_48)) begin	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15, :157:{26,45}, :165:32, :167:82, :168:{11,39,42}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
          $error("Assertion failed\n    at regfile.scala:168 assert(!(io.arb_read_reqs(i).fire && !read_issued))\n");	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
          $fatal;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
      end
      if (~reset & io_arb_read_reqs_6_ready_0 & io_arb_read_reqs_6_valid & ~(use_port_41 | _GEN_59)) begin	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15, :157:{26,45}, :165:32, :167:82, :168:{11,39,42}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
          $error("Assertion failed\n    at regfile.scala:168 assert(!(io.arb_read_reqs(i).fire && !read_issued))\n");	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
          $fatal;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
      end
      if (~reset & io_arb_read_reqs_7_ready_0 & io_arb_read_reqs_7_valid & ~(use_port_47 | _GEN_71)) begin	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15, :157:{26,45}, :165:32, :167:82, :168:{11,39,42}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
          $error("Assertion failed\n    at regfile.scala:168 assert(!(io.arb_read_reqs(i).fire && !read_issued))\n");	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
          $fatal;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
      end
      if (~reset & io_arb_read_reqs_8_ready_0 & io_arb_read_reqs_8_valid & ~(use_port_53 | _GEN_82)) begin	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15, :157:{26,45}, :165:32, :167:82, :168:{11,39,42}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
          $error("Assertion failed\n    at regfile.scala:168 assert(!(io.arb_read_reqs(i).fire && !read_issued))\n");	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
          $fatal;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
      end
      if (~reset & io_arb_read_reqs_9_ready_0 & io_arb_read_reqs_9_valid & ~(use_port_59 | _GEN_88)) begin	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15, :157:{26,45}, :165:32, :167:82, :168:{11,39,42}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
          $error("Assertion failed\n    at regfile.scala:168 assert(!(io.arb_read_reqs(i).fire && !read_issued))\n");	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
          $fatal;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  reg  [5:0]  rrd_data_sels_0;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:177:30]
  reg  [5:0]  rrd_data_sels_1;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:177:30]
  reg  [5:0]  rrd_data_sels_2;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:177:30]
  reg  [5:0]  rrd_data_sels_3;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:177:30]
  reg  [5:0]  rrd_data_sels_4;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:177:30]
  reg  [5:0]  rrd_data_sels_5;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:177:30]
  reg  [5:0]  rrd_data_sels_6;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:177:30]
  reg  [5:0]  rrd_data_sels_7;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:177:30]
  reg  [5:0]  rrd_data_sels_8;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:177:30]
  reg  [5:0]  rrd_data_sels_9;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:177:30]
  always @(posedge clock) begin	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7]
    rrd_data_sels_0 <= 6'h1;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:177:30]
    rrd_data_sels_1 <= use_port_11 ? 6'h20 : use_port_10 ? 6'h10 : use_port_9 ? 6'h8 : use_port_8 ? 6'h4 : use_port_7 ? 6'h2 : 6'h1;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{45,75}, :160:22, :177:30]
    rrd_data_sels_2 <= use_port_17 ? 6'h20 : use_port_16 ? 6'h10 : use_port_15 ? 6'h8 : use_port_14 ? 6'h4 : use_port_13 ? 6'h2 : 6'h1;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45,75}, :160:22, :177:30]
    rrd_data_sels_3 <= use_port_23 ? 6'h20 : use_port_22 ? 6'h10 : use_port_21 ? 6'h8 : use_port_20 ? 6'h4 : use_port_19 ? 6'h2 : 6'h1;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45,75}, :160:22, :177:30]
    rrd_data_sels_4 <= use_port_29 ? 6'h20 : use_port_28 ? 6'h10 : use_port_27 ? 6'h8 : use_port_26 ? 6'h4 : use_port_25 ? 6'h2 : 6'h1;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45,75}, :160:22, :177:30]
    rrd_data_sels_5 <= use_port_35 ? 6'h20 : use_port_34 ? 6'h10 : use_port_33 ? 6'h8 : use_port_32 ? 6'h4 : use_port_31 ? 6'h2 : 6'h1;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45,75}, :160:22, :177:30]
    rrd_data_sels_6 <= use_port_41 ? 6'h20 : use_port_40 ? 6'h10 : use_port_39 ? 6'h8 : use_port_38 ? 6'h4 : use_port_37 ? 6'h2 : 6'h1;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45,75}, :160:22, :177:30]
    rrd_data_sels_7 <= use_port_47 ? 6'h20 : use_port_46 ? 6'h10 : use_port_45 ? 6'h8 : use_port_44 ? 6'h4 : use_port_43 ? 6'h2 : 6'h1;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45,75}, :160:22, :177:30]
    rrd_data_sels_8 <= use_port_53 ? 6'h20 : use_port_52 ? 6'h10 : use_port_51 ? 6'h8 : use_port_50 ? 6'h4 : use_port_49 ? 6'h2 : 6'h1;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45,75}, :160:22, :177:30]
    rrd_data_sels_9 <= use_port_59 ? 6'h20 : use_port_58 ? 6'h10 : use_port_57 ? 6'h8 : use_port_56 ? 6'h4 : use_port_55 ? 6'h2 : 6'h1;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45,75}, :160:22, :177:30]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:1];	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7]
    initial begin	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7]
        `INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7]
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7]
        end	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7]
        rrd_data_sels_0 = _RANDOM[1'h0][5:0];	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :177:30]
        rrd_data_sels_1 = _RANDOM[1'h0][11:6];	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :177:30]
        rrd_data_sels_2 = _RANDOM[1'h0][17:12];	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :177:30]
        rrd_data_sels_3 = _RANDOM[1'h0][23:18];	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :177:30]
        rrd_data_sels_4 = _RANDOM[1'h0][29:24];	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :177:30]
        rrd_data_sels_5 = {_RANDOM[1'h0][31:30], _RANDOM[1'h1][3:0]};	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :177:30]
        rrd_data_sels_6 = _RANDOM[1'h1][9:4];	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :177:30]
        rrd_data_sels_7 = _RANDOM[1'h1][15:10];	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :177:30]
        rrd_data_sels_8 = _RANDOM[1'h1][21:16];	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :177:30]
        rrd_data_sels_9 = _RANDOM[1'h1][27:22];	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :177:30]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  FullyPortedRF_1 rf (	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:138:18]
    .clock                      (clock),
    .reset                      (reset),
    .io_arb_read_reqs_0_bits    ((io_arb_read_reqs_0_valid ? io_arb_read_reqs_0_bits : 6'h0) | (io_arb_read_reqs_0_valid | ~use_port_6 ? 6'h0 : io_arb_read_reqs_1_bits) | (_GEN | ~use_port_12 ? 6'h0 : io_arb_read_reqs_2_bits) | (_GEN_4 | ~use_port_18 ? 6'h0 : io_arb_read_reqs_3_bits) | (_GEN_16 | ~use_port_24 ? 6'h0 : io_arb_read_reqs_4_bits) | (_GEN_27 | ~use_port_30 ? 6'h0 : io_arb_read_reqs_5_bits) | (_GEN_40 | ~use_port_36 ? 6'h0 : io_arb_read_reqs_6_bits) | (_GEN_51 | ~use_port_42 ? 6'h0 : io_arb_read_reqs_7_bits) | (_GEN_63 | ~use_port_48 ? 6'h0 : io_arb_read_reqs_8_bits) | (_GEN_74 | ~use_port_54 ? 6'h0 : io_arb_read_reqs_9_bits)),	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:45, :163:33, :164:{37,42,63,66}]
    .io_arb_read_reqs_1_bits    ((use_port_7 ? io_arb_read_reqs_1_bits : 6'h0) | (use_port_7 | ~use_port_13 ? 6'h0 : io_arb_read_reqs_2_bits) | (_GEN_5 | ~use_port_19 ? 6'h0 : io_arb_read_reqs_3_bits) | (_GEN_17 | ~use_port_25 ? 6'h0 : io_arb_read_reqs_4_bits) | (_GEN_28 | ~use_port_31 ? 6'h0 : io_arb_read_reqs_5_bits) | (_GEN_41 | ~use_port_37 ? 6'h0 : io_arb_read_reqs_6_bits) | (_GEN_52 | ~use_port_43 ? 6'h0 : io_arb_read_reqs_7_bits) | (_GEN_64 | ~use_port_49 ? 6'h0 : io_arb_read_reqs_8_bits) | (_GEN_75 | ~use_port_55 ? 6'h0 : io_arb_read_reqs_9_bits)),	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33, :164:{37,42,63,66}]
    .io_arb_read_reqs_2_bits    ((use_port_8 ? io_arb_read_reqs_1_bits : 6'h0) | (use_port_8 | ~use_port_14 ? 6'h0 : io_arb_read_reqs_2_bits) | (_GEN_7 | ~use_port_20 ? 6'h0 : io_arb_read_reqs_3_bits) | (_GEN_19 | ~use_port_26 ? 6'h0 : io_arb_read_reqs_4_bits) | (_GEN_30 | ~use_port_32 ? 6'h0 : io_arb_read_reqs_5_bits) | (_GEN_43 | ~use_port_38 ? 6'h0 : io_arb_read_reqs_6_bits) | (_GEN_54 | ~use_port_44 ? 6'h0 : io_arb_read_reqs_7_bits) | (_GEN_66 | ~use_port_50 ? 6'h0 : io_arb_read_reqs_8_bits) | (_GEN_77 | ~use_port_56 ? 6'h0 : io_arb_read_reqs_9_bits)),	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33, :164:{37,42,63,66}]
    .io_arb_read_reqs_3_bits    ((use_port_9 ? io_arb_read_reqs_1_bits : 6'h0) | (use_port_9 | ~use_port_15 ? 6'h0 : io_arb_read_reqs_2_bits) | (_GEN_9 | ~use_port_21 ? 6'h0 : io_arb_read_reqs_3_bits) | (_GEN_21 | ~use_port_27 ? 6'h0 : io_arb_read_reqs_4_bits) | (_GEN_32 | ~use_port_33 ? 6'h0 : io_arb_read_reqs_5_bits) | (_GEN_45 | ~use_port_39 ? 6'h0 : io_arb_read_reqs_6_bits) | (_GEN_56 | ~use_port_45 ? 6'h0 : io_arb_read_reqs_7_bits) | (_GEN_68 | ~use_port_51 ? 6'h0 : io_arb_read_reqs_8_bits) | (_GEN_79 | ~use_port_57 ? 6'h0 : io_arb_read_reqs_9_bits)),	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33, :164:{37,42,63,66}]
    .io_arb_read_reqs_4_bits    ((use_port_10 ? io_arb_read_reqs_1_bits : 6'h0) | (use_port_10 | ~use_port_16 ? 6'h0 : io_arb_read_reqs_2_bits) | (_GEN_11 | ~use_port_22 ? 6'h0 : io_arb_read_reqs_3_bits) | (_GEN_23 | ~use_port_28 ? 6'h0 : io_arb_read_reqs_4_bits) | (_GEN_34 | ~use_port_34 ? 6'h0 : io_arb_read_reqs_5_bits) | (_GEN_47 | ~use_port_40 ? 6'h0 : io_arb_read_reqs_6_bits) | (_GEN_58 | ~use_port_46 ? 6'h0 : io_arb_read_reqs_7_bits) | (_GEN_70 | ~use_port_52 ? 6'h0 : io_arb_read_reqs_8_bits) | (_GEN_81 | ~use_port_58 ? 6'h0 : io_arb_read_reqs_9_bits)),	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33, :164:{37,42,63,66}]
    .io_arb_read_reqs_5_bits    ((use_port_11 ? io_arb_read_reqs_1_bits : 6'h0) | (use_port_11 | ~use_port_17 ? 6'h0 : io_arb_read_reqs_2_bits) | (_GEN_13 | ~use_port_23 ? 6'h0 : io_arb_read_reqs_3_bits) | (_GEN_25 | ~use_port_29 ? 6'h0 : io_arb_read_reqs_4_bits) | (_GEN_36 | ~use_port_35 ? 6'h0 : io_arb_read_reqs_5_bits) | (_GEN_49 | ~use_port_41 ? 6'h0 : io_arb_read_reqs_6_bits) | (_GEN_60 | ~use_port_47 ? 6'h0 : io_arb_read_reqs_7_bits) | (_GEN_72 | ~use_port_53 ? 6'h0 : io_arb_read_reqs_8_bits) | (_GEN_83 | ~use_port_59 ? 6'h0 : io_arb_read_reqs_9_bits)),	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{26,45}, :163:33, :164:{37,42,63,66}]
    .io_rrd_read_resps_0        (_rf_io_rrd_read_resps_0),
    .io_rrd_read_resps_1        (_rf_io_rrd_read_resps_1),
    .io_rrd_read_resps_2        (_rf_io_rrd_read_resps_2),
    .io_rrd_read_resps_3        (_rf_io_rrd_read_resps_3),
    .io_rrd_read_resps_4        (_rf_io_rrd_read_resps_4),
    .io_rrd_read_resps_5        (_rf_io_rrd_read_resps_5),
    .io_write_ports_0_valid     (io_write_ports_0_valid),
    .io_write_ports_0_bits_addr (io_write_ports_0_bits_addr),
    .io_write_ports_0_bits_data (io_write_ports_0_bits_data),
    .io_write_ports_1_valid     (io_write_ports_1_valid),
    .io_write_ports_1_bits_addr (io_write_ports_1_bits_addr),
    .io_write_ports_1_bits_data (io_write_ports_1_bits_data),
    .io_write_ports_2_valid     (io_write_ports_2_valid),
    .io_write_ports_2_bits_addr (io_write_ports_2_bits_addr),
    .io_write_ports_2_bits_data (io_write_ports_2_bits_data),
    .io_write_ports_3_valid     (io_write_ports_3_valid),
    .io_write_ports_3_bits_addr (io_write_ports_3_bits_addr),
    .io_write_ports_3_bits_data (io_write_ports_3_bits_data),
    .io_write_ports_4_valid     (io_write_ports_4_valid),
    .io_write_ports_4_bits_addr (io_write_ports_4_bits_addr),
    .io_write_ports_4_bits_data (io_write_ports_4_bits_data)
  );	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:138:18]
  assign io_arb_read_reqs_4_ready = io_arb_read_reqs_4_ready_0;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :167:82]
  assign io_arb_read_reqs_5_ready = io_arb_read_reqs_5_ready_0;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :167:82]
  assign io_arb_read_reqs_6_ready = io_arb_read_reqs_6_ready_0;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :167:82]
  assign io_arb_read_reqs_7_ready = io_arb_read_reqs_7_ready_0;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :167:82]
  assign io_arb_read_reqs_8_ready = io_arb_read_reqs_8_ready_0;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :167:82]
  assign io_arb_read_reqs_9_ready = io_arb_read_reqs_9_ready_0;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :167:82]
  assign io_rrd_read_resps_0 = (rrd_data_sels_0[0] ? _rf_io_rrd_read_resps_0 : 64'h0) | (rrd_data_sels_0[1] ? _rf_io_rrd_read_resps_1 : 64'h0) | (rrd_data_sels_0[2] ? _rf_io_rrd_read_resps_2 : 64'h0) | (rrd_data_sels_0[3] ? _rf_io_rrd_read_resps_3 : 64'h0) | (rrd_data_sels_0[4] ? _rf_io_rrd_read_resps_4 : 64'h0) | (rrd_data_sels_0[5] ? _rf_io_rrd_read_resps_5 : 64'h0);	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :138:18, :177:30, :180:52, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_rrd_read_resps_1 = (rrd_data_sels_1[0] ? _rf_io_rrd_read_resps_0 : 64'h0) | (rrd_data_sels_1[1] ? _rf_io_rrd_read_resps_1 : 64'h0) | (rrd_data_sels_1[2] ? _rf_io_rrd_read_resps_2 : 64'h0) | (rrd_data_sels_1[3] ? _rf_io_rrd_read_resps_3 : 64'h0) | (rrd_data_sels_1[4] ? _rf_io_rrd_read_resps_4 : 64'h0) | (rrd_data_sels_1[5] ? _rf_io_rrd_read_resps_5 : 64'h0);	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :138:18, :177:30, :180:52, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_rrd_read_resps_2 = (rrd_data_sels_2[0] ? _rf_io_rrd_read_resps_0 : 64'h0) | (rrd_data_sels_2[1] ? _rf_io_rrd_read_resps_1 : 64'h0) | (rrd_data_sels_2[2] ? _rf_io_rrd_read_resps_2 : 64'h0) | (rrd_data_sels_2[3] ? _rf_io_rrd_read_resps_3 : 64'h0) | (rrd_data_sels_2[4] ? _rf_io_rrd_read_resps_4 : 64'h0) | (rrd_data_sels_2[5] ? _rf_io_rrd_read_resps_5 : 64'h0);	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :138:18, :177:30, :180:52, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_rrd_read_resps_3 = (rrd_data_sels_3[0] ? _rf_io_rrd_read_resps_0 : 64'h0) | (rrd_data_sels_3[1] ? _rf_io_rrd_read_resps_1 : 64'h0) | (rrd_data_sels_3[2] ? _rf_io_rrd_read_resps_2 : 64'h0) | (rrd_data_sels_3[3] ? _rf_io_rrd_read_resps_3 : 64'h0) | (rrd_data_sels_3[4] ? _rf_io_rrd_read_resps_4 : 64'h0) | (rrd_data_sels_3[5] ? _rf_io_rrd_read_resps_5 : 64'h0);	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :138:18, :177:30, :180:52, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_rrd_read_resps_4 = (rrd_data_sels_4[0] ? _rf_io_rrd_read_resps_0 : 64'h0) | (rrd_data_sels_4[1] ? _rf_io_rrd_read_resps_1 : 64'h0) | (rrd_data_sels_4[2] ? _rf_io_rrd_read_resps_2 : 64'h0) | (rrd_data_sels_4[3] ? _rf_io_rrd_read_resps_3 : 64'h0) | (rrd_data_sels_4[4] ? _rf_io_rrd_read_resps_4 : 64'h0) | (rrd_data_sels_4[5] ? _rf_io_rrd_read_resps_5 : 64'h0);	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :138:18, :177:30, :180:52, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_rrd_read_resps_5 = (rrd_data_sels_5[0] ? _rf_io_rrd_read_resps_0 : 64'h0) | (rrd_data_sels_5[1] ? _rf_io_rrd_read_resps_1 : 64'h0) | (rrd_data_sels_5[2] ? _rf_io_rrd_read_resps_2 : 64'h0) | (rrd_data_sels_5[3] ? _rf_io_rrd_read_resps_3 : 64'h0) | (rrd_data_sels_5[4] ? _rf_io_rrd_read_resps_4 : 64'h0) | (rrd_data_sels_5[5] ? _rf_io_rrd_read_resps_5 : 64'h0);	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :138:18, :177:30, :180:52, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_rrd_read_resps_6 = (rrd_data_sels_6[0] ? _rf_io_rrd_read_resps_0 : 64'h0) | (rrd_data_sels_6[1] ? _rf_io_rrd_read_resps_1 : 64'h0) | (rrd_data_sels_6[2] ? _rf_io_rrd_read_resps_2 : 64'h0) | (rrd_data_sels_6[3] ? _rf_io_rrd_read_resps_3 : 64'h0) | (rrd_data_sels_6[4] ? _rf_io_rrd_read_resps_4 : 64'h0) | (rrd_data_sels_6[5] ? _rf_io_rrd_read_resps_5 : 64'h0);	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :138:18, :177:30, :180:52, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_rrd_read_resps_7 = (rrd_data_sels_7[0] ? _rf_io_rrd_read_resps_0 : 64'h0) | (rrd_data_sels_7[1] ? _rf_io_rrd_read_resps_1 : 64'h0) | (rrd_data_sels_7[2] ? _rf_io_rrd_read_resps_2 : 64'h0) | (rrd_data_sels_7[3] ? _rf_io_rrd_read_resps_3 : 64'h0) | (rrd_data_sels_7[4] ? _rf_io_rrd_read_resps_4 : 64'h0) | (rrd_data_sels_7[5] ? _rf_io_rrd_read_resps_5 : 64'h0);	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :138:18, :177:30, :180:52, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_rrd_read_resps_8 = (rrd_data_sels_8[0] ? _rf_io_rrd_read_resps_0 : 64'h0) | (rrd_data_sels_8[1] ? _rf_io_rrd_read_resps_1 : 64'h0) | (rrd_data_sels_8[2] ? _rf_io_rrd_read_resps_2 : 64'h0) | (rrd_data_sels_8[3] ? _rf_io_rrd_read_resps_3 : 64'h0) | (rrd_data_sels_8[4] ? _rf_io_rrd_read_resps_4 : 64'h0) | (rrd_data_sels_8[5] ? _rf_io_rrd_read_resps_5 : 64'h0);	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :138:18, :177:30, :180:52, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_rrd_read_resps_9 = (rrd_data_sels_9[0] ? _rf_io_rrd_read_resps_0 : 64'h0) | (rrd_data_sels_9[1] ? _rf_io_rrd_read_resps_1 : 64'h0) | (rrd_data_sels_9[2] ? _rf_io_rrd_read_resps_2 : 64'h0) | (rrd_data_sels_9[3] ? _rf_io_rrd_read_resps_3 : 64'h0) | (rrd_data_sels_9[4] ? _rf_io_rrd_read_resps_4 : 64'h0) | (rrd_data_sels_9[5] ? _rf_io_rrd_read_resps_5 : 64'h0);	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :138:18, :177:30, :180:52, src/main/scala/chisel3/util/Mux.scala:30:73]
endmodule

