name cc_dir_ext depth 1024 width 136 ports mrw mask_gran 17 
name cc_banks_0_ext depth 8192 width 64 ports rw 
name tag_array_ext depth 64 width 176 ports mrw mask_gran 22 
name array_0_0_ext depth 256 width 128 ports mwrite,read mask_gran 64 
name tag_array_0_ext depth 64 width 160 ports mrw mask_gran 20 
name dataArrayB0_ext depth 256 width 512 ports mrw mask_gran 64 
name tage_u_2_ext depth 128 width 8 ports mwrite,read mask_gran 1 
name tage_table_2_ext depth 128 width 44 ports mwrite,read mask_gran 11 
name tage_u_8_ext depth 256 width 8 ports mwrite,read mask_gran 1 
name tage_table_8_ext depth 256 width 48 ports mwrite,read mask_gran 12 
name tage_table_32_ext depth 128 width 52 ports mwrite,read mask_gran 13 
name btb_meta_way_0_ext depth 128 width 120 ports mwrite,read mask_gran 30 
name btb_data_way_0_ext depth 128 width 56 ports mwrite,read mask_gran 14 
name btb_ebtb_ext depth 128 width 40 ports write,read 
name bim_col_0_ext depth 256 width 8 ports mrw mask_gran 2 
name meta_ext depth 32 width 240 ports write,read 
name ghist_0_ext depth 32 width 72 ports write,read 
name rob_compact_uop_mem_ext depth 32 width 90 ports mwrite,read mask_gran 30 
name l2_tlb_ram_0_ext depth 512 width 45 ports rw 
name mem_ext depth 8192 width 64 ports mrw mask_gran 8 
