// Generated by CIRCT firtool-1.75.0
// VCS coverage exclude_file
module regfile_12x10(	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:204:20]
  input  [3:0] R0_addr,
  input        R0_en,
  input        R0_clk,
  output [9:0] R0_data,
  input  [3:0] R1_addr,
  input        R1_en,
  input        R1_clk,
  output [9:0] R1_data,
  input  [3:0] W0_addr,
  input        W0_en,
  input        W0_clk,
  input  [9:0] W0_data,
  input  [3:0] W1_addr,
  input        W1_en,
  input        W1_clk,
  input  [9:0] W1_data
);

  reg [9:0] Memory[0:11];	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:204:20]
  always @(posedge W0_clk) begin	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:204:20]
    if (W0_en & 1'h1)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:204:20]
      Memory[W0_addr] <= W0_data;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:204:20]
    if (W1_en & 1'h1)	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:204:20]
      Memory[W1_addr] <= W1_data;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:204:20]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:204:20]
    reg [31:0] _RANDOM_MEM;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:204:20]
    initial begin	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:204:20]
      `INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:204:20]
      `ifdef RANDOMIZE_MEM_INIT	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:204:20]
        for (logic [3:0] i = 4'h0; i < 4'hC; i += 4'h1) begin
          _RANDOM_MEM = `RANDOM;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:204:20]
          Memory[i] = _RANDOM_MEM[9:0];	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:204:20]
        end
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 10'bx;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:204:20]
  assign R1_data = R1_en ? Memory[R1_addr] : 10'bx;	// @[generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:204:20]
endmodule

